export type EmailTemplate = { subject: string; html: string; text: string };
type Order = { id: string; public_order_id?: string | null; platform?: string | null; service_name?: string | null; quantity?: number | null; charge?: number | null; status?: string | null; created_at?: string | null };
const site = () => (process.env.NEXT_PUBLIC_SITE_URL || "https://www.getsocialrush.com").replace(/\/$/, "");
const esc = (value: unknown) => String(value ?? "—").replace(/[&<>\"]/g, (c) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" }[c] as string));
const first = (name?: string | null) => (name || "there").trim().split(/\s+/)[0] || "there";
function frame(title: string, body: string, cta: string, href: string) { return `<!doctype html><html><body style="margin:0;background:#f6f6f3;color:#151515;font-family:Arial,sans-serif"><main style="max-width:620px;margin:24px auto;background:#fff;border:1px solid #ece9e0;border-radius:16px;overflow:hidden"><header style="padding:24px 32px;background:#171717;color:#fff;font-size:22px;font-weight:800">Social<span style="color:#eab308">RUSH</span></header><section style="padding:32px"><h1 style="margin:0 0 18px;font-size:25px">${title}</h1>${body}<p style="margin:28px 0"><a href="${href}" style="display:inline-block;background:#eab308;color:#161616;padding:13px 20px;border-radius:8px;text-decoration:none;font-weight:700">${cta}</a></p></section><footer style="padding:18px 32px;background:#faf9f6;color:#666;font-size:12px">© SocialRUSH · Account communications</footer></main></body></html>`; }
function details(order: Order) { return `<div style="background:#faf9f6;border:1px solid #ece9e0;border-radius:10px;padding:16px;line-height:1.75"><strong>Order ID:</strong> ${esc(order.public_order_id || order.id)}<br><strong>Platform:</strong> ${esc(order.platform)}<br><strong>Service:</strong> ${esc(order.service_name)}<br><strong>Quantity:</strong> ${esc(order.quantity)}<br><strong>Amount:</strong> ₹${Number(order.charge || 0).toFixed(2)}<br><strong>Status:</strong> ${esc(order.status)}${order.created_at ? `<br><strong>Date:</strong> ${esc(new Date(order.created_at).toLocaleDateString("en-IN"))}` : ""}</div>`; }
export function signupNoOrder(name?: string | null): EmailTemplate { const url=`${site()}/dashboard/new-order`; return { subject:"Ready to grow? Your SocialRUSH account is waiting 🚀", html:frame(`Hi ${esc(first(name))},`,`<p>Thanks for joining SocialRUSH.</p><p>We noticed you haven't started your first campaign yet. Choose the service that fits your goal and get started in just a few minutes.</p><p>Need help choosing a service? Simply reply to this email and we'll be happy to help.</p>`,`Start Your First Order`,url),text:`Hi ${first(name)},\n\nThanks for joining SocialRUSH. Start your first campaign: ${url}\n\nReply to this email if you need help.`}; }
export function orderCreated(name: string | null | undefined, order: Order): EmailTemplate { const url=`${site()}/dashboard/orders/${order.id}`; return {subject:"Thanks for choosing SocialRUSH 🎉",html:frame(`Hi ${esc(first(name))},`,`<p>Thank you for choosing SocialRUSH. We've successfully received your order.</p>${details(order)}<p>We're now taking care of your order. Need help? Reply to this email and our team will assist you.</p>`,`Track My Order`,url),text:`Hi ${first(name)},\n\nWe've received your order ${order.public_order_id || order.id}. Track it: ${url}`}; }
export function orderCompleted(name: string | null | undefined, order: Order): EmailTemplate { const url=`${site()}/dashboard/orders`; return {subject:"Your SocialRUSH order is complete ✅",html:frame(`Hi ${esc(first(name))},`,`<p>Great news! Your SocialRUSH order has been completed successfully.</p>${details(order)}<p>We appreciate you choosing SocialRUSH. If you have questions, simply reply to this email.</p>`,`View My Orders`,url),text:`Hi ${first(name)},\n\nYour order ${order.public_order_id || order.id} is complete. View your orders: ${url}`}; }
