import { Activity, CheckCircle2, Clock3, Tags, UserRoundCheck, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { dateTime } from "@/lib/crm/types";
import type { AutomationRunDetails, CrmAutomationRun, CrmAutomationSettings } from "@/lib/crm/types";
import CrmAutomationsPanel from "@/components/admin/CrmAutomationsPanel";

const number = (value: unknown) => typeof value === "number" ? value : Number(value || 0);
function details(value: unknown): AutomationRunDetails | null { return value && typeof value === "object" && !Array.isArray(value) ? value as AutomationRunDetails : null; }
function duration(run: CrmAutomationRun) { if (!run.completed_at) return "In progress"; const seconds=Math.max(0,Math.round((Date.parse(run.completed_at)-Date.parse(run.started_at))/1000)); return seconds < 60 ? `${seconds}s` : `${Math.floor(seconds/60)}m ${seconds%60}s`; }
function badge(status: CrmAutomationRun["status"]) { const styles={completed:"bg-emerald-500/10 text-emerald-200",failed:"bg-red-500/10 text-red-200",running:"bg-amber-500/10 text-amber-100"}; return <span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${styles[status]}`}>{status[0].toUpperCase()+status.slice(1)}</span>; }

export default async function AutomationsPage() {
  const s=await createClient(); const [{data:settingsRow},{data:runsRow},{data:profileRows}]=await Promise.all([s.from("crm_automation_settings").select("id,enabled,new_customer_days,at_risk_days,inactive_days,high_value_percentile,vip_percentile,vip_min_orders,create_retention_followups,create_support_followups,create_refill_followups,updated_at").limit(1).maybeSingle(),s.from("crm_automation_runs").select("id,started_at,completed_at,status,customers_scanned,profiles_touched,tags_removed,tags_added,followups_created,error_message,details").order("started_at",{ascending:false}).limit(20),s.from("crm_customer_profiles").select("lifecycle_stage")]);
  const settings=settingsRow as CrmAutomationSettings|null; const runs=((runsRow||[]) as Array<Omit<CrmAutomationRun,"details">&{details:unknown}>).map(run=>({...run,details:details(run.details)})); const latest=runs[0]||null; const distribution=(profileRows||[]).reduce<Record<string,number>>((counts,row)=>{const key=String(row.lifecycle_stage||"lead");counts[key]=(counts[key]||0)+1;return counts;},{});
  if (!settings) return <main className="mx-auto max-w-[1650px] p-4 sm:p-8"><h1 className="text-3xl font-black text-white">CRM Automations</h1><div className="mt-6 rounded-2xl border border-white/10 bg-[#111111] p-6 text-sm text-[#9CA3AF]">Automation settings are not available yet. Please confirm the production CRM automation setup is accessible to this admin account.</div></main>;
  const cards=[[Activity,"Automation Status",settings.enabled?"Active":"Paused",settings.enabled?"text-emerald-200":"text-[#D1D5DB]"],[Clock3,"Last Run",latest?dateTime(latest.started_at):"No runs yet","text-white"],[Users,"Customers Scanned",latest?.customers_scanned??"—","text-white"],[UserRoundCheck,"Profiles Updated",latest?.profiles_touched??"—","text-white"],[Tags,"Tags Added",latest?.tags_added??"—","text-white"],[CheckCircle2,"Follow-ups Created",latest?.followups_created??"—","text-white"]] as const;
  return <main className="mx-auto max-w-[1650px] p-4 pb-24 sm:p-8 sm:pb-24"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">Customer intelligence</p><h1 className="mt-2 text-3xl font-black text-white">CRM Automations</h1><p className="mt-2 max-w-2xl text-sm text-[#9CA3AF]">Automatically classify customers, identify opportunities and keep your CRM up to date.</p></div><div className={`flex items-center gap-2 text-xs font-bold ${settings.enabled?"text-emerald-200":"text-[#9CA3AF]"}`}><i className={`h-2 w-2 rounded-full ${settings.enabled?"bg-emerald-400":"bg-[#6B7280]"}`}/>{settings.enabled?"Automation Active":"Automation Paused"}</div></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{cards.map(([Icon,title,value,color])=><article key={title} className="rounded-2xl border border-white/10 bg-[#111111] p-4"><div className="flex items-center justify-between text-[#9CA3AF]"><span className="text-[10px] font-bold uppercase tracking-wide">{title}</span><Icon size={15} className="text-orange-300"/></div><b className={`mt-3 block text-xl ${color}`}>{value}</b></article>)}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_.5fr]"><div><CrmAutomationsPanel settings={settings} latest={latest}/></div><aside className="h-fit rounded-2xl border border-white/10 bg-[#111111] p-5"><h2 className="font-bold text-white">Daily automation</h2><p className="mt-2 flex items-center gap-2 text-sm text-emerald-200"><i className="h-2 w-2 rounded-full bg-emerald-400"/>Active · 8:00 AM IST</p><p className="mt-3 text-xs leading-5 text-[#9CA3AF]">{settings.enabled?"Your scheduled automation evaluates CRM opportunities every day.":"The scheduled job will run, but automation processing will skip while CRM automation is paused."}</p><h3 className="mt-6 text-sm font-bold text-white">Current CRM distribution</h3><div className="mt-3 space-y-2">{[["lead","Lead"],["new_customer","New Customer"],["active","Active"],["vip","VIP"],["at_risk","At Risk"],["inactive","Inactive"]].map(([key,label])=><div key={key} className="flex justify-between text-xs"><span className="text-[#9CA3AF]">{label}</span><b className="text-white">{distribution[key]||0}</b></div>)}</div></aside></section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-white/10 bg-[#111111]"><div className="border-b border-white/10 p-5"><h2 className="font-bold text-white">Automation History</h2><p className="mt-1 text-sm text-[#9CA3AF]">Recent automation runs and their impact on your CRM.</p></div>{runs.length?<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead className="text-[#9CA3AF]"><tr>{["Date / Time","Status","Customers","Profiles Updated","Tags Added","Follow-ups","Duration","Action"].map(h=><th key={h} className="px-5 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{runs.map(run=><tr key={run.id} className="border-t border-white/10"><td className="px-5 py-4 text-[#D1D5DB]">{dateTime(run.started_at)}</td><td className="px-5 py-4">{badge(run.status)}</td><td className="px-5 py-4 text-white">{number(run.customers_scanned)}</td><td className="px-5 py-4 text-white">{number(run.profiles_touched)}</td><td className="px-5 py-4 text-white">{number(run.tags_added)}</td><td className="px-5 py-4 text-white">{number(run.followups_created)}</td><td className="px-5 py-4 text-[#D1D5DB]">{duration(run)}</td><td className="px-5 py-4"><details><summary className="cursor-pointer font-bold text-orange-200">View Details</summary><div className="mt-2 w-60 rounded-lg border border-white/10 bg-[#0B0B0F] p-3 text-[#D1D5DB]">{run.status==="failed"?<p>Automation did not complete. Please try again or check the admin activity log.</p>:<><p>High Value threshold: {typeof run.details?.high_value_threshold==="number"?`₹${run.details.high_value_threshold}`:"—"}</p><p className="mt-1">VIP threshold: {typeof run.details?.vip_threshold==="number"?`₹${run.details.vip_threshold}`:"—"}</p><p className="mt-1">Rules: {run.details?.new_customer_days??"—"} / {run.details?.at_risk_days??"—"} / {run.details?.inactive_days??"—"} days</p></>}</div></details></td></tr>)}</tbody></table></div>:<div className="p-10 text-center text-sm text-[#9CA3AF]">No automation runs yet. Your first run will appear here.</div>}</section>
  </main>;
}
