"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import type { CrmPriority, FollowUpStatus, FollowUpType, LifecycleStage, LeadStatus, ReplyClassification } from "@/lib/crm/types";
import { isLeadContactOutreachEligible } from "@/lib/crm/outreach";
import { sendApprovedResendDraft } from "@/lib/crm/resend";
import { istDateTimeInputToIso } from "@/lib/crm/operational";

const lifecycle = new Set<LifecycleStage>(["lead","new_customer","active","vip","at_risk","inactive"]);
const priorities = new Set<CrmPriority>(["low","normal","high"]);
const followTypes = new Set<FollowUpType>(["general","sales","support","payment","refill","retention"]);
const followStatuses = new Set<FollowUpStatus>(["pending","completed","cancelled"]);
async function admin() { const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) throw new Error("Authentication required"); const {data:p}=await supabase.from("profiles").select("role").eq("id",user.id).single(); if(p?.role!=="admin") throw new Error("Admin access required"); return {supabase,user}; }
const value=(d:FormData,n:string)=>String(d.get(n)||"").trim();
const path=(id:string)=>`/admin/crm/customers/${id}`;
export async function saveCustomerLifecycleSettings(d:FormData){const{supabase}=await admin();const enabled=d.get("lifecycle_enabled")==="on",first=Number(d.get("first_order_delay_hours")),inactive=Number(d.get("inactive_days")),limit=Number(d.get("lifecycle_daily_limit"));if(![first,inactive,limit].every(Number.isInteger)||first<1||first>720||inactive<1||inactive>365||limit<1||limit>500)throw new Error("Invalid lifecycle settings.");const{error}=await supabase.from("customer_email_automation_config").update({lifecycle_enabled:enabled,first_order_delay_hours:first,inactive_days:inactive,lifecycle_daily_limit:limit,updated_at:new Date().toISOString()}).eq("id",true);if(error)throw new Error(error.message);revalidatePath("/admin/crm/automations");}
export async function saveCrmDetails(d:FormData) { const {supabase}=await admin(); const customerId=value(d,"customer_id"), stage=value(d,"lifecycle_stage") as LifecycleStage, priority=value(d,"priority") as CrmPriority; if(!customerId||!lifecycle.has(stage)||!priorities.has(priority)) throw new Error("Invalid CRM details."); const payload={customer_id:customerId,lifecycle_stage:stage,priority,lead_source:value(d,"lead_source")||null,internal_summary:value(d,"internal_summary")||null,last_contacted_at:value(d,"last_contacted_at")||null,next_follow_up_at:value(d,"next_follow_up_at")||null,updated_at:new Date().toISOString()}; const {error}=await supabase.from("crm_customer_profiles").upsert(payload,{onConflict:"customer_id"}); if(error) throw new Error(error.message); revalidatePath(path(customerId)); revalidatePath("/admin/crm"); revalidatePath("/admin/crm/customers"); }
export async function addNote(d:FormData) { const {supabase,user}=await admin(); const customerId=value(d,"customer_id"),note=value(d,"note"); if(!customerId||note.length<1||note.length>5000) throw new Error("A note up to 5000 characters is required."); const {error}=await supabase.from("crm_notes").insert({customer_id:customerId,note,created_by:user.id});if(error)throw new Error(error.message);revalidatePath(path(customerId)); }
export async function deleteNote(d:FormData) { const {supabase}=await admin();const id=value(d,"note_id"),customerId=value(d,"customer_id");const {error}=await supabase.from("crm_notes").delete().eq("id",id);if(error)throw new Error(error.message);revalidatePath(path(customerId)); }
export async function setCustomerTags(d:FormData) { const {supabase}=await admin(); const customerId=value(d,"customer_id"),tagIds=d.getAll("tag_ids").map(String); if(!customerId) throw new Error("Customer required."); const {error:removeError}=await supabase.from("crm_customer_tags").delete().eq("customer_id",customerId);if(removeError)throw new Error(removeError.message); if(tagIds.length){const {error}=await supabase.from("crm_customer_tags").insert(tagIds.map(tag_id=>({customer_id:customerId,tag_id})));if(error)throw new Error(error.message)} revalidatePath(path(customerId));revalidatePath("/admin/crm/customers"); }
export async function saveFollowUp(d:FormData) { const {supabase,user}=await admin();const customerId=value(d,"customer_id"),title=value(d,"title"),type=value(d,"follow_up_type") as FollowUpType,due=istDateTimeInputToIso(value(d,"due_at"));if(!customerId||!title||!due||!followTypes.has(type))throw new Error("Title, type and a valid India-time due date are required.");const id=value(d,"follow_up_id");const payload={customer_id:customerId,title:title.slice(0,200),details:value(d,"details")||null,follow_up_type:type,due_at:due,updated_at:new Date().toISOString()};const result=id?await supabase.from("crm_follow_ups").update(payload).eq("id",id):await supabase.from("crm_follow_ups").insert({...payload,status:"pending",created_by:user.id});if(result.error)throw new Error(result.error.message);revalidatePath(path(customerId));revalidatePath("/admin/crm/follow-ups"); }
export async function updateFollowUpStatus(d:FormData) { const {supabase}=await admin();const id=value(d,"follow_up_id"),customerId=value(d,"customer_id"),status=value(d,"status") as FollowUpStatus;if(!followStatuses.has(status))throw new Error("Invalid follow-up status.");const {error}=await supabase.from("crm_follow_ups").update({status,completed_at:status==="completed"?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(error.message);revalidatePath(path(customerId));revalidatePath("/admin/crm/follow-ups"); }

const automationPaths = ["/admin/crm", "/admin/crm/customers", "/admin/crm/follow-ups", "/admin/crm/automations"];
function refreshAutomation() { automationPaths.forEach(route => revalidatePath(route)); }
export async function saveAutomationSettings(input: { enabled: boolean; newCustomerDays: number; atRiskDays: number; inactiveDays: number; highValuePercentile: number; vipPercentile: number; vipMinOrders: number; retention: boolean; support: boolean; refill: boolean }) {
  const { supabase } = await admin();
  const { enabled, newCustomerDays, atRiskDays, inactiveDays, highValuePercentile, vipPercentile, vipMinOrders, retention, support, refill } = input;
  if (!Number.isInteger(newCustomerDays) || newCustomerDays < 1 || newCustomerDays > 90) throw new Error("New customer window must be between 1 and 90 days.");
  if (!Number.isInteger(atRiskDays) || atRiskDays < 7 || atRiskDays > 365) throw new Error("At risk period must be between 7 and 365 days.");
  if (!Number.isInteger(inactiveDays) || inactiveDays < 14 || inactiveDays > 730) throw new Error("Inactive period must be between 14 and 730 days.");
  if (!(newCustomerDays < atRiskDays && atRiskDays < inactiveDays)) throw new Error("Use increasing windows: New Customer, At Risk, then Inactive.");
  if (![.8, .85, .9, .95].includes(highValuePercentile) || ![.8, .85, .9, .95].includes(vipPercentile) || highValuePercentile >= vipPercentile) throw new Error("VIP must be a smaller top segment than High Value.");
  if (!Number.isInteger(vipMinOrders) || vipMinOrders < 1 || vipMinOrders > 100) throw new Error("VIP minimum orders must be between 1 and 100.");
  const { error } = await supabase.from("crm_automation_settings").update({ enabled, new_customer_days: newCustomerDays, at_risk_days: atRiskDays, inactive_days: inactiveDays, high_value_percentile: highValuePercentile, vip_percentile: vipPercentile, vip_min_orders: vipMinOrders, create_retention_followups: retention, create_support_followups: support, create_refill_followups: refill, updated_at: new Date().toISOString() }).not("id", "is", null);
  if (error) throw new Error("Automation settings could not be saved."); refreshAutomation();
}
export async function runCrmAutomation() {
  const { supabase } = await admin(); const { data, error } = await supabase.rpc("admin_run_crm_automation");
  if (error) throw new Error("Automation could not be started. Please try again.");
  const runId = typeof data === "string" ? data : null;
  const { data: run } = runId ? await supabase.from("crm_automation_runs").select("status,customers_scanned,tags_added,followups_created").eq("id", runId).maybeSingle() : { data: null };
  refreshAutomation(); return run;
}

const leadStatuses = new Set<LeadStatus>(["new","researching","ready","contacted","replied","qualified","won","lost","do_not_contact"]);
const normalizeDomain = (raw:string) => raw.trim().toLowerCase().replace(/^https?:\/\//, "").replace(/^www\./, "").split("/")[0];
const leadPaths = (id?:string) => ["/admin/crm/leads", "/admin/crm/outreach", ...(id ? [`/admin/crm/leads/${id}`] : [])].forEach(route => revalidatePath(route));
export async function sendApprovedOutreachDraft(messageId:string) { await admin(); const sent=await sendApprovedResendDraft(messageId); leadPaths(); return sent; }
const replyPaths=()=>["/admin/crm/replies","/admin/crm/automations","/admin/crm/leads","/admin/crm/outreach"].forEach(route=>revalidatePath(route));
export async function saveReplyAutomationSettings(input:{replyDetectionEnabled:boolean;autoClassifyReplies:boolean;autoStopSequenceOnReply:boolean;autoSuppressUnsubscribes:boolean;createReplyFollowups:boolean;generateAiReplyDrafts:boolean}) { const {supabase}=await admin(); const mailboxConnected=Boolean(process.env.RESEND_API_KEY&&process.env.RESEND_WEBHOOK_SECRET); const payload={reply_detection_enabled:mailboxConnected&&input.replyDetectionEnabled,auto_classify_replies:input.autoClassifyReplies,auto_stop_sequence_on_reply:input.autoStopSequenceOnReply,auto_suppress_unsubscribes:input.autoSuppressUnsubscribes,create_reply_followups:input.createReplyFollowups,generate_ai_reply_drafts:false,updated_at:new Date().toISOString()}; const {error}=await supabase.from("crm_reply_automation_settings").upsert({id:true,...payload});if(error)throw new Error(error.message);replyPaths(); }
export async function reviewInboundReply(input:{id:string;classification:ReplyClassification;leadStatus:LeadStatus;draftStatus?:"draft"|"approved"|"discarded"}) {const {supabase,user}=await admin();const valid=new Set<ReplyClassification>(["interested","needs_information","not_now","meeting_request","positive_reply","negative_reply","unsubscribe","out_of_office","bounce","wrong_person","other"]);if(!input.id||!valid.has(input.classification)||!leadStatuses.has(input.leadStatus))throw new Error("Invalid review.");const {data:message,error:readError}=await supabase.from("crm_inbound_messages").select("lead_id").eq("id",input.id).single();if(readError||!message?.lead_id)throw new Error("Reply is unavailable.");const {error}=await supabase.from("crm_inbound_messages").update({admin_classification:input.classification,admin_status:input.leadStatus,needs_admin_review:false,draft_status:input.draftStatus||"draft"}).eq("id",input.id);if(error)throw new Error(error.message);await supabase.from("crm_leads").update({status:input.leadStatus,updated_at:new Date().toISOString()}).eq("id",message.lead_id);await supabase.from("crm_reply_audit_log").insert({lead_id:message.lead_id,inbound_message_id:input.id,action:"manual_override",details:{classification:input.classification,status:input.leadStatus},actor_id:user.id});replyPaths();}
export async function addLead(d:FormData) { const {supabase,user}=await admin(); const business=value(d,"business_name"), domain=normalizeDomain(value(d,"domain")||value(d,"website_url")); const score=Number(value(d,"score")||0); if(!business||!domain||!Number.isFinite(score)||score<0||score>100) throw new Error("Business name, a valid domain, and score from 0–100 are required."); const {data:existing,error:findError}=await supabase.from("crm_leads").select("id,business_name").eq("domain",domain).maybeSingle(); if(findError) throw new Error(findError.message); if(existing) throw new Error(`A lead already exists for this domain: ${existing.business_name} (${existing.id}).`); const payload={business_name:business.slice(0,200),domain,website_url:value(d,"website_url")||null,country:value(d,"country")||null,city:value(d,"city")||null,industry:value(d,"industry")||null,company_type:value(d,"company_type")||"business",employee_range:value(d,"employee_range")||null,instagram_url:value(d,"instagram_url")||null,linkedin_url:value(d,"linkedin_url")||null,youtube_url:value(d,"youtube_url")||null,tiktok_url:value(d,"tiktok_url")||null,source:value(d,"source")||"manual",source_url:value(d,"source_url")||null,fit_summary:value(d,"fit_summary")||null,recommended_service:value(d,"recommended_service")||null,score, status:"new",created_by:user.id}; const {data,error}=await supabase.from("crm_leads").insert(payload).select("id").single(); if(error)throw new Error(error.message); await supabase.from("crm_lead_activities").insert({lead_id:data.id,activity_type:"discovered",details:{source:payload.source},created_by:user.id}); leadPaths(data.id); return data.id; }
export async function addLeadContact(d:FormData) { const {supabase,user}=await admin();const leadId=value(d,"lead_id"),email=value(d,"email").toLowerCase();if(!leadId||!email||!/^\S+@\S+\.\S+$/.test(email))throw new Error("A valid email is required.");const [{data:duplicate},{data:suppression}]=await Promise.all([supabase.from("crm_lead_contacts").select("id").eq("email",email).maybeSingle(),supabase.from("crm_suppression_list").select("reason").eq("email",email).maybeSingle()]);if(duplicate)throw new Error("This email already belongs to a lead contact.");if(suppression)throw new Error(`BLOCKED — this email is suppressed (${suppression.reason}).`);const {error}=await supabase.from("crm_lead_contacts").insert({lead_id:leadId,full_name:value(d,"full_name"),job_title:value(d,"job_title")||null,email,email_type:value(d,"email_type")||"unknown",verification_status:value(d,"verification_status")||"unverified",compliance_status:value(d,"compliance_status")||"review",contact_basis:value(d,"contact_basis")||"other",is_primary:d.get("is_primary")==="on",source_url:value(d,"source_url")||null});if(error)throw new Error(error.message);await supabase.from("crm_lead_activities").insert({lead_id:leadId,activity_type:"contact_added",details:{email},created_by:user.id});leadPaths(leadId); }
export async function addLeadNote(d:FormData) {const {supabase,user}=await admin();const leadId=value(d,"lead_id"),note=value(d,"note");if(!leadId||!note||note.length>5000)throw new Error("A note up to 5000 characters is required.");const {error}=await supabase.from("crm_lead_activities").insert({lead_id:leadId,activity_type:"note",details:{content:note},created_by:user.id});if(error)throw new Error(error.message);leadPaths(leadId);}
export async function changeLeadStatus(d:FormData) {const {supabase,user}=await admin();const leadId=value(d,"lead_id"),status=value(d,"status") as LeadStatus;if(!leadId||!leadStatuses.has(status))throw new Error("Invalid lead status.");const {error}=await supabase.from("crm_leads").update({status,updated_at:new Date().toISOString()}).eq("id",leadId);if(error)throw new Error(error.message);if(status==="do_not_contact"){const {error:enrollmentError}=await supabase.from("crm_lead_enrollments").update({status:"paused",updated_at:new Date().toISOString()}).eq("lead_id",leadId).eq("status","active");if(enrollmentError)throw new Error(enrollmentError.message);}await supabase.from("crm_lead_activities").insert({lead_id:leadId,activity_type:status==="do_not_contact"?"opt_out":"status_changed",details:{status},created_by:user.id});leadPaths(leadId);}
export async function createSequence(d:FormData) {const {supabase,user}=await admin();const name=value(d,"name");if(!name)throw new Error("Sequence name is required.");const {error}=await supabase.from("crm_outreach_sequences").insert({name,description:value(d,"description")||null,status:"draft",daily_send_limit:Math.max(1,Math.min(100,Number(value(d,"daily_send_limit")||20))),timezone:value(d,"timezone")||"Asia/Kolkata",send_window_start:value(d,"send_window_start")||"09:00",send_window_end:value(d,"send_window_end")||"17:00",created_by:user.id});if(error)throw new Error(error.message);leadPaths();}
export async function enrollLeadContact(d:FormData) {const {supabase,user}=await admin();const leadId=value(d,"lead_id"),contactId=value(d,"contact_id"),sequenceId=value(d,"sequence_id");const [{data:lead},{data:contact},{data:settings},{data:suppressions}]=await Promise.all([supabase.from("crm_leads").select("status").eq("id",leadId).single(),supabase.from("crm_lead_contacts").select("*").eq("id",contactId).single(),supabase.from("crm_outreach_settings").select("*").limit(1).maybeSingle(),supabase.from("crm_suppression_list").select("email")]);if(!lead||!contact||!sequenceId||!isLeadContactOutreachEligible(contact,lead,settings,suppressions||[]))throw new Error("This contact is not outreach-ready or is protected by suppression rules.");const {error}=await supabase.from("crm_lead_enrollments").insert({lead_id:leadId,contact_id:contactId,sequence_id:sequenceId,status:"paused",current_step:0});if(error)throw new Error(error.message);await supabase.from("crm_lead_activities").insert({lead_id:leadId,activity_type:"outreach_queued",details:{sequence_id:sequenceId,status:"prepared"},created_by:user.id});leadPaths(leadId);}
export async function saveSequence(input:{id:string;name:string;description:string;status:"draft"|"active"|"paused"|"archived";dailySendLimit:number;timezone:string;sendWindowStart:string;sendWindowEnd:string;steps:Array<{id?:string;delayDays:number;subject:string;body:string;stopOnReply:boolean}>}) {const {supabase}=await admin();if(!input.id||!input.name.trim()||input.steps.length>10||input.dailySendLimit<1||input.dailySendLimit>1000)throw new Error("Invalid sequence settings.");if(input.steps.some((step,i)=>i>9||!Number.isInteger(step.delayDays)||step.delayDays<0||step.delayDays>90||!step.subject.trim()||step.subject.length>250||!step.body.trim()))throw new Error("Each step needs a subject and body; delay must be 0–90 days.");const {error}=await supabase.from("crm_outreach_sequences").update({name:input.name.trim(),description:input.description.trim()||null,status:input.status,daily_send_limit:input.dailySendLimit,timezone:input.timezone.trim()||"Asia/Kolkata",send_window_start:input.sendWindowStart,send_window_end:input.sendWindowEnd,updated_at:new Date().toISOString()}).eq("id",input.id);if(error)throw new Error(error.message);const {error:removeError}=await supabase.from("crm_outreach_sequence_steps").delete().eq("sequence_id",input.id);if(removeError)throw new Error(removeError.message);if(input.steps.length){const {error:stepsError}=await supabase.from("crm_outreach_sequence_steps").insert(input.steps.map((step,index)=>({sequence_id:input.id,step_number:index+1,delay_days:step.delayDays,subject_template:step.subject.trim(),body_template:step.body.trim(),stop_on_reply:step.stopOnReply})));if(stepsError)throw new Error(stepsError.message);}leadPaths();}
export async function saveOutreachSettings(input:{enabled:boolean;autoSend:boolean;requireVerified:boolean;requireCompliance:boolean;dailyLimit:number;fromName:string;fromEmail:string;replyTo:string;provider:string;timezone:string}) {const {supabase}=await admin();if(!Number.isInteger(input.dailyLimit)||input.dailyLimit<1||input.dailyLimit>1000)throw new Error("Daily send limit must be 1–1000.");const email=/^\S+@\S+\.\S+$/;if((input.fromEmail&&!email.test(input.fromEmail))||(input.replyTo&&!email.test(input.replyTo)))throw new Error("Enter valid email addresses.");if(input.autoSend){if(!input.enabled||!input.provider.trim()||!input.fromEmail||!input.requireVerified||!input.requireCompliance)throw new Error("Auto Send requires enabled outreach, a provider, from email, verified-email and compliance safeguards.");throw new Error("Automatic sending is unavailable until provider wiring is complete.");}const {data:existing,error:findError}=await supabase.from("crm_outreach_settings").select("id").limit(1).maybeSingle();if(findError)throw new Error(findError.message);const payload={enabled:input.enabled,auto_send:false,require_verified_business_email:input.requireVerified,require_compliance_eligible:input.requireCompliance,global_daily_send_limit:input.dailyLimit,from_name:input.fromName.trim()||null,from_email:input.fromEmail.trim()||null,reply_to:input.replyTo.trim()||null,provider:input.provider.trim()||null,default_timezone:input.timezone.trim()||"Asia/Kolkata",updated_at:new Date().toISOString()};const result=existing?await supabase.from("crm_outreach_settings").update(payload).eq("id",existing.id):await supabase.from("crm_outreach_settings").insert(payload);if(result.error)throw new Error(result.error.message);leadPaths();}
