/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { date, dateTime, metricsForOrders, money } from "@/lib/crm/types";

export default async function CrmOverviewPage() {
  const supabase=await createClient(); const since=new Date(Date.now()-30*864e5).toISOString(); const now=new Date().toISOString();
  const [profilesResult,ordersResult,crmResult,followUpsResult]=await Promise.all([
    supabase.from("profiles").select("id,full_name,email,created_at").neq("role","admin").order("created_at",{ascending:false}).limit(500),
    supabase.from("orders").select("user_id,charge,status,payment_status,platform,created_at").order("created_at",{ascending:false}).limit(5000),
    supabase.from("crm_customer_profiles").select("customer_id,lifecycle_stage"),
    supabase.from("crm_follow_ups").select("id,customer_id,title,due_at,status,follow_up_type").eq("status","pending").order("due_at").limit(100),
  ]);
  const profiles=(profilesResult.data||[]) as any[]; const orders=(ordersResult.data||[]) as any[]; const crm=(crmResult.data||[]) as any[]; const followUps=(followUpsResult.data||[]) as any[];
  const orderMap=new Map<string,any[]>();orders.forEach(o=>orderMap.set(o.user_id,[...(orderMap.get(o.user_id)||[]),o]));
  const summaries=profiles.map(p=>({profile:p,metrics:metricsForOrders(orderMap.get(p.id)||[])})); const revenue=summaries.reduce((x,s)=>x+s.metrics.totalSpend,0); const valid=summaries.reduce((x,s)=>x+s.metrics.validOrders,0);
  const vip=new Set(crm.filter(x=>x.lifecycle_stage==="vip").map(x=>x.customer_id)); const platformCounts=new Map<string,number>();orders.filter(o=>!['cancelled','refunded','failed'].includes(String(o.status).toLowerCase())).forEach(o=>o.platform&&platformCounts.set(o.platform,(platformCounts.get(o.platform)||0)+1));
  const lifecycleCounts=crm.reduce((m,x)=>{m[x.lifecycle_stage]=(m[x.lifecycle_stage]||0)+1;return m;},{} as Record<string,number>); const customerById=new Map(profiles.map(p=>[p.id,p])); const overdue=followUps.filter(x=>x.due_at<now);
  const cards=[["Total customers",profiles.length],["New customers",profiles.filter(p=>p.created_at>=since).length],["Active customers",summaries.filter(s=>s.metrics.lastOrderAt&&Date.parse(s.metrics.lastOrderAt)>=Date.now()-90*864e5).length],["VIP customers",vip.size],["Repeat customers",summaries.filter(s=>s.metrics.validOrders>=2).length],["Total customer revenue",money(revenue)],["Average order value",money(valid?revenue/valid:0)],["Follow-ups due",followUps.filter(x=>x.due_at<=new Date(Date.now()+864e5).toISOString()).length]];
  return <main className="mx-auto max-w-[1650px] p-4 sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">Customer intelligence</p><h1 className="mt-2 text-3xl font-black text-white">SocialRUSH CRM</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#9CA3AF]">Understand your customers, identify high-value accounts and never miss a follow-up.</p></div><div className="flex gap-2"><Link href="/admin/crm/customers" className="rounded-xl border border-orange-400/30 px-4 py-3 text-xs font-bold text-orange-200">Customers</Link><Link href="/admin/crm/follow-ups" className="rounded-xl bg-gradient-to-r from-[#FF7A00] to-[#FF9F00] px-4 py-3 text-xs font-bold text-white">Follow-ups</Link></div></div>
  <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value])=><article key={String(label)} className="rounded-2xl border border-orange-400/20 bg-[#111111] p-5 shadow-[0_16px_36px_-28px_rgba(255,122,0,.7)]"><p className="text-[10px] font-bold uppercase tracking-wider text-[#9CA3AF]">{label}</p><p className="mt-3 text-2xl font-black text-white">{value}</p></article>)}</section>
  <section className="mt-7 grid gap-5 xl:grid-cols-2"><Panel title="Top customers by spend"><div className="space-y-3">{summaries.sort((a,b)=>b.metrics.totalSpend-a.metrics.totalSpend).slice(0,6).map(s=><Link key={s.profile.id} href={`/admin/crm/customers/${s.profile.id}`} className="flex items-center justify-between rounded-xl bg-[#0B0B0F] p-3 hover:bg-orange-500/10"><span className="min-w-0"><b className="block truncate text-sm text-white">{s.profile.full_name||s.profile.email}</b><small className="text-[#9CA3AF]">{s.metrics.validOrders} valid orders · {s.metrics.topPlatform||"No orders"}</small></span><b className="text-sm text-orange-200">{money(s.metrics.totalSpend)}</b></Link>)}</div></Panel><Panel title="Upcoming follow-ups"><div className="space-y-3">{followUps.slice(0,6).map(f=><Link key={f.id} href={`/admin/crm/customers/${f.customer_id}`} className="block rounded-xl bg-[#0B0B0F] p-3 hover:bg-orange-500/10"><div className="flex justify-between gap-3"><b className="truncate text-sm text-white">{f.title}</b><span className={f.due_at<now?"text-red-300":"text-orange-200"}>{dateTime(f.due_at)}</span></div><small className="text-[#9CA3AF]">{customerById.get(f.customer_id)?.full_name||customerById.get(f.customer_id)?.email||"Customer"} · {f.follow_up_type}</small></Link>)}{!followUps.length&&<Empty text="No pending follow-ups."/>}</div></Panel><Panel title="Most purchased platforms"><div className="space-y-3">{[...platformCounts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6).map(([name,count])=><div key={name} className="flex justify-between rounded-xl bg-[#0B0B0F] p-3 text-sm"><b className="text-white">{name}</b><span className="text-orange-200">{count} orders</span></div>)}{!platformCounts.size&&<Empty text="No paid orders yet."/>}</div></Panel><Panel title="Customer lifecycle"><div className="grid grid-cols-2 gap-3">{["lead","new_customer","active","vip","at_risk","inactive"].map(x=><div key={x} className="rounded-xl bg-[#0B0B0F] p-4"><p className="capitalize text-xs text-[#9CA3AF]">{x.replace("_"," ")}</p><b className="mt-2 block text-xl text-white">{lifecycleCounts[x]||0}</b></div>)}</div></Panel></section>
  <section className="mt-7"><Panel title={`Recent customers${overdue.length?` · ${overdue.length} overdue follow-ups`:""}`}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{summaries.slice(0,6).map(s=><Link key={s.profile.id} href={`/admin/crm/customers/${s.profile.id}`} className="rounded-xl bg-[#0B0B0F] p-4 hover:bg-orange-500/10"><b className="block truncate text-white">{s.profile.full_name||"Unnamed customer"}</b><span className="block truncate text-xs text-[#9CA3AF]">{s.profile.email}</span><span className="mt-3 block text-xs text-orange-200">Joined {date(s.profile.created_at)}</span></Link>)}</div></Panel></section></main>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-white/10 bg-[#111111] p-5"><h2 className="mb-4 text-base font-black text-white">{title}</h2>{children}</section>};function Empty({text}:{text:string}){return <p className="rounded-xl border border-white/10 p-5 text-center text-sm text-[#9CA3AF]">{text}</p>}
