import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { AdminPageHeader } from "@/components/admin/AdminUI";

export default async function AdminSettingsPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const { data: profile } = await supabase.from("profiles").select("full_name, email, role, created_at").eq("id", user!.id).single();
  const checks = [["Authentication", "Supabase Auth", "Operational"], ["Database security", "Row Level Security", "Enabled"], ["Admin access", "Role-based guard", "Enabled"], ["Order processing", "Atomic database RPC", "Operational"]];
  return <main className="mx-auto max-w-[1200px] p-5 sm:p-8"><AdminPageHeader title="Admin settings" description="Review administrator access, platform configuration, and security status."/><div className="mt-7 grid gap-6 lg:grid-cols-2"><section className="panel-card p-6"><h2 className="text-sm font-bold">Administrator profile</h2><p className="mt-1 text-xs text-slate-400">Your privileged account information.</p><div className="mt-6 flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-[#0a1b3d] text-sm font-bold text-white">{(profile?.full_name || "AD").slice(0,2).toUpperCase()}</span><div><p className="text-sm font-bold">{profile?.full_name || "Administrator"}</p><p className="mt-1 text-xs text-slate-400">{profile?.email}</p><span className="mt-2 inline-block rounded-full bg-violet-50 px-2 py-1 text-[9px] font-bold uppercase text-violet-700">{profile?.role}</span></div></div><div className="mt-6 rounded-xl bg-amber-50 p-4 text-xs leading-5 text-amber-700">Administrator accounts can view and modify platform-wide customer data. Keep this account protected with a strong, unique password.</div><Link href="/dashboard/settings" className="mt-5 inline-block rounded-xl border border-slate-200 px-4 py-3 text-xs font-bold text-slate-600 hover:bg-slate-50">Manage profile & password</Link></section><section className="panel-card overflow-hidden"><div className="border-b border-slate-100 p-6"><h2 className="text-sm font-bold">Platform health</h2><p className="mt-1 text-xs text-slate-400">Current security and infrastructure configuration.</p></div><div className="divide-y divide-slate-100">{checks.map(([name,detail,status]) => <div key={name} className="flex items-center gap-4 px-6 py-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-50 text-emerald-600">✓</span><div className="flex-1"><p className="text-xs font-semibold">{name}</p><p className="mt-1 text-[10px] text-slate-400">{detail}</p></div><span className="text-[10px] font-bold text-emerald-600">{status}</span></div>)}</div></section><section className="panel-card p-6 lg:col-span-2"><h2 className="text-sm font-bold">Quick administration</h2><p className="mt-1 text-xs text-slate-400">Common platform configuration areas.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Service catalog","/admin/services"],["User access","/admin/users"],["Order workflow","/admin/orders"],["Support queue","/admin/support"]].map(([label,href]) => <Link key={href} href={href} className="rounded-xl border border-slate-200 p-4 text-xs font-bold text-slate-700 transition hover:border-blue-200 hover:bg-blue-50 hover:text-blue-600">{label}<span className="float-right">→</span></Link>)}</div></section></div></main>;
}
