import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import RevenueAuditDecision from "@/components/admin/RevenueAuditDecision";
import { buildRevenueAudit, phase2Baseline } from "@/lib/analytics/revenue-audit";

const ranges = { today: 1, "7d": 7, "30d": 30, "90d": 90 } as const;
const funnel = ["service_selected", "order_started", "checkout_started", "payment_started", "payment_completed", "order_created"] as const;
const pct = (from: number, to: number) => from ? `${((to / from) * 100).toFixed(1)}%` : "—";
const money = (value: number) => value.toLocaleString("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const orderIdFromMetadata = (metadata: unknown) => {
  if (!metadata || typeof metadata !== "object" || Array.isArray(metadata)) return null;
  const value = (metadata as Record<string, unknown>).order_id;
  return typeof value === "string" && value.length <= 100 ? value : null;
};

export default async function Page({ searchParams }: { searchParams: { range?: string } }) {
  const db = await createClient(); const key = searchParams.range && searchParams.range in ranges ? searchParams.range as keyof typeof ranges : "30d"; const days=ranges[key]; const since=new Date(Date.now()-days*86_400_000).toISOString();
  const [analyticsResult,ordersResult,transactionsResult,supportResult]=await Promise.all([db.from("analytics_events").select("event_name,customer_id,anonymous_session_id,platform,service_code,device_category,source,medium,campaign,safe_metadata,created_at").gte("created_at",since),db.from("orders").select("id,user_id,service_name,platform,charge,status,payment_status,created_at").gte("created_at",since),db.from("transactions").select("amount,type,status,payment_method,created_at").gte("created_at",since),db.from("support_tickets").select("id",{count:"exact",head:true}).gte("created_at",since)]);
  const events=analyticsResult.data??[],orders=ordersResult.data??[],transactions=transactionsResult.data??[],supportCount=supportResult.count??0; const queryFailed=Boolean(analyticsResult.error||ordersResult.error||transactionsResult.error||supportResult.error);
  if(analyticsResult.error)console.error("[admin analytics] analytics events query failed",{code:analyticsResult.error.code});if(ordersResult.error)console.error("[admin analytics] orders query failed",{code:ordersResult.error.code});if(transactionsResult.error)console.error("[admin analytics] transactions query failed",{code:transactionsResult.error.code});if(supportResult.error)console.error("[admin analytics] support count query failed",{code:supportResult.error.code});
  const count=(name:string)=>events.filter(e=>e.event_name===name).length; const visitors=new Set(events.map(e=>e.customer_id||e.anonymous_session_id).filter(Boolean)).size; const createdOrders=orders.filter(o=>o.status!=="failed"&&o.status!=="cancelled"); const paidOrders=createdOrders.filter(o=>["paid","completed"].includes(o.payment_status||"")); const completedOrders=createdOrders.filter(o=>o.status==="completed"); const completedCustomers=new Set(completedOrders.map(o=>o.user_id).filter(Boolean)); const repeatOrders=Math.max(0,completedOrders.length-completedCustomers.size); const starts=count("order_started"),paymentStarts=count("payment_started"),paymentCompletions=count("payment_completed"); const gross=paidOrders.reduce((s,o)=>s+Number(o.charge||0),0); const refunds=transactions.filter(t=>t.type==="refund"&&t.status==="completed").reduce((s,t)=>s+Number(t.amount||0),0); const netRevenue=Math.max(0,gross-refunds),refundRate=gross?(refunds/gross)*100:0,aov=paidOrders.length?gross/paidOrders.length:0,revenuePerDay=netRevenue/Math.max(1,days); const repeatRate=completedOrders.length?(repeatOrders/completedOrders.length)*100:0; const rawPaymentSuccess=paymentStarts?(paymentCompletions/paymentStarts)*100:null; const paymentTrackingReliable=paymentStarts>0&&(paymentCompletions>0||paidOrders.length===0)&&paymentCompletions<=paymentStarts; const paymentSuccess=paymentTrackingReliable?rawPaymentSuccess:null; const first=events.length?events.reduce((a,e)=>a<e.created_at?a:e.created_at,events[0].created_at):null;
  const serviceRevenue=new Map<string,{revenue:number;orders:number;platform:string}>();for(const o of paidOrders){const name=o.service_name||"Unknown service",cur=serviceRevenue.get(name)||{revenue:0,orders:0,platform:o.platform||"—"};cur.revenue+=Number(o.charge||0);cur.orders++;serviceRevenue.set(name,cur);}const topServices=[...serviceRevenue.entries()].sort((a,b)=>b[1].revenue-a[1].revenue).slice(0,5);
  const orderAttribution=new Map<string,{source:string;medium:string;campaign:string|null}>();for(const event of events){if(event.event_name!=="order_created")continue;const orderId=orderIdFromMetadata(event.safe_metadata);if(!orderId||orderAttribution.has(orderId))continue;orderAttribution.set(orderId,{source:event.source?.trim()||"unattributed",medium:event.medium?.trim()||"unknown",campaign:event.campaign?.trim()||null});}
  const sourceRevenue=new Map<string,{source:string;medium:string;revenue:number;orders:number}>();const campaignRevenue=new Map<string,{campaign:string;source:string;revenue:number;orders:number}>();let attributedPaidOrders=0,attributedRevenue=0;
  for(const order of paidOrders){const attribution=orderAttribution.get(order.id);const source=attribution?.source||"unattributed",medium=attribution?.medium||"unknown",charge=Number(order.charge||0);const sourceKey=`${source}::${medium}`,sourceRow=sourceRevenue.get(sourceKey)||{source,medium,revenue:0,orders:0};sourceRow.revenue+=charge;sourceRow.orders++;sourceRevenue.set(sourceKey,sourceRow);if(attribution&&source!=="unattributed"){attributedPaidOrders++;attributedRevenue+=charge;}if(attribution?.campaign){const campaignKey=`${source}::${attribution.campaign}`,campaignRow=campaignRevenue.get(campaignKey)||{campaign:attribution.campaign,source,revenue:0,orders:0};campaignRow.revenue+=charge;campaignRow.orders++;campaignRevenue.set(campaignKey,campaignRow);}}
  const topSources=[...sourceRevenue.values()].sort((a,b)=>b.revenue-a.revenue).slice(0,8),topCampaigns=[...campaignRevenue.values()].sort((a,b)=>b.revenue-a.revenue).slice(0,5);const attributionCoverage=paidOrders.length?(attributedPaidOrders/paidOrders.length)*100:0,unattributedRevenue=Math.max(0,gross-attributedRevenue);
  const funnelData=funnel.map(name=>({name,total:name==="order_created"?createdOrders.length:count(name)})); const funnelTrackingReliable=funnelData.every((step,index)=>index===0||step.total<=funnelData[index-1].total); const audit=buildRevenueAudit({gross,netRevenue,aov,refundRate,repeatRate,paymentSuccess,paymentTrackingReliable,revenuePerDay,paidOrders:paidOrders.length,funnel:funnelData,funnelTrackingReliable,services:topServices.map(([name,s])=>({name,...s}))});
  const paymentDisplay=paymentTrackingReliable&&paymentSuccess!==null?`${paymentSuccess.toFixed(1)}%`:paidOrders.length?"Tracking incomplete":"—"; const cards=[["Unique sessions/users",visitors],["Order starts",starts],["Orders created",createdOrders.length],["Order conversion",pct(starts,createdOrders.length)],["Tracked payment success",paymentDisplay],["Repeat-order rate",pct(completedOrders.length,repeatOrders)],["Support tickets",supportCount],["Refund rate",`${refundRate.toFixed(1)}%`]];
  return <main className="p-4 pb-24 sm:p-8"><div className="mx-auto max-w-[1500px]"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-orange-400">SocialRUSH $1M Command Center</p><h1 className="mt-2 text-3xl font-black text-white">Revenue &amp; Conversion</h1><p className="mt-2 max-w-4xl text-sm text-slate-400">Verified order and transaction records drive revenue decisions. First-party event tracking is shown separately and is never substituted for verified payment status.</p></div><div className="rounded-2xl border border-orange-400/20 bg-orange-500/10 px-4 py-3 text-sm text-orange-100">Reporting timezone: Asia/Kolkata<br/>Collection started: {first?new Date(first).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"}):"No events yet"}</div></div>
  {queryFailed?<div role="alert" className="mt-5 rounded-2xl border border-amber-400/25 bg-amber-500/10 p-4 text-sm leading-6 text-amber-100"><strong>Analytics reports are temporarily unavailable.</strong><p>Do not use the scale decision until the missing data source recovers.</p></div>:null}
  {!queryFailed&&(!paymentTrackingReliable||!funnelTrackingReliable)?<div className="mt-5 rounded-2xl border border-sky-400/20 bg-sky-500/10 p-4 text-sm leading-6 text-sky-100"><strong>Tracking calibration in progress.</strong><p>Verified paid orders and revenue remain authoritative. Event funnel percentages are diagnostic only until sequential tracking is consistent.</p></div>:null}
  <div className="mt-5 flex flex-wrap gap-2">{Object.keys(ranges).map(range=><Link key={range} href={`?range=${range}`} className={`rounded-xl px-4 py-2 text-xs font-bold ${range===key?"bg-orange-500 text-white":"border border-white/10 text-slate-300"}`}>{range==="today"?"Today":`Last ${range.slice(0,-1)} days`}</Link>)}</div>
  <section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(([label,value])=><article key={label} className="min-w-0 rounded-2xl border border-white/10 bg-[#111] p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 break-words text-2xl font-black text-white">{value}</p></article>)}</section>
  <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Gross revenue",money(gross),"Verified paid orders before refunds"],["Net revenue",money(netRevenue),"Verified gross revenue minus completed refunds"],["Average order value",money(aov),"Target: ₹1,500+"],["Revenue / day",money(revenuePerDay),`Average across ${key==="today"?"today":`${days} days`}`],["Paid orders",paidOrders.length,"Verified paid/completed orders"]].map(([label,value,note])=><article key={label} className="rounded-2xl border border-white/10 bg-[#111] p-5"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 text-2xl font-black text-white">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{note}</p></article>)}</section>
  <section className="mt-6 rounded-2xl border border-emerald-400/20 bg-[#111] p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-300">Acquisition → verified revenue</p><h2 className="mt-2 text-xl font-black text-white">Which traffic actually becomes paid orders?</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">Revenue comes only from verified paid-order records. First-party analytics is used only to attach source, medium and campaign to the matching order ID. Historical orders without a matching attribution event stay explicitly unattributed.</p></div><span className="w-fit rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-xs font-black text-emerald-200">{attributionCoverage.toFixed(1)}% paid-order coverage</span></div>
  <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Attributed paid orders",attributedPaidOrders,"Paid orders linked to a source"],["Attributed revenue",money(attributedRevenue),"Verified paid-order revenue with source data"],["Unattributed revenue",money(unattributedRevenue),"Kept visible instead of guessed"],["Tracked source rows",sourceRevenue.size,"Source / medium combinations"]].map(([label,value,note])=><article key={label} className="rounded-xl border border-white/10 bg-black/25 p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 text-xl font-black text-white">{value}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{note}</p></article>)}</div>
  <div className="mt-5 grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><article className="rounded-xl border border-white/10 bg-black/25 p-4"><div className="grid grid-cols-[1fr_auto_auto_auto] gap-3 border-b border-white/10 pb-3 text-[10px] font-black uppercase tracking-[.12em] text-slate-500"><span>Source / medium</span><span>Orders</span><span>AOV</span><span>Revenue</span></div>{topSources.length?<div className="divide-y divide-white/[.06]">{topSources.map(row=><div key={`${row.source}:${row.medium}`} className="grid grid-cols-[1fr_auto_auto_auto] items-center gap-3 py-3 text-xs"><div className="min-w-0"><p className="truncate font-bold capitalize text-white">{row.source}</p><p className="truncate text-[11px] text-slate-500">{row.medium}</p></div><span className="text-right text-slate-300">{row.orders}</span><span className="text-right text-slate-300">{money(row.orders?row.revenue/row.orders:0)}</span><span className="text-right font-black text-white">{money(row.revenue)}</span></div>)}</div>:<p className="py-8 text-center text-sm text-slate-500">No paid-order attribution data in this range yet.</p>}</article>
  <article className="rounded-xl border border-white/10 bg-black/25 p-4"><h3 className="text-sm font-black text-white">Campaign revenue</h3><p className="mt-1 text-[11px] leading-5 text-slate-500">UTM campaigns with verified paid-order matches.</p>{topCampaigns.length?<div className="mt-4 space-y-3">{topCampaigns.map(row=><div key={`${row.source}:${row.campaign}`} className="rounded-lg border border-white/[.07] bg-white/[.025] p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-xs font-bold text-white">{row.campaign}</p><p className="mt-1 truncate text-[10px] capitalize text-slate-500">{row.source} · {row.orders} paid order{row.orders===1?"":"s"}</p></div><b className="shrink-0 text-xs text-emerald-200">{money(row.revenue)}</b></div></div>)}</div>:<p className="mt-4 rounded-lg border border-dashed border-white/10 p-5 text-center text-xs leading-5 text-slate-500">Campaign attribution will populate from new tagged traffic. No historical campaign revenue is inferred.</p>}</article></div>
  </section>
  <section className="mt-6 rounded-2xl border border-orange-400/20 bg-[#111] p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-orange-300">Phase 2 movement</p><h2 className="mt-2 text-xl font-black text-white">Day 30 baseline → current selected range</h2></div><p className="text-xs text-slate-500">Baseline: 30-day audit before Phase 2</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["AOV",phase2Baseline.aov,aov,"₹"],["Revenue / day",phase2Baseline.revenuePerDay,revenuePerDay,"₹"],["Repeat rate",phase2Baseline.repeatRate,repeatRate,"%"],["Refund rate",phase2Baseline.refundRate,refundRate,"%"]].map(([label,base,current,unit])=>{const b=Number(base),v=Number(current),change=b?((v-b)/b)*100:0;const lowerIsBetter=label==="Refund rate";const improved=lowerIsBetter?v<=b:v>=b;return <article key={String(label)} className="rounded-xl border border-white/10 bg-black/25 p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 text-lg font-black text-white">{unit==="₹"?money(v):`${v.toFixed(1)}%`}</p><p className="mt-1 text-[11px] text-slate-500">Baseline {unit==="₹"?money(b):`${b.toFixed(1)}%`}</p><p className={`mt-2 text-xs font-bold ${improved?"text-emerald-300":"text-amber-300"}`}>{change>=0?"+":""}{change.toFixed(1)}% vs baseline</p></article>})}</div><p className="mt-4 text-[11px] leading-5 text-slate-500">Compare like-for-like ranges when judging progress. Revenue figures use verified paid-order records; event-funnel telemetry is not used to manufacture revenue.</p></section>
  <RevenueAuditDecision decision={queryFailed?"WATCH":audit.decision} signals={queryFailed?[{status:"watch",title:"Audit data unavailable",reason:"One or more required data sources failed to load.",action:"Wait for the data source to recover before making a scale decision.",href:"/admin/analytics",score:999}]:audit.signals}/>
  <section className="mt-6 rounded-2xl border border-white/10 bg-[#111] p-5"><h2 className="text-xl font-black text-white">Tracked journey events</h2><p className="mt-1 text-xs leading-5 text-slate-500">Aggregate event counts are diagnostic. They are only treated as a sequential funnel when every later stage is less than or equal to the prior stage.</p>{events.length?<ol className="mt-5 grid gap-3 lg:grid-cols-6">{funnelData.map((step,index)=>{const previous=index?funnelData[index-1]:null;const validTransition=Boolean(previous&&step.total<=previous.total);return <li key={step.name} className="rounded-xl bg-black/30 p-4"><p className="break-words text-xs capitalize text-slate-300">{step.name.replaceAll("_"," ")}</p><p className="mt-2 text-2xl font-black text-white">{step.total}</p><p className="mt-1 text-xs text-orange-300">{!previous?"Entry event":validTransition?`${pct(previous.total,step.total)} continued · ${previous.total?pct(previous.total,Math.max(0,previous.total-step.total)):"—"} drop-off`:"Non-sequential event count"}</p></li>})}</ol>:<p className="mt-5 rounded-xl border border-dashed border-white/15 p-8 text-center text-slate-400">Not enough data.</p>}</section>
  <section className="mt-6 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-white/10 bg-[#111] p-5"><h2 className="text-xl font-black text-white">Top revenue services</h2><p className="mt-1 text-xs text-slate-500">Verified paid-order revenue in the selected range.</p>{topServices.length?<div className="mt-5 space-y-3">{topServices.map(([name,s],i)=><div key={name} className="grid grid-cols-[auto_1fr_auto] items-center gap-3 rounded-xl bg-black/30 p-4"><span className="grid h-8 w-8 place-items-center rounded-lg bg-orange-500/15 text-xs font-black text-orange-300">{i+1}</span><div className="min-w-0"><p className="truncate text-sm font-bold text-white">{name}</p><p className="text-xs capitalize text-slate-500">{s.platform} · {s.orders} order{s.orders===1?"":"s"}</p></div><p className="text-sm font-black text-white">{money(s.revenue)}</p></div>)}</div>:<p className="mt-5 text-sm text-slate-400">No paid orders in this range.</p>}</article><article className="rounded-2xl border border-orange-400/20 bg-gradient-to-br from-orange-500/10 to-transparent p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-orange-300">Decision guardrails</p><h2 className="mt-2 text-xl font-black text-white">Scale only what verified data supports</h2><div className="mt-5 space-y-3 text-sm text-slate-300"><p>Tracked payment success: <b className="text-white">95%+</b> <span className="text-slate-500">(only when tracking is reliable)</span></p><p>AOV: <b className="text-white">₹1,500+</b></p><p>Refund rate: <b className="text-white">&lt;5%</b></p><p>Repeat orders: <b className="text-white">25%+</b></p><p className="pt-2 text-xs leading-5 text-slate-500">Verified order/payment status remains authoritative when analytics events are incomplete.</p></div></article></section>
  </div></main>;
}
