export type AuditSignal={status:"scale"|"fix"|"watch";title:string;reason:string;action:string;href:string;score:number};
export type FunnelStep={name:string;total:number};
export type ServicePerformance={name:string;platform:string;revenue:number;orders:number};
export type RevenueAuditInput={gross:number;netRevenue:number;aov:number;refundRate:number;repeatRate:number;paymentSuccess:number|null;paymentTrackingReliable:boolean;revenuePerDay:number;paidOrders:number;funnel:FunnelStep[];funnelTrackingReliable:boolean;services:ServicePerformance[]};
export const revenueTargets={payment:95,aov:1500,refund:5,repeat:25};
export const phase2Baseline={aov:475,revenuePerDay:1842,repeatRate:38,refundRate:3};
const delta=(current:number,baseline:number)=>baseline?((current-baseline)/baseline)*100:0;
export function buildRevenueAudit(input:RevenueAuditInput){
 const target=revenueTargets,signals:AuditSignal[]=[];
 if(input.paymentTrackingReliable&&input.paymentSuccess!==null){if(input.paymentSuccess<target.payment)signals.push({status:"fix",title:"Tracked payment completion is below target",reason:`${input.paymentSuccess.toFixed(1)}% vs ${target.payment}%+ target`,action:"Audit payment and checkout friction before adding traffic.",href:"/admin/payments",score:100+(target.payment-input.paymentSuccess)});else signals.push({status:"scale",title:"Tracked payment completion is healthy",reason:`${input.paymentSuccess.toFixed(1)}% meets the ${target.payment}%+ target`,action:"Keep monitoring while increasing qualified traffic.",href:"/admin/analytics",score:60});}else if(input.paidOrders>0)signals.push({status:"watch",title:"Payment event tracking needs calibration",reason:`${input.paidOrders} verified paid orders exist, but payment-event tracking is incomplete or inconsistent`,action:"Use verified paid orders for revenue decisions while payment events are repaired.",href:"/admin/analytics",score:105});
 if(input.aov<target.aov)signals.push({status:"fix",title:"Average order value remains the primary growth constraint",reason:`₹${Math.round(input.aov).toLocaleString("en-IN")} vs ₹${target.aov.toLocaleString("en-IN")}+ target · ${delta(input.aov,phase2Baseline.aov)>=0?"+":""}${delta(input.aov,phase2Baseline.aov).toFixed(1)}% vs Day 30 baseline`,action:"Prioritize larger quantities, packages, campaign stacks and relevant cross-sells before broad paid scaling.",href:"/packages",score:115});else signals.push({status:"scale",title:"AOV supports controlled growth",reason:`₹${Math.round(input.aov).toLocaleString("en-IN")} meets the ₹${target.aov.toLocaleString("en-IN")}+ target`,action:"Protect this AOV while scaling verified winning acquisition paths.",href:"/admin/analytics",score:70});
 if(input.refundRate>=target.refund)signals.push({status:"fix",title:"Refund leakage is too high",reason:`${input.refundRate.toFixed(1)}% vs <${target.refund}% target`,action:"Inspect refund reasons and weak services before promotion.",href:"/admin/orders",score:110});else signals.push({status:"scale",title:"Refund rate is controlled",reason:`${input.refundRate.toFixed(1)}% is below the ${target.refund}% ceiling`,action:"Continue monitoring service quality as volume grows.",href:"/admin/orders",score:55});
 if(input.repeatRate<target.repeat)signals.push({status:"watch",title:"Repeat revenue has headroom",reason:`${input.repeatRate.toFixed(1)}% vs ${target.repeat}%+ target`,action:"Use reactivation, reorder and retainer journeys to increase LTV.",href:"/admin/crm/reactivation",score:75});else signals.push({status:"scale",title:"Repeat purchase behavior is strong",reason:`${input.repeatRate.toFixed(1)}% meets the ${target.repeat}%+ target`,action:"Keep reactivation and recurring-client journeys active.",href:"/admin/crm/reactivation",score:65});
 if(input.revenuePerDay>0)signals.push({status:input.revenuePerDay>=phase2Baseline.revenuePerDay?"scale":"watch",title:"Revenue velocity vs Day 30 baseline",reason:`₹${Math.round(input.revenuePerDay).toLocaleString("en-IN")}/day · ${delta(input.revenuePerDay,phase2Baseline.revenuePerDay)>=0?"+":""}${delta(input.revenuePerDay,phase2Baseline.revenuePerDay).toFixed(1)}% vs ₹${phase2Baseline.revenuePerDay.toLocaleString("en-IN")}/day baseline`,action:"Use verified paid-order revenue to judge whether Phase 2 is increasing revenue velocity.",href:"/admin/analytics",score:72});
 if(!input.funnelTrackingReliable)signals.push({status:"watch",title:"Sequential funnel is not yet reliable",reason:"Aggregate event totals cannot be treated as one customer cohort.",action:"Keep funnel percentages diagnostic until session-linked instrumentation is consistent.",href:"/admin/analytics",score:108});
 const leader=input.services[0];if(leader&&leader.orders>=2)signals.push({status:"scale",title:`Verified revenue leader: ${leader.name}`,reason:`₹${Math.round(leader.revenue).toLocaleString("en-IN")} from ${leader.orders} paid orders in this range`,action:"Give this service more qualified SEO, reactivation and partner attention without changing unverified claims.",href:"/services",score:80});
 if(input.paidOrders<5)signals.push({status:"watch",title:"Sample size is still small",reason:`Only ${input.paidOrders} paid orders in the selected range`,action:"Treat scale decisions as directional until more verified orders accumulate.",href:"/admin/analytics",score:120});
 const ranked=signals.sort((a,b)=>b.score-a.score),blockers=ranked.filter(x=>x.status==="fix");
 const decision=input.paidOrders<5?"WATCH":blockers.length?"FIX BEFORE SCALE":"SCALE CONTROLLED";
 return {decision,signals:ranked,targets:target,baseline:phase2Baseline};
}
