export type AuditSignal={status:"scale"|"fix"|"watch";title:string;reason:string;action:string;href:string;score:number};
export type FunnelStep={name:string;total:number};
export type ServicePerformance={name:string;platform:string;revenue:number;orders:number};
export type RevenueAuditInput={gross:number;netRevenue:number;aov:number;refundRate:number;repeatRate:number;paymentSuccess:number|null;paymentTrackingReliable:boolean;revenuePerDay:number;paidOrders:number;funnel:FunnelStep[];funnelTrackingReliable:boolean;services:ServicePerformance[]};
const target={payment:95,aov:1500,refund:5,repeat:25};
export function buildRevenueAudit(input:RevenueAuditInput){
 const signals:AuditSignal[]=[];
 if(input.paymentTrackingReliable&&input.paymentSuccess!==null){if(input.paymentSuccess<target.payment)signals.push({status:"fix",title:"Tracked payment completion is below target",reason:`${input.paymentSuccess.toFixed(1)}% vs ${target.payment}%+ target`,action:"Audit payment and checkout friction before adding traffic.",href:"/admin/payments",score:100+(target.payment-input.paymentSuccess)});else signals.push({status:"scale",title:"Tracked payment completion is healthy",reason:`${input.paymentSuccess.toFixed(1)}% meets the ${target.payment}%+ target`,action:"Keep monitoring while increasing qualified traffic.",href:"/admin/analytics",score:60});}else if(input.paidOrders>0)signals.push({status:"watch",title:"Payment event tracking needs calibration",reason:`${input.paidOrders} verified paid orders exist, but payment-event tracking is incomplete or inconsistent`,action:"Use verified paid orders for revenue decisions while payment events are repaired.",href:"/admin/analytics",score:105});
 if(input.aov<target.aov)signals.push({status:"fix",title:"Average order value needs work",reason:`₹${Math.round(input.aov).toLocaleString("en-IN")} vs ₹${target.aov.toLocaleString("en-IN")}+ target`,action:"Prioritize quantity ladders, campaign stacks and relevant cross-sells.",href:"/admin/analytics",score:90});else signals.push({status:"scale",title:"AOV is ready to support growth",reason:`₹${Math.round(input.aov).toLocaleString("en-IN")} meets the ₹${target.aov.toLocaleString("en-IN")}+ target`,action:"Protect this AOV while scaling winning acquisition paths.",href:"/admin/analytics",score:65});
 if(input.refundRate>=target.refund)signals.push({status:"fix",title:"Refund leakage is too high",reason:`${input.refundRate.toFixed(1)}% vs <${target.refund}% target`,action:"Inspect refund reasons and weak services before promotion.",href:"/admin/orders",score:95+input.refundRate});else signals.push({status:"scale",title:"Refund rate is controlled",reason:`${input.refundRate.toFixed(1)}% is below the ${target.refund}% ceiling`,action:"Continue monitoring service quality as volume grows.",href:"/admin/orders",score:55});
 if(input.repeatRate<target.repeat)signals.push({status:"watch",title:"Repeat revenue has headroom",reason:`${input.repeatRate.toFixed(1)}% vs ${target.repeat}%+ target`,action:"Use reactivation, reorder and retainer journeys to increase LTV.",href:"/admin/crm/reactivation",score:75});else signals.push({status:"scale",title:"Repeat purchase behavior is strong",reason:`${input.repeatRate.toFixed(1)}% meets the ${target.repeat}%+ target`,action:"Scale retention and reseller/retainer journeys.",href:"/admin/crm/reactivation",score:70});
 let biggest:{from:string;to:string;rate:number;lost:number}|null=null;if(input.funnelTrackingReliable){for(let i=1;i<input.funnel.length;i++){const prev=input.funnel[i-1],cur=input.funnel[i];if(prev.total<=0)continue;const rate=((prev.total-cur.total)/prev.total)*100;if(rate<0)continue;if(!biggest||rate>biggest.rate)biggest={from:prev.name,to:cur.name,rate,lost:Math.max(0,prev.total-cur.total)};}if(biggest&&biggest.rate>20)signals.push({status:"fix",title:"Biggest tracked funnel leak",reason:`${biggest.rate.toFixed(1)}% drop from ${biggest.from.replaceAll("_"," ")} → ${biggest.to.replaceAll("_"," ")} (${biggest.lost} lost)`,action:"Fix this transition before spending more on acquisition.",href:"/admin/analytics",score:110+biggest.rate});}else signals.push({status:"watch",title:"Sequential funnel is not yet reliable",reason:"Tracked stage totals move backwards or exceed prior stages, so aggregate events cannot be treated as one customer cohort.",action:"Calibrate funnel instrumentation before using drop-off percentages for spend decisions.",href:"/admin/analytics",score:108});
 const leader=input.services[0];if(leader&&leader.orders>=2)signals.push({status:"scale",title:`Winning service: ${leader.name}`,reason:`₹${Math.round(leader.revenue).toLocaleString("en-IN")} from ${leader.orders} paid orders in this range`,action:"Give this service more SEO, homepage, remarketing and partner attention without changing unverified claims.",href:"/services",score:80});
 if(input.paidOrders<5)signals.push({status:"watch",title:"Sample size is still small",reason:`Only ${input.paidOrders} paid orders in the selected range`,action:"Treat scale decisions as directional until more verified orders accumulate.",href:"/admin/analytics",score:120});
 const ranked=signals.sort((a,b)=>b.score-a.score);const blockers=ranked.filter(x=>x.status==="fix");const decision=input.paidOrders<5?"WATCH":blockers.length?"FIX BEFORE SCALE":"SCALE CONTROLLED";
 return {decision,signals:ranked,biggestLeak:biggest,targets:target};
}
