import type { AuditSignal, ServicePerformance } from "./revenue-audit";
export type ScaleLane={status:"now"|"next"|"hold";title:string;why:string;actions:string[];href:string};
export function buildScalePlan({decision,signals,services,paidOrders}:{decision:string;signals:AuditSignal[];services:ServicePerformance[];paidOrders:number}){
 const fixes=signals.filter(s=>s.status==="fix"); const leader=services[0]; const lanes:ScaleLane[]=[];
 if(decision==="FIX BEFORE SCALE")lanes.push({status:"now",title:"Repair the revenue bottleneck",why:fixes[0]?.reason||"The audit found a blocking conversion issue.",actions:fixes.slice(0,3).map(x=>x.action),href:fixes[0]?.href||"/admin/analytics"});
 else if(decision==="WATCH")lanes.push({status:"now",title:"Grow the evidence base",why:`${paidOrders} verified paid orders is not enough for an aggressive scale call.`,actions:["Keep acquisition low-cost and measurable.","Prioritize existing SEO, reactivation, referrals and qualified agency outreach.","Re-check the 30-day audit as verified paid orders accumulate."],href:"/admin/analytics"});
 else lanes.push({status:"now",title:"Scale qualified acquisition carefully",why:"Core audit guardrails are not currently blocking controlled growth.",actions:["Increase attention on proven conversion paths.","Protect payment completion, AOV and refund performance while volume rises.","Review the audit weekly and stop scaling if a blocker appears."],href:"/admin/analytics"});
 if(leader)lanes.push({status:leader.orders>=2?"next":"hold",title:`Revenue leader: ${leader.name}`,why:`₹${Math.round(leader.revenue).toLocaleString("en-IN")} from ${leader.orders} verified paid order${leader.orders===1?"":"s"} in this range.`,actions:leader.orders>=2?["Strengthen internal links and commercial SEO around this service.","Feature it in relevant reactivation, partner and remarketing journeys.","Do not change pricing or claims without current service economics."]:["Collect more verified orders before concentrating spend.","Keep the service discoverable through existing organic paths."],href:"/services"});
 lanes.push({status:decision==="SCALE CONTROLLED"?"next":"hold",title:"Agency + reseller growth",why:"Higher-value B2B demand can improve revenue concentration only after the core checkout is dependable.",actions:["Use the existing agency qualification funnel and CRM outreach.","Prioritize qualified bulk/reseller leads over broad spam outreach.","Track verified revenue separately from lead volume."],href:"/admin/crm"});
 lanes.push({status:decision==="SCALE CONTROLLED"?"next":"hold",title:"International expansion",why:"Country/service pages already exist; expansion should follow measured demand rather than page count.",actions:["Scale countries showing qualified traffic and paid orders.","Keep checkout amounts authoritative in INR where applicable.","Avoid creating thin country pages without evidence of demand."],href:"/admin/analytics"});
 return lanes;
}
