import AudienceLandingPage from "@/components/marketing/audiences/AudienceLandingPage";
import BulkLeadEngine from "@/components/marketing/BulkLeadEngine";
import BreadcrumbJsonLd from "@/components/seo/BreadcrumbJsonLd";
import { audiencePages } from "@/lib/marketing/audience-pages";
import { createPageMetadata, SEO_SITE_URL } from "@/lib/seo/metadata";
const config=audiencePages.agencies;
export const metadata=createPageMetadata({title:"Social Media Services for Agencies India | SocialRUSH",description:"SocialRUSH agency and reseller services in India with qualified bulk enquiries, WhatsApp campaign handoff, agency workspace, bulk job planning and repeat campaign workflows.",path:"/for-agencies",keywords:["social media services for agencies India","social media reseller services India","agency social media campaign services","bulk social media service enquiry","social media packages for agencies","social media reseller panel India","bulk Instagram services India","agency YouTube growth services"]});
const jsonLd=(value:object)=>JSON.stringify(value).replace(/</g,"\\u003c");
export default function ForAgenciesPage(){const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:config.faqs.map(faq=>({"@type":"Question",name:faq.question,acceptedAnswer:{"@type":"Answer",text:faq.answer}}))};const discoverySchema={"@context":"https://schema.org","@type":"ItemList",name:"SocialRUSH agency and reseller workflow",itemListElement:[["Qualified Bulk / Agency Enquiry","/for-agencies#bulk-lead-engine"],["Agency / Reseller Hub","/dashboard/reseller"],["Bulk Job Planner","/dashboard/reseller/bulk-planner"],["Campaign Stacks","/dashboard/campaign-stacks"],["Agency Support","/contact#support-form"]].map(([name,path],index)=>({"@type":"ListItem",position:index+1,name,url:`${SEO_SITE_URL}${path}`}))};return <><BreadcrumbJsonLd items={[{name:"Home",path:"/"},{name:"For Agencies",path:"/for-agencies"}]}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(faqSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(discoverySchema)}}/><AudienceLandingPage config={config}/><BulkLeadEngine/></>}
