"use client";

import Link from "next/link";
import { AlertTriangle, CheckCircle2, CircleDashed, Copy, CreditCard, Eye, Landmark, ReceiptText, RefreshCw, Search, Wallet, XCircle } from "lucide-react";
import { useMemo, useState } from "react";
import CurrencyAmount from "@/components/currency/CurrencyAmount";

type Invoice = { id: string; invoice_number: string; amount: number; status: string; created_at: string; order_id: string | null };
type Payment = { id: string; amount: number; type: string; status: string; payment_method: string | null; provider_order_id: string | null; provider_payment_id: string | null; provider_refund_id: string | null; description: string | null; metadata: Record<string, unknown> | null; created_at: string };
type Props = { invoices: Invoice[]; payments: Payment[]; invoiceError?: string; paymentError?: string; walletBalance: number };

const completed = new Set(["paid", "completed", "success", "successful"]);
const pending = new Set(["pending", "processing", "created"]);
const failed = new Set(["failed", "cancelled", "canceled"]);

function statusLabel(status: string) { return status.replaceAll("_", " "); }
function statusStyle(status: string) {
  const value = status.toLowerCase();
  if (completed.has(value)) return "border-emerald-400/25 bg-emerald-500/10 text-emerald-200";
  if (pending.has(value)) return "border-amber-400/25 bg-amber-500/10 text-amber-200";
  if (failed.has(value)) return "border-red-400/25 bg-red-500/10 text-red-200";
  if (value === "refunded") return "border-sky-400/25 bg-sky-500/10 text-sky-200";
  return "border-white/15 bg-white/[.06] text-slate-200";
}
function StatusBadge({ status }: { status: string }) { return <span className={`inline-flex max-w-full items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-bold capitalize ${statusStyle(status)}`}><i className="h-1.5 w-1.5 shrink-0 rounded-full bg-current" /><span className="truncate">{statusLabel(status)}</span></span>; }
function methodLabel(method: string | null, type: string) { return (method || (type === "debit" ? "wallet" : type)).replaceAll("_", " "); }
function reference(item: Payment) { return item.provider_payment_id || item.provider_order_id || item.provider_refund_id || item.id; }
function relatedOrder(item: Payment) { const id = item.metadata?.order_id; return typeof id === "string" ? id : null; }
function dateTime(value: string) { return new Date(value).toLocaleString("en-IN", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }); }

export default function BillingDashboardContent({ invoices, payments, invoiceError, paymentError, walletBalance }: Props) {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [method, setMethod] = useState("all"); const [selected, setSelected] = useState<Payment | null>(null); const [copied, setCopied] = useState("");
  const statuses = useMemo(() => Array.from(new Set(payments.map((item) => item.status).filter(Boolean))).sort(), [payments]);
  const methods = useMemo(() => Array.from(new Set(payments.map((item) => item.payment_method).filter((item): item is string => Boolean(item)))).sort(), [payments]);
  const filtered = useMemo(() => payments.filter((item) => {
    const haystack = `${reference(item)} ${item.id} ${relatedOrder(item) || ""} ${item.description || ""}`.toLowerCase();
    return haystack.includes(search.toLowerCase()) && (status === "all" || item.status === status) && (method === "all" || item.payment_method === method);
  }), [method, payments, search, status]);
  const summary = useMemo(() => ({ total: payments.length, completed: payments.filter((item) => completed.has(item.status.toLowerCase())).length, pending: payments.filter((item) => pending.has(item.status.toLowerCase())).length, failed: payments.filter((item) => failed.has(item.status.toLowerCase()) || item.status.toLowerCase() === "refunded").length }), [payments]);
  const copy = async (value: string) => { await navigator.clipboard.writeText(value); setCopied(value); window.setTimeout(() => setCopied(""), 1600); };

  return <main className="min-h-[calc(100vh-5rem)] overflow-x-clip bg-[radial-gradient(circle_at_top_left,rgba(255,122,0,.14),transparent_32%),#050505] px-4 pb-24 pt-5 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-[1500px]">
    <header className="flex flex-col gap-5 border-b border-white/10 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-orange-300">Billing</p><h1 className="mt-2 text-3xl font-black tracking-[-.035em] text-white sm:text-4xl">Billing &amp; payment history</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Review your SocialRUSH payment activity, transaction status and related order information.</p></div><Link href="/dashboard/wallet" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-orange-400/25 bg-orange-500/10 px-4 text-sm font-bold text-orange-100 transition hover:border-orange-400/60 hover:bg-orange-500/20 focus:outline-none focus:ring-4 focus:ring-orange-400/15"><Wallet className="h-4 w-4" />View Wallet</Link></header>

    {!paymentError && payments.length ? <section aria-label="Payment summary" className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Total payments", summary.total, ReceiptText, "text-white"], ["Completed", summary.completed, CheckCircle2, "text-emerald-300"], ["Pending", summary.pending, RefreshCw, "text-amber-200"], ["Failed / refunded", summary.failed, XCircle, "text-red-300"]].map(([label, value, Icon, tone]) => { const SummaryIcon = Icon as typeof ReceiptText; return <article key={String(label)} className="rounded-2xl border border-white/10 bg-[linear-gradient(135deg,rgba(255,255,255,.06),rgba(255,255,255,.018))] p-4 shadow-[0_18px_36px_-30px_rgba(0,0,0,.9)]"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.13em] text-slate-400"><SummaryIcon className={`h-4 w-4 ${tone}`} />{String(label)}</div><p className="mt-2 text-2xl font-black text-white sm:text-3xl">{String(value)}</p></article>; })}</section> : null}

    <section className="mt-5 overflow-hidden rounded-2xl border border-white/10 bg-[#101116] shadow-[0_28px_60px_-42px_rgba(0,0,0,.95)]"><div className="flex flex-col gap-4 border-b border-white/10 p-4 sm:p-5"><div><h2 className="text-base font-black text-white">Payment activity</h2><p className="mt-1 text-xs text-slate-400">Live transaction records from your account.</p></div>{!paymentError && payments.length ? <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-[minmax(0,1.5fr)_minmax(10rem,.65fr)_minmax(10rem,.65fr)]"><label className="relative min-w-0"><span className="sr-only">Search payment activity</span><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-orange-300" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="min-h-11 w-full rounded-xl border border-white/10 bg-black/25 py-2 pl-9 pr-3 text-sm text-white outline-none placeholder:text-slate-500 focus:border-orange-400/60 focus:ring-4 focus:ring-orange-400/10" placeholder="Search payment or order reference" /></label><label><span className="sr-only">Filter payment status</span><select value={status} onChange={(event) => setStatus(event.target.value)} className="min-h-11 w-full rounded-xl border border-white/10 bg-black/25 px-3 text-sm text-white outline-none focus:border-orange-400/60"><option value="all">All statuses</option>{statuses.map((item) => <option key={item} value={item}>{statusLabel(item)}</option>)}</select></label><label><span className="sr-only">Filter payment method</span><select value={method} onChange={(event) => setMethod(event.target.value)} className="min-h-11 w-full rounded-xl border border-white/10 bg-black/25 px-3 text-sm text-white outline-none focus:border-orange-400/60"><option value="all">All methods</option>{methods.map((item) => <option key={item} value={item}>{methodLabel(item, "")}</option>)}</select></label></div> : null}</div>
      {paymentError ? <ErrorState /> : <><div className="hidden lg:block"><div className="grid grid-cols-[minmax(13rem,1.2fr)_minmax(10rem,.75fr)_minmax(9rem,.7fr)_minmax(9rem,.65fr)_minmax(10rem,.85fr)_7rem] gap-4 border-b border-white/10 bg-black/20 px-5 py-3 text-[9px] font-black uppercase tracking-[.14em] text-slate-500"><span>Reference</span><span>Method</span><span>Amount</span><span>Status</span><span>Date &amp; order</span><span className="text-right">Details</span></div>{filtered.map((item) => <DesktopRow key={item.id} item={item} open={() => setSelected(item)} />)}{!filtered.length ? <EmptyState filtered={payments.length > 0} /> : null}</div><div className="grid gap-3 p-3 lg:hidden">{filtered.map((item) => <MobileCard key={item.id} item={item} open={() => setSelected(item)} />)}{!filtered.length ? <EmptyState filtered={payments.length > 0} /> : null}</div></>}
    </section>
    {!invoiceError && invoices.length ? <section className="mt-5 rounded-2xl border border-white/10 bg-[#101116] p-4 sm:p-5"><h2 className="text-sm font-black">Invoice records</h2><p className="mt-1 text-xs text-slate-400">Invoice metadata available for your account. No downloadable documents are currently provided.</p><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{invoices.map((item) => <div key={item.id} className="min-w-0 rounded-xl border border-white/10 bg-black/20 p-3"><div className="flex items-center justify-between gap-2"><p className="truncate text-xs font-bold text-orange-200">{item.invoice_number}</p><StatusBadge status={item.status} /></div><div className="mt-3 flex items-end justify-between gap-3"><span className="text-xs text-slate-400">{new Date(item.created_at).toLocaleDateString("en-IN")}</span><span className="text-sm font-black"><CurrencyAmount amountINR={item.amount} /></span></div>{item.order_id ? <Link className="mt-3 inline-flex min-h-10 items-center text-xs font-bold text-orange-300" href={`/dashboard/orders/${item.order_id}`}>View Order</Link> : null}</div>)}</div></section> : null}
    <aside className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-orange-400/15 bg-orange-500/[.06] p-4 text-xs text-slate-300"><span>Wallet balance <strong className="ml-1 text-white"><CurrencyAmount amountINR={walletBalance} /></strong></span><Link href="/dashboard/wallet" className="font-bold text-orange-200">Manage wallet</Link></aside>
  </div>{selected ? <PaymentDetails item={selected} close={() => setSelected(null)} copy={copy} copied={copied} /> : null}</main>;
}

function DesktopRow({ item, open }: { item: Payment; open: () => void }) { const order = relatedOrder(item); return <article className="grid grid-cols-[minmax(13rem,1.2fr)_minmax(10rem,.75fr)_minmax(9rem,.7fr)_minmax(9rem,.65fr)_minmax(10rem,.85fr)_7rem] items-center gap-4 px-5 py-4 transition hover:bg-white/[.035]"><div className="min-w-0"><p className="truncate font-mono text-xs font-bold text-orange-300">{reference(item)}</p><p className="mt-1 truncate text-[10px] text-slate-500">{item.description || item.type}</p></div><div className="flex min-w-0 items-center gap-2 capitalize text-sm font-semibold text-white"><MethodIcon method={item.payment_method} type={item.type} /> <span className="truncate">{methodLabel(item.payment_method, item.type)}</span></div><span className={`text-sm font-black ${item.type === "refund" ? "text-sky-200" : "text-white"}`}><CurrencyAmount amountINR={item.amount} /></span><StatusBadge status={item.status} /><div className="min-w-0"><p className="text-xs text-slate-300">{dateTime(item.created_at)}</p>{order ? <Link href={`/dashboard/orders/${order}`} className="mt-1 inline-block font-mono text-[10px] font-bold text-orange-300">Order #{order.slice(0, 8)}</Link> : null}</div><button aria-label={`View details for ${reference(item)}`} type="button" onClick={open} className="ml-auto inline-flex min-h-10 items-center justify-center gap-1 rounded-lg border border-orange-400/25 bg-orange-500/10 px-3 text-[11px] font-bold text-orange-100 focus:outline-none focus:ring-4 focus:ring-orange-400/15"><Eye className="h-3.5 w-3.5" />View</button></article>; }
function MobileCard({ item, open }: { item: Payment; open: () => void }) { const order = relatedOrder(item); return <article className="min-w-0 rounded-2xl border border-white/10 bg-[linear-gradient(135deg,rgba(255,255,255,.055),rgba(255,255,255,.018))] p-4"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-2 capitalize text-sm font-black text-white"><MethodIcon method={item.payment_method} type={item.type} /><span className="truncate">{methodLabel(item.payment_method, item.type)}</span></div><StatusBadge status={item.status} /></div><div className="mt-4 flex items-end justify-between gap-3"><p className={`text-xl font-black ${item.type === "refund" ? "text-sky-200" : "text-white"}`}><CurrencyAmount amountINR={item.amount} /></p><p className="text-right text-[11px] text-slate-400">{dateTime(item.created_at)}</p></div><div className="mt-4 rounded-xl border border-white/[.08] bg-black/20 p-3"><p className="text-[9px] font-black uppercase tracking-[.12em] text-slate-500">Payment reference</p><p className="mt-1 truncate font-mono text-xs font-bold text-orange-200">{reference(item)}</p>{order ? <Link href={`/dashboard/orders/${order}`} className="mt-2 inline-flex text-xs font-bold text-orange-300">View Order #{order.slice(0, 8)}</Link> : null}</div><button type="button" onClick={open} className="mt-3 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-orange-400/25 bg-orange-500/10 text-sm font-bold text-orange-100 focus:outline-none focus:ring-4 focus:ring-orange-400/15"><Eye className="h-4 w-4" />Details</button></article>; }
function MethodIcon({ method, type }: { method: string | null; type: string }) { const value = (method || type).toLowerCase(); const Icon = value.includes("wallet") ? Wallet : value.includes("bank") || value.includes("upi") ? Landmark : CreditCard; return <span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg border border-white/10 bg-white/[.05] text-orange-300"><Icon className="h-4 w-4" /></span>; }
function EmptyState({ filtered }: { filtered: boolean }) { return <div className="p-8 text-center sm:p-12"><CircleDashed className="mx-auto h-7 w-7 text-orange-300" /><p className="mt-3 text-base font-black text-white">{filtered ? "No payment activity matches these filters" : "No billing activity yet"}</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-400">{filtered ? "Try adjusting the search or filters to see other transaction records." : "Your payment and transaction records will appear here after you fund your wallet or place an order."}</p>{!filtered ? <Link href="/dashboard/wallet" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-gradient-to-r from-[#FF7A00] to-[#FFB000] px-5 text-sm font-black">View Wallet</Link> : null}</div>; }
function ErrorState() { return <div className="p-8 text-center sm:p-12"><AlertTriangle className="mx-auto h-7 w-7 text-red-300" /><p className="mt-3 text-base font-black text-white">Payment activity is unavailable right now.</p><p className="mt-2 text-sm text-slate-400">Please refresh the page and try again.</p></div>; }
function PaymentDetails({ item, close, copy, copied }: { item: Payment; close: () => void; copy: (value: string) => Promise<void>; copied: string }) { const order = relatedOrder(item); const ref = reference(item); return <div role="presentation" onMouseDown={close} className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><article role="dialog" aria-modal="true" aria-labelledby="payment-details-title" onMouseDown={(event) => event.stopPropagation()} className="max-h-[85dvh] w-full max-w-lg overflow-y-auto rounded-3xl border border-orange-400/25 bg-[#111217] p-5 shadow-2xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-orange-300">Payment record</p><h2 id="payment-details-title" className="mt-1 text-xl font-black">Payment details</h2></div><button type="button" aria-label="Close payment details" onClick={close} className="grid h-11 w-11 place-items-center rounded-xl border border-white/10 text-xl text-slate-300 focus:outline-none focus:ring-4 focus:ring-orange-400/15">×</button></div><dl className="mt-5 space-y-2 text-xs"><Detail label="Amount" value={<CurrencyAmount amountINR={item.amount} />} /><Detail label="Status" value={<StatusBadge status={item.status} />} /><Detail label="Date" value={dateTime(item.created_at)} /><Detail label="Payment method" value={methodLabel(item.payment_method, item.type)} /><Detail label="Reference" value={ref} breakable /><Detail label="Gateway reference" value={item.provider_payment_id || item.provider_order_id || item.provider_refund_id} breakable /><Detail label="Wallet effect" value={completed.has(item.status.toLowerCase()) ? `${item.type === "debit" ? "Debit" : "Credit"} applied` : "No completed wallet effect"} />{item.description ? <Detail label="Description" value={item.description} /> : null}{order ? <Detail label="Related order" value={<Link href={`/dashboard/orders/${order}`} className="font-bold text-orange-300">View Order #{order.slice(0, 8)}</Link>} /> : null}</dl><button type="button" onClick={() => void copy(ref)} className="mt-4 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-white/10 text-sm font-bold text-slate-200 focus:outline-none focus:ring-4 focus:ring-orange-400/15"><Copy className="h-4 w-4" />{copied === ref ? "Copied" : "Copy payment reference"}</button></article></div>; }
function Detail({ label, value, breakable }: { label: string; value: React.ReactNode; breakable?: boolean }) { if (!value) return null; return <div className="flex min-w-0 justify-between gap-4 rounded-xl border border-white/[.07] bg-black/20 p-3"><dt className="shrink-0 text-slate-400">{label}</dt><dd className={`min-w-0 text-right font-bold text-white ${breakable ? "break-all" : ""}`}>{value}</dd></div>; }
