import Link from "next/link";
import { ArrowRight, CircleHelp, CreditCard, Gift, HeartHandshake, LayoutList, LockKeyhole, Plus, ShieldCheck, ShoppingBag, Wallet, Zap } from "lucide-react";
import { formatCurrency } from "@/lib/currency";
import { supportStatus } from "@/lib/support/customer";

type Order = { id: string; serviceName: string; platform: string; quantity: number; status: string; price: number; createdAt: string; progress: number | null; refillEligible: boolean };
type Transaction = { id: string; amount: number; type: string; status: string; paymentMethod: string; createdAt: string };
type Ticket = { id: string; subject: string; status: string; updated_at: string; order_id: string | null } | null;
type Profile = { id: string; label: string; platform: string; public_url: string; lastUsedAt: string };
const active = new Set(["pending", "processing", "in_progress", "partial", "awaiting_action"]);
const statusClass: Record<string, string> = { completed: "bg-emerald-500/10 text-emerald-300", processing: "bg-orange-500/10 text-orange-200", in_progress: "bg-orange-500/10 text-orange-200", pending: "bg-slate-500/15 text-slate-300", partial: "bg-amber-500/10 text-amber-200", failed: "bg-red-500/10 text-red-300", cancelled: "bg-red-500/10 text-red-300", refunded: "bg-slate-500/15 text-slate-300", open: "bg-orange-500/10 text-orange-200", waiting_for_support: "bg-amber-500/10 text-amber-200", waiting_for_customer: "bg-blue-500/10 text-blue-200", resolved: "bg-emerald-500/10 text-emerald-300", closed: "bg-slate-500/15 text-slate-300" };
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase()); }
function date(value: string) { return new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)); }
function Status({ value }: { value: string }) { const support = supportStatus(value); const isSupport = ["open", "waiting_for_support", "waiting_for_customer", "resolved", "closed"].includes(value); return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ${isSupport ? support.className : statusClass[value] || "bg-slate-500/15 text-slate-300"}`}>{isSupport ? support.label : label(value)}</span>; }
function Panel({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`dashboard-glass min-w-0 p-5 sm:p-6 ${className}`}>{children}</section>; }
function SectionError() { return <p role="status" className="mt-4 rounded-xl border border-white/10 bg-white/[.03] p-3 text-xs text-slate-300">This section could not be loaded. Please try again.</p>; }
function Platform({ name }: { name: string }) { return <span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-orange-500/10 text-xs font-black uppercase text-orange-300">{name.slice(0, 1)}</span>; }

export default function DashboardOverviewContent({ userName, walletBalance, orders, activeOrders, completedOrders, transactions, ticket, openTickets, rewardBalance, savedProfiles, errors }: { userName: string; walletBalance: number; orders: Order[]; activeOrders: number; completedOrders: number; transactions: Transaction[]; ticket: Ticket; openTickets: number; rewardBalance: number; savedProfiles: Profile[]; errors: Record<string, boolean> }) {
  const money = (amount: number) => formatCurrency(amount, "INR");
  const activeOrder = orders.filter(o => active.has(o.status)).sort((a, b) => ["processing", "pending", "partial"].indexOf(a.status) - ["processing", "pending", "partial"].indexOf(b.status))[0];
  const newCustomer = !errors.orders && !errors.payments && !errors.support && !errors.profiles && orders.length === 0 && transactions.length === 0 && !ticket && savedProfiles.length === 0;
  const cards = [{ title: "Wallet balance", value: money(walletBalance), icon: Wallet, href: "/dashboard/wallet" }, { title: "Active orders", value: activeOrders.toLocaleString("en-IN"), icon: Zap, href: "/dashboard/orders" }, { title: "Completed orders", value: completedOrders.toLocaleString("en-IN"), icon: ShoppingBag, href: "/dashboard/orders" }, { title: "Rewards", value: money(rewardBalance), icon: Gift, href: "/dashboard/rewards" }];
  return <main className="mx-auto w-full max-w-[1500px] overflow-x-clip px-4 pb-10 pt-5 sm:px-6 sm:pt-8 lg:px-8">
    <header className="rounded-3xl border border-orange-400/20 bg-gradient-to-br from-[#17120d] to-[#101217] p-5 shadow-[0_24px_70px_-48px_rgba(255,122,0,.8)] sm:p-7">
      <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.15em] text-orange-200"><ShieldCheck className="h-3.5 w-3.5" /> Secure customer account</p><h1 className="mt-3 text-3xl font-black tracking-tight text-white">Welcome back{userName ? `, ${userName}` : ""}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-300">Manage your orders, payments, support and rewards from one secure account.</p></div><Link href="/dashboard/new-order" className="btn-dashboard-primary min-h-12 gap-2 px-5 text-sm"><Plus className="h-4 w-4" />Place New Order</Link></div>
      <nav aria-label="Quick actions" className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-4"><Link className="btn-dashboard-secondary gap-2 px-3 text-xs" href="/dashboard/add-funds"><CreditCard className="h-4 w-4" />Add Funds</Link><Link className="btn-dashboard-secondary gap-2 px-3 text-xs" href="/dashboard/orders"><LayoutList className="h-4 w-4" />Track Orders</Link><Link className="btn-dashboard-secondary gap-2 px-3 text-xs" href="/dashboard/support"><CircleHelp className="h-4 w-4" />Contact Support</Link><Link className="btn-dashboard-secondary gap-2 px-3 text-xs" href="/dashboard/saved-profiles"><HeartHandshake className="h-4 w-4" />Saved Profiles</Link></nav>
    </header>
    {newCustomer ? <Panel className="mt-5 border-orange-400/25"><p className="text-xs font-black uppercase tracking-[.14em] text-orange-300">Getting started</p><h2 className="mt-2 text-2xl font-black text-white">Welcome to SocialRUSH</h2><p className="mt-2 text-sm text-slate-300">Choose a service, review its price and delivery information, place your order securely, then track it here.</p><ol className="mt-5 grid gap-2 text-sm text-slate-200 sm:grid-cols-4"><li>1. Choose a service</li><li>2. Review details</li><li>3. Place securely</li><li>4. Track your order</li></ol><div className="mt-5 flex flex-wrap gap-2"><Link href="/dashboard/new-order" className="btn-dashboard-primary px-5 text-sm">Place Your First Order</Link><Link href="/services" className="btn-dashboard-secondary px-5 text-sm">Explore Services</Link><Link href="/dashboard/support" className="btn-dashboard-secondary px-5 text-sm">Contact Support</Link></div></Panel> : null}
    <section aria-label="Account summary" className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(({ title, value, icon: Icon, href }) => <Link key={title} href={href} className="dashboard-glass min-h-32 p-4 transition hover:border-orange-400/35"><Icon className="h-5 w-5 text-orange-300" /><p className="mt-4 text-[11px] font-bold uppercase tracking-wide text-slate-400">{title}</p><p className="mt-1 text-xl font-black text-white">{value}</p></Link>)}</section>
    {activeOrder ? <Panel className="mt-5 border-orange-400/25"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><Platform name={activeOrder.platform} /><div><p className="text-xs font-black uppercase tracking-[.14em] text-orange-300">Active order</p><h2 className="mt-1 text-lg font-black text-white">{activeOrder.serviceName}</h2><p className="mt-1 text-xs text-slate-300">#{activeOrder.id.slice(0, 8).toUpperCase()} · {activeOrder.quantity.toLocaleString("en-IN")} quantity · {date(activeOrder.createdAt)}</p></div></div><Status value={activeOrder.status} /></div>{activeOrder.progress !== null ? <div className="mt-5"><div className="mb-2 flex justify-between text-xs text-slate-300"><span>Delivery progress</span><span>{Math.round(activeOrder.progress)}%</span></div><div className="h-2 rounded-full bg-white/10"><div className="h-2 rounded-full bg-gradient-to-r from-orange-500 to-amber-400" style={{ width: `${Math.max(0, Math.min(activeOrder.progress, 100))}%` }} /></div></div> : <p className="mt-5 text-xs text-slate-300">Status: {label(activeOrder.status)}. Delivery progress will appear when it is available.</p>}<div className="mt-5 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-slate-300">{activeOrder.refillEligible ? "Refill eligibility is available for this order." : ""}</span><Link href={`/dashboard/orders/${activeOrder.id}`} className="btn-dashboard-secondary gap-2 px-4 text-xs">View Order <ArrowRight className="h-3.5 w-3.5" /></Link></div></Panel> : null}
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.85fr]">
      <Panel><div className="flex items-center justify-between"><div><h2 className="text-lg font-black text-white">Recent orders</h2><p className="mt-1 text-xs text-slate-400">Your newest orders, first.</p></div><Link href="/dashboard/orders" className="text-xs font-bold text-orange-300">View All Orders</Link></div>{errors.orders ? <SectionError /> : orders.length ? <div className="mt-4 divide-y divide-white/10">{orders.map(order => <div key={order.id} className="flex items-center gap-3 py-3"><Platform name={order.platform} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-white">{order.serviceName}</p><p className="mt-1 text-xs text-slate-400">{order.quantity.toLocaleString("en-IN")} · {date(order.createdAt)}</p></div><div className="shrink-0 text-right"><Status value={order.status} /><Link className="mt-2 block text-xs font-bold text-orange-300" href={`/dashboard/orders/${order.id}`}>Details</Link></div></div>)}</div> : <p className="mt-4 rounded-2xl border border-dashed border-white/15 p-5 text-sm text-slate-300">No orders yet. Your first order will appear here.</p>}</Panel>
      <Panel><div className="flex items-center justify-between"><div><h2 className="text-lg font-black text-white">Wallet & payments</h2><p className="mt-1 text-xs text-slate-400">Available balance: {money(walletBalance)}</p></div><Link href="/dashboard/add-funds" className="btn-dashboard-primary px-3 text-xs">Add Funds</Link></div>{errors.payments ? <SectionError /> : transactions.length ? <div className="mt-4 space-y-3">{transactions.map(transaction => <div key={transaction.id} className="flex items-center justify-between gap-3"><div><p className="text-sm font-bold capitalize text-white">{transaction.paymentMethod.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-slate-400">{date(transaction.createdAt)}</p></div><div className="text-right"><p className="text-sm font-black text-white">{money(transaction.amount)}</p><Status value={transaction.status} /></div></div>)}</div> : <p className="mt-4 text-sm text-slate-300">No payment activity yet.</p>}<Link href="/dashboard/wallet" className="mt-5 inline-flex text-xs font-bold text-orange-300">View Wallet <ArrowRight className="ml-1 h-3.5 w-3.5" /></Link></Panel>
    </section>
    <section className="mt-5 grid gap-5 lg:grid-cols-3"><Panel>{errors.support ? <><h2 className="text-lg font-black text-white">Support</h2><SectionError /></> : ticket ? <><div className="flex justify-between gap-2"><h2 className="text-lg font-black text-white">Support</h2><Status value={ticket.status} /></div><p className="mt-4 truncate text-sm font-bold text-white">{ticket.subject}</p><p className="mt-2 text-xs text-slate-400">Updated {date(ticket.updated_at)}{ticket.order_id ? " · Linked order" : ""}</p><Link href="/dashboard/support" className="mt-5 inline-flex text-xs font-bold text-orange-300">View Ticket <ArrowRight className="ml-1 h-3.5 w-3.5" /></Link></> : <><h2 className="text-lg font-black text-white">Need assistance?</h2><p className="mt-2 text-sm leading-6 text-slate-300">Create a support ticket and keep the conversation inside your account.</p><Link href="/dashboard/support" className="mt-5 btn-dashboard-secondary px-4 text-xs">Create Ticket</Link></>}</Panel><Panel><div className="flex justify-between gap-2"><h2 className="text-lg font-black text-white">Rewards</h2><Gift className="h-5 w-5 text-orange-300" /></div>{errors.rewards ? <SectionError /> : <><p className="mt-4 text-2xl font-black text-white">{money(rewardBalance)}</p><p className="mt-1 text-xs text-slate-400">Credited reward balance</p><Link href="/dashboard/rewards" className="mt-5 inline-flex text-xs font-bold text-orange-300">View Rewards <ArrowRight className="ml-1 h-3.5 w-3.5" /></Link></>}</Panel><Panel><h2 className="text-lg font-black text-white">Saved profiles</h2>{errors.profiles ? <SectionError /> : savedProfiles.length ? <div className="mt-3 space-y-3">{savedProfiles.map(profile => <div className="flex items-center gap-2" key={profile.id}><Platform name={profile.platform} /><div className="min-w-0"><p className="truncate text-sm font-bold text-white">{profile.label}</p><p className="truncate text-xs text-slate-400">{new URL(profile.public_url).hostname}</p></div></div>)}</div> : <p className="mt-3 text-sm leading-6 text-slate-300">Save frequently used public profiles to place future orders faster.</p>}<Link href="/dashboard/saved-profiles" className="mt-5 inline-flex text-xs font-bold text-orange-300">Manage Saved Profiles <ArrowRight className="ml-1 h-3.5 w-3.5" /></Link></Panel></section>
    {openTickets > 0 && !errors.support ? <p className="mt-4 flex items-center gap-2 text-xs text-amber-200"><LockKeyhole className="h-3.5 w-3.5" />You have {openTickets} open support {openTickets === 1 ? "ticket" : "tickets"}.</p> : null}
  </main>;
}
