import Link from "next/link";
import { ArrowRight, BadgeCheck, CircleHelp, CreditCard, Gift, HeartHandshake, LayoutList, Plus, ReceiptText, ShieldCheck, ShoppingBag, Sparkles, Ticket, Wallet, Zap } from "lucide-react";
import PlatformIcon from "@/components/PlatformIcon";
import { formatCurrency } from "@/lib/currency";
import { supportStatus } from "@/lib/support/customer";
import OrderConversionCards, { type DraftSummary, type ServiceShortcut } from "./OrderConversionCards";

type Order = { id: string; serviceName: string; platform: string; quantity: number; status: string; price: number; createdAt: string; progress: number | null; refillEligible: boolean };
type Transaction = { id: string; amount: number; type: string; status: string; paymentMethod: string; createdAt: string };
type TicketData = { id: string; subject: string; status: string; updated_at: string; order_id: string | null } | null;
type Profile = { id: string; label: string; platform: string; public_url: string; lastUsedAt: string };
const activeStatuses = new Set(["pending", "processing", "in_progress", "partial", "awaiting_action"]);
const actionStatuses = new Set(["awaiting_action", "waiting_for_customer", "failed"]);
const title = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const date = (value: string) => new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value));
const statusStyles: Record<string, string> = { completed: "border-emerald-400/25 bg-emerald-500/10 text-emerald-300", processing: "border-orange-400/25 bg-orange-500/10 text-orange-200", in_progress: "border-orange-400/25 bg-orange-500/10 text-orange-200", pending: "border-amber-400/25 bg-amber-500/10 text-amber-200", partial: "border-amber-400/25 bg-amber-500/10 text-amber-200", failed: "border-red-400/25 bg-red-500/10 text-red-300", cancelled: "border-red-400/25 bg-red-500/10 text-red-300" };

function Status({ value }: { value: string }) {
  const support = supportStatus(value); const isSupport = ["open", "waiting_for_support", "waiting_for_customer", "answered", "resolved", "closed"].includes(value);
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-black ${isSupport ? support.className : statusStyles[value] || "border-white/10 bg-white/5 text-slate-300"}`}><i className="h-1.5 w-1.5 rounded-full bg-current" />{isSupport ? support.label : title(value)}</span>;
}
function Platform({ name, className = "" }: { name: string; className?: string }) { return <span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/10 bg-white/[.045] text-orange-300 ${className}`}><PlatformIcon platform={name} className="h-5 w-5" /></span>; }
function Panel({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`dashboard-glass min-w-0 p-4 sm:p-5 ${className}`}>{children}</section>; }
function SectionError() { return <p role="status" className="mt-4 rounded-xl border border-white/10 bg-white/[.03] p-3 text-xs text-slate-300">This section could not be loaded. Please try again.</p>; }

export default function DashboardOverviewContent({ greeting, userName, walletBalance, orders, activeCampaigns, totalOrders, activeOrders, completedOrders, transactions, ticket, openTickets, rewardBalance, savedProfiles, firstOrder, draft, shortcuts, errors }: { greeting: string; userName: string; walletBalance: number; orders: Order[]; activeCampaigns: Order[]; totalOrders: number; activeOrders: number; completedOrders: number; transactions: Transaction[]; ticket: TicketData; openTickets: number; rewardBalance: number; savedProfiles: Profile[]; firstOrder: boolean; draft: DraftSummary | null; shortcuts: ServiceShortcut[]; errors: Record<string, boolean> }) {
  const money = (amount: number) => formatCurrency(amount, "INR");
  const pendingOrders = orders.filter((order) => ["pending", "processing", "in_progress", "partial"].includes(order.status)).length;
  const failedPayment = transactions.find((transaction) => transaction.status === "failed");
  const attention = Boolean(openTickets || failedPayment || orders.some((order) => actionStatuses.has(order.status)));
  const metrics = [
    ["Wallet balance", money(walletBalance), "Add funds", Wallet, "/dashboard/add-funds", "text-orange-300"],
    ["Active orders", activeOrders.toLocaleString("en-IN"), "Track orders", Zap, "/dashboard/orders", "text-amber-300"],
    ["Completed", completedOrders.toLocaleString("en-IN"), "View history", ShoppingBag, "/dashboard/orders", "text-emerald-300"],
    ["Total orders", totalOrders.toLocaleString("en-IN"), "View orders", ReceiptText, "/dashboard/orders", "text-sky-300"],
  ] as const;
  return <main className="dashboard-premium-page dashboard-home-page mx-auto w-full max-w-[1500px] overflow-x-clip px-4 pb-10 pt-5 text-white sm:px-6 sm:pt-7 lg:px-8">
    <header className="relative overflow-hidden rounded-[1.35rem] border border-orange-400/20 bg-[radial-gradient(circle_at_85%_0%,rgba(255,137,20,.18),transparent_34%),linear-gradient(125deg,#17150f,#101218_60%,#101116)] p-5 shadow-[0_24px_70px_-48px_rgba(255,122,0,.85)] sm:p-6">
      <div aria-hidden className="pointer-events-none absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(255,190,110,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(255,190,110,.12)_1px,transparent_1px)] [background-size:32px_32px] [mask-image:linear-gradient(125deg,black,transparent_70%)]" />
      <div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-orange-200"><ShieldCheck className="h-3.5 w-3.5" />Secure customer account</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">{greeting}{userName ? `, ${userName}` : ""}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-300">Manage your campaigns, orders and account from one place.</p></div><Link href="/dashboard/new-order" className="btn-dashboard-primary gap-2 px-5 text-sm"><Plus className="h-4 w-4" />Start New Campaign</Link></div>
      <div className="relative mt-5 flex flex-wrap gap-x-4 gap-y-2 border-t border-white/10 pt-4 text-xs text-slate-300"><span className="inline-flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-emerald-400" />Account Active</span><span>Wallet <b className="text-white">{money(walletBalance)}</b></span><span><b className="text-white">{activeOrders}</b> Active Orders</span><span>{openTickets ? <><b className="text-white">{openTickets}</b> Open {openTickets === 1 ? "Ticket" : "Tickets"}</> : <span className="text-emerald-300">Support: All Clear</span>}</span></div>
      <nav aria-label="Hero quick actions" className="relative mt-4 grid grid-cols-2 gap-2 sm:flex sm:flex-wrap"><Link className="btn-dashboard-secondary gap-2 px-3 text-xs" href="/dashboard/add-funds"><CreditCard className="h-4 w-4" />Add Funds</Link><Link className="btn-dashboard-secondary gap-2 px-3 text-xs" href="/dashboard/orders"><LayoutList className="h-4 w-4" />Track Orders</Link><Link className="btn-dashboard-secondary gap-2 px-3 text-xs" href="/dashboard/support"><CircleHelp className="h-4 w-4" />Contact Support</Link><Link className="btn-dashboard-secondary gap-2 px-3 text-xs" href="/dashboard/saved-profiles"><HeartHandshake className="h-4 w-4" />Saved Profiles</Link></nav>
    </header>

    {(firstOrder || draft) ? <OrderConversionCards firstOrder={firstOrder} draft={draft} shortcuts={shortcuts} /> : null}

    <section aria-label="Account overview" className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{metrics.map(([label, value, action, Icon, href, tone]) => <Link key={label} href={href} className="dashboard-glass group min-h-32 p-4 transition duration-200 hover:-translate-y-0.5 hover:border-orange-400/35"><Icon className={`h-5 w-5 ${tone}`} /><p className="mt-4 text-[10px] font-black uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-1 text-xl font-black tracking-tight">{value}</p><span className="mt-2 inline-flex items-center gap-1 text-[11px] font-bold text-orange-300">{action}<ArrowRight className="h-3 w-3 transition group-hover:translate-x-0.5" /></span></Link>)}</section>

    <section className="mt-4 grid gap-4 xl:grid-cols-[1.45fr_.85fr]">
      <Panel className="xl:row-span-2"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-black">Recent Orders</h2><p className="mt-1 text-xs text-slate-400">Track your newest campaigns at a glance.</p></div><Link href="/dashboard/orders" className="shrink-0 text-xs font-bold text-orange-300">View all</Link></div>{errors.orders ? <SectionError /> : orders.length ? <div className="mt-3 divide-y divide-white/10">{orders.map((order) => <article key={order.id} className="flex gap-3 py-3 first:pt-1"><Platform name={order.platform} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><h3 className="break-words text-sm font-bold text-white">{order.serviceName}</h3><p className="mt-1 text-xs text-slate-400">{order.quantity.toLocaleString("en-IN")} quantity · {date(order.createdAt)}</p></div><Status value={order.status} /></div>{activeStatuses.has(order.status) && order.progress !== null ? <div className="mt-3"><div className="mb-1 flex justify-between text-[10px] font-bold text-slate-400"><span>Delivery progress</span><span>{Math.round(order.progress)}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-orange-500 to-amber-300" style={{ width: `${Math.max(0, Math.min(order.progress, 100))}%` }} /></div></div> : activeStatuses.has(order.status) ? <p className="mt-2 text-[11px] text-slate-400">{title(order.status)} — delivery updates will appear when available.</p> : null}<div className="mt-2 flex justify-between gap-2"><span className="text-[10px] text-slate-500">#{order.id.slice(0, 8).toUpperCase()}</span><Link className="inline-flex items-center gap-1 text-xs font-bold text-orange-300" href={`/dashboard/orders/${order.id}`}>Details <ArrowRight className="h-3 w-3" /></Link></div></div></article>)}</div> : <div className="mt-4 rounded-2xl border border-dashed border-white/15 p-5"><p className="font-bold">No orders yet</p><p className="mt-1 text-xs text-slate-400">Ready to start your next campaign?</p><Link href="/dashboard/new-order" className="mt-3 inline-flex text-xs font-bold text-orange-300">Place New Order <ArrowRight className="ml-1 h-3.5 w-3.5" /></Link></div>}</Panel>
      <Panel><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Order Activity</h2><p className="mt-1 text-xs text-slate-400">Current order distribution</p></div><ReceiptText className="h-5 w-5 text-orange-300" /></div>{errors.orders ? <SectionError /> : <div className="mt-5 grid grid-cols-3 gap-2"><div className="rounded-xl border border-emerald-400/15 bg-emerald-500/[.07] p-3"><p className="text-xl font-black text-emerald-300">{completedOrders}</p><p className="mt-1 text-[10px] font-bold uppercase text-slate-400">Completed</p></div><div className="rounded-xl border border-orange-400/15 bg-orange-500/[.07] p-3"><p className="text-xl font-black text-orange-200">{activeOrders}</p><p className="mt-1 text-[10px] font-bold uppercase text-slate-400">Active</p></div><div className="rounded-xl border border-amber-400/15 bg-amber-500/[.07] p-3"><p className="text-xl font-black text-amber-200">{pendingOrders}</p><p className="mt-1 text-[10px] font-bold uppercase text-slate-400">In view</p></div></div>}</Panel>
      <Panel><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-black">Active Campaigns</h2><p className="mt-1 text-xs text-slate-400">Orders currently receiving updates.</p></div><Link href="/dashboard/orders?status=processing" className="text-xs font-bold text-orange-300">View all</Link></div>{errors.orders ? <SectionError /> : activeCampaigns.length ? <div className="mt-4 space-y-3">{activeCampaigns.map((order) => <article key={order.id} className="rounded-xl border border-white/10 bg-white/[.025] p-3"><div className="flex items-start gap-3"><Platform name={order.platform} className="h-9 w-9 rounded-lg" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><p className="truncate text-sm font-bold">{order.serviceName}</p><Status value={order.status} /></div><p className="mt-1 text-[11px] text-slate-400">#{order.id.slice(0, 8).toUpperCase()} · {order.quantity.toLocaleString("en-IN")} quantity · {date(order.createdAt)}</p>{order.progress !== null ? <div className="mt-2"><div className="mb-1 flex justify-between text-[10px] font-bold text-slate-400"><span>Delivery progress</span><span>{Math.round(Math.max(0, Math.min(100, order.progress)))}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-orange-500 to-amber-300" style={{ width: `${Math.max(0, Math.min(100, order.progress))}%` }} /></div></div> : null}<Link href={`/dashboard/orders/${order.id}`} className="mt-2 inline-flex text-xs font-bold text-orange-300">View order <ArrowRight className="ml-1 h-3.5 w-3.5" /></Link></div></div></article>)}</div> : <div className="mt-4 rounded-2xl border border-dashed border-white/15 p-5"><p className="font-bold">No active campaigns right now.</p><p className="mt-1 text-xs text-slate-400">Start a campaign when you are ready.</p><Link href="/dashboard/new-order" className="mt-3 inline-flex text-xs font-bold text-orange-300">Start a Campaign <ArrowRight className="ml-1 h-3.5 w-3.5" /></Link></div>}</Panel>
      <Panel>{attention ? <><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-amber-300" /><div><h2 className="text-lg font-black">Needs Your Attention</h2><p className="text-xs text-slate-400">Actionable account updates only.</p></div></div><div className="mt-4 space-y-2">{openTickets ? <Link href="/dashboard/support" className="flex items-center justify-between rounded-xl border border-amber-400/20 bg-amber-500/[.07] p-3 text-xs"><span>{openTickets} open support {openTickets === 1 ? "ticket" : "tickets"}</span><ArrowRight className="h-4 w-4 text-amber-300" /></Link> : null}{failedPayment ? <Link href="/dashboard/wallet" className="flex items-center justify-between rounded-xl border border-red-400/20 bg-red-500/[.07] p-3 text-xs"><span>A payment needs review</span><ArrowRight className="h-4 w-4 text-red-300" /></Link> : null}</div></> : <div className="flex items-center gap-3"><BadgeCheck className="h-8 w-8 text-emerald-300" /><div><h2 className="font-black">Everything looks good</h2><p className="mt-1 text-xs text-slate-400">No account actions need your attention.</p></div></div>}</Panel>
    </section>

    <section className="mt-4 grid gap-4 lg:grid-cols-[1.2fr_.8fr] xl:grid-cols-[1.1fr_.9fr]">
      <Panel><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-black">Wallet & Payments</h2><p className="mt-1 text-xs text-slate-400">Available balance <b className="text-white">{money(walletBalance)}</b></p></div><Link href="/dashboard/add-funds" className="btn-dashboard-primary shrink-0 px-3 text-xs">Add Funds</Link></div>{errors.payments ? <SectionError /> : transactions.length ? <div className="mt-4 divide-y divide-white/10">{transactions.map((transaction) => <div className="flex items-center justify-between gap-3 py-3" key={transaction.id}><div className="flex min-w-0 items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-white/5 text-orange-300"><CreditCard className="h-4 w-4" /></span><div className="min-w-0"><p className="truncate text-sm font-bold">{title(transaction.paymentMethod)}</p><p className="mt-0.5 text-[11px] text-slate-400">{date(transaction.createdAt)}</p></div></div><div className="shrink-0 text-right"><p className="text-sm font-black">{money(transaction.amount)}</p><Status value={transaction.status} /></div></div>)}</div> : <p className="mt-4 text-sm text-slate-300">No payment activity yet.</p>}<Link href="/dashboard/wallet" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-orange-300">View Wallet <ArrowRight className="h-3.5 w-3.5" /></Link></Panel>
      <Panel>{errors.support ? <><h2 className="text-lg font-black">Support</h2><SectionError /></> : ticket ? <><div className="flex items-center justify-between gap-2"><div><h2 className="text-lg font-black">Support</h2><p className="mt-1 text-xs text-slate-400">{openTickets} open {openTickets === 1 ? "ticket" : "tickets"}</p></div><Ticket className="h-5 w-5 text-orange-300" /></div><div className="mt-4 rounded-xl border border-white/10 bg-white/[.025] p-3"><p className="truncate text-sm font-bold">{ticket.subject}</p><p className="mt-1 text-[11px] text-slate-400">Updated {date(ticket.updated_at)}</p><div className="mt-3"><Status value={ticket.status} /></div></div><div className="mt-4 flex flex-wrap gap-3"><Link href="/dashboard/support" className="inline-flex items-center gap-1 text-xs font-bold text-orange-300">View Ticket <ArrowRight className="h-3.5 w-3.5" /></Link><Link href="/dashboard/support" className="text-xs font-bold text-slate-300">Contact Support</Link></div></> : <><div className="flex items-center gap-3"><CircleHelp className="h-6 w-6 text-orange-300" /><div><h2 className="text-lg font-black">Support</h2><p className="text-xs text-emerald-300">Support: All Clear</p></div></div><p className="mt-4 text-sm leading-6 text-slate-300">Need a hand? Create a ticket and keep the conversation in your account.</p><Link href="/dashboard/support" className="mt-4 btn-dashboard-secondary px-4 text-xs">Contact Support</Link></>}</Panel>
    </section>
    <section className="mt-4 grid gap-4 lg:grid-cols-2"><Panel><div className="flex items-center justify-between"><h2 className="text-lg font-black">Rewards</h2><Gift className="h-5 w-5 text-pink-300" /></div>{errors.rewards ? <SectionError /> : <><p className="mt-4 text-2xl font-black">{money(rewardBalance)}</p><p className="mt-1 text-xs text-slate-400">Available reward balance</p><Link href="/dashboard/rewards" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-orange-300">View Rewards <ArrowRight className="h-3.5 w-3.5" /></Link></>}</Panel><Panel><div className="flex items-center justify-between"><h2 className="text-lg font-black">Saved Profiles</h2><HeartHandshake className="h-5 w-5 text-orange-300" /></div>{errors.profiles ? <SectionError /> : savedProfiles.length ? <div className="mt-3 space-y-2">{savedProfiles.map((profile) => <div key={profile.id} className="flex items-center gap-3 rounded-xl bg-white/[.025] p-2"><Platform name={profile.platform} className="h-8 w-8 rounded-lg" /><p className="min-w-0 flex-1 truncate text-sm font-bold">{profile.label}</p><Link href="/dashboard/new-order" aria-label={`Use ${profile.label}`} className="text-xs font-bold text-orange-300">Use</Link></div>)}</div> : <p className="mt-3 text-sm leading-6 text-slate-300">Save frequently used public profiles to make future orders faster.</p>}<Link href="/dashboard/saved-profiles" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-orange-300">{savedProfiles.length ? "Manage Saved Profiles" : "Add Profile"} <ArrowRight className="h-3.5 w-3.5" /></Link></Panel></section>
    <nav aria-label="Dashboard quick actions" className="mt-4 flex flex-wrap gap-2 rounded-2xl border border-white/10 bg-white/[.025] p-3"><span className="mr-1 flex items-center px-1 text-[10px] font-black uppercase tracking-[.14em] text-slate-400">Quick Actions</span><Link href="/dashboard/new-order" className="btn-dashboard-secondary gap-1.5 px-3 text-xs"><Plus className="h-3.5 w-3.5" />New Order</Link><Link href="/dashboard/packages" className="btn-dashboard-secondary px-3 text-xs">Packages</Link><Link href="/dashboard/add-funds" className="btn-dashboard-secondary px-3 text-xs">Add Funds</Link><Link href="/dashboard/orders" className="btn-dashboard-secondary px-3 text-xs">Track Orders</Link><Link href="/dashboard/support" className="btn-dashboard-secondary px-3 text-xs">Support</Link></nav>
  </main>;
}
