"use client";
import Link from "next/link";
import { Bell, CheckCheck, LoaderCircle } from "lucide-react";
import { useEffect, useRef, useState } from "react";
type Notice = { id:string; title:string; message:string; href:string|null; read_at:string|null; created_at:string };
export default function NotificationBell() {
  const [open,setOpen]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[items,setItems]=useState<Notice[]>([]); const root=useRef<HTMLDivElement>(null); const unread=items.filter(x=>!x.read_at).length;
  async function load(){setLoading(true);setError("");try{const r=await fetch("/api/notifications",{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.error);setItems(p.data||[])}catch(e){setError(e instanceof Error?e.message:"Notifications could not be loaded.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]); useEffect(()=>{if(open)void load()},[open]); useEffect(()=>{const click=(e:MouseEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false)};const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};document.addEventListener("mousedown",click);document.addEventListener("keydown",key);return()=>{document.removeEventListener("mousedown",click);document.removeEventListener("keydown",key)}},[]);
  async function mark(id:string){try{const r=await fetch(`/api/notifications/${id}`,{method:"PATCH"});if(!r.ok)throw new Error();setItems(xs=>xs.map(x=>x.id===id?{...x,read_at:new Date().toISOString()}:x))}catch{setError("Notification could not be updated. Please try again.");void load()}} async function markAll(){try{const r=await fetch("/api/notifications/read-all",{method:"POST"});if(!r.ok)throw new Error();setItems(xs=>xs.map(x=>({...x,read_at:x.read_at||new Date().toISOString()})))}catch{setError("Notifications could not be updated. Please try again.");void load()}}
  return <div ref={root} className="relative shrink-0"><button type="button" onClick={()=>setOpen(x=>!x)} aria-expanded={open} aria-haspopup="dialog" aria-label={`Notifications${unread?`, ${unread} unread`:""}`} className="relative grid h-11 w-11 place-items-center rounded-xl border border-white/10 bg-white/[.035] text-slate-100 transition hover:border-orange-400/35 hover:bg-orange-500/[.08]"><Bell className="h-4 w-4" />{unread?<span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-orange-500 px-1 text-[10px] font-black text-white">{unread>9?"9+":unread}</span>:null}</button>{open?<section role="dialog" aria-label="Notifications" className="absolute right-0 top-full z-[90] mt-2 w-[min(24rem,calc(100vw-2rem))] overflow-hidden rounded-2xl border border-orange-400/25 bg-[#111111]/[.98] shadow-[0_24px_60px_-26px_rgba(0,0,0,.8)] backdrop-blur-xl"><div className="flex items-center justify-between border-b border-white/10 p-4"><div><h2 className="text-sm font-black text-white">Notifications</h2><p className="mt-0.5 text-[11px] text-slate-400">{unread?`${unread} unread`:"You're all caught up"}</p></div><button type="button" disabled={!unread} onClick={()=>void markAll()} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg px-2 text-xs font-bold text-orange-200 disabled:opacity-40"><CheckCheck className="h-4 w-4" />Read all</button></div><div className="max-h-[26rem] overflow-y-auto">{loading?<div className="grid min-h-40 place-items-center text-sm text-slate-300"><LoaderCircle className="h-5 w-5 animate-spin" /></div>:error?<div className="p-5 text-sm text-red-200">{error}<button className="mt-2 block text-orange-200" onClick={()=>void load()}>Try again</button></div>:items.length?items.map(x=><Link key={x.id} href={x.href||"/dashboard"} onClick={()=>{if(!x.read_at)void mark(x.id);setOpen(false)}} className={`block border-b border-white/[.06] p-4 transition hover:bg-orange-500/[.07] ${x.read_at?"":"bg-orange-500/[.06]"}`}><div className="flex gap-3"><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${x.read_at?"bg-slate-600":"bg-orange-400"}`} /><div><p className="text-sm font-bold text-white">{x.title}</p><p className="mt-1 text-xs leading-5 text-slate-300">{x.message}</p><p className="mt-1.5 text-[10px] text-slate-500">{new Date(x.created_at).toLocaleString("en-IN")}</p></div></div></Link>):<div className="grid min-h-44 place-items-center p-6 text-center"><div><Bell className="mx-auto h-6 w-6 text-orange-300" /><p className="mt-3 text-sm font-bold text-white">No notifications yet</p><p className="mt-1 text-xs leading-5 text-slate-400">Order and support updates will appear here.</p></div></div>}</div></section>:null}</div>;
}
