"use client";

import Link from "next/link";
import { ArrowRight, Clock3, Trash2 } from "lucide-react";
import PlatformIcon from "@/components/PlatformIcon";
import { formatCurrency } from "@/lib/currency";
import { track } from "@/lib/analytics/events";

export type DraftSummary = { platform: string; serviceCode: string; serviceName: string; quantity: number; updatedAt: string };
export type ServiceShortcut = { code: string; platform: string; name: string; price: number };

export default function OrderConversionCards({ firstOrder, draft, shortcuts }: { firstOrder: boolean; draft: DraftSummary | null; shortcuts: ServiceShortcut[] }) {
  const discard = async () => { const response = await fetch("/api/order-draft", { method: "DELETE" }); if (response.ok) { track("order_started", { step: "draft_discarded" }); window.location.reload(); } };
  return <section className="mt-4 grid gap-4 xl:grid-cols-2">
    {firstOrder ? <article className="relative overflow-hidden rounded-[1.35rem] border border-orange-400/25 bg-[radial-gradient(circle_at_85%_10%,rgba(255,122,0,.22),transparent_35%),linear-gradient(135deg,#17120c,#101116)] p-5 shadow-[0_24px_60px_-42px_rgba(255,122,0,.95)] sm:p-6">
      <p className="text-[10px] font-black uppercase tracking-[.16em] text-orange-200">Your first campaign</p><h2 className="mt-2 text-2xl font-black tracking-tight">Ready to launch your first campaign?</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-300">Choose a service that matches your growth goal and place your first SocialRUSH order in just a few steps.</p>
      <div className="mt-4 grid gap-2 sm:grid-cols-3">{shortcuts.map((service) => <Link key={service.code} href={`/dashboard/new-order?platform=${service.platform}&service=${service.code}`} onClick={() => track("service_selected", { service_code: service.code, platform: service.platform, step: "first_order_shortcut" })} className="rounded-xl border border-white/10 bg-black/20 p-3 transition hover:border-orange-400/50 hover:bg-orange-500/10 focus:outline-none focus:ring-4 focus:ring-orange-400/20"><PlatformIcon platform={service.platform} className="h-5 w-5 text-orange-300" /><p className="mt-2 text-xs font-black">{service.name}</p><p className="mt-1 text-[10px] text-slate-400">From {formatCurrency(service.price, "INR")} / 1K</p></Link>)}</div>
      <Link href="/dashboard/new-order" onClick={() => track("order_started", { step: "first_order_cta" })} className="btn-dashboard-primary mt-5 gap-2 px-5 text-sm">Start Your First Order <ArrowRight className="h-4 w-4" /></Link>
    </article> : null}
    {draft ? <article className="rounded-[1.35rem] border border-amber-400/25 bg-[linear-gradient(135deg,rgba(255,122,0,.13),rgba(16,17,22,.98)_55%)] p-5 shadow-[0_24px_60px_-45px_rgba(255,122,0,.7)] sm:p-6"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-orange-400/25 bg-orange-500/10 text-orange-200"><Clock3 className="h-5 w-5" /></span><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-orange-200">Saved order</p><h2 className="mt-1 text-xl font-black">Continue your order</h2><p className="mt-1 text-sm text-slate-300">You were configuring an order earlier. Pick up where you left off.</p></div></div><dl className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl border border-white/10 bg-black/20 p-3"><dt className="text-slate-500">Platform</dt><dd className="mt-1 font-bold capitalize">{draft.platform}</dd></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><dt className="text-slate-500">Service</dt><dd className="mt-1 font-bold">{draft.serviceName}</dd></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><dt className="text-slate-500">Quantity</dt><dd className="mt-1 font-bold">{draft.quantity.toLocaleString("en-IN")}</dd></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><dt className="text-slate-500">Last updated</dt><dd className="mt-1 font-bold">{new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" }).format(new Date(draft.updatedAt))}</dd></div></dl><div className="mt-4 flex flex-wrap gap-3"><Link href="/dashboard/new-order?draft=1" onClick={() => track("order_started", { step: "draft_resumed" })} className="btn-dashboard-primary gap-2 px-4 text-xs">Continue Order <ArrowRight className="h-4 w-4" /></Link><button onClick={() => void discard()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/15 px-4 text-xs font-bold text-slate-300 hover:border-red-400/35 hover:text-red-200"><Trash2 className="h-4 w-4" />Discard</button></div></article> : null}
  </section>;
}
