"use client";

import Link from "next/link";
import { ArrowRight, Clock3, RotateCcw, ShoppingBag } from "lucide-react";
import { track } from "@/lib/analytics/events";

export default function ReactivationRecoveryPanel({ completedOrders, pendingOrders, paymentChecks, unfinishedCheckouts, hasDraft }: { completedOrders: number; pendingOrders: number; paymentChecks: number; unfinishedCheckouts: number; hasDraft: boolean }) {
  if (completedOrders < 1 && pendingOrders < 1 && paymentChecks < 1 && unfinishedCheckouts < 1) return null;
  const path = (source: string) => track("checkout_recovery_click", { source, surface: "dashboard_reactivation" });

  return <section className="mx-auto mt-5 max-w-[1500px] px-4 sm:px-6 lg:px-8"><div className="sr-smart-recovery rounded-2xl border border-orange-400/20 bg-[radial-gradient(circle_at_top_left,rgba(255,122,0,.12),transparent_38%),#101116] p-5 text-white sm:p-6"><p className="text-[10px] font-black uppercase tracking-[.16em] text-orange-300">Continue your next revenue action</p><h2 className="mt-2 text-xl font-black sm:text-2xl">Pick up where you left off.</h2><p className="mt-2 max-w-3xl text-xs leading-6 text-slate-400">Review an unfinished or payment-verification order before starting again. If your previous campaign is complete, repeat it from Order History with current live pricing shown before checkout.</p><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
    {unfinishedCheckouts > 0 && hasDraft ? <Link href="/dashboard/new-order?draft=1" onClick={()=>path("resume_unfinished_checkout")} className="sr-smart-recovery-card rounded-xl border border-emerald-400/20 bg-emerald-500/[.06] p-4 transition hover:border-emerald-400/40"><Clock3 className="h-5 w-5 text-emerald-300"/><b className="mt-3 block text-sm">Resume your checkout</b><span className="mt-1 block text-xs leading-5 text-slate-400">You have a recent checkout that did not create an order. Your saved configuration can be reviewed before trying payment again.</span><span className="mt-3 inline-flex items-center gap-1 text-xs font-black text-emerald-200">Continue safely <ArrowRight className="h-3.5 w-3.5"/></span></Link> : null}
    {(pendingOrders > 0 || paymentChecks > 0) ? <Link href="/dashboard/order-history?status=pending" onClick={()=>path("review_unfinished_order")} className="sr-smart-recovery-card rounded-xl border border-orange-400/20 bg-orange-500/[.06] p-4 transition hover:border-orange-400/40"><Clock3 className="h-5 w-5 text-orange-300"/><b className="mt-3 block text-sm">Review unfinished order</b><span className="mt-1 block text-xs leading-5 text-slate-400">Check order and payment status first to avoid placing an accidental duplicate.</span><span className="mt-3 inline-flex items-center gap-1 text-xs font-black text-orange-200">Open order history <ArrowRight className="h-3.5 w-3.5"/></span></Link> : null}
    {completedOrders > 0 ? <Link href="/dashboard/order-history" onClick={()=>path("repeat_completed_campaign")} className="sr-smart-recovery-card rounded-xl border border-white/10 bg-white/[.035] p-4 transition hover:border-orange-400/30"><RotateCcw className="h-5 w-5 text-orange-300"/><b className="mt-3 block text-sm">Repeat a completed campaign</b><span className="mt-1 block text-xs leading-5 text-slate-400">Reuse an eligible previous service, quantity and target while reviewing the current price.</span><span className="mt-3 inline-flex items-center gap-1 text-xs font-black text-orange-200">Find a completed order <ArrowRight className="h-3.5 w-3.5"/></span></Link> : null}
    <Link href="/dashboard/new-order" onClick={()=>path("start_fresh_order")} className="sr-smart-recovery-card rounded-xl border border-white/10 bg-white/[.035] p-4 transition hover:border-orange-400/30"><ShoppingBag className="h-5 w-5 text-orange-300"/><b className="mt-3 block text-sm">Start a fresh order</b><span className="mt-1 block text-xs leading-5 text-slate-400">Use this when the previous order is already resolved or you need a different service.</span><span className="mt-3 inline-flex items-center gap-1 text-xs font-black text-orange-200">New order <ArrowRight className="h-3.5 w-3.5"/></span></Link>
  </div><p className="mt-4 text-[11px] leading-5 text-slate-500">Payment-verification status should be checked before retrying payment or creating another order. This panel does not mark any payment as successful.</p></div></section>;
}
