"use client";

import { motion, AnimatePresence, useInView } from "framer-motion";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { formatCurrency } from "@/lib/currency";
import { usePreferredCurrency } from "@/lib/currency/use-currency";

export type WalletTransaction = { id: string; amount: number; type: string; status: string; payment_method: string | null; description: string | null; created_at: string };
export type WalletOrder = { id: string; charge: number; status: string; created_at: string; serviceName: string };
export type WalletInitialData = { balance: number; totalDeposits: number; totalSpent: number; totalOrders: number; pendingPayments: number; email: string; transactions: WalletTransaction[]; orders: WalletOrder[] };

type RazorpayResponse = { razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string };
type RazorpayOptions = { key: string; amount: number; currency: string; name: string; description: string; order_id: string; prefill: { email: string }; theme: { color: string }; handler: (response: RazorpayResponse) => void | Promise<void>; modal?: { ondismiss?: () => void } };
declare global { interface Window { Razorpay?: new (options: RazorpayOptions) => { open: () => void } } }

const methods = [
  { id: "upi", name: "UPI", detail: "Google Pay, PhonePe & UPI", icon: "UPI" },
  { id: "razorpay", name: "Razorpay", detail: "Secure hosted checkout", icon: "R" },
  { id: "credit_card", name: "Credit Card", detail: "Visa, Mastercard & RuPay", icon: "CC" },
  { id: "debit_card", name: "Debit Card", detail: "All major bank cards", icon: "DC" },
  { id: "net_banking", name: "Net Banking", detail: "50+ supported banks", icon: "NB" },
];

function Counter({ value, moneyValue = false, formatter }: { value: number; moneyValue?: boolean; formatter?: (value: number) => string }) {
  const ref = useRef<HTMLSpanElement>(null); const visible = useInView(ref, { once: true }); const [shown, setShown] = useState(0);
  useEffect(() => { if (!visible) return; const start = performance.now(); let frame = 0; const tick = (now: number) => { const progress = Math.min((now - start) / 900, 1); setShown(value * (1 - Math.pow(1 - progress, 3))); if (progress < 1) frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [value, visible]);
  return <span ref={ref}>{moneyValue ? (formatter ? formatter(shown) : Math.round(shown).toLocaleString("en-IN")) : Math.round(shown).toLocaleString("en-IN")}</span>;
}

function StatIcon({ name }: { name: string }) {
  const paths: Record<string, React.ReactNode> = {
    balance: <><path d="M4 6h14a2 2 0 0 1 2 2v11H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h12"/><path d="M15 12h5"/></>,
    deposit: <><circle cx="12" cy="12" r="9"/><path d="M12 7v10M8 11l4-4 4 4"/></>,
    orders: <><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 8h6M9 12h6M9 16h4"/></>,
    spent: <><path d="M3 12h18M12 3v18"/><path d="m16 8 5 4-5 4M8 16l-5-4 5-4"/></>,
    pending: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
  };
  return <svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}

function monthlySeries(transactions: WalletTransaction[], orders: WalletOrder[]) {
  const months = Array.from({ length: 6 }, (_, offset) => { const date = new Date(); date.setMonth(date.getMonth() - (5 - offset)); return { key: `${date.getFullYear()}-${date.getMonth()}`, label: date.toLocaleDateString("en-IN", { month: "short" }) }; });
  return months.map((month) => ({ ...month, deposits: transactions.filter((item) => { const date = new Date(item.created_at); return `${date.getFullYear()}-${date.getMonth()}` === month.key && item.type === "credit" && item.status === "completed"; }).reduce((sum, item) => sum + item.amount, 0), spending: transactions.filter((item) => { const date = new Date(item.created_at); return `${date.getFullYear()}-${date.getMonth()}` === month.key && item.type === "debit" && item.status === "completed"; }).reduce((sum, item) => sum + item.amount, 0), orders: orders.filter((item) => { const date = new Date(item.created_at); return `${date.getFullYear()}-${date.getMonth()}` === month.key; }).length }));
}

function MiniChart({ title, value, data, color }: { title: string; value: string; data: number[]; color: string }) {
  const max = Math.max(...data, 1);
  return <motion.article whileHover={{ y: -4 }} className="rounded-2xl border border-slate-200/80 bg-white/80 p-5 shadow-sm backdrop-blur"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{title}</p><p className="mt-2 text-xl font-bold text-[#07152f]">{value}</p></div><span className={`h-2 w-2 rounded-full ${color}`}/></div><div className="mt-5 flex h-20 items-end gap-2">{data.map((height, index) => <motion.span key={index} initial={{ height: 0 }} whileInView={{ height: `${Math.max((height / max) * 100, 5)}%` }} viewport={{ once: true }} transition={{ delay: index * .05 }} className={`flex-1 rounded-t ${color}`}/>)}</div></motion.article>;
}

function loadRazorpay() {
  return new Promise<boolean>((resolve) => {
    if (window.Razorpay) return resolve(true);
    const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js"; script.onload = () => resolve(true); script.onerror = () => resolve(false); document.body.appendChild(script);
  });
}

export default function WalletDashboard({ initial }: { initial: WalletInitialData }) {
  const router = useRouter();
  const { currency } = usePreferredCurrency("INR"); const money = (value: number) => formatCurrency(value, currency);
  const [balance, setBalance] = useState(initial.balance); const [method, setMethod] = useState("upi"); const [amount, setAmount] = useState(2000); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(false);
  const series = useMemo(() => monthlySeries(initial.transactions, initial.orders), [initial]);
  const activities = useMemo(() => [...initial.transactions.slice(0, 4).map((item) => ({ id: item.id, date: item.created_at, title: item.type === "credit" ? `Wallet funded ${money(item.amount)}` : item.type === "refund" ? `Refund added ${money(item.amount)}` : `Campaign investment ${money(item.amount)}`, tone: item.type === "credit" || item.type === "refund" ? "emerald" : "blue" })), ...initial.orders.slice(0, 4).map((item) => ({ id: item.id, date: item.created_at, title: `${item.serviceName} campaign ${item.status === "completed" ? "completed" : "created"}`, tone: item.status === "completed" ? "emerald" : "blue" }))].sort((a,b) => +new Date(b.date) - +new Date(a.date)).slice(0, 6), [initial]);

  async function startPayment(event: React.FormEvent) {
    event.preventDefault(); setError(""); setLoading(true);
    const loaded = await loadRazorpay();
    if (!loaded || !window.Razorpay) { setError("Secure checkout could not be loaded. Please try again."); setLoading(false); return; }
    const response = await fetch("/api/razorpay/create-order", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ amount, method }) });
    const payload = await response.json() as { data?: { keyId: string; orderId: string; amount: number; currency: string; email: string }; error?: string };
    if (!response.ok || !payload.data) { setError(payload.error || "Unable to initialize payment."); setLoading(false); return; }
    const checkout = new window.Razorpay({ key: payload.data.keyId, amount: payload.data.amount, currency: payload.data.currency, name: "SocialRUSH Wallet", description: `Add ${money(amount)} to campaign wallet`, order_id: payload.data.orderId, prefill: { email: payload.data.email || initial.email }, theme: { color: "#2563eb" }, modal: { ondismiss: () => setLoading(false) }, handler: async (result) => { const verification = await fetch("/api/razorpay/verify-payment", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(result) }); const verified = await verification.json() as { data?: { balance: number }; error?: string }; setLoading(false); if (!verification.ok || !verified.data) { setError(verified.error || "Payment verification failed."); return; } const updatedBalance = Number(verified.data.balance); setBalance(updatedBalance); window.dispatchEvent(new CustomEvent("wallet-balance-updated", { detail: updatedBalance })); setSuccess(true); window.setTimeout(() => setSuccess(false), 3500); router.refresh(); } });
    checkout.open();
  }

  const stats = [
    { label: "Current Balance", value: balance, money: true, note: "Available campaign budget", icon: "balance", tone: "from-blue-600 to-blue-700" },
    { label: "Total Deposits", value: initial.totalDeposits, money: true, note: "Lifetime wallet funding", icon: "deposit", tone: "from-emerald-500 to-teal-600" },
    { label: "Total Orders", value: initial.totalOrders, money: false, note: "Campaigns created", icon: "orders", tone: "from-violet-500 to-purple-600" },
    { label: "Total Spent", value: initial.totalSpent, money: true, note: "Campaign investment", icon: "spent", tone: "from-cyan-500 to-blue-600" },
    { label: "Pending Payments", value: initial.pendingPayments, money: false, note: "Awaiting confirmation", icon: "pending", tone: "from-amber-400 to-orange-500" },
  ];

  return <main className="min-h-[calc(100vh-5rem)] overflow-hidden bg-[radial-gradient(circle_at_top_right,#dbeafe_0,transparent_25%),linear-gradient(180deg,#f8faff_0%,#f3f6fb_100%)] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1650px]"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="inline-flex rounded-full border border-blue-200 bg-white/70 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.18em] text-blue-700 shadow-sm">Financial command center</span><h1 className="mt-4 text-3xl font-bold tracking-[-.035em] text-[#07152f] sm:text-4xl">SocialRUSH Wallet</h1><p className="mt-2 text-sm text-slate-500">Manage campaign funds, payments, spending, and transaction activity securely.</p></div><div className="flex items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50 px-3 py-2 text-[10px] font-bold text-emerald-700"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500"/>Payments operational</div></div>

    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{stats.map((stat,index) => <motion.article key={stat.label} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .06 }} whileHover={{ y: -5 }} className={`relative overflow-hidden rounded-2xl p-5 text-white shadow-xl shadow-slate-900/10 bg-gradient-to-br ${stat.tone}`}><div className="absolute -right-8 -top-8 h-24 w-24 rounded-full bg-white/10"/><div className="relative flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-wider text-white/65">{stat.label}</p><p className="mt-2 text-2xl font-bold"><Counter value={stat.value} moneyValue={stat.money} formatter={money}/></p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/15"><StatIcon name={stat.icon}/></span></div><p className="relative mt-4 text-[10px] text-white/60">{stat.note}</p></motion.article>)}</section>

    <div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><section className="overflow-hidden rounded-3xl border border-white/80 bg-white/75 shadow-[0_25px_80px_-40px_rgba(15,45,95,.45)] backdrop-blur-xl"><div className="border-b border-slate-100 p-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-600">Add funds</p><h2 className="mt-2 text-xl font-bold text-[#07152f]">Fund your campaign wallet</h2><p className="mt-1 text-xs text-slate-400">Choose a secure payment method and amount.</p></div><form onSubmit={startPayment} className="p-6"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{methods.map((item) => <motion.button whileHover={{ y: -3 }} whileTap={{ scale: .98 }} type="button" key={item.id} onClick={() => setMethod(item.id)} className={`flex items-center gap-3 rounded-2xl border p-4 text-left transition ${method === item.id ? "border-blue-500 bg-blue-50 ring-2 ring-blue-500/10" : "border-slate-200 bg-white hover:border-blue-200"}`}><span className={`grid h-10 w-10 place-items-center rounded-xl text-[10px] font-black ${method === item.id ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-600"}`}>{item.icon}</span><span className="min-w-0"><b className="block text-xs">{item.name}</b><small className="mt-1 block truncate text-[9px] text-slate-400">{item.detail}</small></span></motion.button>)}</div><div className="mt-6 rounded-2xl bg-slate-50 p-5"><label className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Custom amount<div className="relative mt-2"><input type="number" min={100} max={500000} value={amount} onChange={(event) => setAmount(Number(event.target.value))} className="w-full rounded-xl border border-slate-200 bg-white py-3.5 px-4 text-lg font-bold outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></div></label><div className="mt-3 grid grid-cols-5 gap-2">{[500,1000,2000,5000,10000].map((value) => <button type="button" key={value} onClick={() => setAmount(value)} className={`rounded-lg py-2 text-[9px] font-bold transition ${amount === value ? "bg-blue-600 text-white" : "bg-white text-slate-500 shadow-sm hover:text-blue-600"}`}>{money(value)}</button>)}</div></div>{error && <p className="mt-4 rounded-xl border border-rose-100 bg-rose-50 p-3 text-xs text-rose-700">{error}</p>}<button disabled={loading || amount < 100} className="mt-5 w-full rounded-xl bg-gradient-to-r from-blue-600 to-blue-700 py-3.5 text-sm font-bold text-white shadow-lg shadow-blue-600/20 transition hover:-translate-y-0.5 disabled:opacity-50">{loading ? "Opening secure checkout..." : `Continue securely · ${money(amount)}`}</button></form></section>

      <section className="rounded-3xl bg-[#07152f] p-6 text-white shadow-2xl shadow-blue-950/20"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-400">Recent activity</p><h2 className="mt-2 text-xl font-bold">Wallet timeline</h2></div><span className="rounded-full bg-emerald-400/10 px-3 py-1.5 text-[9px] font-bold text-emerald-400">Live</span></div><div className="mt-6 space-y-1">{activities.map((item,index) => <motion.div key={item.id} initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .05 }} className="relative flex gap-4 py-3"><div className="relative"><span className={`relative z-10 grid h-9 w-9 place-items-center rounded-xl text-sm font-bold ${item.tone === "emerald" ? "bg-emerald-400/15 text-emerald-400" : "bg-blue-400/15 text-blue-400"}`}>{item.tone === "emerald" ? "+" : "↗"}</span>{index < activities.length - 1 && <i className="absolute left-1/2 top-9 h-7 border-l border-white/10"/>}</div><div><p className="text-xs font-semibold">{item.title}</p><p className="mt-1 text-[9px] text-slate-500">{new Date(item.date).toLocaleString("en-IN")}</p></div></motion.div>)}{activities.length === 0 && <p className="py-12 text-center text-xs text-slate-500">Your wallet activity will appear here.</p>}</div></section></div>

    <section className="mt-6"><div className="mb-4"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-600">Wallet analytics</p><h2 className="mt-1 text-xl font-bold text-[#07152f]">Financial performance</h2></div><div className="grid gap-4 md:grid-cols-3"><MiniChart title="Monthly deposits" value={money(series.reduce((sum,item) => sum + item.deposits, 0))} data={series.map((item) => item.deposits)} color="bg-emerald-500"/><MiniChart title="Monthly spending" value={money(series.reduce((sum,item) => sum + item.spending, 0))} data={series.map((item) => item.spending)} color="bg-blue-500"/><MiniChart title="Order activity" value={`${series.reduce((sum,item) => sum + item.orders, 0)} campaigns`} data={series.map((item) => item.orders)} color="bg-violet-500"/></div><div className="mt-2 flex justify-around px-4 text-[8px] font-semibold uppercase text-slate-400">{series.map((item) => <span key={item.key}>{item.label}</span>)}</div></section>

    <section className="mt-6 overflow-hidden rounded-3xl border border-slate-200/80 bg-white/80 shadow-sm backdrop-blur"><div className="flex items-center justify-between border-b border-slate-100 p-6"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-600">Transaction history</p><h2 className="mt-2 text-xl font-bold">All wallet movements</h2></div><span className="rounded-lg bg-slate-100 px-3 py-2 text-[9px] font-bold text-slate-500">{initial.transactions.length} records</span></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-50 text-[9px] uppercase tracking-wider text-slate-400"><tr>{["Transaction ID","Date","Payment Method","Amount","Status"].map((head) => <th key={head} className="px-6 py-3">{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{initial.transactions.map((item) => <tr key={item.id} className="hover:bg-slate-50"><td className="px-6 py-4 font-bold text-blue-600">#{item.id.slice(0,8).toUpperCase()}</td><td className="px-6 py-4 text-slate-500">{new Date(item.created_at).toLocaleString("en-IN")}</td><td className="px-6 py-4 font-semibold capitalize">{(item.payment_method || item.description || item.type).replaceAll("_", " ")}</td><td className={`px-6 py-4 font-bold ${item.type === "debit" ? "text-slate-800" : "text-emerald-600"}`}>{item.type === "debit" ? "-" : "+"}{money(item.amount)}</td><td className="px-6 py-4"><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold capitalize ${item.status === "completed" ? "bg-emerald-50 text-emerald-700" : item.status === "pending" ? "bg-amber-50 text-amber-700" : "bg-rose-50 text-rose-700"}`}><i className="h-1.5 w-1.5 rounded-full bg-current"/>{item.status}</span></td></tr>)}{initial.transactions.length === 0 && <tr><td colSpan={5} className="p-14 text-center text-slate-400">No transactions yet.</td></tr>}</tbody></table></div></section>

    <section className="mt-6 flex flex-wrap items-center justify-center gap-3 rounded-2xl border border-blue-100 bg-blue-50/70 p-5">{["Secure Payments","SSL Protected","Encrypted Transactions","Fraud Monitoring"].map((item) => <span key={item} className="rounded-full border border-white bg-white px-4 py-2 text-[10px] font-bold text-blue-700 shadow-sm">✓ {item}</span>)}</section>
  </div><AnimatePresence>{success && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-5 backdrop-blur-sm"><motion.div initial={{ scale: .75, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: .8, opacity: 0 }} className="w-full max-w-sm rounded-3xl bg-white p-8 text-center shadow-2xl"><motion.span initial={{ scale: 0 }} animate={{ scale: 1 }} transition={{ type: "spring", delay: .15 }} className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-50 text-3xl text-emerald-600">✓</motion.span><h2 className="mt-5 text-2xl font-bold">Wallet funded!</h2><p className="mt-2 text-sm text-slate-500">{money(amount)} was added successfully.</p><p className="mt-5 rounded-xl bg-slate-50 p-3 text-sm font-bold text-blue-600">New balance: {money(balance)}</p></motion.div></motion.div>}</AnimatePresence></main>;
}
