import type { Metadata } from "next";
import PageHero from "@/components/marketing/PageHero";
import PublicShell from "@/components/marketing/PublicShell";
import { caseStudies } from "@/lib/marketing/content";

export const metadata: Metadata = { title: "Social Growth Case Studies", description: "Representative SocialRUSH campaign scenarios for creators, YouTube channels, local brands, and agencies." };

export default function CaseStudiesPage() {
  return <PublicShell><PageHero eyebrow="Campaign scenarios" title="How structured ordering supports clearer social growth." description="Representative examples showing how creators, businesses, and agencies can organize social growth campaigns through SocialRUSH." /><section className="px-5 py-16 sm:px-6 lg:py-20"><div className="mx-auto max-w-7xl"><p className="mb-8 rounded-xl border border-blue-100 bg-blue-50 p-4 text-xs leading-6 text-blue-800">These are illustrative scenarios, not verified customer performance claims or guarantees. Outcomes vary by platform, account, content, quantity, and delivery conditions.</p><div className="grid gap-6 lg:grid-cols-2">{caseStudies.map((study, index) => <article key={study.type} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="h-2 bg-gradient-to-r from-blue-600 to-cyan-400" /><div className="p-6 sm:p-7"><div className="flex items-center justify-between gap-4"><span className="text-[10px] font-bold uppercase tracking-wider text-blue-600">{study.category}</span><span className="text-xs font-bold text-slate-300">0{index + 1}</span></div><h2 className="mt-4 text-xl font-bold text-[#07152f]">{study.type}</h2><dl className="mt-6 space-y-5"><div><dt className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Goal</dt><dd className="mt-2 text-xs leading-6 text-slate-600">{study.goal}</dd></div><div><dt className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Approach</dt><dd className="mt-2 text-xs leading-6 text-slate-600">{study.strategy}</dd></div><div className="rounded-xl bg-emerald-50 p-4"><dt className="text-[9px] font-bold uppercase tracking-wider text-emerald-700">Operational value</dt><dd className="mt-2 text-sm font-bold leading-6 text-emerald-900">{study.result}</dd></div></dl></div></article>)}</div></div></section></PublicShell>;
}
