import PolicyPage from "@/components/marketing/PolicyPage";

const sections = [
  { title: "Acceptance of terms", body: ["By accessing SocialRUSH, creating an account, approving a proposal, or purchasing a service, you agree to these Terms & Conditions and any service-specific scope supplied to you. If a signed agreement conflicts with these terms, the signed agreement controls for that engagement."] },
  { title: "Services", body: ["SocialRUSH provides digital marketing, SEO, advertising management, content, website, consulting, campaign management, AI automation, WhatsApp automation, CRM, lead-generation, and related platform services.", "Deliverables, exclusions, timelines, review rounds, and dependencies are defined in the proposal, order, or statement of work."] },
  { title: "Accounts and user responsibilities", body: ["You must provide accurate information, protect account credentials, maintain lawful access to submitted accounts and assets, and promptly review requests for approvals or information."], bullets: ["Do not use services for unlawful, deceptive, infringing, abusive, or unauthorized activity.", "Do not submit personal data, creative assets, or account access you are not permitted to use.", "Ensure your offers, claims, landing pages, and communications comply with applicable laws and platform policies."] },
  { title: "Campaign management", body: ["Platform approvals, algorithms, inventory, market demand, competition, and policy decisions are controlled by third parties. We do not guarantee rankings, leads, revenue, advertising approval, uninterrupted availability, or a specific performance outcome."] },
  { title: "Billing and taxes", body: ["Fees, billing schedule, taxes, media budgets, and third-party costs are disclosed through the applicable proposal, invoice, order, or checkout. Payment is due as stated. We may pause delivery for overdue balances or missing required approvals."] },
  { title: "Client materials and approvals", body: ["You retain ownership of materials you provide and grant us permission to use them for agreed delivery. You are responsible for their legality and accuracy. Delays in feedback, access, content, or approvals may change the delivery schedule."] },
  { title: "Intellectual property", body: ["Final ownership and licensing of approved deliverables are governed by the written scope. SocialRUSH retains its pre-existing tools, templates, methods, know-how, and reusable components unless expressly agreed otherwise."] },
  { title: "Support and communication", body: ["Support channels, meeting cadence, and response expectations are defined by the service. Communications must remain professional. Emergency response or round-the-clock support is available only when specifically included."] },
  { title: "Cancellation and refunds", body: ["Cancellation, committed costs, and refund eligibility follow the signed scope and our Refund Policy. Work completed, resources reserved, and non-recoverable third-party costs may remain payable."] },
  { title: "Liability", body: ["To the extent permitted by law, SocialRUSH is not liable for indirect, incidental, special, or consequential losses, third-party platform actions, or losses caused by client instructions, missing access, unlawful materials, or external outages. Aggregate liability is limited to fees paid for the affected service during the relevant period."] },
  { title: "Changes, governing terms, and contact", body: ["We may update these terms prospectively. Continued use after an update constitutes acceptance where permitted by law. Questions or formal notices may be sent to support@socialrush.in."] },
];
export default function TermsPage() { return <PolicyPage title="Terms & Conditions" summary="The commercial and operational terms governing SocialRUSH services, accounts, campaigns, billing, and support." sections={sections}/>; }
