import type { Metadata } from "next";
import PageHero from "@/components/marketing/PageHero";
import PortalCTA from "@/components/marketing/PortalCTA";
import PublicShell from "@/components/marketing/PublicShell";

export const metadata: Metadata = { title: "About SocialRUSH", description: "SocialRUSH simplifies social media growth ordering with transparent pricing, secure wallet funding, campaign tracking, and customer support." };

export default function AboutPage() {
  return <PublicShell><PageHero eyebrow="About SocialRUSH" title="Social growth ordering, made clearer." description="SocialRUSH gives creators, brands, businesses, and agencies one professional workspace for choosing services, funding a wallet, placing campaigns, tracking progress, and getting help." /><section className="px-5 py-16 sm:px-6 lg:py-20"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Why we built it</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-[#07152f]">Replace scattered messages with a transparent dashboard.</h2><p className="mt-5 text-sm leading-7 text-slate-600">Customers should understand the service, rate, quantity, total price, and delivery estimate before ordering. That belief shapes SocialRUSH—from wallet funding and campaign checkout to order history and support tickets.</p><p className="mt-4 text-sm leading-7 text-slate-600">We focus on a curated social growth catalog and a straightforward customer experience instead of overwhelming buyers with provider-style labels.</p></div><div className="rounded-3xl bg-[#07152f] p-6 text-white sm:p-8"><h2 className="text-xl font-bold">What customers control</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{["Platform and service", "Campaign quantity", "Public destination link", "Wallet budget", "Order tracking", "Support history"].map((item) => <div key={item} className="rounded-xl bg-white/10 p-4 text-xs font-semibold"><span className="mr-2 text-blue-300">✓</span>{item}</div>)}</div></div></div><div className="mx-auto mt-14 grid max-w-7xl gap-5 md:grid-cols-3">{[["Trust by design", "No social account passwords are requested for standard campaigns. Customers submit only the required public link."], ["Clarity at checkout", "Current rates, quantities, totals, and campaign details remain visible before confirmation."], ["Useful support", "Order-specific help stays organized through protected support tickets and campaign IDs."]].map(([title, text]) => <article key={title} className="rounded-2xl border border-slate-200 p-6"><h3 className="font-bold text-[#07152f]">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{text}</p></article>)}</div><div className="mt-14 text-center"><PortalCTA className="inline-flex min-h-12 items-center rounded-xl bg-blue-600 px-6 py-3.5 text-sm font-bold text-white transition hover:bg-blue-700">Start Growing →</PortalCTA></div></section></PublicShell>;
}
