"use client";

import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Preferences = { orders: boolean; payments: boolean; support: boolean; marketing: boolean; security: boolean };
const defaults: Preferences = { orders: true, payments: true, support: true, marketing: false, security: true };

function Toggle({ enabled, onChange }: { enabled: boolean; onChange: () => void }) { return <button type="button" role="switch" aria-checked={enabled} onClick={onChange} className={`relative h-6 w-11 rounded-full transition ${enabled ? "bg-blue-600" : "bg-slate-200"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${enabled ? "left-6" : "left-1"}`}/></button>; }

export default function SettingsPage() {
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [email, setEmail] = useState(""); const [originalEmail, setOriginalEmail] = useState(""); const [name, setName] = useState(""); const [preferences, setPreferences] = useState<Preferences>(defaults); const [apiAccess, setApiAccess] = useState(false); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [toast, setToast] = useState<{ type: "success" | "error"; text: string } | null>(null);
  useEffect(() => { const supabase = createClient(); void supabase.auth.getUser().then(async ({ data }) => { if (!data.user) return; setEmail(data.user.email || ""); setOriginalEmail(data.user.email || ""); const { data: profile } = await supabase.from("profiles").select("full_name, notification_preferences, api_access").eq("id", data.user.id).maybeSingle(); setName(profile?.full_name || ""); setPreferences({ ...defaults, ...((profile?.notification_preferences as Partial<Preferences> | null) || {}) }); setApiAccess(Boolean(profile?.api_access)); setLoading(false); }); }, []);
  const showToast = (type: "success" | "error", text: string) => { setToast({ type, text }); window.setTimeout(() => setToast(null), 3500); };
  async function saveProfile() { setSaving(true); const supabase = createClient(); const { error } = await supabase.rpc("update_my_settings", { p_full_name: name, p_notifications: preferences, p_api_access: apiAccess }); if (!error && email !== originalEmail) { const result = await supabase.auth.updateUser({ email }); if (result.error) { setSaving(false); showToast("error", result.error.message); return; } setOriginalEmail(email); showToast("success", "Settings saved. Check your inbox to confirm the new email."); } else if (error) showToast("error", error.message); else showToast("success", "Account settings saved successfully."); setSaving(false); }
  async function changePassword(event: React.FormEvent) { event.preventDefault(); if (password.length < 8) { showToast("error", "Password must be at least 8 characters."); return; } if (password !== confirmPassword) { showToast("error", "Passwords do not match."); return; } const { error } = await createClient().auth.updateUser({ password }); if (error) showToast("error", error.message); else { setPassword(""); setConfirmPassword(""); showToast("success", "Password updated successfully."); } }
  const updatePreference = (key: keyof Preferences) => setPreferences((items) => ({ ...items, [key]: !items[key] }));

  if (loading) return <main className="p-8"><div className="mx-auto max-w-6xl space-y-5">{[1,2,3].map((item) => <div key={item} className="h-44 animate-pulse rounded-3xl bg-slate-100"/>)}</div></main>;
  return <main className="min-h-[calc(100vh-5rem)] bg-[linear-gradient(180deg,#f8faff,#f3f6fb)] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-6xl"><div><span className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-600">Account control center</span><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#07152f]">Account Settings</h1><p className="mt-2 text-sm text-slate-500">Manage your profile, security, notifications, and developer access.</p></div><div className="mt-7 grid gap-6 xl:grid-cols-2">
    <section className="rounded-3xl border border-white bg-white/80 p-6 shadow-sm backdrop-blur"><div className="flex items-center gap-4"><span className="grid h-16 w-16 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-cyan-500 text-lg font-bold text-white shadow-lg shadow-blue-600/20">{name.split(" ").map((item) => item[0]).join("").slice(0,2).toUpperCase() || "SR"}</span><div><h2 className="text-sm font-bold">Profile information</h2><p className="mt-1 text-xs text-slate-400">Your personal account details.</p></div></div><div className="mt-6 space-y-4"><label className="block text-[10px] font-bold uppercase tracking-wider text-slate-500">Full name<input value={name} onChange={(event) => setName(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-xs outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></label><label className="block text-[10px] font-bold uppercase tracking-wider text-slate-500">Email address<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-xs outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></label><p className="rounded-xl bg-blue-50 p-3 text-[10px] leading-5 text-blue-700">Changing your email requires confirmation from the new address.</p></div></section>
    <section className="rounded-3xl border border-white bg-white/80 p-6 shadow-sm backdrop-blur"><h2 className="text-sm font-bold">Change password</h2><p className="mt-1 text-xs text-slate-400">Use a strong password you do not reuse elsewhere.</p><form onSubmit={changePassword} className="mt-6 space-y-4"><label className="block text-[10px] font-bold uppercase tracking-wider text-slate-500">New password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-xs outline-none focus:border-blue-500" placeholder="At least 8 characters"/></label><label className="block text-[10px] font-bold uppercase tracking-wider text-slate-500">Confirm password<input type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-xs outline-none focus:border-blue-500"/></label><button className="rounded-xl bg-[#07152f] px-5 py-3 text-xs font-bold text-white">Update password</button></form></section>
    <section className="rounded-3xl border border-white bg-white/80 p-6 shadow-sm backdrop-blur"><h2 className="text-sm font-bold">Notification preferences</h2><p className="mt-1 text-xs text-slate-400">Choose which account updates reach your inbox.</p><div className="mt-5 divide-y divide-slate-100">{([ ["orders","Campaign updates","Status, delivery, and completion alerts"], ["payments","Wallet & payments","Funding, refunds, and transaction alerts"], ["support","Support replies","Notifications when the team responds"], ["marketing","Product news","New services and platform updates"] ] as [keyof Preferences,string,string][]).map(([key,title,text]) => <div key={key} className="flex items-center justify-between gap-4 py-4"><div><p className="text-xs font-bold">{title}</p><p className="mt-1 text-[10px] text-slate-400">{text}</p></div><Toggle enabled={preferences[key]} onChange={() => updatePreference(key)}/></div>)}</div></section>
    <section className="rounded-3xl border border-white bg-white/80 p-6 shadow-sm backdrop-blur"><h2 className="text-sm font-bold">Security settings</h2><p className="mt-1 text-xs text-slate-400">Control account protection and developer access.</p><div className="mt-5 divide-y divide-slate-100"><div className="flex items-center justify-between gap-4 py-4"><div><p className="text-xs font-bold">Security alerts</p><p className="mt-1 text-[10px] text-slate-400">Receive important sign-in and account alerts.</p></div><Toggle enabled={preferences.security} onChange={() => updatePreference("security")}/></div><div className="flex items-center justify-between gap-4 py-4"><div><p className="text-xs font-bold">API access</p><p className="mt-1 text-[10px] text-slate-400">Enable API key generation and developer tools.</p></div><Toggle enabled={apiAccess} onChange={() => setApiAccess(!apiAccess)}/></div></div><div className="mt-4 flex gap-3"><Link href="/dashboard/api-docs" className="rounded-xl border border-slate-200 px-4 py-3 text-xs font-bold text-slate-600">Developer settings</Link><button className="rounded-xl border border-slate-200 px-4 py-3 text-xs font-bold text-slate-600">View active sessions</button></div></section>
    <section className="rounded-3xl border border-rose-200 bg-rose-50/70 p-6 xl:col-span-2"><h2 className="text-sm font-bold text-rose-700">Account danger zone</h2><p className="mt-2 max-w-2xl text-xs leading-6 text-rose-600/80">Account deletion permanently removes profile access and requires a secure support review. Export any information you need before requesting deletion.</p><Link href="/dashboard/support" className="mt-5 inline-flex rounded-xl border border-rose-200 bg-white px-4 py-3 text-xs font-bold text-rose-600">Request account deletion</Link></section>
    </div><div className="sticky bottom-4 mt-6 flex justify-end"><button onClick={saveProfile} disabled={saving} className="rounded-xl bg-blue-600 px-6 py-3.5 text-sm font-bold text-white shadow-xl shadow-blue-600/25 disabled:opacity-50">{saving ? "Saving..." : "Save changes"}</button></div></div><AnimatePresence>{toast && <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className={`fixed bottom-6 right-6 z-[60] rounded-xl px-5 py-3 text-xs font-bold text-white shadow-xl ${toast.type === "success" ? "bg-emerald-600" : "bg-rose-600"}`}>{toast.type === "success" ? "✓" : "!"} {toast.text}</motion.div>}</AnimatePresence></main>;
}
