import { addPackage, deletePackage, updatePackage } from "@/app/admin/actions";
import ConfirmSubmitButton from "@/components/admin/ConfirmSubmitButton";
import { AdminPageHeader, AdminStatus, Modal, inputClass, primaryButton } from "@/components/admin/AdminUI";
import { createClient } from "@/lib/supabase/server";

type PackageRow = { id: number; name: string; platform: string; price: number; features: string[]; is_active: boolean };

function PackageForm({ action, item }: { action: (data: FormData) => Promise<void>; item?: PackageRow }) {
  return <form action={action} className="grid gap-4 sm:grid-cols-2">{item && <input type="hidden" name="id" value={item.id} />}<label className="text-xs font-semibold sm:col-span-2">Package name<input name="name" required defaultValue={item?.name} className={inputClass} /></label><label className="text-xs font-semibold">Platform<select name="platform" defaultValue={item?.platform || "instagram"} className={inputClass}>{["instagram","youtube","facebook","linkedin","tiktok","twitter"].map((platform) => <option key={platform}>{platform}</option>)}</select></label><label className="text-xs font-semibold">Price (INR)<input name="price" required type="number" min="0" step="0.01" defaultValue={item?.price ?? 0} className={inputClass} /></label><label className="text-xs font-semibold">Status<select name="is_active" defaultValue={item?.is_active === false ? "false" : "true"} className={inputClass}><option value="true">Enabled</option><option value="false">Disabled</option></select></label><label className="text-xs font-semibold sm:col-span-2">Features, one per line<textarea name="features" required defaultValue={item?.features.join("\n")} className={`${inputClass} min-h-32 resize-y`} /></label><button className={`${primaryButton} sm:col-span-2`}>{item ? "Save package" : "Add package"}</button></form>;
}

export default async function AdminPackagesPage() {
  const supabase = await createClient();
  const { data, error } = await supabase.from("packages").select("id,name,platform,price,features,is_active").order("id", { ascending: false });
  const packages = (data ?? []).map((item) => ({ ...item, price: Number(item.price), features: Array.isArray(item.features) ? item.features.map(String) : [] }));
  return <main className="mx-auto max-w-[1500px] p-5 sm:p-8"><AdminPageHeader title="Package management" description="Create and maintain fixed-price packages without changing the customer portal." action={<Modal label="+ Add package" title="Create package"><PackageForm action={addPackage} /></Modal>} />{error && <p className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-800">Packages require the latest admin migration. Apply it with Supabase before using this page.</p>}<section className="panel-card mt-7 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-400"><tr>{["Package","Platform","Price","Features","Status","Actions"].map((head) => <th key={head} className="px-5 py-3">{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{packages.map((item) => <tr key={item.id}><td className="px-5 py-4 font-bold">{item.name}</td><td className="px-5 py-4 capitalize text-slate-500">{item.platform}</td><td className="px-5 py-4 font-bold">₹{item.price.toLocaleString("en-IN")}</td><td className="max-w-sm px-5 py-4 text-slate-500">{item.features.join(" · ")}</td><td className="px-5 py-4"><AdminStatus value={item.is_active ? "active" : "inactive"} /></td><td className="px-5 py-4"><div className="flex gap-2"><Modal label="Edit" title={`Edit ${item.name}`}><PackageForm action={updatePackage} item={item} /></Modal><form action={deletePackage}><input type="hidden" name="id" value={item.id} /><ConfirmSubmitButton message={`Delete ${item.name}? This cannot be undone.`} className="rounded-xl bg-rose-50 px-4 py-3 text-xs font-bold text-rose-600">Delete</ConfirmSubmitButton></form></div></td></tr>)}{!packages.length && <tr><td colSpan={6} className="p-14 text-center text-slate-400">No packages have been created.</td></tr>}</tbody></table></div></section></main>;
}
