import PolicyPage from "@/components/marketing/PolicyPage";

const sections = [
  { title: "Scope", body: ["This Privacy Policy explains how SocialRUSH collects, uses, stores, and shares personal information when you visit our public website, submit an enquiry, create an account, purchase services, or communicate with our team."] },
  { title: "Information we collect", body: ["We may collect information you provide directly and limited technical information generated when you use our services."], bullets: ["Name, business name, email address, phone number, and enquiry details.", "Account, billing, transaction, and support records.", "Campaign instructions, website links, creative materials, and service communications.", "Device, browser, IP address, access time, and security logs."] },
  { title: "How we use information", body: ["We use information to respond to enquiries, deliver contracted services, manage accounts and campaigns, process and reconcile payments, provide support, improve security, and meet legal obligations.", "We may also use aggregated or de-identified information for service planning and performance analysis."] },
  { title: "Payments and service providers", body: ["Payments may be processed by third-party payment providers such as Razorpay. SocialRUSH does not store complete card details. Payment providers process data under their own privacy and security terms.", "We may use vetted hosting, analytics, communications, advertising, and automation providers where necessary to deliver services."] },
  { title: "Campaign and communication data", body: ["Information supplied for campaign management is used only for agreed delivery, reporting, troubleshooting, and support. Clients must have lawful authority to share the data and assets they provide."] },
  { title: "Data sharing", body: ["We do not sell personal information. We may share information with authorized staff, contractors, service providers, professional advisers, or authorities where required for delivery, security, legal compliance, or the protection of rights."] },
  { title: "Retention and security", body: ["We retain information only as long as reasonably necessary for service delivery, accounting, dispute management, security, and legal requirements. We use reasonable administrative and technical safeguards, but no online system can be guaranteed completely secure."] },
  { title: "Your choices", body: ["You may request access, correction, or deletion of eligible personal information, or object to certain communications, by emailing support@socialrush.in. Some records may be retained where required by law or legitimate business obligations."] },
  { title: "Updates and contact", body: ["We may update this policy as our services or legal obligations change. The effective date will be revised on this page. Privacy questions may be sent to support@socialrush.in."] },
];
export default function PrivacyPolicyPage() { return <PolicyPage title="Privacy Policy" summary="How SocialRUSH handles personal, business, campaign, and payment-related information." sections={sections}/>; }
