import Link from "next/link";
import { ArrowRight, Check, ChevronDown, Layers3, Route, Sparkles } from "lucide-react";
import BlogShell from "@/components/marketing/blog/BlogShell";
import CustomCampaignCta from "@/components/marketing/CustomCampaignCta";
import type { AudiencePageConfig } from "@/lib/marketing/audience-pages";

export default function AudienceLandingPage({ config }: { config: AudiencePageConfig }) {
  return <BlogShell><main className="relative overflow-x-clip bg-[#07080D] pb-14 text-white sm:pb-20"><div className="pointer-events-none absolute inset-x-0 top-0 h-[680px] bg-[radial-gradient(circle_at_12%_8%,rgba(255,108,0,.24),transparent_27%),radial-gradient(circle_at_86%_18%,rgba(71,85,255,.16),transparent_24%)]" />
    <section className="relative mx-auto grid max-w-7xl gap-9 px-4 pb-14 pt-12 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-20 lg:pt-20"><div className="self-center"><p className="inline-flex items-center gap-2 rounded-full border border-orange-300/30 bg-orange-400/10 px-3 py-1.5 text-[10px] font-black tracking-[.17em] text-orange-200"><Sparkles className="h-3.5 w-3.5" />{config.eyebrow}</p><h1 className="mt-5 max-w-3xl text-4xl font-black tracking-[-.045em] sm:text-5xl lg:text-6xl">{config.headline} <span className="text-orange-300">{config.emphasis}</span></h1><p className="mt-5 max-w-2xl text-base leading-8 text-slate-300">{config.description}</p><div className="mt-7 flex flex-wrap gap-3"><Link href={config.primaryCta.href} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-gradient-to-r from-[#FF7000] to-[#FFAD00] px-5 text-sm font-black text-white shadow-[0_16px_32px_-16px_rgba(255,122,0,.95)] transition hover:brightness-110 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-200">{config.primaryCta.label}<ArrowRight className="h-4 w-4" /></Link><Link href="/contact#support-form" className="inline-flex min-h-12 items-center rounded-xl border border-white/15 bg-white/[.04] px-5 text-sm font-bold text-slate-100 transition hover:border-orange-300/55 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-300">Discuss a Custom Campaign</Link></div><ul className="mt-7 flex flex-wrap gap-2.5">{config.valuePoints.map((point) => <li key={point} className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-xs font-bold text-slate-200"><Check className="h-3.5 w-3.5 text-orange-300" />{point}</li>)}</ul></div><HeroPanel audience={config.audience} /></section>
    <section className="relative mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div><p className="text-[10px] font-black tracking-[.18em] text-orange-300">BUILT FOR YOUR WORKFLOW</p><h2 className="mt-2 text-3xl font-black tracking-tight">A useful starting point, not a one-size-fits-all pitch.</h2></div><div className="mt-6 grid gap-4 md:grid-cols-3">{config.useCases.map((item, index) => <article key={item.title} className="rounded-3xl border border-white/10 bg-[#10131c] p-5 shadow-[0_20px_40px_-35px_rgba(0,0,0,.9)]"><span className="text-xs font-black text-orange-300">0{index + 1}</span><h3 className="mt-7 text-lg font-black">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{item.text}</p></article>)}</div></section>
    <section className="relative mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="rounded-[1.75rem] border border-white/10 bg-[#0e1018] p-5 sm:p-7"><p className="text-[10px] font-black tracking-[.18em] text-orange-300">RECOMMENDED PATHS</p><h2 className="mt-2 text-3xl font-black tracking-tight">Choose where to start.</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{config.paths.map((path) => <Link key={path.title} href={path.href} className="group min-h-48 rounded-2xl border border-white/[.09] bg-white/[.035] p-4 transition hover:-translate-y-1 hover:border-orange-300/45 hover:bg-orange-400/[.06] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-300"><span className="text-[10px] font-black tracking-[.14em] text-orange-200">{path.platform.toUpperCase()}</span><h3 className="mt-5 text-base font-black">{path.title}</h3><p className="mt-2 text-xs leading-5 text-slate-400">{path.text}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-black text-orange-200">Explore <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>
    <section className="relative mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="rounded-[1.75rem] border border-white/10 bg-[linear-gradient(120deg,#10131c,#14100d)] p-5 sm:p-7"><p className="text-[10px] font-black tracking-[.18em] text-orange-300">HOW IT WORKS</p><h2 className="mt-2 text-3xl font-black tracking-tight">A straightforward campaign path.</h2><div className="mt-6 grid gap-3 md:grid-cols-3">{[["Choose platform","Start with the social platform that fits your current requirement."],["Review current details","Check the service information and public-link requirements before ordering."],["Order or contact support","Place an order, or contact support for a larger requirement."]].map(([title,text], index) => <div key={title} className="rounded-2xl border border-white/[.08] bg-black/20 p-5"><Route className="h-5 w-5 text-orange-300" /><p className="mt-5 text-xs font-black text-orange-300">STEP 0{index + 1}</p><h3 className="mt-2 text-base font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div>)}</div></div></section>
    <CustomCampaignCta />
    <section className="relative mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8"><p className="text-[10px] font-black tracking-[.18em] text-orange-300">FAQ</p><h2 className="mt-2 text-3xl font-black tracking-tight">Questions from {config.audience.toLowerCase()}.</h2><div className="mt-6 space-y-2">{config.faqs.map((faq) => <details key={faq.question} className="group rounded-2xl border border-white/10 bg-[#10131c] px-5"><summary className="flex min-h-14 cursor-pointer list-none items-center justify-between gap-4 py-3 text-sm font-black [&::-webkit-details-marker]:hidden">{faq.question}<ChevronDown className="h-4 w-4 shrink-0 text-orange-300 transition group-open:rotate-180" /></summary><p className="border-t border-white/[.08] py-4 text-sm leading-6 text-slate-300">{faq.answer}</p></details>)}</div></section>
  </main></BlogShell>;
}

function HeroPanel({ audience }: { audience: string }) { return <aside className="relative mx-auto w-full max-w-xl rounded-[2rem] border border-white/15 bg-[#10131c]/90 p-4 shadow-[0_35px_80px_-35px_rgba(0,0,0,.95)] backdrop-blur"><div className="rounded-[1.45rem] border border-white/[.08] bg-[#090b11] p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black tracking-[.16em] text-orange-300">SOCIALRUSH WORKSPACE</p><p className="mt-1 text-xl font-black">{audience} campaign path</p></div><Layers3 className="h-6 w-6 text-orange-300" /></div><div className="mt-6 space-y-3">{["Choose a platform", "Review current service details", "Continue with public-link ordering"].map((item, index) => <div key={item} className="flex items-center gap-4 rounded-xl border border-white/[.08] bg-white/[.035] p-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-orange-400/10 text-xs font-black text-orange-200">0{index + 1}</span><span className="text-sm font-bold text-slate-200">{item}</span><Check className="ml-auto h-4 w-4 text-orange-300" /></div>)}</div><div className="mt-5 rounded-xl border border-orange-300/20 bg-orange-400/[.07] p-4"><p className="text-xs font-black text-orange-100">Need a larger requirement?</p><p className="mt-1 text-xs leading-5 text-slate-400">Use the existing support workflow to discuss it.</p></div></div></aside>; }
