export const comparisonSlugs = ["ytviews", "socialking", "media-mister"] as const;
export type ComparisonSlug = typeof comparisonSlugs[number];
type Value = "Yes" | "No" | "Information not clearly published" | "Varies by service";
type Comparison = { slug:ComparisonSlug; name:string; website:string; reviewed:string; summary:string; facts:Record<string,Value> };
const unclear:Value="Information not clearly published";
export const comparisons:Record<ComparisonSlug,Comparison>={
  ytviews:{slug:"ytviews",name:"YTViews",website:"https://www.ytviews.in/",reviewed:"31 July 2026",summary:"YTViews publishes social-media service information, but several account and policy features were not clearly documented in the public pages reviewed.",facts:{"Multiple platforms":"Yes","Public pricing visibility":"Varies by service","No password requirement":unclear,"Customer dashboard":unclear,"Wallet system":unclear,"Order tracking":unclear,"Refill information":unclear,"Support options":"Yes","Payment-method visibility":unclear,"Service-health information":unclear,"Verified review process":unclear,"Published case studies":unclear,"Refund-policy clarity":unclear}},
  socialking:{slug:"socialking",name:"SocialKing",website:"https://socialking.in/",reviewed:"31 July 2026",summary:"SocialKing offers public social-media service pages. Features not clearly stated in the public information reviewed are marked as such rather than inferred.",facts:{"Multiple platforms":"Yes","Public pricing visibility":"Varies by service","No password requirement":unclear,"Customer dashboard":unclear,"Wallet system":unclear,"Order tracking":unclear,"Refill information":unclear,"Support options":unclear,"Payment-method visibility":unclear,"Service-health information":unclear,"Verified review process":unclear,"Published case studies":unclear,"Refund-policy clarity":unclear}},
  "media-mister":{slug:"media-mister",name:"Media Mister",website:"https://www.mediamister.com/",reviewed:"31 July 2026",summary:"Media Mister publicly lists a broad service catalog, package pricing, account/dashboard features, support channels, and refill and refund information. Terms can vary by service.",facts:{"Multiple platforms":"Yes","Public pricing visibility":"Yes","No password requirement":"Yes","Customer dashboard":"Yes","Wallet system":unclear,"Order tracking":"Yes","Refill information":"Varies by service","Support options":"Yes","Payment-method visibility":"Yes","Service-health information":unclear,"Verified review process":unclear,"Published case studies":unclear,"Refund-policy clarity":"Yes"}},
};
export const socialRushFacts:Record<string,Value>={"Multiple platforms":"Yes","Public pricing visibility":"Yes","No password requirement":"Yes","Customer dashboard":"Yes","Wallet system":"Yes","Order tracking":"Yes","Refill information":"Varies by service","Support options":"Yes","Payment-method visibility":"Yes","Service-health information":"Yes","Verified review process":"Yes","Published case studies":"Yes","Refund-policy clarity":"Yes"};
