export type PlatformContentGapDecision = "implement" | "defer" | "covered";
export type AdditionalContentPlatform = "YouTube" | "Facebook" | "X / Twitter" | "TikTok" | "Telegram";

export type PlatformContentGapCandidate = Readonly<{
  id: string;
  queryTheme: string;
  intent: "informational" | "commercial-research";
  decision: PlatformContentGapDecision;
  primaryTarget: string;
  reason: string;
  cannibalizationRisk: "low" | "medium" | "high";
  businessRelevance: 1 | 2 | 3 | 4 | 5;
  internalLinkValue: 1 | 2 | 3 | 4 | 5;
  uniqueInformationValue: 1 | 2 | 3 | 4 | 5;
}>;

export const youtubeContentGapCandidates: readonly PlatformContentGapCandidate[] = [
  {
    id: "subscribers-price-india",
    queryTheme: "YouTube subscribers price in India",
    intent: "commercial-research",
    decision: "covered",
    primaryTarget: "/blog/youtube-subscribers-price-in-india",
    reason: "The existing pricing guide already owns this research intent.",
    cannibalizationRisk: "high",
    businessRelevance: 5,
    internalLinkValue: 5,
    uniqueInformationValue: 1,
  },
  {
    id: "views-price-india",
    queryTheme: "YouTube views price in India",
    intent: "commercial-research",
    decision: "covered",
    primaryTarget: "/blog/youtube-views-price-in-india",
    reason: "The existing views pricing guide already owns this research intent.",
    cannibalizationRisk: "high",
    businessRelevance: 5,
    internalLinkValue: 5,
    uniqueInformationValue: 1,
  },
  {
    id: "subscribers-vs-views",
    queryTheme: "YouTube subscribers vs views",
    intent: "informational",
    decision: "covered",
    primaryTarget: "/blog/youtube-subscribers-vs-views-india",
    reason: "The existing comparison guide already owns this distinction.",
    cannibalizationRisk: "high",
    businessRelevance: 5,
    internalLinkValue: 5,
    uniqueInformationValue: 1,
  },
  {
    id: "new-channel-promotion",
    queryTheme: "how to promote a new YouTube channel in India",
    intent: "informational",
    decision: "covered",
    primaryTarget: "/blog/how-to-promote-new-youtube-channel-in-india",
    reason: "Existing long-form guidance already covers new-channel promotion.",
    cannibalizationRisk: "high",
    businessRelevance: 4,
    internalLinkValue: 4,
    uniqueInformationValue: 1,
  },
  {
    id: "watch-hours-vs-views",
    queryTheme: "YouTube watch hours vs views",
    intent: "informational",
    decision: "defer",
    primaryTarget: "/youtube-growth-india",
    reason: "The question is distinct, but a new URL should wait for verified query evidence so it does not fragment the existing YouTube growth cluster.",
    cannibalizationRisk: "medium",
    businessRelevance: 5,
    internalLinkValue: 5,
    uniqueInformationValue: 4,
  },
] as const;

export const facebookContentGapCandidates: readonly PlatformContentGapCandidate[] = [
  {
    id: "followers-price-india",
    queryTheme: "Facebook followers price in India",
    intent: "commercial-research",
    decision: "covered",
    primaryTarget: "/blog/facebook-followers-price-in-india",
    reason: "The existing pricing guide already owns this research intent.",
    cannibalizationRisk: "high",
    businessRelevance: 5,
    internalLinkValue: 5,
    uniqueInformationValue: 1,
  },
  {
    id: "local-business-growth",
    queryTheme: "Facebook page growth tips for local businesses",
    intent: "informational",
    decision: "covered",
    primaryTarget: "/blog/facebook-page-growth-tips-for-local-businesses",
    reason: "Existing long-form guidance already owns local-business page growth.",
    cannibalizationRisk: "high",
    businessRelevance: 4,
    internalLinkValue: 4,
    uniqueInformationValue: 1,
  },
  {
    id: "followers-vs-engagement",
    queryTheme: "Facebook followers vs engagement",
    intent: "informational",
    decision: "covered",
    primaryTarget: "/blog/facebook-followers-vs-engagement-india",
    reason: "The existing comparison guide already owns follower-count versus engagement intent.",
    cannibalizationRisk: "high",
    businessRelevance: 5,
    internalLinkValue: 5,
    uniqueInformationValue: 1,
  },
  {
    id: "likes-vs-followers",
    queryTheme: "Facebook page likes vs followers",
    intent: "informational",
    decision: "defer",
    primaryTarget: "/facebook-growth-india",
    reason: "This is a useful platform-mechanics question, but a separate article needs verified demand before adding another overlapping Facebook URL.",
    cannibalizationRisk: "medium",
    businessRelevance: 4,
    internalLinkValue: 4,
    uniqueInformationValue: 4,
  },
  {
    id: "group-members-growth",
    queryTheme: "Facebook group members growth strategy",
    intent: "informational",
    decision: "defer",
    primaryTarget: "/facebook-growth-india",
    reason: "The group-member service already has a canonical transactional owner; add a separate informational guide only when query evidence proves a distinct need.",
    cannibalizationRisk: "medium",
    businessRelevance: 4,
    internalLinkValue: 4,
    uniqueInformationValue: 3,
  },
] as const;

export const twitterContentGapCandidates: readonly PlatformContentGapCandidate[] = [
  {
    id: "followers-price-india",
    queryTheme: "Twitter or X followers price in India",
    intent: "commercial-research",
    decision: "covered",
    primaryTarget: "/blog/twitter-followers-price-in-india",
    reason: "The existing pricing guide already owns follower-price research intent.",
    cannibalizationRisk: "high",
    businessRelevance: 5,
    internalLinkValue: 5,
    uniqueInformationValue: 1,
  },
  {
    id: "follower-safety",
    queryTheme: "is it safe to buy Twitter or X followers",
    intent: "commercial-research",
    decision: "covered",
    primaryTarget: "/blog/is-it-safe-to-buy-twitter-followers",
    reason: "The existing safety guide already owns this risk-evaluation intent.",
    cannibalizationRisk: "high",
    businessRelevance: 5,
    internalLinkValue: 4,
    uniqueInformationValue: 1,
  },
  {
    id: "followers-vs-engagement",
    queryTheme: "Twitter or X followers vs engagement",
    intent: "informational",
    decision: "defer",
    primaryTarget: "/x-growth-india",
    reason: "A separate comparison article could overlap with the broad X growth hub and follower canonical without verified query evidence.",
    cannibalizationRisk: "medium",
    businessRelevance: 4,
    internalLinkValue: 5,
    uniqueInformationValue: 4,
  },
  {
    id: "retweets-vs-likes",
    queryTheme: "Twitter retweets vs likes",
    intent: "informational",
    decision: "defer",
    primaryTarget: "/x-growth-india",
    reason: "The distinction is useful but should remain inside the hub until demand evidence supports a standalone guide.",
    cannibalizationRisk: "medium",
    businessRelevance: 4,
    internalLinkValue: 4,
    uniqueInformationValue: 4,
  },
  {
    id: "crypto-engagement-planning",
    queryTheme: "Twitter or X crypto engagement strategy",
    intent: "informational",
    decision: "defer",
    primaryTarget: "/x-growth-india",
    reason: "Multiple crypto service pages already exist; a broad guide should be added only if it can own a clearly distinct research intent.",
    cannibalizationRisk: "medium",
    businessRelevance: 4,
    internalLinkValue: 4,
    uniqueInformationValue: 3,
  },
] as const;

export const tiktokContentGapCandidates: readonly PlatformContentGapCandidate[] = [
  {
    id: "public-link-safety",
    queryTheme: "TikTok public-link ordering safety",
    intent: "commercial-research",
    decision: "covered",
    primaryTarget: "/blog/why-public-link-ordering-is-safer",
    reason: "The existing public-link safety guide covers this cross-platform ordering question.",
    cannibalizationRisk: "high",
    businessRelevance: 4,
    internalLinkValue: 4,
    uniqueInformationValue: 1,
  },
  {
    id: "creator-growth-strategy",
    queryTheme: "TikTok growth strategy for Indian creators",
    intent: "informational",
    decision: "covered",
    primaryTarget: "/blog/social-media-growth-strategy-indian-creators",
    reason: "The current creator-growth guide already covers TikTok inside a broader multi-platform strategy.",
    cannibalizationRisk: "medium",
    businessRelevance: 4,
    internalLinkValue: 4,
    uniqueInformationValue: 2,
  },
  {
    id: "followers-price-india",
    queryTheme: "TikTok followers price in India",
    intent: "commercial-research",
    decision: "defer",
    primaryTarget: "/tiktok-growth-india",
    reason: "No dedicated pricing guide exists yet; create one only when verified query evidence supports a separate research URL.",
    cannibalizationRisk: "medium",
    businessRelevance: 5,
    internalLinkValue: 5,
    uniqueInformationValue: 4,
  },
  {
    id: "followers-vs-views",
    queryTheme: "TikTok followers vs views",
    intent: "informational",
    decision: "defer",
    primaryTarget: "/tiktok-growth-india",
    reason: "The comparison is distinct, but the current TikTok cluster is intentionally compact and should not expand without demand evidence.",
    cannibalizationRisk: "medium",
    businessRelevance: 4,
    internalLinkValue: 4,
    uniqueInformationValue: 4,
  },
  {
    id: "organic-growth-india",
    queryTheme: "how to grow TikTok organically in India",
    intent: "informational",
    decision: "defer",
    primaryTarget: "/tiktok-growth-india",
    reason: "The broad TikTok growth hub should absorb this topic until verified demand supports a dedicated organic-growth guide.",
    cannibalizationRisk: "medium",
    businessRelevance: 4,
    internalLinkValue: 4,
    uniqueInformationValue: 4,
  },
] as const;

export const telegramContentGapCandidates: readonly PlatformContentGapCandidate[] = [
  {
    id: "members-price-india",
    queryTheme: "Telegram members price in India",
    intent: "commercial-research",
    decision: "covered",
    primaryTarget: "/blog/telegram-members-price-in-india",
    reason: "The existing pricing guide already owns this research intent.",
    cannibalizationRisk: "high",
    businessRelevance: 5,
    internalLinkValue: 5,
    uniqueInformationValue: 1,
  },
  {
    id: "member-safety",
    queryTheme: "is it safe to buy Telegram members",
    intent: "commercial-research",
    decision: "covered",
    primaryTarget: "/blog/is-it-safe-to-buy-telegram-members",
    reason: "The existing safety guide already owns this risk-evaluation intent.",
    cannibalizationRisk: "high",
    businessRelevance: 5,
    internalLinkValue: 4,
    uniqueInformationValue: 1,
  },
  {
    id: "public-link-safety",
    queryTheme: "Telegram public-link ordering safety",
    intent: "commercial-research",
    decision: "covered",
    primaryTarget: "/blog/why-public-link-ordering-is-safer",
    reason: "The shared public-link guide already covers the ordering-safety question.",
    cannibalizationRisk: "high",
    businessRelevance: 4,
    internalLinkValue: 4,
    uniqueInformationValue: 1,
  },
  {
    id: "members-vs-post-views",
    queryTheme: "Telegram members vs post views",
    intent: "informational",
    decision: "defer",
    primaryTarget: "/services/telegram",
    reason: "The service hub already explains the available Telegram engagement options; a separate comparison URL needs verified query evidence.",
    cannibalizationRisk: "medium",
    businessRelevance: 4,
    internalLinkValue: 5,
    uniqueInformationValue: 4,
  },
  {
    id: "reactions-vs-poll-votes",
    queryTheme: "Telegram reactions vs poll votes",
    intent: "informational",
    decision: "defer",
    primaryTarget: "/services/telegram",
    reason: "This is a narrow service-selection question that should stay inside the Telegram hub unless demand evidence proves a standalone guide is useful.",
    cannibalizationRisk: "medium",
    businessRelevance: 3,
    internalLinkValue: 4,
    uniqueInformationValue: 4,
  },
] as const;

export const additionalPlatformContentGapSources = [
  { source: "YouTube" as const, candidates: youtubeContentGapCandidates },
  { source: "Facebook" as const, candidates: facebookContentGapCandidates },
  { source: "X / Twitter" as const, candidates: twitterContentGapCandidates },
  { source: "TikTok" as const, candidates: tiktokContentGapCandidates },
  { source: "Telegram" as const, candidates: telegramContentGapCandidates },
] as const;
