"use client";

import { AnimatePresence, motion } from "framer-motion";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type PlatformId = "instagram" | "youtube" | "facebook" | "twitter";
type Service = { id: string; platform: PlatformId; name: string; description: string; rate: number; delivery: string; quality: string; refill: string; minimum: number; maximum: number; features: string[]; popular?: boolean };

const platforms: { id: PlatformId; name: string; description: string; gradient: string }[] = [
  { id: "instagram", name: "Instagram", description: "Audience, engagement and content visibility", gradient: "from-fuchsia-500 to-rose-500" },
  { id: "youtube", name: "YouTube", description: "Channel growth and video promotion", gradient: "from-red-500 to-rose-600" },
  { id: "facebook", name: "Facebook", description: "Page authority and brand engagement", gradient: "from-blue-500 to-blue-700" },
  { id: "twitter", name: "Twitter / X", description: "Profile authority and conversation reach", gradient: "from-slate-700 to-slate-950" },
];

const services: Service[] = [
  { id: "ig-followers", platform: "instagram", name: "Instagram Real Followers", description: "Increase your Instagram presence with high-quality followers delivered gradually. Ideal for creators, influencers, brands, and businesses looking to build stronger social proof and profile authority.", rate: 599, delivery: "1-7 days", quality: "Premium", refill: "30 days", minimum: 100, maximum: 100000, features: ["Gradual delivery", "Refill support", "Premium quality", "Safe ordering"], popular: true },
  { id: "ig-likes", platform: "instagram", name: "Instagram Real Likes", description: "Improve engagement and content performance with likes delivered from active social media promotion campaigns.", rate: 299, delivery: "1-3 days", quality: "Quality Checked", refill: "30 days", minimum: 100, maximum: 50000, features: ["Fast delivery", "Higher engagement", "Refill available", "Quality checked"] },
  { id: "ig-views", platform: "instagram", name: "Instagram Video Views", description: "Increase video visibility and maximize content exposure across reels and video content.", rate: 49, delivery: "1-2 days", quality: "Premium", refill: "15 days", minimum: 500, maximum: 500000, features: ["Fast delivery", "Content exposure", "Safe service", "Quality checked"] },
  { id: "yt-subscribers", platform: "youtube", name: "YouTube Subscribers", description: "Build channel authority and strengthen your audience base with premium subscriber growth solutions.", rate: 3999, delivery: "3-10 days", quality: "Premium", refill: "30 days", minimum: 100, maximum: 50000, features: ["Premium quality", "Gradual delivery", "Refill support", "Long-term growth"], popular: true },
  { id: "yt-likes", platform: "youtube", name: "YouTube Likes", description: "Increase engagement and improve social proof across your videos with high-quality likes.", rate: 899, delivery: "1-4 days", quality: "High", refill: "30 days", minimum: 100, maximum: 50000, features: ["Fast delivery", "Premium quality", "Refill available", "Safe ordering"] },
  { id: "yt-views", platform: "youtube", name: "YouTube Views", description: "Boost video discoverability and expand audience reach through increased video exposure.", rate: 499, delivery: "2-7 days", quality: "High Retention", refill: "30 days", minimum: 500, maximum: 500000, features: ["High retention", "Gradual delivery", "Refill support", "Quality checked"] },
  { id: "fb-followers", platform: "facebook", name: "Facebook Followers", description: "Grow your page audience and improve brand credibility with quality follower campaigns.", rate: 499, delivery: "2-8 days", quality: "Premium", refill: "30 days", minimum: 100, maximum: 100000, features: ["Premium quality", "Gradual delivery", "Refill support", "Safe service"], popular: true },
  { id: "fb-likes", platform: "facebook", name: "Facebook Post Likes", description: "Increase engagement on your Facebook posts and improve audience interaction.", rate: 299, delivery: "1-5 days", quality: "High", refill: "30 days", minimum: 100, maximum: 50000, features: ["Fast delivery", "Higher engagement", "Refill available", "Quality checked"] },
  { id: "fb-views", platform: "facebook", name: "Facebook Video Views", description: "Expand reach and improve performance of Facebook video content.", rate: 199, delivery: "1-3 days", quality: "Premium", refill: "15 days", minimum: 500, maximum: 500000, features: ["Fast delivery", "Content reach", "Safe service", "Quality checked"] },
  { id: "x-followers", platform: "twitter", name: "Twitter/X Followers", description: "Build authority and increase profile visibility with premium follower growth.", rate: 999, delivery: "2-7 days", quality: "Premium", refill: "30 days", minimum: 100, maximum: 100000, features: ["Premium quality", "Gradual delivery", "Refill support", "Safe ordering"], popular: true },
];

function PlatformIcon({ platform, className = "h-6 w-6" }: { platform: PlatformId; className?: string }) {
  const paths = {
    instagram: <><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/></>,
    youtube: <><path d="M21 12s0-4-1-5-1-1-7-1-7-1-1 0-1 1-1 5-1 5 0 4 1 5 1 1 7 1 7 1s6 0 7-1c1-1 1-5 1-5Z"/><path d="m10 9 5 3-5 3Z"/></>,
    facebook: <path d="M14 8h3V4h-3c-3 0-5 2-5 5v3H6v4h3v6h4v-6h3l1-4h-4V9c0-.6.4-1 1-1Z"/>,
    twitter: <path d="M4 4l16 16M20 4 4 20M9 4l11 16M4 4l11 16"/>,
  };
  return <svg viewBox="0 0 24 24" className={className} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[platform]}</svg>;
}

const fadeUp = { initial: { opacity: 0, y: 14 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.35 } };

export default function NewCampaignPage() {
  const router = useRouter();
  const [platform, setPlatform] = useState<PlatformId>("instagram");
  const [selectedId, setSelectedId] = useState("ig-followers");
  const [link, setLink] = useState("");
  const [quantity, setQuantity] = useState(1000);
  const [databaseIds, setDatabaseIds] = useState<Record<PlatformId, number>>({ instagram: 0, youtube: 0, facebook: 0, twitter: 0 });
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    void createClient().from("services").select("id, categories(name)").eq("status", "active").then(({ data }) => {
      const ids = { instagram: 0, youtube: 0, facebook: 0, twitter: 0 };
      for (const row of data ?? []) { const name = ((row.categories as unknown as { name?: string } | null)?.name || "").toLowerCase(); const key = name.includes("instagram") ? "instagram" : name.includes("youtube") ? "youtube" : name.includes("facebook") ? "facebook" : name.includes("twitter") || name.includes("x/") ? "twitter" : null; if (key && !ids[key]) ids[key] = row.id; }
      setDatabaseIds(ids);
    });
  }, []);

  const visibleServices = useMemo(() => services.filter((service) => service.platform === platform), [platform]);
  const selected = services.find((service) => service.id === selectedId) ?? visibleServices[0];
  const total = Math.max(0, selected.rate / 1000 * quantity);
  const currentPlatform = platforms.find((item) => item.id === platform)!;

  function choosePlatform(id: PlatformId) { setPlatform(id); const first = services.find((service) => service.platform === id); if (first) setSelectedId(first.id); }
  function packageForQuantity(value: number) { return value <= 1000 ? "starter" : value <= 5000 ? "growth" : value <= 15000 ? "professional" : "premium"; }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); const serviceId = databaseIds[platform]; if (!serviceId) { setError("This platform is still being configured. Please try again shortly."); return; } setSubmitting(true); const response = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ serviceId, link, package: packageForQuantity(quantity) }) }); const payload = await response.json() as { error?: string }; setSubmitting(false); if (!response.ok) { setError(payload.error || "Unable to create campaign."); return; } router.push("/dashboard/order-history"); router.refresh(); }

  return <main className="min-h-[calc(100vh-5rem)] overflow-hidden bg-[radial-gradient(circle_at_top_right,#dbeafe_0,transparent_28%),linear-gradient(180deg,#f8faff_0%,#f4f7fb_100%)] p-4 sm:p-6 lg:p-8">
    <motion.section {...fadeUp} className="mx-auto max-w-[1650px]"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="inline-flex rounded-full border border-blue-200 bg-white/70 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.18em] text-blue-700 shadow-sm backdrop-blur">Campaign studio</span><h1 className="mt-4 text-3xl font-bold tracking-[-.035em] text-[#07152f] sm:text-4xl">Create a new growth campaign</h1><p className="mt-2 text-sm text-slate-500">Select a platform, choose a service, and configure your campaign with live pricing.</p></div><div className="flex gap-2 text-[10px] font-semibold text-slate-500">{["Premium quality", "Secure checkout", "Live tracking"].map((item) => <span key={item} className="rounded-full border border-white bg-white/70 px-3 py-2 shadow-sm">✓ {item}</span>)}</div></div>

      <div className="mt-7 grid gap-5 xl:grid-cols-[240px_minmax(0,1fr)_370px]">
        <aside className="rounded-3xl border border-white/80 bg-white/70 p-4 shadow-[0_20px_60px_-35px_rgba(15,45,95,.4)] backdrop-blur-xl"><p className="px-2 text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">Choose platform</p><div className="mt-4 space-y-2">{platforms.map((item) => <motion.button whileHover={{ x: 4 }} whileTap={{ scale: .98 }} key={item.id} type="button" onClick={() => choosePlatform(item.id)} className={`w-full rounded-2xl border p-3.5 text-left transition ${platform === item.id ? "border-blue-200 bg-blue-50 shadow-sm" : "border-transparent hover:border-slate-200 hover:bg-white"}`}><div className="flex items-center gap-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-gradient-to-br text-white shadow-md ${item.gradient}`}><PlatformIcon platform={item.id} className="h-5 w-5"/></span><div className="min-w-0"><p className={`text-xs font-bold ${platform === item.id ? "text-blue-700" : "text-slate-700"}`}>{item.name}</p><p className="mt-1 line-clamp-2 text-[9px] leading-4 text-slate-400">{item.description}</p></div></div></motion.button>)}</div><div className="mt-5 rounded-2xl bg-[#07152f] p-4 text-white"><p className="text-[10px] font-bold uppercase tracking-wider text-blue-400">Need guidance?</p><p className="mt-2 text-[10px] leading-5 text-slate-400">Our campaign specialists can help choose the right service for your goals.</p><a href="/dashboard/support" className="mt-3 inline-flex text-[10px] font-bold text-white">Talk to support →</a></div></aside>

        <section className="min-w-0"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-600">{currentPlatform.name} services</p><h2 className="mt-1 text-xl font-bold text-[#07152f]">Choose your growth objective</h2></div><span className="rounded-full bg-white px-3 py-2 text-[10px] font-semibold text-slate-400 shadow-sm">{visibleServices.length} services</span></div><AnimatePresence mode="wait"><motion.div key={platform} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .25 }} className="mt-4 grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{visibleServices.map((service) => <motion.button whileHover={{ y: -5 }} whileTap={{ scale: .985 }} type="button" key={service.id} onClick={() => setSelectedId(service.id)} className={`relative overflow-hidden rounded-3xl border bg-white p-5 text-left shadow-sm transition ${selected.id === service.id ? "border-blue-500 ring-2 ring-blue-500/10 shadow-xl shadow-blue-900/10" : "border-slate-200/80 hover:border-blue-200 hover:shadow-xl"}`}>{service.popular && <span className="absolute right-4 top-4 rounded-full bg-amber-50 px-2.5 py-1 text-[8px] font-black uppercase tracking-wider text-amber-700">Popular</span>}<span className={`grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br text-white shadow-lg ${currentPlatform.gradient}`}><PlatformIcon platform={service.platform} className="h-5 w-5"/></span><h3 className="mt-5 pr-14 text-sm font-bold text-[#07152f]">{service.name}</h3><p className="mt-2 min-h-10 text-[11px] leading-5 text-slate-500">{service.description}</p><div className="mt-5 flex items-end justify-between border-t border-slate-100 pt-4"><div><p className="text-[8px] uppercase tracking-wider text-slate-400">Rate</p><p className="mt-1 text-lg font-bold text-blue-600">₹{service.rate}<span className="text-[9px] font-medium text-slate-400"> / 1000</span></p></div><div className="text-right"><p className="text-[8px] uppercase text-slate-400">Delivery</p><p className="mt-1 text-[10px] font-bold text-slate-600">{service.delivery}</p></div></div><span className={`absolute bottom-0 left-0 h-1 bg-gradient-to-r from-blue-600 to-cyan-400 transition-all ${selected.id === service.id ? "w-full" : "w-0"}`}/></motion.button>)}</motion.div></AnimatePresence>
          <motion.div layout className="mt-5 rounded-3xl border border-slate-200/80 bg-white p-5 shadow-sm"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[9px] font-bold uppercase tracking-wider text-blue-600">Selected service</p><h3 className="mt-2 text-base font-bold">{selected.name}</h3><p className="mt-1 text-xs text-slate-500">{selected.description}</p></div><div className="flex flex-wrap gap-2">{[["Quality",selected.quality],["Delivery",selected.delivery],["Refill",selected.refill]].map(([label,value]) => <div key={label} className="rounded-xl bg-slate-50 px-4 py-3"><p className="text-[8px] uppercase text-slate-400">{label}</p><p className="mt-1 text-[10px] font-bold">{value}</p></div>)}</div></div></motion.div>
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} key={`${selected.id}-details`} className="mt-4 grid gap-3 rounded-3xl border border-blue-100 bg-gradient-to-r from-blue-50 to-cyan-50 p-4 sm:grid-cols-2 lg:grid-cols-3">
            {selected.features.map((feature) => <div key={feature} className="flex items-center gap-2 text-[10px] font-bold text-blue-800"><span className="grid h-5 w-5 place-items-center rounded-full bg-white text-emerald-600 shadow-sm">✓</span>{feature}</div>)}
            <div className="rounded-xl bg-white/80 p-3"><p className="text-[8px] font-bold uppercase tracking-wider text-slate-400">Minimum order</p><p className="mt-1 text-xs font-bold text-[#07152f]">{selected.minimum.toLocaleString("en-IN")}</p></div>
            <div className="rounded-xl bg-white/80 p-3"><p className="text-[8px] font-bold uppercase tracking-wider text-slate-400">Maximum order</p><p className="mt-1 text-xs font-bold text-[#07152f]">{selected.maximum.toLocaleString("en-IN")}</p></div>
          </motion.div>
        </section>

        <aside className="h-fit overflow-hidden rounded-3xl border border-white/80 bg-white/80 shadow-[0_25px_80px_-35px_rgba(15,45,95,.45)] backdrop-blur-xl xl:sticky xl:top-24"><div className="bg-gradient-to-br from-[#07152f] to-[#123a78] p-6 text-white"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-blue-300">Live campaign preview</p><h2 className="mt-2 text-lg font-bold">Order summary</h2></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10"><PlatformIcon platform={selected.platform} className="h-5 w-5"/></span></div><div className="mt-5 rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs font-bold">{selected.name}</p><p className="mt-1 text-[10px] text-slate-400">{currentPlatform.name} · {selected.quality}</p></div><div className="mt-5 space-y-3 text-[10px]"><div className="flex justify-between"><span className="text-slate-400">Rate</span><span className="font-bold">₹{selected.rate} / 1000</span></div><div className="flex justify-between"><span className="text-slate-400">Quantity</span><span className="font-bold">{quantity.toLocaleString("en-IN")}</span></div><div className="flex justify-between"><span className="text-slate-400">Estimated delivery</span><span className="font-bold">{selected.delivery}</span></div><div className="flex justify-between"><span className="text-slate-400">Quality score</span><span className="font-bold text-emerald-400">9.7 / 10</span></div><div className="flex justify-between"><span className="text-slate-400">Refill status</span><span className="font-bold text-blue-300">{selected.refill} available</span></div></div><div className="mt-5 flex items-end justify-between border-t border-white/10 pt-5"><span className="text-xs text-slate-300">Total price</span><motion.span key={total} initial={{ scale: .9, opacity: .5 }} animate={{ scale: 1, opacity: 1 }} className="text-3xl font-bold">₹{total.toFixed(2)}</motion.span></div></div>
          <form onSubmit={submit} className="p-6"><label className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Profile or content link<input type="url" required value={link} onChange={(event) => setLink(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10" placeholder="https://social-platform.com/profile"/></label><label className="mt-5 block text-[10px] font-bold uppercase tracking-wider text-slate-500">Campaign quantity<input type="number" required min={100} max={10000} step={100} value={quantity} onChange={(event) => setQuantity(Math.max(0, Number(event.target.value)))} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></label><div className="mt-3 grid grid-cols-5 gap-1.5">{[100,500,1000,5000,10000].map((value) => <button key={value} type="button" onClick={() => setQuantity(value)} className={`rounded-lg py-2 text-[9px] font-bold transition ${quantity === value ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-500 hover:bg-blue-50 hover:text-blue-600"}`}>{value >= 1000 ? `${value / 1000}K` : value}</button>)}</div>{error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-[10px] leading-5 text-rose-700">{error}</p>}<button disabled={submitting} className="mt-5 w-full rounded-xl bg-gradient-to-r from-blue-600 to-blue-700 py-3.5 text-xs font-bold text-white shadow-lg shadow-blue-600/20 transition hover:-translate-y-0.5 hover:shadow-xl disabled:opacity-50">{submitting ? "Processing..." : "Proceed to checkout →"}</button><div className="mt-4 grid grid-cols-2 gap-2">{["Premium quality","Refill available","Fast delivery","Secure checkout"].map((badge) => <span key={badge} className="text-[9px] font-semibold text-slate-500">✓ {badge}</span>)}</div></form>
        </aside>
      </div>

      <section className="mt-12 grid gap-5 lg:grid-cols-3"><motion.article whileHover={{ y: -4 }} className="rounded-3xl border border-white bg-white/70 p-6 shadow-sm backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-wider text-blue-600">Customer reviews</p><div className="mt-4 text-sm tracking-widest text-amber-400">★★★★★</div><blockquote className="mt-4 text-sm leading-7 text-slate-600">“The campaign setup feels polished, transparent, and genuinely built for professional teams.”</blockquote><p className="mt-5 text-xs font-bold">Maya Kapoor · Brand Director</p></motion.article><motion.article whileHover={{ y: -4 }} className="rounded-3xl bg-[#07152f] p-6 text-white shadow-xl"><p className="text-[10px] font-bold uppercase tracking-wider text-blue-400">Why SocialRUSH</p><ul className="mt-5 space-y-4">{["Transparent live pricing", "Quality-assured campaign delivery", "Real-time dashboard tracking", "Dedicated customer support"].map((item) => <li key={item} className="flex gap-3 text-xs text-slate-300"><span className="text-emerald-400">✓</span>{item}</li>)}</ul></motion.article><article className="rounded-3xl border border-white bg-white/70 p-6 shadow-sm backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-wider text-blue-600">Frequently asked</p><div className="mt-4 space-y-2">{[["When does delivery begin?","Campaign review begins immediately after checkout."],["Can I track progress?","Yes, live status remains available in Campaign History."],["What is refill coverage?","Eligible delivery is reviewed during the displayed refill window."]].map(([question,answer]) => <details key={question} className="group rounded-xl border border-slate-200 bg-white"><summary className="flex cursor-pointer list-none justify-between p-3 text-[10px] font-bold"><span>{question}</span><span className="text-blue-600 group-open:rotate-45">+</span></summary><p className="border-t px-3 py-3 text-[10px] leading-5 text-slate-500">{answer}</p></details>)}</div></article></section>
    </motion.section>
  </main>;
}
