import Link from "next/link";
import MarketingHeader from "@/components/marketing/MarketingHeader";
import MarketingFooter from "@/components/marketing/MarketingFooter";
import PortalCTA from "@/components/marketing/PortalCTA";

type IconName = "search" | "ads" | "meta" | "social" | "web" | "ai" | "whatsapp" | "leads" | "content" | "local" | "chart" | "spark" | "shield" | "arrow";

const iconPaths: Record<IconName, React.ReactNode> = {
  search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4M11 8v6M8 11h6"/></>,
  ads: <><path d="m4 17 7-12 3 6 6 6"/><path d="M6 14h11M3 20h18"/></>,
  meta: <><path d="M3 16c2-8 4-10 6-10 3 0 5 12 8 12 2 0 3-3 4-6"/><path d="M21 16c-2-8-4-10-6-10-3 0-5 12-8 12-2 0-3-3-4-6"/></>,
  social: <><circle cx="6" cy="12" r="3"/><circle cx="18" cy="6" r="3"/><circle cx="18" cy="18" r="3"/><path d="m8.6 10.5 6.8-3M8.6 13.5l6.8 3"/></>,
  web: <><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M7 6.5h.01M10 6.5h.01"/></>,
  ai: <><rect x="5" y="5" width="14" height="14" rx="4"/><path d="M9 10h.01M15 10h.01M9 15c2 1 4 1 6 0M12 2v3M2 12h3M19 12h3"/></>,
  whatsapp: <><path d="M20 11.5A8 8 0 0 1 8.1 18.5L3 20l1.5-5A8 8 0 1 1 20 11.5Z"/><path d="M8.5 8.5c1 3 2 4 5 5"/></>,
  leads: <><circle cx="9" cy="8" r="4"/><path d="M3 20c0-4 2-7 6-7s6 3 6 7M18 8v6M15 11h6"/></>,
  content: <><path d="M5 3h10l4 4v14H5Z"/><path d="M14 3v5h5M8 12h8M8 16h6"/></>,
  local: <><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,
  chart: <><path d="M4 19V9M10 19V5M16 19v-7M22 19H2"/></>,
  spark: <><path d="m12 3 1.3 4.7L18 9l-4.7 1.3L12 15l-1.3-4.7L6 9l4.7-1.3Z"/><path d="m19 15 .6 2.4L22 18l-2.4.6L19 21l-.6-2.4L16 18l2.4-.6Z"/></>,
  shield: <><path d="M12 3 5 6v5c0 4.6 2.8 7.8 7 10 4.2-2.2 7-5.4 7-10V6Z"/><path d="m9 12 2 2 4-4"/></>,
  arrow: <><path d="M5 12h14M14 7l5 5-5 5"/></>,
};

function Icon({ name, className = "h-5 w-5" }: { name: IconName; className?: string }) {
  return <svg viewBox="0 0 24 24" className={className} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{iconPaths[name]}</svg>;
}

const services: { name: string; description: string; icon: IconName; tag: string }[] = [
  { name: "SEO Services", description: "Build sustainable organic visibility with technical SEO, keyword strategy, and authoritative content.", icon: "search", tag: "Organic growth" },
  { name: "Google Ads Management", description: "Turn search intent into qualified enquiries with expertly managed, conversion-focused campaigns.", icon: "ads", tag: "Paid acquisition" },
  { name: "Meta Ads Management", description: "Reach valuable audiences across Facebook and Instagram with creative testing and smart optimization.", icon: "meta", tag: "Performance media" },
  { name: "Social Media Marketing", description: "Create a consistent brand presence through strategy, publishing, community, and performance reporting.", icon: "social", tag: "Brand building" },
  { name: "Website Design", description: "Launch fast, responsive websites designed to communicate trust and convert visitors into customers.", icon: "web", tag: "Digital experience" },
  { name: "AI Automation", description: "Automate repetitive sales, marketing, and support workflows with practical AI systems built for your team.", icon: "ai", tag: "Operational efficiency" },
  { name: "WhatsApp Automation", description: "Improve response times with automated enquiries, lead qualification, reminders, and customer journeys.", icon: "whatsapp", tag: "Conversational growth" },
  { name: "Lead Generation", description: "Build reliable pipelines using audience research, landing pages, media campaigns, and lead nurturing.", icon: "leads", tag: "Pipeline growth" },
  { name: "Content Marketing", description: "Earn attention and trust through useful articles, campaign creative, and strategic brand storytelling.", icon: "content", tag: "Authority building" },
  { name: "Local SEO", description: "Help nearby customers discover your business through maps visibility, local content, and profile optimization.", icon: "local", tag: "Local discovery" },
];

const faqs = [
  ["What does SocialRUSH do?", "SocialRUSH is an AI-powered digital marketing and automation agency. We help businesses improve visibility, acquire qualified leads, strengthen customer journeys, and automate repetitive work."],
  ["Who do you work with?", "We partner with businesses, startups, creators, and local brands. Every engagement is shaped around commercial goals, available resources, and the realities of your market."],
  ["How do you build a marketing strategy?", "We begin with a discovery and digital audit, define measurable priorities, select the right channels, and create a practical execution roadmap with clear reporting."],
  ["How quickly can a project start?", "Most engagements can begin after scope approval and onboarding. Your proposal will clearly state the expected start date, milestones, dependencies, and delivery schedule."],
  ["Do you guarantee specific results?", "No responsible agency can guarantee rankings, revenue, or advertising outcomes. We commit to transparent execution, careful optimization, and reporting against agreed performance indicators."],
  ["Will I receive performance reports?", "Yes. Clients receive clear updates covering work completed, campaign performance, insights, and recommended next steps at the cadence agreed in the proposal."],
  ["Can you work with our existing team?", "Absolutely. We can operate as your external growth partner or collaborate with internal marketing, sales, design, and technology teams."],
  ["How is pricing decided?", "Pricing depends on scope, channels, campaign complexity, required technology, and delivery timeline. We provide a written proposal before any paid engagement begins."],
];

export default function HomePage() {
  return <main className="min-h-screen overflow-hidden bg-white text-slate-900">
    <MarketingHeader/>

    <section className="relative bg-[linear-gradient(180deg,#f3f7ff_0%,#fff_100%)] px-5 pb-20 pt-16 sm:px-6 lg:px-8 lg:pb-28 lg:pt-24">
      <div className="hero-grid absolute inset-0 opacity-50"/><div className="absolute -left-20 top-10 h-80 w-80 rounded-full bg-blue-200/40 blur-3xl"/><div className="absolute right-0 top-20 h-96 w-96 rounded-full bg-cyan-200/30 blur-3xl"/>
      <div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.03fr_.97fr]">
        <div>
          <span className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-white/80 px-3.5 py-2 text-[11px] font-bold uppercase tracking-[.14em] text-blue-700 shadow-sm backdrop-blur"><Icon name="spark" className="h-4 w-4"/> AI-powered digital growth agency</span>
          <h1 className="mt-7 max-w-3xl text-4xl font-bold leading-[1.07] tracking-[-.05em] text-[#07152f] sm:text-5xl lg:text-[64px]">Marketing that turns attention into <span className="bg-gradient-to-r from-blue-600 to-cyan-500 bg-clip-text text-transparent">measurable growth.</span></h1>
          <p className="mt-6 max-w-2xl text-base leading-8 text-slate-600 sm:text-lg">SocialRUSH is an AI-powered digital marketing and automation agency helping businesses, startups, creators, and local brands attract customers, improve conversions, and scale efficiently.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><PortalCTA className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3.5 text-sm font-bold text-white shadow-xl shadow-blue-600/20 transition hover:-translate-y-0.5 hover:bg-blue-700">Get a Growth Plan <Icon name="arrow" className="h-4 w-4"/></PortalCTA><Link href="#services" className="inline-flex items-center justify-center rounded-xl border border-slate-200 bg-white px-6 py-3.5 text-sm font-bold text-slate-700 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-200 hover:text-blue-600">Explore Services</Link></div>
          <div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-[11px] font-semibold text-slate-500">{["Strategy-led execution", "Transparent reporting", "Secure payments", "Dedicated support"].map((item) => <span key={item} className="flex items-center gap-2"><i className="grid h-5 w-5 place-items-center rounded-full bg-emerald-50 not-italic text-emerald-600">✓</i>{item}</span>)}</div>
        </div>
        <div className="relative mx-auto w-full max-w-xl">
          <div className="absolute -inset-6 rounded-[40px] bg-gradient-to-br from-blue-300/30 to-cyan-200/20 blur-2xl"/>
          <div className="relative rounded-[30px] border border-white bg-white/75 p-3 shadow-[0_35px_90px_-30px_rgba(15,55,115,.38)] backdrop-blur-xl">
            <div className="rounded-[24px] border border-slate-200 bg-[#f8fafc] p-5 sm:p-6">
              <div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-blue-600">Growth command center</p><h2 className="mt-1 text-base font-bold text-[#07152f]">Marketing performance</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-[9px] font-bold text-emerald-700">● Live</span></div>
              <div className="mt-6 rounded-2xl bg-gradient-to-br from-blue-600 to-blue-800 p-5 text-white shadow-xl shadow-blue-900/20"><div className="flex items-start justify-between"><div><p className="text-[9px] uppercase tracking-wider text-blue-200">Qualified pipeline</p><p className="mt-2 text-3xl font-bold">₹28.4L</p></div><span className="rounded-full bg-white/15 px-2.5 py-1 text-[9px] font-bold text-emerald-300">+32.8%</span></div><div className="mt-7 flex h-20 items-end gap-2">{[28,42,35,58,52,76,68,91].map((height,index) => <span key={index} style={{ height: `${height}%` }} className="flex-1 rounded-t-sm bg-white/80"/>)}</div></div>
              <div className="mt-4 grid gap-3 sm:grid-cols-3">{[["4.8x","Marketing ROI"],["-31%","Cost per lead"],["+67%","Conversion rate"]].map(([value,label]) => <article key={label} className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><p className="text-lg font-bold text-[#07152f]">{value}</p><p className="mt-1 text-[8px] uppercase tracking-wider text-slate-400">{label}</p></article>)}</div>
              <div className="mt-4 flex items-center justify-between rounded-xl border border-blue-100 bg-blue-50 p-3"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-blue-600 text-white"><Icon name="ai" className="h-4 w-4"/></span><div><p className="text-[10px] font-bold text-[#07152f]">AI workflow optimization</p><p className="mt-0.5 text-[8px] text-slate-500">12 hours saved this week</p></div></div><span className="text-xs font-bold text-blue-600">Active</span></div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section className="border-y border-slate-100 bg-white px-5 py-8"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-7 md:grid-cols-4">{[["120+","Growth projects"],["4.7x","Average reported ROAS"],["92%","Client retention"],["24h","Response target"]].map(([value,label]) => <div key={label} className="text-center"><p className="text-2xl font-bold text-[#07152f]">{value}</p><p className="mt-1 text-[9px] font-semibold uppercase tracking-wider text-slate-400">{label}</p></div>)}</div></section>

    <section id="about" className="px-5 py-20 sm:px-6 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-2"><div className="relative rounded-[30px] bg-[#07152f] p-7 text-white shadow-2xl shadow-blue-950/20 sm:p-10"><div className="absolute right-0 top-0 h-40 w-40 rounded-full bg-blue-500/20 blur-3xl"/><p className="relative text-xs font-bold uppercase tracking-[.2em] text-blue-400">Built for ambitious teams</p><h2 className="relative mt-4 text-3xl font-bold tracking-tight">One partner for strategy, technology, and execution.</h2><div className="relative mt-8 grid gap-3 sm:grid-cols-2">{["Channel strategy","Conversion systems","Campaign operations","Automation workflows"].map((item,index) => <div key={item} className="rounded-2xl border border-white/10 bg-white/5 p-4"><span className="text-xs font-bold text-blue-400">0{index+1}</span><p className="mt-3 text-sm font-semibold">{item}</p></div>)}</div></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">About SocialRUSH</p><h2 className="mt-4 text-3xl font-bold tracking-[-.04em] text-[#07152f] sm:text-4xl">We make digital growth clearer, smarter, and more accountable.</h2><p className="mt-5 text-sm leading-7 text-slate-600 sm:text-base">SocialRUSH brings together marketing strategy, performance media, search, creative, web experiences, and intelligent automation. Our work is designed around business outcomes—not vanity metrics.</p><p className="mt-4 text-sm leading-7 text-slate-600 sm:text-base">From the first audit to ongoing optimization, clients get a collaborative team, clear priorities, documented delivery, and straightforward reporting.</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{[["Strategy first","Every channel supports a defined commercial objective."],["Transparent delivery","Clear scope, timelines, ownership, and performance updates."]].map(([title,text]) => <div key={title} className="border-l-2 border-blue-500 pl-4"><h3 className="text-sm font-bold text-[#07152f]">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div>)}</div></div></div></section>

    <section id="services" className="bg-[#f6f9ff] px-5 py-20 sm:px-6 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Digital growth services</p><h2 className="mt-4 text-3xl font-bold tracking-[-.04em] text-[#07152f] sm:text-4xl">A connected growth engine for your business.</h2><p className="mt-4 text-sm leading-7 text-slate-500 sm:text-base">Choose focused services or combine channels into an integrated strategy aligned to acquisition, conversion, and retention.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{services.map((service) => <article key={service.name} className="group rounded-2xl border border-white bg-white/85 p-5 shadow-sm transition duration-300 hover:-translate-y-1.5 hover:border-blue-200 hover:shadow-xl hover:shadow-blue-900/5"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-600 transition group-hover:bg-blue-600 group-hover:text-white"><Icon name={service.icon}/></span><p className="mt-5 text-[9px] font-bold uppercase tracking-wider text-blue-600">{service.tag}</p><h3 className="mt-2 text-sm font-bold text-[#07152f]">{service.name}</h3><p className="mt-3 text-[11px] leading-5 text-slate-500">{service.description}</p><PortalCTA className="mt-5 inline-flex items-center gap-1 text-[10px] font-bold text-blue-600">Launch campaign <Icon name="arrow" className="h-3 w-3"/></PortalCTA></article>)}</div></div></section>

    <section id="work" className="px-5 py-20 sm:px-6 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Selected case studies</p><h2 className="mt-4 text-3xl font-bold tracking-[-.04em] text-[#07152f] sm:text-4xl">Growth systems built around real business goals.</h2></div><p className="max-w-md text-xs leading-6 text-slate-500">Illustrative engagement summaries. Results vary by market, offer, budget, and execution conditions.</p></div><div className="mt-12 grid gap-6 lg:grid-cols-3">{[
      { sector: "Local healthcare", title: "A stronger local acquisition engine", text: "Search strategy, landing-page improvements, and lead routing created a more reliable enquiry workflow.", metrics: [["+74%","Qualified enquiries"],["-29%","Cost per enquiry"]], color: "from-blue-600 to-cyan-500" },
      { sector: "B2B technology", title: "From scattered activity to one revenue system", text: "Content, paid search, CRM automation, and reporting were aligned around priority accounts and opportunities.", metrics: [["3.6x","Attributed pipeline"],["+41%","Demo conversion"]], color: "from-violet-600 to-blue-600" },
      { sector: "Consumer services", title: "Faster follow-up with intelligent automation", text: "WhatsApp workflows and sales alerts reduced manual handling while keeping customer conversations personal.", metrics: [["-68%","Response time"],["21 hrs","Saved monthly"]], color: "from-cyan-500 to-emerald-500" },
    ].map((study) => <article key={study.title} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className={`h-2 bg-gradient-to-r ${study.color}`}/><div className="p-6"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-blue-600">{study.sector}</p><h3 className="mt-3 text-xl font-bold leading-7 text-[#07152f]">{study.title}</h3><p className="mt-3 text-xs leading-6 text-slate-500">{study.text}</p><div className="mt-6 grid grid-cols-2 gap-3">{study.metrics.map(([value,label]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><p className="text-lg font-bold text-[#07152f]">{value}</p><p className="mt-1 text-[8px] uppercase tracking-wider text-slate-400">{label}</p></div>)}</div></div></article>)}</div></div></section>

    <section id="reviews" className="bg-[#07152f] px-5 py-20 text-white sm:px-6 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-400">Client perspectives</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">A partner your team can rely on.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[["The team brought structure to our digital marketing and made every recommendation easy to understand. We finally have a clear view of what is working.","Aarav Mehta","Founder, consumer brand"],["SocialRUSH connected our campaigns, landing pages, and follow-up process. The collaboration feels thoughtful, responsive, and commercially focused.","Sofia Khan","Marketing Lead, B2B services"],["Their automation work reduced repetitive tasks without making our customer experience feel robotic. That balance mattered enormously to us.","Daniel Joseph","Director, local services"]].map(([quote,name,role]) => <figure key={name} className="rounded-2xl border border-white/10 bg-white/5 p-6 transition hover:-translate-y-1 hover:bg-white/[.07]"><div className="text-sm tracking-widest text-amber-400">★★★★★</div><blockquote className="mt-5 text-sm leading-7 text-slate-300">“{quote}”</blockquote><figcaption className="mt-6 border-t border-white/10 pt-5"><p className="text-xs font-bold">{name}</p><p className="mt-1 text-[10px] text-slate-500">{role}</p></figcaption></figure>)}</div></div></section>

    <section id="faq" className="relative bg-[#f6f9ff] px-5 py-20 sm:px-6 lg:px-8 lg:py-28"><div className="hero-grid absolute inset-0 opacity-30"/><div className="relative mx-auto max-w-4xl"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Frequently asked questions</p><h2 className="mt-4 text-3xl font-bold tracking-[-.04em] text-[#07152f] sm:text-4xl">What to expect from working together.</h2><p className="mt-4 text-sm leading-7 text-slate-500">Clear answers about our agency, process, reporting, and commercial approach.</p></div><div className="mt-12 grid gap-3 md:grid-cols-2">{faqs.map(([question,answer],index) => <details key={question} className="group h-fit overflow-hidden rounded-2xl border border-white bg-white/85 shadow-sm open:border-blue-200 open:shadow-lg"><summary className="flex cursor-pointer list-none items-center gap-4 p-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-blue-50 text-xs font-bold text-blue-600">{String(index+1).padStart(2,"0")}</span><span className="flex-1 text-sm font-bold text-[#07152f]">{question}</span><span className="grid h-7 w-7 place-items-center rounded-full bg-slate-50 text-blue-600 transition group-open:rotate-45">+</span></summary><p className="border-t border-blue-50 px-5 py-5 pl-[5.25rem] text-xs leading-6 text-slate-500">{answer}</p></details>)}</div></div></section>

    <section id="contact" className="px-5 py-20 sm:px-6 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl overflow-hidden rounded-[32px] bg-gradient-to-br from-blue-600 to-[#07152f] shadow-2xl shadow-blue-950/20 lg:grid-cols-[1fr_.9fr]"><div className="relative p-7 text-white sm:p-10 lg:p-14"><div className="absolute -left-20 -top-20 h-72 w-72 rounded-full bg-cyan-400/20 blur-3xl"/><div className="relative"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-200">Start a conversation</p><h2 className="mt-4 max-w-xl text-3xl font-bold tracking-tight sm:text-4xl">Let’s build your next growth system.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-blue-100">Tell us about your business, current challenges, and priorities. We’ll recommend a focused next step—without pressure or inflated promises.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="mailto:support@socialrush.in?subject=Digital%20Marketing%20Consultation" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-6 py-3.5 text-sm font-bold text-blue-700 shadow-lg">Email Our Team <Icon name="arrow" className="h-4 w-4"/></a><PortalCTA className="inline-flex items-center justify-center rounded-xl border border-white/20 bg-white/10 px-6 py-3.5 text-sm font-bold text-white backdrop-blur">Create Client Account</PortalCTA></div></div></div><div className="border-t border-white/10 bg-white/10 p-7 text-white backdrop-blur sm:p-10 lg:border-l lg:border-t-0 lg:p-14"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-200">Contact details</p><div className="mt-7 space-y-5">{[["Business enquiries","support@socialrush.in"],["Response target","Within one business day"],["Client services","India and international"]].map(([label,value]) => <div key={label} className="border-b border-white/10 pb-5"><p className="text-[9px] uppercase tracking-wider text-blue-200/70">{label}</p><p className="mt-2 text-sm font-semibold">{value}</p></div>)}</div><div className="mt-6 flex items-center gap-3 rounded-xl bg-emerald-400/10 p-3 text-xs font-semibold text-emerald-300"><Icon name="shield" className="h-5 w-5"/> Secure and confidential enquiry handling</div></div></div></section>

    <MarketingFooter/>
  </main>;
}
