"use client";

import Link from "next/link";
import { useState } from "react";
import Logo from "./Logo";
import FooterSocialLinks from "./marketing/FooterSocialLinks";

const columns = [
  { title: "Platform", links: [["Instagram Followers", "/buy-instagram-followers-india"], ["YouTube Subscribers", "/youtube-subscribers"], ["Facebook Followers", "/buy-facebook-followers-india"], ["Twitter/X Followers", "/twitter-followers"], ["Dashboard", "/dashboard"]] },
  { title: "Company", links: [["About SocialRUSH", "/about"], ["How It Works", "/about"], ["Pricing", "/pricing"], ["Contact", "/contact"], ["Support", "/support"]] },
  { title: "Resources", links: [["Creator Tools", "/tools"], ["Help Center", "/support"], ["FAQs", "/faq"], ["Blog", "/blog"], ["Contact Support", "/contact"]] },
  { title: "Legal", links: [["Terms & Conditions", "/terms-and-conditions"], ["Privacy Policy", "/privacy-policy"], ["Refund Policy", "/refund-policy"], ["Service Policy", "/terms-and-conditions"]] },
];

export default function Footer() {
  const [subscribed, setSubscribed] = useState(false);
  return <footer className="relative overflow-hidden bg-gradient-to-br from-[#0B0B0F] via-[#0B0B0F] to-[#0B0B0F] text-white"><div className="absolute -left-24 top-20 h-72 w-72 rounded-full bg-orange-600/15 blur-3xl"/><div className="absolute -right-24 bottom-0 h-80 w-80 rounded-full bg-amber-500/10 blur-3xl"/><div className="hero-grid absolute inset-0 opacity-[.06]"/><div className="relative mx-auto max-w-7xl px-5 pb-8 pt-14 sm:px-6 lg:px-8"><div className="rounded-3xl border border-white/10 bg-white/[.065] p-6 shadow-2xl backdrop-blur-xl sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-xl"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-orange-400">Social growth insights</p><h2 className="mt-3 text-2xl font-bold">Get campaign strategies in your inbox.</h2><p className="mt-2 text-sm text-slate-400">Practical growth ideas, platform updates, and SocialRUSH product news.</p></div><form onSubmit={(event) => { event.preventDefault(); setSubscribed(true); }} className="flex w-full max-w-lg flex-col gap-2 sm:flex-row"><input type="email" required aria-label="Email address" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-sm text-white outline-none placeholder:text-slate-500 focus:border-orange-400" placeholder="you@company.com"/><button className="rounded-xl bg-orange-600 px-5 py-3 text-sm font-bold shadow-lg shadow-orange-600/20 hover:bg-orange-500">{subscribed ? "Subscribed ✓" : "Join newsletter"}</button></form></div></div>
      <div className="grid gap-10 py-14 lg:grid-cols-[1.35fr_3fr]"><div><Logo light/><p className="mt-5 max-w-sm text-sm leading-7 text-slate-400">SocialRUSH helps creators, brands and businesses manage social media growth campaigns with public-link ordering, transparent pricing, secure checkout, dashboard tracking and WhatsApp support.</p><div className="mt-5 inline-flex items-center gap-2 rounded-full border border-emerald-400/15 bg-emerald-400/10 px-3 py-2 text-[9px] font-bold uppercase tracking-wider text-emerald-400"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400"/>Platform Operational</div><FooterSocialLinks /></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-4">{columns.map((column) => <div key={column.title}><h3 className="text-[10px] font-bold uppercase tracking-[.18em] text-white">{column.title}</h3><ul className="mt-5 space-y-3.5">{column.links.map(([label,href]) => <li key={label}><Link href={href} className="text-xs text-slate-400 transition hover:text-orange-300">{label}</Link></li>)}</ul></div>)}</div></div>
      <div className="flex flex-wrap items-center justify-center gap-3 border-y border-white/10 py-5">{["Secure Payments","SSL Protected","Refill Support","Real-Time Tracking","Professional Support"].map((item) => <span key={item} className="flex items-center gap-2 text-[9px] font-semibold text-slate-400"><i className="text-emerald-400">✓</i>{item}</span>)}</div><div className="flex flex-col gap-3 pt-7 text-center text-[10px] text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:text-left"><p>© 2026 SocialRUSH. All rights reserved.</p><p>Secure payments <span className="mx-2 text-slate-700">•</span> Refill support <span className="mx-2 text-slate-700">•</span> Real-time tracking</p><Link href="/support" className="font-bold text-orange-400 hover:text-orange-300">Support centre</Link></div></div></footer>;
}
