import Link from "next/link";
import { campaignPackages } from "@/lib/campaign-packages";

const studies = [
  ["D2C Wellness Brand", "+184%", "qualified content reach", "A 90-day visibility program aligned creator content, campaign timing, and weekly optimization."],
  ["B2B Technology Company", "3.6x", "campaign engagement", "A professional visibility strategy strengthened thought leadership and meaningful brand interactions."],
  ["Creator Management Agency", "42%", "faster operations", "Centralized workflows and automation reduced manual coordination across a multi-creator portfolio."],
];

export default function GrowthProof() {
  return <>
    <section className="border-y border-slate-100 bg-white px-5 py-10"><div className="mx-auto max-w-7xl"><p className="text-center text-[10px] font-bold uppercase tracking-[.2em] text-slate-400">Built for modern growth teams</p><div className="mt-7 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">{["NORTHSTAR", "VELOCE", "LUMEN", "ARCSTONE", "NOVALABS", "MOTION"].map((name) => <div key={name} className="grid h-12 place-items-center rounded-xl border border-slate-100 bg-slate-50/60 text-[11px] font-black tracking-[.15em] text-slate-400">{name}</div>)}</div><div className="mt-8 flex flex-wrap justify-center gap-3">{["Secure campaign wallet", "Role-based data protection", "99.9% platform availability", "Real-time reporting", "Automation-ready API"].map((badge) => <span key={badge} className="rounded-full border border-blue-100 bg-blue-50 px-3 py-2 text-[10px] font-bold text-blue-700">✓ {badge}</span>)}</div></div></section>

    <section className="bg-[#f7f9fc] px-5 py-20 sm:px-6 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Campaign performance</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-[#0a1733] sm:text-4xl">Growth programs backed by measurable outcomes.</h2><p className="mt-4 text-sm leading-7 text-slate-500">Professional campaign strategy, clear execution, and transparent reporting turn marketing activity into business momentum.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{studies.map(([sector,result,metric,detail]) => <article key={sector} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><p className="text-[10px] font-bold uppercase tracking-wider text-blue-600">{sector}</p><p className="mt-6 text-4xl font-bold tracking-tight text-[#0a1733]">{result}</p><p className="mt-2 text-sm font-semibold text-emerald-600">{metric}</p><p className="mt-5 border-t border-slate-100 pt-5 text-xs leading-6 text-slate-500">{detail}</p><Link href="/register" className="mt-5 inline-flex text-xs font-bold text-blue-600">Build a similar campaign →</Link></article>)}</div><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4">{[["96.8%","campaigns on track"],["2.4x","average reach improvement"],["38%","less manual coordination"],["24/7","performance visibility"]].map(([value,label]) => <div key={label} className="rounded-2xl bg-[#0a1733] p-5 text-center text-white"><p className="text-2xl font-bold">{value}</p><p className="mt-2 text-[10px] uppercase tracking-wider text-slate-400">{label}</p></div>)}</div></div></section>

    <section className="px-5 py-20 sm:px-6 lg:px-8 lg:py-28"><div className="mx-auto max-w-[1500px]"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Campaign packages</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-[#0a1733] sm:text-4xl">Choose the growth program that fits your ambition.</h2><p className="mt-4 text-sm leading-7 text-slate-500">Every package combines campaign execution, performance visibility, and professional support around a clear marketing outcome.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{campaignPackages.map((item,index) => <article key={item.id} className={`relative flex flex-col rounded-3xl p-6 ${index === 2 ? "border-2 border-blue-600 bg-white shadow-2xl shadow-blue-900/10" : index === 4 ? "bg-[#0a1733] text-white" : "border border-slate-200 bg-white shadow-sm"}`}>{index === 2 && <span className="absolute right-5 top-0 -translate-y-1/2 rounded-full bg-blue-600 px-3 py-1 text-[9px] font-bold uppercase text-white">Recommended</span>}<p className={`text-xs font-bold uppercase tracking-wider ${index === 4 ? "text-blue-400" : "text-blue-600"}`}>{item.name}</p><p className="mt-4 text-2xl font-bold">{item.priceLabel}</p><p className={`mt-2 text-xs ${index === 4 ? "text-slate-400" : "text-slate-500"}`}>{item.duration}</p><div className={`mt-5 rounded-xl p-3 ${index === 4 ? "bg-white/5" : "bg-slate-50"}`}><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Expected outcome</p><p className="mt-2 text-[11px] font-semibold leading-5">{item.outcome}</p></div><ul className={`mt-5 space-y-3 text-[11px] ${index === 4 ? "text-slate-400" : "text-slate-500"}`}>{item.features.map((feature) => <li key={feature} className="flex gap-2"><span className="text-emerald-500">✓</span>{feature}</li>)}</ul><div className="mt-auto pt-6"><dl className="space-y-3 border-t border-slate-200/20 pt-5 text-[10px]"><div><dt className="text-slate-400">Recommended for</dt><dd className="mt-1 font-semibold">{item.audience}</dd></div><div className="flex justify-between"><dt className="text-slate-400">ROI potential</dt><dd className="font-bold text-emerald-500">{item.roi}</dd></div></dl><Link href={item.id === "enterprise" ? "/dashboard/support" : "/register"} className={`mt-5 block rounded-xl py-3 text-center text-xs font-bold ${index === 4 ? "bg-white text-[#0a1733]" : "bg-blue-600 text-white"}`}>{item.id === "enterprise" ? "Request proposal" : "Choose package"}</Link></div></article>)}</div></div></section>
  </>;
}
