export const agencyServices = [
  { slug:"instagram-followers",name:"Instagram Real Followers",platform:"Instagram",price:"₹599 / 1000",summary:"Build social proof and strengthen your Instagram presence with premium follower growth services.",deliverables:["Gradual processing","30-day refill support","Live order tracking","Secure wallet checkout"],ideal:"Creators, influencers, brands, and businesses" },
  { slug:"instagram-likes",name:"Instagram Likes",platform:"Instagram",price:"₹299 / 1000",summary:"Improve engagement and make your content look more active and trustworthy.",deliverables:["Fast processing","Eligible refill coverage","Post and reel support","Dashboard tracking"],ideal:"Reels, posts, launches, and brand content" },
  { slug:"instagram-views",name:"Instagram Views",platform:"Instagram",price:"₹49 / 1000",summary:"Boost reel and video visibility with fast, affordable view delivery.",deliverables:["Reels and video support","Fast activation","Transparent pricing","Order history"],ideal:"Creators, publishers, and campaign teams" },
  { slug:"youtube-subscribers",name:"YouTube Subscribers",platform:"YouTube",price:"₹3,999 / 1000",summary:"Grow your channel authority and build a stronger subscriber base.",deliverables:["Gradual processing","30-day refill support","Channel-safe ordering","Status tracking"],ideal:"YouTubers, educators, brands, and media teams" },
  { slug:"youtube-likes",name:"YouTube Likes",platform:"YouTube",price:"₹899 / 1000",summary:"Increase video engagement and improve social proof on your content.",deliverables:["Video-level campaigns","Quality checked delivery","Refill eligibility","Support access"],ideal:"Videos, premieres, and campaign content" },
  { slug:"youtube-views",name:"YouTube Views",platform:"YouTube",price:"₹499 / 1000",summary:"Improve video reach and visibility with high-quality view campaigns.",deliverables:["High-retention options","Gradual delivery","Real-time status","Clear estimates"],ideal:"Channels, creators, brands, and agencies" },
  { slug:"facebook-followers",name:"Facebook Followers",platform:"Facebook",price:"₹499 / 1000",summary:"Build your page audience and improve brand credibility.",deliverables:["Page campaigns","Gradual processing","Refill coverage","Secure checkout"],ideal:"Businesses, communities, and public pages" },
  { slug:"facebook-likes",name:"Facebook Post Likes",platform:"Facebook",price:"₹299 / 1000",summary:"Increase engagement on your Facebook posts and improve audience activity.",deliverables:["Post-specific delivery","Fast activation","Order tracking","Support tickets"],ideal:"Business posts, promotions, and content teams" },
  { slug:"facebook-views",name:"Facebook Video Views",platform:"Facebook",price:"₹199 / 1000",summary:"Expand video reach and improve content performance.",deliverables:["Video campaigns","Fast processing","Transparent rates","Live dashboard"],ideal:"Video publishers, businesses, and creators" },
  { slug:"linkedin-followers",name:"LinkedIn Profile Followers",platform:"LinkedIn",price:"From ₹1,499 / 1000",summary:"Strengthen professional profile visibility with a structured follower growth campaign.",deliverables:["Professional profile campaigns","Gradual processing","Clear order status","Support access"],ideal:"Founders, consultants, recruiters, and business creators" },
  { slug:"linkedin-likes",name:"LinkedIn Post Likes",platform:"LinkedIn",price:"From ₹899 / 1000",summary:"Improve visible engagement on important professional posts and company updates.",deliverables:["Public post campaigns","Transparent quantity pricing","Dashboard tracking","Support access"],ideal:"Thought leadership, hiring, launches, and company news" },
  { slug:"tiktok-followers",name:"TikTok Followers",platform:"TikTok",price:"From ₹799 / 1000",summary:"Build profile social proof with a clear, trackable TikTok follower campaign.",deliverables:["Profile growth campaigns","Gradual processing","Order tracking","Eligible support"],ideal:"Creators, artists, brands, and entertainment accounts" },
  { slug:"tiktok-likes",name:"TikTok Likes",platform:"TikTok",price:"From ₹299 / 1000",summary:"Increase visible interaction on selected public TikTok videos.",deliverables:["Video-specific ordering","Fast processing","Transparent pricing","Campaign history"],ideal:"Short-form videos, launches, and creator content" },
  { slug:"tiktok-views",name:"TikTok Video Views",platform:"TikTok",price:"From ₹99 / 1000",summary:"Support content reach with affordable, trackable TikTok video view campaigns.",deliverables:["Public video links","Fast activation","Live status","Support tickets"],ideal:"Creators, musicians, brands, and publishers" },
  { slug:"twitter-followers",name:"Twitter/X Followers",platform:"Twitter/X",price:"₹999 / 1000",summary:"Grow profile authority and improve visibility on X/Twitter.",deliverables:["Profile growth campaigns","Gradual processing","Refill eligibility","Campaign tracking"],ideal:"Founders, creators, brands, and communities" },
];

export const publicFaqs = [
  ["What is SocialRUSH?","SocialRUSH is a premium social media growth platform for ordering and tracking Instagram, YouTube, Facebook, LinkedIn, TikTok, and Twitter/X growth services from one secure dashboard."],
  ["How do I place an order?","Create an account, add funds through the wallet, open New Campaign, choose a service, paste the public profile or content link, select quantity, and confirm checkout."],
  ["Do I need to share my password?","No. SocialRUSH never asks for your social media password. Customers provide only the public profile, post, reel, channel, or video link required for processing."],
  ["How do payments work?","Add funds securely through supported Razorpay payment methods. Verified payments credit your wallet, and campaign charges are deducted only when an order is placed."],
  ["How long does delivery take?","Delivery varies by service and quantity. The estimated processing window is displayed before checkout and progress remains visible in Campaign History."],
  ["What is refill support?","Eligible services include refill coverage for the displayed period. If qualifying delivery drops during that window, open a support ticket with the order ID."],
  ["Can I track my order?","Yes. Order status, amount, destination, date, and progress are available inside your protected dashboard."],
  ["Which platforms do you support?","The public catalog covers Instagram, YouTube, Facebook, LinkedIn, TikTok, and Twitter/X. Live availability is shown inside the campaign dashboard."],
  ["What if my order is delayed?","Check the delivery estimate first. If processing exceeds that window, create a support ticket and the team will review the order."],
  ["Can agencies use SocialRUSH?","Yes. The wallet, order history, service catalog, and support workflow are suitable for agencies and social media managers handling multiple campaigns."],
];

export const caseStudies = [
  {type:"Independent creator",category:"Instagram Growth",goal:"Strengthen profile presentation before a product collaboration.",strategy:"A gradual follower campaign supported by selected reel visibility orders and clear delivery tracking.",result:"A more established profile presentation and a simpler repeat-order workflow through the dashboard."},
  {type:"Education channel",category:"YouTube Growth",goal:"Improve channel authority around a new content series.",strategy:"Subscriber growth and selected video reach campaigns scheduled across the launch period.",result:"Stronger channel social proof with every campaign and transaction visible in one workspace."},
  {type:"Local retail brand",category:"Facebook Growth",goal:"Increase visible activity around promotional video content.",strategy:"Page follower, post engagement, and video view services selected according to campaign priorities.",result:"More consistent public presentation and easier campaign management for the internal marketing team."},
  {type:"Boutique agency",category:"Multi-platform",goal:"Manage repeat client requests without scattered payment and status records.",strategy:"Centralized wallet funding, structured orders, campaign history, and support tickets.",result:"A cleaner operational workflow with transparent pricing and searchable order records."},
];

export const testimonials = [
  ["The dashboard is straightforward. I can see the rate, place an order, and track the status without messaging someone for every update.","AK","Independent creator"],
  ["Wallet funding and campaign history made repeat orders much easier for our small marketing team.","RS","Local business owner"],
  ["We manage several creator campaigns, so having order IDs, amounts, and support in one place is genuinely useful.","NM","Agency manager"],
  ["The delivery estimate was clear and support responded with an order-specific update when I needed help.","VP","YouTube creator"],
];
