export const agencyServices = [
  { slug: "seo", name: "SEO Services", summary: "Build durable search visibility through technical improvements, keyword strategy, and useful content.", deliverables: ["Technical and content audit", "Keyword and competitor research", "On-page optimization", "Monthly performance reporting"], ideal: "Growing companies, ecommerce teams, and service businesses" },
  { slug: "google-ads", name: "Google Ads Management", summary: "Capture high-intent demand with accountable search and performance campaigns.", deliverables: ["Account and conversion setup", "Campaign architecture", "Ad and landing-page testing", "Budget and bid optimization"], ideal: "Lead-generation, ecommerce, and local businesses" },
  { slug: "meta-ads", name: "Meta Ads Management", summary: "Reach valuable audiences with thoughtful creative, testing, and conversion-focused media buying.", deliverables: ["Audience and offer strategy", "Creative testing plan", "Campaign management", "Attribution reporting"], ideal: "Consumer brands, educators, and service companies" },
  { slug: "social-media", name: "Social Media Marketing", summary: "Build a consistent brand presence with channel strategy, content operations, and community management.", deliverables: ["Channel strategy", "Content calendar", "Publishing workflows", "Engagement reporting"], ideal: "Brands, founders, creators, and local companies" },
  { slug: "web-development", name: "Website Design & Development", summary: "Launch fast, accessible websites engineered to communicate trust and generate enquiries.", deliverables: ["UX and content structure", "Responsive design", "Development and QA", "Analytics and conversion setup"], ideal: "Startups, professional services, and established businesses" },
  { slug: "ai-chatbots", name: "AI Chatbots", summary: "Give prospects and customers helpful, on-brand answers while routing complex requests to your team.", deliverables: ["Conversation design", "Knowledge-base setup", "Lead capture and routing", "Testing and improvement"], ideal: "Support, sales, education, and appointment-led businesses" },
  { slug: "whatsapp", name: "WhatsApp Automation", summary: "Improve response times with compliant enquiry, reminder, and follow-up workflows.", deliverables: ["Journey mapping", "Message templates", "CRM or form integration", "Handover and monitoring"], ideal: "Clinics, local services, education, and sales teams" },
  { slug: "crm-automation", name: "CRM & Lead Automation", summary: "Connect forms, campaigns, pipelines, and follow-up so every qualified opportunity receives attention.", deliverables: ["Pipeline architecture", "Lead scoring and routing", "Automated follow-up", "Dashboard and team training"], ideal: "B2B, high-consideration sales, and multi-location teams" },
  { slug: "content", name: "Content Marketing", summary: "Earn attention and trust with strategic articles, guides, campaigns, and brand storytelling.", deliverables: ["Editorial strategy", "Topic and audience research", "Content production", "Distribution and measurement"], ideal: "Expert-led brands, SaaS, and professional services" },
  { slug: "local-seo", name: "Local SEO & Business Profile", summary: "Help nearby customers find and choose your business across maps and local search.", deliverables: ["Profile optimization", "Local keyword plan", "Citation and review guidance", "Local visibility reporting"], ideal: "Clinics, restaurants, studios, stores, and local services" },
];

export const publicFaqs = [
  ["What does SocialRUSH do?", "SocialRUSH is an AI-powered digital marketing and automation agency. We help businesses improve visibility, generate qualified demand, strengthen customer journeys, and automate repetitive work."],
  ["How does onboarding work?", "We begin with a discovery call and a review of your goals, audience, current channels, and constraints. You then receive a written scope with deliverables, timelines, responsibilities, and fees."],
  ["Which industries do you work with?", "We work with startups, ecommerce companies, professional services, local businesses, educators, clinics, hospitality teams, and creator-led brands. Fit depends on the goal and scope rather than industry alone."],
  ["Can you manage SEO, advertising, websites, and automation together?", "Yes. We can deliver a focused project or coordinate several channels as one growth system, with shared measurement and clear ownership."],
  ["How long will results take?", "Timelines vary by service, market, budget, and starting position. Paid campaigns can generate early learning quickly, while SEO and complex automation usually require sustained work. We provide realistic milestones before work starts."],
  ["How do you report performance?", "Reporting is agreed during onboarding and may include dashboards, written summaries, and review calls. We explain work completed, key indicators, insights, and recommended actions."],
  ["What support is included?", "Each engagement defines a primary contact, communication channel, and response expectations. Urgent platform incidents are prioritized, while strategic requests are scheduled into the delivery plan."],
  ["How does billing work?", "Projects may be billed by milestone, monthly retainer, or agreed fixed scope. Fees, taxes, media budgets, third-party costs, and payment dates are disclosed in the proposal or checkout before payment."],
  ["Do you offer a strategy call?", "Yes. Use the contact page to request an introductory consultation. We will confirm whether we are a suitable fit and suggest the most useful next step."],
];

export const caseStudies = [
  { type: "B2B software company", category: "SEO", goal: "Increase qualified organic discovery for high-intent solution terms.", strategy: "Technical cleanup, topic clusters, conversion-focused pages, and a measurement framework.", result: "+83% non-brand organic sessions and 38% more qualified demo enquiries over nine months." },
  { type: "Professional services firm", category: "Lead Generation", goal: "Build a more predictable pipeline without relying only on referrals.", strategy: "Search campaigns, focused landing pages, CRM routing, and weekly message testing.", result: "42% lower cost per qualified enquiry and a 3.4x attributed pipeline-to-spend ratio." },
  { type: "Ecommerce wellness brand", category: "Meta Ads", goal: "Improve acquisition efficiency while introducing new creative concepts.", strategy: "Offer segmentation, structured creative testing, product-page improvements, and budget reallocation.", result: "4.1x blended return on ad spend during the measured campaign period." },
  { type: "Multi-location clinic", category: "Local SEO", goal: "Increase appointment demand from nearby customers across three locations.", strategy: "Business Profile optimization, local pages, review workflows, and citation consistency.", result: "+69% local discovery actions and 31% more tracked appointment calls in six months." },
  { type: "Education startup", category: "Website & Automation", goal: "Replace manual lead handling with a clearer digital enrollment journey.", strategy: "Website redesign, qualification forms, CRM stages, WhatsApp reminders, and team alerts.", result: "Response time reduced from hours to minutes, with 24 team hours saved each month." },
];

export const testimonials = [
  ["SocialRUSH gave our marketing a structure we could actually operate. The team connected search, landing pages, and reporting, and every recommendation came with a clear commercial reason.", "Aarav Mehta", "Founder, local services company"],
  ["The creative testing process was disciplined and transparent. We understood what changed, why it changed, and how the learning influenced the next campaign cycle.", "Sofia Khan", "Ecommerce founder"],
  ["Our new website finally explains our offer clearly. The enquiry and follow-up automation also removed a surprising amount of repetitive administrative work.", "Daniel Joseph", "Independent consultant"],
  ["Local search had always felt vague. The team helped us fix our profiles, location pages, and review process, then reported progress in language our clinic team understood.", "Dr. Rhea Kapoor", "Clinic owner"],
  ["They worked well with our internal product and sales teams. The result was not another disconnected tool—it was a practical lead workflow people actually adopted.", "Kabir Shah", "Startup co-founder"],
];
