"use client";

import Link from "next/link";
import { ArrowRight, Camera, CheckCircle2, ChevronRight, Eye, Layers3, LineChart, Sparkles, Target, Users, Video } from "lucide-react";
import { useMemo, useState } from "react";

type VerifiedStory = { slug: string; title: string; platform: string; customer_type: string; challenge: string; outcome: string };

const scenarios = [
  { id: "creator", filter: "Creators", platform: "Instagram", title: "Independent Creator", goal: "Build a stronger visible profile presence", challenge: "A consistent content rhythm needs a profile presentation that feels ready for new visitors.", approach: "Plan support around published content, beginning with the profile and then prioritising selected posts.", services: ["Instagram Followers", "Instagram Likes", "Instagram Views"], track: ["Profile visits", "Follower count", "Post engagement"], href: "/services/instagram", tone: "instagram", icon: Camera },
  { id: "education", filter: "YouTube", platform: "YouTube", title: "Education Channel", goal: "Give useful videos a clearer launch plan", challenge: "Evergreen educational content often needs a deliberate publishing and visibility rhythm.", approach: "Map subscriber, views and likes services to the channel calendar rather than treating every video identically.", services: ["YouTube Subscribers", "YouTube Views", "YouTube Likes"], track: ["Video views", "Audience retention", "Channel visits"], href: "/services/youtube", tone: "youtube", icon: Video },
  { id: "retail", filter: "Local Business", platform: "Facebook + Instagram", title: "Local Retail Brand", goal: "Create a more considered public social presence", challenge: "Product posts, seasonal activity and a local audience all need a consistent campaign structure.", approach: "Use a simple planning cadence across business-page activity and visual product content.", services: ["Facebook Page Followers", "Instagram Followers", "Instagram Views"], track: ["Profile visits", "Post reach", "Website clicks"], href: "/services/facebook", tone: "facebook", icon: Users },
  { id: "agency", filter: "Agencies", platform: "Multi-platform", title: "Boutique Agency", goal: "Coordinate service discovery across client workspaces", challenge: "Multiple clients and platforms make service selection and order tracking more complex.", approach: "Organise platforms, selected services and tracking responsibilities before individual campaign orders are placed.", services: ["Instagram Services", "YouTube Services", "Facebook Services", "LinkedIn Services"], track: ["Order status", "Platform activity", "Client reporting"], href: "/services", tone: "agency", icon: Layers3 },
] as const;

const filters = ["All", "Creators", "YouTube", "Local Business", "Agencies"];

function PlatformPreview({ scenario }: { scenario: typeof scenarios[number] }) {
  const Icon = scenario.icon;
  const thumb = scenario.tone === "youtube" ? "bg-red-500/20" : scenario.tone === "facebook" ? "bg-blue-500/20" : scenario.tone === "agency" ? "bg-violet-500/20" : "bg-fuchsia-500/20";
  return <div className={`cs-preview cs-${scenario.tone}`} aria-label={`Illustrative ${scenario.platform} interface preview`}>
    <div className="flex items-center justify-between border-b border-white/10 px-4 py-3 text-[10px] font-bold text-slate-400"><span className="flex items-center gap-2"><Icon className="h-4 w-4 text-white"/> {scenario.platform}</span><span className="rounded-full bg-white/10 px-2 py-1">UI PREVIEW</span></div>
    <div className="p-4"><div className="flex items-center gap-3"><div className={`grid h-11 w-11 place-items-center rounded-2xl ${thumb}`}><Icon className="h-5 w-5 text-white"/></div><div><div className="h-2.5 w-24 rounded bg-white/80"/><div className="mt-2 h-2 w-16 rounded bg-white/15"/></div><button className="ml-auto rounded-lg bg-white px-2.5 py-1.5 text-[9px] font-black text-slate-950">Profile</button></div>
      <div className="mt-5 grid grid-cols-3 gap-2">{[1,2,3].map((i) => <div key={i} className={`aspect-[.85] rounded-xl border border-white/10 ${thumb} p-2`}><div className="h-full rounded-lg bg-gradient-to-br from-white/20 to-transparent"/></div>)}</div>
      <div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl border border-white/10 bg-black/20 p-3"><p className="text-[9px] text-slate-400">Campaign focus</p><p className="mt-1 text-xs font-bold text-white">{scenario.goal}</p></div><div className="rounded-xl border border-orange-300/20 bg-orange-400/10 p-3"><p className="text-[9px] text-orange-100/70">Planning</p><p className="mt-1 text-xs font-bold text-orange-100">Service mix</p></div></div>
    </div>
  </div>;
}

export default function CaseStudiesShowcase({ verified }: { verified: VerifiedStory[] }) {
  const [filter, setFilter] = useState("All");
  const visible = useMemo(() => filter === "All" ? scenarios : scenarios.filter((scenario) => scenario.filter === filter), [filter]);
  return <main className="case-studies-premium overflow-hidden">
    <section className="cs-hero relative px-4 pb-14 pt-14 sm:px-6 lg:px-8 lg:pb-24 lg:pt-20"><div className="cs-grid absolute inset-0 opacity-40"/><div className="relative mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.02fr_.98fr] lg:items-center"><div><p className="cs-eyebrow"><Sparkles className="h-3.5 w-3.5"/> Case studies & growth scenarios</p><h1 className="mt-5 max-w-3xl text-5xl font-black tracking-[-.065em] text-white sm:text-6xl lg:text-7xl">See how SocialRUSH strategies can support different growth goals.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-[#b5bdcb] sm:text-lg">These planning examples show possible service combinations and campaign structures. They are not customer performance claims or guaranteed outcomes.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#scenarios" className="btn-primary gap-2">Explore scenarios <ArrowRight className="h-4 w-4"/></a><Link href="/services" className="btn-secondary">View services</Link></div><p className="mt-6 text-xs font-bold text-slate-400">Transparent scenarios <span className="mx-2 text-orange-300">•</span> No fabricated outcomes <span className="mx-2 text-orange-300">•</span> Clear service context</p></div>
      <div className="relative mx-auto w-full max-w-xl py-5"><div className="cs-orbit cs-orbit-one"/><div className="cs-orbit cs-orbit-two"/><div className="cs-dashboard relative overflow-hidden rounded-[2rem] border border-orange-300/25 p-4 shadow-[0_35px_80px_rgba(0,0,0,.48)] sm:p-5"><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-[.18em] text-orange-200">Strategy workspace</span><span className="flex items-center gap-1 text-[10px] text-emerald-300"><i className="h-1.5 w-1.5 rounded-full bg-emerald-300"/> Planning mode</span></div><div className="mt-5 grid grid-cols-[1.1fr_.9fr] gap-3"><div className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="flex gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-gradient-to-br from-fuchsia-500 to-orange-400"><Camera className="h-4 w-4"/></span><span className="grid h-8 w-8 place-items-center rounded-xl bg-red-500/70"><Video className="h-4 w-4"/></span></div><p className="mt-6 text-xs font-bold text-white">Objective</p><p className="mt-1 text-sm text-slate-400">Profile & content visibility</p><div className="mt-5 h-1.5 w-full rounded-full bg-white/10"><div className="h-full w-2/3 rounded-full bg-gradient-to-r from-orange-500 to-amber-300"/></div></div><div className="grid gap-3"><div className="rounded-2xl border border-white/10 bg-white/[.045] p-3"><Target className="h-4 w-4 text-orange-300"/><p className="mt-3 text-[10px] text-slate-400">Service mix</p><p className="text-xs font-bold">Context-led</p></div><div className="rounded-2xl border border-white/10 bg-white/[.045] p-3"><Eye className="h-4 w-4 text-sky-300"/><p className="mt-3 text-[10px] text-slate-400">Tracking</p><p className="text-xs font-bold">Independent</p></div></div></div><div className="mt-3 grid grid-cols-3 gap-2">{["Platform", "Delivery approach", "Order status"].map((label, i) => <div key={label} className="rounded-xl border border-white/10 bg-white/[.035] p-3"><p className="text-[9px] text-slate-500">{label}</p><p className="mt-2 text-[10px] font-bold text-white">{i === 0 ? "Multi-channel" : i === 1 ? "Campaign plan" : "Dashboard"}</p></div>)}</div></div></div></div></section>
    <section id="scenarios" className="border-y border-white/[.07] bg-[#0a0d15] px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="cs-eyebrow">Scenario navigator</p><h2 className="mt-3 text-3xl font-black text-white">Growth planning, by context.</h2></div><div className="flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="Scenario categories">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} role="tab" aria-selected={filter === item} className={`cs-filter ${filter === item ? "cs-filter-active" : ""}`}>{item}</button>)}</div></div></div></section>
    <section className="px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl space-y-10">{visible.map((scenario, index) => <article id={scenario.id} key={scenario.id} className={`cs-scenario ${index % 2 ? "lg:grid-flow-col-dense" : ""}`}><div className={index % 2 ? "lg:col-start-2" : ""}><div className="flex flex-wrap gap-2"><span className="cs-label">Illustrative planning scenario</span><span className="cs-platform">{scenario.platform}</span></div><h2 className="mt-5 text-3xl font-black text-white sm:text-4xl">{scenario.title}</h2><p className="mt-4 text-lg font-semibold text-orange-100">{scenario.goal}</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><div><h3>The context</h3><p>{scenario.challenge}</p></div><div><h3>SocialRUSH approach</h3><p>{scenario.approach}</p></div></div><div className="mt-7"><p className="text-[10px] font-black uppercase tracking-[.16em] text-slate-500">Suggested service mix</p><div className="mt-3 flex flex-wrap gap-2">{scenario.services.map((service) => <span key={service} className="cs-service-chip">{service}<ChevronRight className="h-3 w-3"/></span>)}</div></div><Link href={scenario.href} className="mt-7 inline-flex min-h-11 items-center gap-2 text-sm font-black text-orange-300">Explore {scenario.platform.split(" + ")[0]} services <ArrowRight className="h-4 w-4"/></Link></div><div className={index % 2 ? "lg:col-start-1 lg:row-start-1" : ""}><PlatformPreview scenario={scenario}/></div></article>)}</div></section>
    <section className="border-y border-white/[.07] bg-[#0c0f18] px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="cs-eyebrow">Planning timeline</p><h2 className="mt-4 text-3xl font-black text-white">A measured campaign structure.</h2><p className="mt-4 max-w-md text-sm leading-7 text-slate-400">This is a planning sequence, not a forecast of performance progression.</p></div><ol className="cs-timeline">{[["01", "Establish profile presence"], ["02", "Support selected content"], ["03", "Plan post or video visibility"], ["04", "Track orders and adapt"]].map(([number, title]) => <li key={number}><span>{number}</span><p>{title}</p></li>)}</ol></div></section>
    <section className="px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="cs-track-card"><p className="cs-eyebrow">Customer education</p><h2 className="mt-4 text-3xl font-black text-white">What should you track after running a campaign?</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400">Monitor your own follower count, engagement rate, views, profile visits, website clicks, leads and sales in your platform and business analytics. SocialRUSH service delivery does not guarantee downstream business outcomes.</p><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3">{["Follower count", "Engagement rate", "Video views", "Profile visits", "Website clicks", "Own analytics"].map((item) => <div key={item} className="rounded-xl border border-white/10 bg-black/15 p-3 text-xs font-bold text-slate-200"><LineChart className="mb-3 h-4 w-4 text-orange-300"/>{item}</div>)}</div></div><div className="cs-transparency"><CheckCircle2 className="h-6 w-6 text-emerald-300"/><h2 className="mt-5 text-2xl font-black text-white">What these case studies represent</h2>{[["Planning examples", "How different customers might structure campaigns."], ["Real service information", "Availability and pricing remain tied to the current catalog."], ["No guaranteed outcomes", "Results depend on content, audience and platform behaviour."], ["Track independently", "Use your own analytics for business decisions."]].map(([title, description]) => <div key={title} className="mt-5 border-t border-white/10 pt-4"><h3 className="text-sm font-black text-orange-100">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-400">{description}</p></div>)}</div></div></section>
    {verified.length ? <section className="border-t border-white/[.07] bg-[#0c0f18] px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="cs-eyebrow">Permission-backed stories</p><h2 className="mt-3 text-3xl font-black">Verified customer case studies</h2><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{verified.map((story) => <Link key={story.slug} href={`/case-studies/${story.slug}`} className="cs-verified-card"><p className="text-[10px] font-black uppercase tracking-[.15em] text-emerald-300">Verified story · {story.platform}</p><h3 className="mt-4 text-xl font-black">{story.title}</h3><p className="mt-3 text-sm text-slate-400">{story.challenge}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-orange-300">Read story <ArrowRight className="h-4 w-4"/></span></Link>)}</div></div></section> : null}
    <section className="px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="cs-final mx-auto max-w-7xl"><div><p className="cs-eyebrow">Your next campaign</p><h2 className="mt-4 max-w-2xl text-4xl font-black text-white">Ready to build a growth plan for your own profile or brand?</h2><p className="mt-4 max-w-xl text-sm leading-7 text-slate-300">Explore SocialRUSH services, compare live pricing and create an order based on your own goals.</p></div><div className="flex flex-wrap gap-3"><Link href="/services" className="btn-primary gap-2">Explore services <ArrowRight className="h-4 w-4"/></Link><Link href="/packages" className="btn-secondary">View packages</Link></div></div></section>
  </main>;
}
