import Link from "next/link";
import PublicShell from "@/components/marketing/PublicShell";
import InteractiveHomepageShell from "@/components/marketing/InteractiveHomepageShell";
import PlatformIcon from "@/components/PlatformIcon";
import { ArrowRight, CircleDollarSign, ShieldCheck } from "lucide-react";
import BreadcrumbJsonLd from "@/components/seo/BreadcrumbJsonLd";
import MarketCurrencyInitializer from "./MarketCurrencyInitializer";
import type { InternationalMarket } from "@/lib/seo/international";
import { internationalMarkets, publishedCountryServicePages } from "@/lib/seo/international";

const marketFlags: Record<string, string> = { uk: "🇬🇧", ca: "🇨🇦", au: "🇦🇺", ae: "🇦🇪", sg: "🇸🇬" };

const platforms = [["Instagram","instagram"],["YouTube","youtube"],["Facebook","facebook"],["LinkedIn","linkedin"],["TikTok","tiktok"],["Telegram","telegram"],["X / Twitter","x"]] as const;

export default function CountryHubPage({ market }: { market: InternationalMarket }) {
  const path = `/${market.slug}`;
  const services = publishedCountryServicePages.filter((page) => page.market.slug === market.slug);
  const otherMarkets = internationalMarkets.filter((item) => item.slug !== market.slug);
  const schema = [
    {
      "@context": "https://schema.org",
      "@type": "CollectionPage",
      name: `Social Media Growth Services in ${market.name}`,
      url: `https://www.getsocialrush.com/${market.slug}`,
      description: `SocialRUSH market hub for discovering social media growth services in ${market.name}.`,
    },
    {
      "@context": "https://schema.org",
      "@type": "ItemList",
      name: `${market.name} SocialRUSH service pages`,
      itemListElement: services.map((service, index) => ({
        "@type": "ListItem",
        position: index + 1,
        name: service.h1,
        url: `https://www.getsocialrush.com/${market.slug}/${service.serviceSlug}`,
      })),
    },
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: [{ "@type": "Question", name: market.faq.question, acceptedAnswer: { "@type": "Answer", text: market.faq.answer } }],
    },
  ];
  return <PublicShell>
    <MarketCurrencyInitializer currency={market.currency} />
    <BreadcrumbJsonLd items={[{ name: "Home", path: "/" }, { name: market.name, path }]} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
    <InteractiveHomepageShell><main className="service-money-page overflow-hidden bg-[#090b10] text-white">
      <section className="relative min-h-[700px] overflow-hidden border-b border-white/10 bg-[#0b0d13] px-5 py-16 sm:px-6 lg:flex lg:items-center lg:px-8 lg:py-24"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_82%_16%,rgba(255,118,0,.26),transparent_28%),radial-gradient(circle_at_8%_0%,rgba(37,99,235,.17),transparent_27%),linear-gradient(180deg,rgba(255,255,255,.015),transparent)]"/><div className="relative mx-auto grid max-w-6xl gap-7 lg:grid-cols-[1.2fr_.8fr] lg:items-end">
        <div><p className="inline-flex items-center gap-2 rounded-full border border-orange-300/25 bg-orange-400/10 px-3 py-2 text-[10px] font-black uppercase tracking-[.18em] text-orange-200"><span aria-hidden className="text-base">{marketFlags[market.slug] || "🌍"}</span> SocialRUSH in {market.name}</p><h1 className="mt-4 max-w-4xl text-4xl font-black tracking-tight text-white sm:text-6xl">Social media growth services for {market.name}.</h1><p className="mt-6 max-w-3xl text-base leading-8 text-slate-300 sm:text-lg">A focused place for {market.audience} to explore supported social media services. Start with your campaign goal, compare clear service information and place an order using a public profile or content link.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#market-services" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-gradient-to-r from-orange-500 to-amber-500 px-6 py-3 text-sm font-black text-white shadow-[0_16px_38px_-18px_rgba(255,122,0,.9)] transition hover:-translate-y-0.5 hover:brightness-110 motion-reduce:transform-none">Explore {market.name} services <ArrowRight className="h-4 w-4" /></a><Link href="/packages" className="inline-flex min-h-12 items-center rounded-xl border border-white/15 px-5 py-3 text-sm font-black text-white">Compare larger packages</Link></div></div>
        <aside className="sr-surface relative overflow-hidden rounded-[2rem] border border-orange-300/20 bg-[linear-gradient(145deg,rgba(255,255,255,.055),rgba(12,14,20,.94))] p-6 shadow-[0_32px_80px_-40px_rgba(0,0,0,.95)] backdrop-blur sm:p-7"><CircleDollarSign className="h-7 w-7 text-orange-300" /><p className="text-xs font-black uppercase tracking-[.14em] text-orange-200">Market information</p><p className="mt-3 text-sm leading-7 text-slate-300">{market.paymentNote}</p><p className="mt-3 border-t border-white/10 pt-3 text-xs leading-5 text-slate-400">Display currency helps planning; checkout remains INR-authoritative.</p></aside>
      </div></section>
      <section className="px-5 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black">Plan a campaign with the right context.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-300">For visitors in {market.name}, the emphasis is on {market.emphasis}. SocialRUSH does not promise reach, revenue, rankings or business outcomes; it makes the available service details and order process easier to review.</p><div className="mt-8 grid gap-4 md:grid-cols-3">{[["Discover", "Browse by platform and compare available options."], ["Review", "Check public-link requirements, delivery information and refill details where shown."], ["Order", "Select a suitable service and track the order through your account."]].map(([title, text]) => <article key={title} className="rounded-3xl border border-white/10 bg-[radial-gradient(circle_at_100%_0%,rgba(255,122,0,.1),transparent_40%),#101219] p-6 shadow-[0_22px_55px_-42px_rgba(0,0,0,.95)]"><h3 className="font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p></article>)}</div></div></section>
      <section className="border-y border-white/10 bg-[#0b0d13] px-5 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black">Supported platforms</h2><p className="mt-3 text-sm leading-7 text-slate-300">Explore current service availability by platform. Service pages remain the source of truth for specific options.</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{platforms.map(([platform,key]) => <Link key={platform} href={`/services?platform=${key}`} className="group flex min-h-28 flex-col items-center justify-center gap-3 rounded-2xl border border-white/10 bg-white/[.035] p-4 text-center text-sm font-bold text-white shadow-[0_18px_45px_-38px_rgba(0,0,0,.95)] transition hover:-translate-y-1 hover:border-orange-400/40 hover:bg-orange-400/[.07] hover:text-orange-200 motion-reduce:transform-none"><span className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/[.05] text-orange-200"><PlatformIcon platform={key} className="h-5 w-5" /></span>{platform}</Link>)}</div></div></section>
      {services.length ? <section id="market-services" className="px-5 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black">Popular services in {market.name}</h2><p className="mt-3 text-sm leading-7 text-slate-300">These country-specific pages use the current catalog and the established ordering flow.</p><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{services.map((service) => <Link key={service.serviceSlug} href={`/${market.slug}/${service.serviceSlug}`} className="group relative overflow-hidden rounded-3xl border border-white/10 bg-[radial-gradient(circle_at_100%_0%,rgba(255,122,0,.12),transparent_40%),#101219] p-6 font-black shadow-[0_22px_55px_-42px_rgba(0,0,0,.95)] transition hover:-translate-y-1 hover:border-orange-400/40 motion-reduce:transform-none"><span className="block text-[10px] uppercase tracking-[.16em] text-orange-300">{market.name} service</span><span className="mt-3 block">{service.h1}</span><span className="mt-5 inline-flex items-center gap-1 text-xs text-orange-200">View service <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section> : null}
      <section className="border-y border-white/10 bg-[#101219] px-5 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[.16em] text-orange-300">Choose by campaign size</p><h2 className="mt-3 text-3xl font-black">Move into the right revenue path.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-300">Use a country service page for a focused requirement. For larger, multi-service or recurring campaigns, use the appropriate planning path instead of assuming a discount or local payment method.</p><div className="mt-7 grid gap-3 md:grid-cols-3"><Link href="/packages" className="group rounded-3xl border border-white/10 bg-black/25 p-6 shadow-[0_20px_50px_-42px_rgba(0,0,0,.95)] transition hover:-translate-y-1 hover:border-orange-400/40 hover:bg-orange-400/[.04] motion-reduce:transform-none"><b className="text-white">Larger single-service requirement</b><span className="mt-2 block text-sm leading-6 text-slate-400">Compare current package quantities and pricing.</span><span className="mt-4 block text-sm font-black text-orange-300">Compare packages →</span></Link><Link href="/dashboard/campaign-stacks" className="group rounded-3xl border border-white/10 bg-black/25 p-6 shadow-[0_20px_50px_-42px_rgba(0,0,0,.95)] transition hover:-translate-y-1 hover:border-orange-400/40 hover:bg-orange-400/[.04] motion-reduce:transform-none"><b className="text-white">Multi-service campaign</b><span className="mt-2 block text-sm leading-6 text-slate-400">Plan complementary services with current catalog information.</span><span className="mt-4 block text-sm font-black text-orange-300">Campaign stacks →</span></Link><Link href="/for-agencies#bulk-lead-engine" className="group rounded-3xl border border-white/10 bg-black/25 p-6 shadow-[0_20px_50px_-42px_rgba(0,0,0,.95)] transition hover:-translate-y-1 hover:border-orange-400/40 hover:bg-orange-400/[.04] motion-reduce:transform-none"><b className="text-white">Agency or recurring requirement</b><span className="mt-2 block text-sm leading-6 text-slate-400">Share platform, expected volume, frequency and campaign scope.</span><span className="mt-4 block text-sm font-black text-orange-300">Discuss requirement →</span></Link></div></div></section>
      <section className="px-5 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-6xl gap-6 md:grid-cols-2"><article className="rounded-[2rem] border border-orange-400/25 bg-[radial-gradient(circle_at_100%_0%,rgba(255,122,0,.2),transparent_42%),rgba(255,122,0,.07)] p-7 shadow-[0_28px_70px_-50px_rgba(255,122,0,.8)]"><CircleDollarSign className="h-6 w-6 text-orange-300" /><h2 className="text-2xl font-black">Currency display for planning</h2><p className="mt-3 text-sm leading-7 text-slate-300">{market.paymentNote} Display currency is a convenience only and does not create a separate SEO URL, payment method or local checkout.</p></article><article className="rounded-[2rem] border border-white/10 bg-[linear-gradient(145deg,rgba(255,255,255,.045),#101219)] p-7 shadow-[0_24px_65px_-48px_rgba(0,0,0,.95)]"><ShieldCheck className="h-6 w-6 text-emerald-300" /><h2 className="text-2xl font-black">Order with confidence</h2><p className="mt-3 text-sm leading-7 text-slate-300">Use public profile, post, page, channel or video links. SocialRUSH does not ask for social-account passwords, OTPs or recovery codes.</p><Link href="/trust" className="mt-5 inline-flex text-sm font-bold text-orange-300">Read customer safety guidance</Link></article></div></section>
      <section className="border-t border-white/10 bg-[#0b0d13] px-5 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-black">Questions for visitors in {market.name}</h2><article className="mt-6 rounded-[2rem] border border-white/10 bg-[linear-gradient(145deg,rgba(255,255,255,.045),#101219)] p-7 shadow-[0_24px_65px_-48px_rgba(0,0,0,.95)]"><h3 className="text-lg font-black">{market.faq.question}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{market.faq.answer}</p></article></div></section>
      <section className="border-t border-white/10 px-5 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[.16em] text-orange-300">Other international markets</p><div className="mt-5 flex flex-wrap gap-3">{otherMarkets.map((item) => <Link key={item.slug} href={`/${item.slug}`} className="rounded-xl border border-white/10 bg-[#101219] px-4 py-3 text-sm font-bold transition hover:border-orange-400/40">{item.name}</Link>)}</div></div></section>
    </main></InteractiveHomepageShell>
  </PublicShell>;
}
