import Link from "next/link";
import { ArrowRight, BookOpen, BriefcaseBusiness, Layers3, PackageSearch, TrendingUp } from "lucide-react";

const moneyPages = [
  { title: "Buy Instagram Followers India", text: "Review live INR pricing, quantity, delivery and refill information for a public Instagram profile.", href: "/buy-instagram-followers-india" },
  { title: "Buy YouTube Subscribers India", text: "Compare the current subscriber rate and order requirements for a public YouTube channel.", href: "/youtube-subscribers" },
  { title: "Buy LinkedIn Followers India", text: "Review current LinkedIn follower pricing and the public-link order flow for profiles or company pages.", href: "/linkedin-followers" },
  { title: "Buy Facebook Followers India", text: "Explore the current Facebook follower path for supported public pages and profiles.", href: "/buy-facebook-followers-india" },
  { title: "Buy TikTok Followers India", text: "Review the active TikTok follower service, quantity rules and public-profile requirements.", href: "/tiktok-followers" },
  { title: "Buy X / Twitter Followers India", text: "Compare current follower options for an eligible public X / Twitter profile.", href: "/twitter-followers" },
];

const authorityGuides = [
  { title: "How to grow Instagram followers in India", text: "Build profile clarity, content consistency and genuine engagement before or alongside a follower campaign.", href: "/blog/how-to-grow-instagram-followers-organically-india" },
  { title: "How to increase YouTube subscribers in India", text: "Use channel positioning, searchable topics, playlists and retention to make subscriber growth more meaningful.", href: "/blog/how-to-increase-youtube-subscribers-in-india" },
  { title: "LinkedIn followers vs engagement in India", text: "Compare visible audience scale with useful professional interaction before choosing the next LinkedIn goal.", href: "/blog/linkedin-followers-vs-engagement-india" },
];

const discoveryLinks = [
  { title: "Social media growth services", text: "Compare the live catalog across seven supported platforms.", href: "/services", icon: PackageSearch },
  { title: "Social media growth packages", text: "Choose a platform, goal and quantity before starting an order.", href: "/packages", icon: Layers3 },
  { title: "Agency & reseller services", text: "Use a clearer path for repeat client campaigns and larger requirements.", href: "/for-agencies", icon: BriefcaseBusiness },
  { title: "Social media growth guides", text: "Use practical India-focused guides alongside any paid campaign.", href: "/blog", icon: BookOpen },
];

export default function IndiaGrowthDiscovery({ compact = false }: { compact?: boolean }) {
  return <section className="border-y border-white/10 bg-[#090909] px-4 py-10 text-white sm:px-6 lg:px-8" aria-labelledby="india-growth-discovery-title"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="text-[10px] font-black uppercase tracking-[.18em] text-orange-300">India social media growth directory</p><h2 id="india-growth-discovery-title" className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">Compare SocialRUSH services for Instagram, YouTube, LinkedIn, Facebook, TikTok and X.</h2><p className="mt-3 text-sm leading-6 text-slate-400">Use these commercial service pages to review current INR pricing, quantity limits, delivery estimates and refill information before checkout. Paid audience or engagement services do not guarantee organic reach, leads, sales or platform outcomes.</p></div><Link href="/social-media-growth-india" className="inline-flex min-h-11 items-center gap-2 self-start rounded-xl border border-orange-400/30 bg-orange-500/10 px-4 text-sm font-black text-orange-200 transition hover:border-orange-300/50 hover:bg-orange-500/15">Explore social media growth India <ArrowRight className="h-4 w-4" /></Link></div>
  <div className={`mt-6 grid gap-3 ${compact ? "lg:grid-cols-3" : "sm:grid-cols-2 lg:grid-cols-3"}`}>{moneyPages.map(item=><Link key={item.href} href={item.href} className="group rounded-2xl border border-white/10 bg-[#111216] p-5 transition hover:-translate-y-0.5 hover:border-orange-400/30"><span className="grid h-10 w-10 place-items-center rounded-xl bg-orange-500/10 text-orange-300"><TrendingUp className="h-5 w-5" /></span><h3 className="mt-4 text-base font-black">{item.title}</h3><p className="mt-2 text-xs leading-5 text-slate-400">{item.text}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-black text-orange-300">Check live service <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5" /></span></Link>)}</div>
  {!compact?<><div className="mt-6 flex items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-orange-300">India growth guides</p><h3 className="mt-1 text-xl font-black">Build organic strategy around your paid campaign.</h3></div><Link href="/blog" className="hidden text-xs font-black text-orange-300 sm:inline-flex sm:items-center sm:gap-1">Browse all guides <ArrowRight className="h-3.5 w-3.5" /></Link></div><div className="mt-3 grid gap-3 md:grid-cols-3">{authorityGuides.map(item=><Link key={item.href} href={item.href} className="group rounded-2xl border border-orange-400/15 bg-orange-500/[.045] p-4 transition hover:border-orange-400/35"><BookOpen className="h-5 w-5 text-orange-300"/><h3 className="mt-3 text-sm font-black">{item.title}</h3><p className="mt-2 text-xs leading-5 text-slate-400">{item.text}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-black text-orange-300">Read guide <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5"/></span></Link>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{discoveryLinks.map(({title,text,href,icon:Icon})=><Link key={href} href={href} className="rounded-2xl border border-white/[.07] bg-black/20 p-4 transition hover:border-white/20"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-white/[.05] text-slate-300"><Icon className="h-4 w-4"/></span><div><h3 className="text-sm font-black">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></div></Link>)}</div></>:null}</div></section>;
}
