import Link from "next/link";
import { ArrowRight, BookOpen, BriefcaseBusiness, Layers3, PackageSearch, TrendingUp, UsersRound } from "lucide-react";

const moneyPages = [
  { title: "Buy YouTube Subscribers India", text: "Compare the current subscriber rate, larger quantity options and public-channel requirements.", href: "/youtube-subscribers", priority: "30-day revenue leader" },
  { title: "Buy X / Twitter Followers India", text: "Review current follower options for an eligible public X / Twitter profile.", href: "/twitter-followers", priority: "High-value service path" },
  { title: "Buy Instagram Followers India", text: "Review live INR pricing, quantity, delivery and refill information for a public Instagram profile.", href: "/buy-instagram-followers-india" },
  { title: "Buy LinkedIn Followers India", text: "Review current LinkedIn follower pricing and the public-link order flow for profiles or company pages.", href: "/linkedin-followers" },
  { title: "Buy Facebook Followers India", text: "Explore the current Facebook follower path for supported public pages and profiles.", href: "/buy-facebook-followers-india" },
  { title: "Buy TikTok Followers India", text: "Review the active TikTok follower service, quantity rules and public-profile requirements.", href: "/tiktok-followers" },
];

const highValuePaths = [
  { title: "Need a larger campaign?", text: "Compare current packages and quantities without assuming a discount.", href: "/packages", cta: "Compare packages", icon: Layers3 },
  { title: "Agency or reseller requirement?", text: "Send platform, budget, frequency and campaign scope through the qualified bulk enquiry flow.", href: "/for-agencies#bulk-lead-engine", cta: "Discuss bulk requirement", icon: UsersRound },
  { title: "Multi-platform planning", text: "Browse the live service catalog before building a larger or repeat campaign.", href: "/services", cta: "Explore all services", icon: PackageSearch },
];

const authorityGuides = [
  { title: "How to grow Instagram followers in India", text: "Build profile clarity, content consistency and genuine engagement before or alongside a follower campaign.", href: "/blog/how-to-grow-instagram-followers-organically-india" },
  { title: "How to increase YouTube subscribers in India", text: "Use channel positioning, searchable topics, playlists and retention to make subscriber growth more meaningful.", href: "/blog/how-to-increase-youtube-subscribers-in-india" },
  { title: "LinkedIn followers vs engagement in India", text: "Compare visible audience scale with useful professional interaction before choosing the next LinkedIn goal.", href: "/blog/linkedin-followers-vs-engagement-india" },
];

const discoveryLinks = [
  { title: "Social media growth services", text: "Compare the live catalog across seven supported platforms.", href: "/services", icon: PackageSearch },
  { title: "Social media growth packages", text: "Choose a platform, goal and quantity before starting an order.", href: "/packages", icon: Layers3 },
  { title: "Agency & reseller services", text: "Use a clearer path for repeat client campaigns and larger requirements.", href: "/for-agencies", icon: BriefcaseBusiness },
  { title: "Social media growth guides", text: "Use practical India-focused guides alongside any paid campaign.", href: "/blog", icon: BookOpen },
];

export default function IndiaGrowthDiscovery({ compact = false }: { compact?: boolean }) {
  return <section className="border-y border-white/10 bg-[#090909] px-4 py-10 text-white sm:px-6 lg:px-8" aria-labelledby="india-growth-discovery-title"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="text-[10px] font-black uppercase tracking-[.18em] text-orange-300">India social media growth directory</p><h2 id="india-growth-discovery-title" className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">Choose a service path based on your campaign size and platform.</h2><p className="mt-3 text-sm leading-6 text-slate-400">Review current INR pricing, quantity limits, delivery estimates and refill information before checkout. Paid audience or engagement services do not guarantee organic reach, leads, sales or platform outcomes.</p></div><Link href="/social-media-growth-india" className="inline-flex min-h-11 items-center gap-2 self-start rounded-xl border border-orange-400/30 bg-orange-500/10 px-4 text-sm font-black text-orange-200 transition hover:border-orange-300/50 hover:bg-orange-500/15">Explore social media growth India <ArrowRight className="h-4 w-4" /></Link></div>
  <div className={`mt-6 grid gap-3 ${compact ? "lg:grid-cols-3" : "sm:grid-cols-2 lg:grid-cols-3"}`}>{moneyPages.map(item=><Link key={item.href} href={item.href} className="group relative rounded-2xl border border-white/10 bg-[#111216] p-5 transition hover:-translate-y-0.5 hover:border-orange-400/30">{item.priority?<span className="absolute right-4 top-4 rounded-full border border-orange-300/20 bg-orange-400/10 px-2 py-1 text-[9px] font-black uppercase tracking-wider text-orange-200">{item.priority}</span>:null}<span className="grid h-10 w-10 place-items-center rounded-xl bg-orange-500/10 text-orange-300"><TrendingUp className="h-5 w-5" /></span><h3 className="mt-4 pr-16 text-base font-black">{item.title}</h3><p className="mt-2 text-xs leading-5 text-slate-400">{item.text}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-black text-orange-300">Check live service <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5" /></span></Link>)}</div>
  <div className="mt-6 rounded-[2rem] border border-orange-300/15 bg-[radial-gradient(circle_at_top_left,rgba(255,122,0,.12),transparent_35%),#0e1015] p-5 sm:p-6"><div className="max-w-2xl"><p className="text-[10px] font-black uppercase tracking-[.16em] text-orange-300">Larger requirement paths</p><h3 className="mt-2 text-xl font-black">Don&apos;t force a larger requirement through a small single-service order.</h3><p className="mt-2 text-xs leading-5 text-slate-400">For larger quantities, repeat campaigns or multiple client accounts, compare the appropriate commercial path first. Final pricing and availability still come from active service information.</p></div><div className="mt-5 grid gap-3 md:grid-cols-3">{highValuePaths.map(({title,text,href,cta,icon:Icon})=><Link key={href} href={href} className="group rounded-2xl border border-white/10 bg-black/20 p-4 transition hover:border-orange-300/30"><Icon className="h-5 w-5 text-orange-300"/><h4 className="mt-3 text-sm font-black">{title}</h4><p className="mt-2 text-xs leading-5 text-slate-400">{text}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-black text-orange-300">{cta}<ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5"/></span></Link>)}</div></div>
  {!compact?<><div className="mt-6 flex items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-orange-300">India growth guides</p><h3 className="mt-1 text-xl font-black">Build organic strategy around your paid campaign.</h3></div><Link href="/blog" className="hidden text-xs font-black text-orange-300 sm:inline-flex sm:items-center sm:gap-1">Browse all guides <ArrowRight className="h-3.5 w-3.5" /></Link></div><div className="mt-3 grid gap-3 md:grid-cols-3">{authorityGuides.map(item=><Link key={item.href} href={item.href} className="group rounded-2xl border border-orange-400/15 bg-orange-500/[.045] p-4 transition hover:border-orange-400/35"><BookOpen className="h-5 w-5 text-orange-300"/><h3 className="mt-3 text-sm font-black">{item.title}</h3><p className="mt-2 text-xs leading-5 text-slate-400">{item.text}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-black text-orange-300">Read guide <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5"/></span></Link>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{discoveryLinks.map(({title,text,href,icon:Icon})=><Link key={href} href={href} className="rounded-2xl border border-white/[.07] bg-black/20 p-4 transition hover:border-white/20"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-white/[.05] text-slate-300"><Icon className="h-4 w-4"/></span><div><h3 className="text-sm font-black">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></div></Link>)}</div></>:null}</div></section>;
}
