"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Camera, Check, ChevronDown, ChevronUp, CirclePlay, ExternalLink, Link2, Minus, Pause, Plus, ShieldCheck, Sparkles } from "lucide-react";
import { linkRules, validateCampaignLink } from "@/lib/order-service-experience";

type Live = { id: number; rate: number; min: number; max: number; deliveryTime: string; refillPolicy: string; available: boolean } | null;
const comments = ["Love this concept 🔥", "Such a clean post 👏", "This looks amazing 🙌", "Nice work!", "Very clean ✨"];
const faqs = [
  ["Do I need my Instagram password?", "No. This service uses only the correct public Instagram post or Reel link. Never share your password, OTP, or recovery code."],
  ["Which Instagram link should I submit?", "Submit the exact public post or Reel URL. A profile link is not accepted for Instagram Comments."],
  ["Can I use a Reel link?", "Yes. Public post, Reel, and supported video-post URLs are accepted by the existing order validation."],
  ["How is the total calculated?", "The estimate uses the currently displayed live rate and your selected whole-number quantity. The secure order flow confirms the final service details."],
  ["Can I track my order?", "Yes. Your SocialRUSH dashboard retains the order record and its available status information."],
  ["Does this guarantee engagement or reach?", "No. A comments service does not guarantee engagement, reach, ranking, sales, or any platform outcome."],
] as const;

const number = (value: number) => value.toLocaleString("en-IN");

export default function InstagramCommentsLanding({ live }: { live: Live }) {
  // `live` is resolved server-side from the protected service catalog (with
  // its catalog fallback), so pricing and limits never live in this page.
  const min = live?.min ?? 1;
  const max = live?.max ?? 1;
  const rate = live?.rate ?? 0;
  const [quantity, setQuantity] = useState(min);
  const [link, setLink] = useState("");
  const [attempted, setAttempted] = useState(false);
  const [playing, setPlaying] = useState(false);
  const [shown, setShown] = useState(3);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const safeQuantity = Math.max(min, Math.min(max, Math.round(quantity || min)));
  const linkError = link.trim() ? validateCampaignLink(link, linkRules["instagram-comments"]) : "";
  const valid = live?.available !== false && !!link.trim() && !linkError && quantity >= min && quantity <= max && Number.isInteger(quantity);
  const total = (rate * safeQuantity) / 1000;
  const presets = useMemo(() => [min, 100, 250, 500, 1000, 2500, max].filter((v, i, all) => v >= min && v <= max && all.indexOf(v) === i), [min, max]);
  const href = `/dashboard/new-order?platform=instagram&service=instagram-comments&resume=1&quantity=${safeQuantity}&link=${encodeURIComponent(link.trim())}`;
  useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setShown((value) => value >= comments.length ? 1 : value + 1), 1250); return () => window.clearInterval(timer); }, [playing]);
  const updateQuantity = (value: number) => setQuantity(Number.isFinite(value) ? Math.max(min, Math.min(max, Math.round(value))) : min);
  const order = () => { setAttempted(true); if (valid) window.location.assign(href); };

  return <main className="overflow-hidden bg-[#08090d] text-[#f8f5ef]">
    <section className="relative px-4 pb-16 pt-12 sm:px-6 lg:px-8 lg:pb-24 lg:pt-20">
      <div className="pointer-events-none absolute -left-40 top-0 h-[30rem] w-[30rem] rounded-full bg-orange-500/20 blur-[110px]" /><div className="pointer-events-none absolute right-0 top-20 h-80 w-80 rounded-full bg-fuchsia-600/15 blur-[120px]" />
      <div className="relative mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center">
        <div><p className="inline-flex items-center gap-2 rounded-full border border-orange-300/25 bg-orange-400/10 px-3 py-2 text-[10px] font-black tracking-[.16em] text-orange-200"><Camera className="h-4 w-4" /> INSTAGRAM COMMENTS SERVICE INDIA</p>
          <h1 className="mt-6 max-w-3xl text-4xl font-black leading-[1.04] tracking-[-.055em] sm:text-6xl">Buy Instagram <span className="bg-gradient-to-r from-orange-300 via-amber-300 to-orange-400 bg-clip-text text-transparent">Comments</span> in India</h1>
          <p className="mt-6 max-w-2xl text-base leading-8 text-slate-300 sm:text-lg">Configure comments for a public Instagram post or Reel with live pricing, clear quantity controls, delivery details, and dashboard tracking.</p>
          <div className="mt-8 flex flex-col gap-3 min-[430px]:flex-row"><a href="#order" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-gradient-to-r from-[#ff7a00] to-[#ffb000] px-6 text-sm font-black text-black">Start Your Order</a><Link href="/services?platform=instagram" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/15 px-6 text-sm font-black">Explore Instagram Services</Link><a href="https://wa.me/918860330771?text=Hi%20SocialRUSH%2C%20I%20need%20help%20with%20Instagram%20Comments" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-emerald-400/30 bg-emerald-400/10 px-5 text-sm font-black text-emerald-200">WhatsApp</a></div>
          <div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-xs font-bold text-slate-300">{["No Password Required", "Transparent Pricing", "Order Tracking"].map(item => <span key={item} className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-orange-300" />{item}</span>)}</div>
        </div>
        <CampaignPreview rate={rate} delivery={live?.deliveryTime ?? "Current estimate unavailable"} refill={live?.refillPolicy ?? "Current terms unavailable"} quantity={safeQuantity} />
      </div>
    </section>

    <section id="order" className="scroll-mt-16 border-y border-white/10 bg-[#10121a] px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[minmax(0,1fr)_370px]">
      <article className="rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_95%_0%,rgba(235,70,151,.18),transparent_30%),#161923] p-5 sm:p-8"><p className="text-[10px] font-black tracking-[.18em] text-orange-300">QUICK ORDER BUILDER</p><h2 className="mt-3 text-2xl font-black sm:text-3xl">Build Your Instagram Comments Order</h2><p className="mt-2 text-sm text-slate-300">Choose your comment quantity and review the total before continuing.</p>
        <div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{presets.map(value => <button type="button" onClick={() => updateQuantity(value)} key={value} className={`min-h-16 rounded-2xl border p-3 text-left transition ${quantity === value ? "border-orange-300 bg-orange-400/15" : "border-white/10 bg-black/20 hover:border-white/30"}`}><b className="text-lg">{number(value)}</b><span className="block text-[10px] font-bold uppercase tracking-wider text-slate-400">comments</span></button>)}</div>
        <label className="mt-7 block text-sm font-black">Comment quantity<div className="mt-2 flex overflow-hidden rounded-2xl border border-white/15 bg-black/25 focus-within:border-orange-300"><button type="button" aria-label="Decrease quantity" onClick={() => updateQuantity(quantity - 1)} className="grid min-h-14 w-14 place-items-center text-orange-200"><Minus className="h-4 w-4" /></button><input aria-label="Comment quantity" inputMode="numeric" value={quantity || ""} onChange={e => setQuantity(e.target.value === "" ? 0 : Number(e.target.value.replace(/\D/g, "")))} className="min-w-0 flex-1 bg-transparent text-center text-lg font-black outline-none" /><button type="button" aria-label="Increase quantity" onClick={() => updateQuantity(quantity + 1)} className="grid min-h-14 w-14 place-items-center text-orange-200"><Plus className="h-4 w-4" /></button></div></label>
        <p className={`mt-2 text-xs ${attempted && (quantity < min || quantity > max || !Number.isInteger(quantity)) ? "text-red-300" : "text-slate-400"}`}>Min {number(min)} · Max {number(max)} · Whole comments only</p>
        <label className="mt-7 block text-sm font-black">Instagram Post / Reel Link<div className={`mt-2 rounded-2xl border bg-black/25 focus-within:ring-4 focus-within:ring-orange-500/10 ${link.trim() && !linkError ? "border-emerald-400/60" : attempted && (!link.trim() || linkError) ? "border-red-400" : "border-white/15"}`}><div className="flex items-center gap-3 px-4"><Link2 className="h-4 w-4 shrink-0 text-orange-200" /><input aria-invalid={Boolean(attempted && (!link.trim() || linkError))} value={link} onChange={e => setLink(e.target.value)} placeholder="https://www.instagram.com/p/..." className="min-h-14 min-w-0 w-full bg-transparent text-base outline-none placeholder:text-slate-500" /></div></div></label>
        <p role="alert" className={`mt-2 text-xs ${link.trim() && !linkError ? "text-emerald-300" : attempted ? "text-red-300" : "text-slate-400"}`}>{link.trim() && !linkError ? "✓ Valid Instagram post/reel link" : linkError || "Use the exact public post or Reel URL. Profile URLs are not accepted."}</p>
      </article>
      <aside className="h-fit rounded-[2rem] border border-orange-300/20 bg-[#0d0f15] p-6 shadow-2xl lg:sticky lg:top-24"><p className="text-[10px] font-black tracking-[.16em] text-orange-300">LIVE ORDER SUMMARY</p><h2 className="mt-3 text-xl font-black">Instagram Comments</h2><dl className="mt-6 space-y-4 text-sm">{[["Quantity", number(safeQuantity)], ["Live rate", `₹${number(rate)} / 1K`], ["Delivery", live?.deliveryTime ?? "Current estimate unavailable"], ["Refill/support", live?.refillPolicy ?? "Current terms unavailable"], ["Instagram link", link ? "Added" : "Required"], ["Availability", live?.available === false ? "Unavailable" : "Available"]].map(([label, value]) => <div className="flex justify-between gap-4" key={label}><dt className="text-slate-400">{label}</dt><dd className="max-w-[58%] text-right font-bold">{value}</dd></div>)}</dl><div className="mt-6 border-t border-white/10 pt-5"><p className="text-xs font-bold text-slate-400">ESTIMATED TOTAL</p><p className="mt-1 text-3xl font-black text-orange-200">₹{total.toLocaleString("en-IN", { maximumFractionDigits: 2 })}</p></div><button type="button" onClick={order} className="mt-6 min-h-13 w-full rounded-xl bg-gradient-to-r from-[#ff7a00] to-[#ffb000] px-4 text-sm font-black text-black">Continue to Secure Order</button><p className="mt-3 text-center text-[11px] text-slate-400">Secure checkout · Public link only</p></aside>
    </div></section>

    <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><article className="rounded-[2rem] border border-white/10 bg-[#141720] p-6 sm:p-8"><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] font-black tracking-[.16em] text-fuchsia-200">INTERACTIVE UI PREVIEW</p><h2 className="mt-2 text-2xl font-black">See the comment experience</h2></div><button aria-label={playing ? "Pause preview" : "Play preview"} onClick={() => setPlaying(!playing)} className="grid h-12 w-12 place-items-center rounded-full bg-orange-400 text-black">{playing ? <Pause className="h-5 w-5" /> : <CirclePlay className="h-5 w-5" />}</button></div><div className="mt-7 rounded-2xl border border-white/10 bg-[#0c0e14] p-4"><div className="flex items-center gap-3"><div className="h-9 w-9 rounded-full bg-gradient-to-br from-fuchsia-500 via-orange-400 to-amber-300" /><b>@yourbrand</b><span className="ml-auto text-[10px] font-black text-slate-500">UI PREVIEW</span></div><div className="mt-4 aspect-[4/3] rounded-xl bg-[radial-gradient(circle_at_72%_28%,rgba(255,173,57,.9),transparent_10%),linear-gradient(145deg,#6c1c54,#151d3d_48%,#e66a25)] p-5"><div className="h-full rounded-lg border border-white/20 bg-black/15" /></div><div className="mt-4 flex justify-between text-slate-300"><span>♡ &nbsp; ◯ &nbsp; ↗</span><span>{12 + shown} comments</span></div><p className="mt-3 text-sm"><b>@yourbrand</b> A creative moment, shared simply.</p><div className="mt-4 space-y-3">{comments.slice(0, shown).map((comment, index) => <p key={comment} className="text-sm text-slate-200"><b className="mr-2 text-white">@{["creator_one", "dailycontent", "socialstudio", "brandwatch", "frameclub"][index]}</b>{comment}</p>)}</div></div></article>
      <article className="rounded-[2rem] border border-orange-300/15 bg-gradient-to-br from-[#19161a] to-[#101218] p-6 sm:p-8"><p className="text-[10px] font-black tracking-[.16em] text-orange-300">CAMPAIGN SETUP</p><h2 className="mt-2 text-2xl font-black">Configured for public content</h2><div className="mt-7 space-y-3">{[["Platform", "Instagram"], ["Service", "Comments"], ["Destination", "Post / Reel"], ["Quantity", number(safeQuantity)], ["Delivery", live?.deliveryTime ?? "Shown at checkout"], ["Status", "Ready to configure"]].map(([label, value]) => <div key={label} className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[.03] p-3 text-sm"><span className="text-slate-400">{label}</span><b>{value}</b></div>)}</div><div className="mt-7 flex items-center gap-3 rounded-xl border border-emerald-400/25 bg-emerald-400/10 p-3 text-sm text-emerald-100"><ShieldCheck className="h-5 w-5 shrink-0" />Secure configuration. No account credentials requested.</div></article></div></section>

    <section className="border-y border-white/10 bg-[#11131b] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-[10px] font-black tracking-[.16em] text-orange-300">WHY SOCIALRUSH</p><h2 className="mt-3 text-3xl font-black">Clear setup before secure checkout.</h2><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[["Transparent live pricing", "A calculated estimate from the active service rate."], ["Public Post/Reel ordering", "The correct content URL, not account access."], ["Dashboard tracking", "Keep order records organized in one place."], ["Service details", "Availability, delivery, and support terms shown clearly."], ["Secure checkout", "Continue through the existing protected order flow."], ["Correct-link guidance", "Avoid submitting an Instagram profile by mistake."]].map(([title, text], index) => <article key={title} className={`rounded-2xl border border-white/10 bg-[#1a1d27] p-5 ${index === 0 ? "md:col-span-2" : ""}`}><Sparkles className="h-5 w-5 text-orange-300" /><h3 className="mt-4 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{text}</p></article>)}</div></div></section>

    <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-black">Use the correct Instagram link</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{[["Profile link", "instagram.com/username", false], ["Post link", "instagram.com/p/...", true], ["Reel link", "instagram.com/reel/...", true]].map(([title, example, accepted]) => <article key={String(title)} className={`rounded-2xl border p-5 ${accepted ? "border-emerald-400/35 bg-emerald-400/10" : "border-white/10 bg-white/[.03]"}`}><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{title}</p><p className="mt-3 font-bold">{example}</p><p className={`mt-4 text-sm font-bold ${accepted ? "text-emerald-200" : "text-slate-400"}`}>{accepted ? "✓ Accepted for this service" : "Not accepted for comments"}</p></article>)}</div><div className="mt-5 grid gap-3 rounded-2xl border border-orange-300/20 bg-orange-400/10 p-5 sm:grid-cols-4">{[["Public Instagram link", "Required", true], ["Instagram password", "Not required", false], ["OTP", "Never share", false], ["Recovery code", "Never share", false]].map(([a,b,ok]) => <div key={String(a)}><p className="text-xs text-slate-300">{a}</p><p className={`mt-1 font-black ${ok ? "text-emerald-200" : "text-orange-200"}`}>{ok ? "✓" : "×"} {b}</p></div>)}</div></div></section>

    <section className="bg-[#11131b] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-black">How it works</h2><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Choose Instagram Comments", "Select Quantity", "Paste Public Post/Reel Link", "Review Live Total", "Continue to Secure Checkout", "Track Your Order"].map((step, index) => <article key={step} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><span className="text-xs font-black text-orange-300">0{index + 1}</span><h3 className="mt-4 font-black">{step}</h3></article>)}</div></div></section>

    <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><div><p className="text-[10px] font-black tracking-[.16em] text-orange-300">RELATED INSTAGRAM SERVICES</p><h2 className="mt-3 text-3xl font-black">Explore the Instagram service ecosystem</h2><div className="mt-6 grid grid-cols-2 gap-3">{[["Followers", "/buy-instagram-followers-india"], ["Likes", "/instagram-likes"], ["Views", "/instagram-views"], ["Services", "/services?platform=instagram"]].map(([name, path]) => <Link href={path} key={name} className="rounded-2xl border border-white/10 bg-white/[.03] p-5 font-black transition hover:border-orange-300/50">{name}<ExternalLink className="float-right h-4 w-4 text-orange-200" /></Link>)}</div><p className="mt-6 text-sm leading-7 text-slate-300">Profile services and content services are distinct. This page only configures Instagram Comments for eligible public content.</p></div><div><p className="text-[10px] font-black tracking-[.16em] text-orange-300">FAQ</p><h2 className="mt-3 text-3xl font-black">Good to know</h2><div className="mt-6 divide-y divide-white/10 rounded-2xl border border-white/10">{faqs.map(([question, answer], index) => <div key={question}><button aria-expanded={openFaq === index} onClick={() => setOpenFaq(openFaq === index ? null : index)} className="flex min-h-15 w-full items-center justify-between gap-4 p-4 text-left text-sm font-black">{question}{openFaq === index ? <ChevronUp className="h-4 w-4 shrink-0 text-orange-200" /> : <ChevronDown className="h-4 w-4 shrink-0 text-orange-200" />}</button>{openFaq === index && <p className="px-4 pb-5 text-sm leading-7 text-slate-300">{answer}</p>}</div>)}</div></div></div></section>
  </main>;
}

function CampaignPreview({ rate, delivery, refill, quantity }: { rate: number; delivery: string; refill: string; quantity: number }) {
  return <aside className="relative rounded-[2rem] border border-white/15 bg-[linear-gradient(145deg,rgba(36,22,42,.98),rgba(13,16,26,.98))] p-5 shadow-[0_30px_100px_-30px_rgba(225,69,146,.35)] sm:p-7"><div className="flex items-center justify-between"><span className="inline-flex items-center gap-2 text-sm font-black"><span className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-fuchsia-500 via-orange-400 to-amber-300"><Camera className="h-5 w-5 text-white" /></span>Instagram Comments</span><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-[10px] font-black text-emerald-200">LIVE SERVICE</span></div><p className="mt-5 text-[10px] font-black tracking-[.16em] text-slate-400">INSTAGRAM COMMENTS CAMPAIGN DASHBOARD · UI PREVIEW</p><div className="mt-4 grid gap-4 sm:grid-cols-[.9fr_1.1fr]"><div className="rounded-2xl border border-white/10 bg-black/20 p-3"><div className="flex items-center gap-2"><span className="h-7 w-7 rounded-full bg-gradient-to-br from-fuchsia-500 to-amber-300" /><b className="text-xs">@yourbrand</b></div><div className="mt-3 aspect-square rounded-xl bg-[linear-gradient(135deg,#381d51,#d04a83,#f8a334)]" /><p className="mt-3 text-xs"><b>@yourbrand</b> Original content preview.</p><p className="mt-2 text-xs text-slate-400">♡ 1,240 · ◯ 18 · ↗</p></div><div className="rounded-2xl border border-white/10 bg-black/20 p-3"><p className="text-[10px] font-black tracking-wider text-orange-200">COMMENT ACTIVITY</p>{comments.slice(0, 3).map((comment, index) => <p key={comment} className="mt-3 text-xs text-slate-200"><b>@{["creator_one", "dailycontent", "socialstudio"][index]}</b> {comment}</p>)}<p className="mt-5 border-t border-white/10 pt-3 text-xs text-slate-400">Start → Processing → Comment activity → Order tracking</p></div></div><dl className="mt-5 grid grid-cols-2 gap-3 text-xs"><Info label="Starting from" value={`₹${number(rate)} / 1K`} /><Info label="Selected quantity" value={number(quantity)} /><Info label="Delivery" value={delivery} /><Info label="Refill/support" value={refill} /><Info label="Post / Reel link" value="Required" /><Info label="Secure order" value="Protected" /></dl><a href="#order" className="mt-5 inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-gradient-to-r from-[#ff7a00] to-[#ffb000] text-sm font-black text-black">Build Your Order</a></aside>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-white/[.035] p-3"><dt className="text-[10px] font-bold text-slate-400">{label}</dt><dd className="mt-1 truncate font-black text-white">{value}</dd></div>; }
