"use client";

import Link from "next/link";
import { ArrowRight, Ban, CheckCircle2, CircleHelp, CreditCard, FileText, ReceiptText, RefreshCcw, ShieldAlert, WalletCards } from "lucide-react";
import PublicShell from "./PublicShell";
import type { PolicySection } from "./PolicyPage";

type Props = { sections: PolicySection[]; title: string; subtitle: string; badge: string; breadcrumbLabel: string };
const mayApply = ["A campaign that has not started may be considered for cancellation or wallet credit at SocialRUSH's discretion.", "A verified duplicate charge, failed credit, or confirmed technical payment error can be investigated.", "If a service becomes unavailable, the undelivered portion may be cancelled and an appropriate wallet credit issued."];
const usuallyNot = ["Processing, partial, or completed delivery is generally not refundable for the delivered portion.", "A campaign sent to an incorrect but valid public link may be non-refundable once processing begins.", "Refill support is not a cash refund and only applies where the service states eligibility."];
const faqs = [["How do SocialRUSH refunds work?", "Eligibility depends on payment verification, campaign status, delivery already completed, refill terms, and the circumstances of the request. Contact support for review of a specific order."], ["Are refunds sent to my wallet?", "Approved wallet credits appear in account transactions. Eligible cancelled orders may receive a wallet credit; the outcome depends on policy review and the order state."], ["Can I get a refund for a completed order?", "Processing, partial, and completed campaigns are generally not refundable for the delivered portion. If a service becomes unavailable, the remaining portion may be reviewed."], ["What if I submitted the wrong link?", "Review service, quantity, and public destination link before checkout. An order sent to an incorrect but valid link may be non-refundable once processing starts."], ["What if payment failed but money was deducted?", "Keep the payment reference and check Billing or Wallet. Verified duplicate charges, failed credits, and confirmed technical payment errors can be investigated by support."], ["Is refill the same as a refund?", "No. Eligible services may have refill support for the period displayed at checkout. Refill support is not a cash refund."]] as const;

function Card({ title, Icon, children, tone = "base" }: { title: string; Icon: typeof CheckCircle2; children: React.ReactNode; tone?: "base" | "good" | "bad" }) {
  const colors = tone === "good" ? "border-emerald-400/25 bg-emerald-400/[.06]" : tone === "bad" ? "border-rose-400/25 bg-rose-400/[.06]" : "border-white/10 bg-white/[.035]";
  return <article className={`rounded-2xl border p-5 ${colors}`}><Icon className={`h-5 w-5 ${tone === "bad" ? "text-rose-300" : tone === "good" ? "text-emerald-300" : "text-orange-300"}`} /><h3 className="mt-4 text-base font-black text-white">{title}</h3><div className="mt-3 text-sm leading-6 text-[#B8C0CE]">{children}</div></article>;
}

export default function RefundPolicyPage({ sections }: Props) {
  return <PublicShell><main className="overflow-x-clip bg-[#080A10] text-white">
    <section className="relative border-b border-white/[.08] px-4 py-10 sm:px-6 sm:py-14 lg:px-8"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_12%_12%,rgba(255,118,0,.18),transparent_30%),radial-gradient(circle_at_88%_18%,rgba(28,55,103,.38),transparent_34%)]" /><div className="relative mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="text-xs font-semibold text-[#A8AFBD]"><Link href="/" className="hover:text-orange-200">Home</Link><span className="mx-2">/</span><span>Refund Policy</span></nav><div className="mt-6 grid gap-7 rounded-[2rem] border border-white/[.1] bg-[#101522]/90 p-6 shadow-[0_30px_80px_-45px_rgba(0,0,0,.95)] sm:p-8 lg:grid-cols-[minmax(0,1fr)_280px] lg:p-10"><div><p className="text-[11px] font-black uppercase tracking-[.18em] text-orange-300">SocialRUSH Refund Policy</p><h1 className="mt-4 max-w-3xl text-3xl font-black tracking-[-.05em] text-white sm:text-5xl">Clear guidance on refunds and order issues</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-[#B8C0CE] sm:text-base">Understand when a refund or wallet adjustment may apply and what to do if an order or payment needs review.</p><div className="mt-7 flex flex-col gap-3 min-[420px]:flex-row"><a href="#refund-guidelines" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#FF6200] to-[#FF9A00] px-5 py-3 text-sm font-black text-white">Read Refund Guidelines <ArrowRight className="h-4 w-4" /></a><Link href="/support" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/15 bg-white/[.04] px-5 py-3 text-sm font-black text-white">Contact Support</Link></div></div><aside className="rounded-2xl border border-orange-400/20 bg-gradient-to-b from-orange-400/[.12] to-white/[.025] p-5"><p className="text-[10px] font-black uppercase tracking-[.16em] text-orange-200">Before you request review</p><div className="mt-5 space-y-3">{[["Order status", "Check your order"], ["Payment record", "Check Billing / Wallet"], ["Helpful context", "Keep order and payment IDs"]].map(([label, value]) => <div key={label} className="rounded-xl border border-white/[.08] bg-[#0B0E16] p-3"><p className="text-[10px] text-[#8F96A3]">{label}</p><p className="mt-1 text-sm font-bold text-white">{value}</p></div>)}</div></aside></div></div></section>
    <section id="refund-guidelines" className="scroll-mt-24 px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-[11px] font-black uppercase tracking-[.16em] text-orange-300">Quick policy summary</p><h2 className="mt-3 text-2xl font-black tracking-[-.035em] sm:text-3xl">A clear starting point for eligibility</h2><div className="mt-7 grid gap-4 lg:grid-cols-2"><Card title="May be eligible for review" Icon={CheckCircle2} tone="good"><ul className="space-y-3">{mayApply.map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-emerald-300" />{item}</li>)}</ul></Card><Card title="Usually not eligible" Icon={Ban} tone="bad"><ul className="space-y-3">{usuallyNot.map((item) => <li key={item} className="flex gap-2"><Ban className="mt-1 h-4 w-4 shrink-0 text-rose-300" />{item}</li>)}</ul></Card></div></div></section>
    <section className="border-y border-white/[.08] bg-[#0C1019] px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-[11px] font-black uppercase tracking-[.16em] text-orange-300">What to do next</p><h2 className="mt-3 text-2xl font-black tracking-[-.035em] sm:text-3xl">Start with the issue you see</h2><div className="mt-7 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{[["Order issue?", "Check order status", "/dashboard/orders", ReceiptText], ["Payment issue?", "Check Wallet or Billing", "/dashboard/billing", CreditCard], ["Cancelled order?", "Review wallet activity", "/dashboard/wallet", WalletCards], ["Need help?", "Contact Support", "/support", CircleHelp]].map(([title, label, href, Icon]) => { const I = Icon as typeof CircleHelp; return <Link href={href as string} key={title as string} className="group rounded-2xl border border-white/[.09] bg-white/[.025] p-5 transition hover:-translate-y-1 hover:border-orange-400/40"><I className="h-5 w-5 text-orange-300"/><h3 className="mt-5 font-black text-white">{title as string}</h3><p className="mt-2 text-sm text-[#A8AFBD]">{label as string}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-black text-orange-200">Open <ArrowRight className="h-3.5 w-3.5" /></span></Link>})}</div></div></section>
    <section className="px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-2"><Card title="Wallet adjustment" Icon={WalletCards}><p>When an eligible order is cancelled or an approved adjustment is made, the amount may be credited to your SocialRUSH wallet. Wallet credits appear in account transactions.</p><div className="mt-5 rounded-xl border border-white/[.09] bg-[#090C13] p-4"><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#8F96A3]">UI Preview</p><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span className="text-[#A8AFBD]">Order total</span><span className="font-bold text-white">₹X</span></div><div className="flex justify-between"><span className="text-[#A8AFBD]">Status</span><span className="font-bold text-rose-300">Cancelled</span></div><div className="flex justify-between border-t border-white/[.08] pt-3"><span className="text-[#A8AFBD]">Wallet adjustment</span><span className="font-black text-emerald-300">+₹X</span></div></div></div></Card><Card title="Payment-provider refund" Icon={CreditCard}><p>Verified duplicate charges, failed credits, or technical payment errors are investigated. Where appropriate, an approved amount may be credited to the wallet or returned to the original payment method.</p><p className="mt-3">Payment-provider processing is outside SocialRUSH control. A payment refund is not automatic or guaranteed; it follows review and applicable payment processing.</p></Card></div></section>
    <section className="border-y border-white/[.08] bg-[#0C1019] px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-3"><Card title="Submitted the wrong link?" Icon={ShieldAlert}><p>Check service, quantity, and public destination link before checkout. A campaign sent to an incorrect but valid link may be non-refundable once processing begins. Contact support with the order ID if review is needed.</p></Card><Card title="Refill and refund are different" Icon={RefreshCcw}><p>Refill support only applies to eligible services for the period displayed at checkout. It is not automatically a refund, and it does not apply to every service.</p></Card><Card title="Requesting a review" Icon={FileText}><p>Include your order ID, relevant public link, payment reference when relevant, and a short description. Never send passwords, OTPs, or recovery codes.</p><Link href="/support" className="mt-4 inline-flex text-sm font-black text-orange-200">Contact Support <ArrowRight className="ml-1 h-4 w-4" /></Link></Card></div></section>
    <section className="px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-[11px] font-black uppercase tracking-[.16em] text-orange-300">Illustrative policy examples</p><h2 className="mt-3 text-2xl font-black tracking-[-.035em] sm:text-3xl">Examples are not guarantees</h2><div className="mt-7 grid gap-3 md:grid-cols-3">{[["Cancelled order", "An order cancelled before delivery may be reviewed for a wallet adjustment under the policy."], ["Completed order", "Completed delivery may not qualify for a refund, especially for the delivered portion."], ["Wrong link", "Support review may be needed; the outcome depends on the order status and whether processing began."]].map(([title, body]) => <article key={title} className="rounded-2xl border border-white/[.09] bg-white/[.03] p-5"><p className="text-[10px] font-black uppercase tracking-[.14em] text-orange-200">Illustrative Policy Example</p><h3 className="mt-4 font-black text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-[#A8AFBD]">{body}</p></article>)}</div></div></section>
    <section className="border-y border-white/[.08] bg-[#0C1019] px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-orange-300">Common questions</p><h2 className="mt-3 text-2xl font-black tracking-[-.035em] sm:text-3xl">Refund and payment FAQ</h2><p className="mt-4 text-sm leading-7 text-[#A8AFBD]">For an account-specific answer, open a support request with the details needed for review.</p></div><div className="space-y-3">{faqs.map(([question, answer]) => <details key={question} className="group rounded-xl border border-white/[.09] bg-white/[.025] p-4"><summary className="cursor-pointer list-none pr-8 text-sm font-black text-white">{question}<span className="float-right text-orange-300 group-open:rotate-45">+</span></summary><p className="mt-3 text-sm leading-6 text-[#B8C0CE]">{answer}</p></details>)}</div></div></section>
    <section className="px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-orange-300">Published policy</p><h2 className="mt-3 text-2xl font-black tracking-[-.035em] sm:text-3xl">Full refund guidelines</h2><p className="mt-4 text-sm leading-7 text-[#A8AFBD]">The complete policy remains available below for reference.</p></div><div className="space-y-3">{sections.map((section) => <article key={section.title} className="rounded-2xl border border-white/[.09] bg-white/[.025] p-5"><h3 className="font-black text-white">{section.title}</h3>{section.body.map((body) => <p key={body} className="mt-2 text-sm leading-6 text-[#B8C0CE]">{body}</p>)}{section.bullets?.length ? <ul className="mt-3 list-disc space-y-1 pl-5 text-sm leading-6 text-[#B8C0CE]">{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul> : null}</article>)}</div></div></section>
    <section className="border-t border-white/[.08] px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl rounded-2xl border border-orange-400/20 bg-orange-400/[.06] p-5"><p className="text-[11px] font-black uppercase tracking-[.16em] text-orange-200">Related help</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-3 text-sm font-bold">{[["Customer Safety", "/trust"], ["Terms", "/terms-and-conditions"], ["Privacy Policy", "/privacy-policy"], ["FAQ", "/faq"], ["Contact", "/contact"], ["Billing", "/dashboard/billing"], ["Wallet", "/dashboard/wallet"]].map(([label, href]) => <Link key={label} href={href} className="text-[#D7DBE3] hover:text-orange-200">{label} →</Link>)}</div></div></section>
  </main></PublicShell>;
}
