"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import {
  ArrowRight, Check, ChevronDown, CirclePause,
  CirclePlay, Link2, LockKeyhole, MessageCircle,
  Minus, Plus, Send, ShieldCheck, Sparkles,
} from "lucide-react";
import PublicShell from "@/components/marketing/PublicShell";
import { formatCurrency } from "@/lib/currency";
import { usePreferredCurrency } from "@/lib/currency/use-currency";
import { validateQuantity } from "@/lib/service-pricing";
import { linkRules, validateCampaignLink } from "@/lib/order-service-experience";
import { getServiceById } from "@/lib/smm-service-catalog";
type LiveServiceFacts = { rate: number; min: number; max: number; deliveryTime: string; refillPolicy: string; available: boolean };

const fallback = getServiceById("telegram-members");
const faqs = [
  ["Do I need my Telegram password?", "No. SocialRUSH only needs the public Telegram channel or group URL required by the service."],
  ["Which Telegram link should I submit?", "Submit the correct public t.me or telegram.me channel or group link. Verify it before continuing."],
  ["Can I track my order?", "Yes. Once your order is placed, its status and details remain available in your SocialRUSH dashboard."],
  ["How is the price calculated?", "The total updates from the live service rate and your selected quantity before secure checkout."],
  ["How long does delivery take?", "The current delivery estimate is displayed alongside the service before you continue to checkout."],
  ["Is refill/support available?", "The current refill or support information is displayed with the active service. Check it before placing your order."],
];

export default function TelegramFollowersLanding({ live }: { live: LiveServiceFacts | null }) {
  const service = fallback;
  const { currency } = usePreferredCurrency("INR");
  const min = live?.min ?? service?.minQuantity ?? 100;
  const max = live?.max ?? service?.maxQuantity ?? 1000000;
  const rate = live?.rate ?? service?.pricePer1000 ?? 0;
  const delivery = live?.deliveryTime ?? service?.deliveryTime ?? "Current estimate shown before checkout";
  const refill = live?.refillPolicy ?? service?.refillPolicy ?? "Check service details";
  const [quantity, setQuantity] = useState(min);
  const [link, setLink] = useState("");
  const [showErrors, setShowErrors] = useState(false);
  const [playing, setPlaying] = useState(false);
  const [openFaq, setOpenFaq] = useState(0);
  const rule = linkRules["telegram-members"];
  const qtyError = service ? validateQuantity(quantity, { ...service, minQuantity: min, maxQuantity: max }) : "Service unavailable";
  const linkError = link.trim() ? validateCampaignLink(link, rule) : "";
  const total = (rate * quantity) / 1000;
  const quick = useMemo(() => [...new Set([min, 100, 500, 1000, 2000, 5000].filter((item) => item >= min && item <= max))], [min, max]);
  const ready = !qtyError && Boolean(link.trim()) && !linkError;
  const orderHref = `/dashboard/new-order?platform=telegram&service=telegram-members&resume=1&quantity=${quantity}&link=${encodeURIComponent(link.trim())}`;
  const updateQuantity = (value: number) => setQuantity(Math.max(min, Math.min(max, Math.round(Number.isFinite(value) ? value : min))));
  const formatQty = (value: number) => value >= 1000 ? `${value / 1000}K` : value.toLocaleString("en-IN");

  return <PublicShell tone="light3d">
    <section className="relative overflow-hidden bg-[#07080D] px-4 pb-16 pt-12 sm:px-6 lg:px-8 lg:pb-24 lg:pt-20">
      <div className="pointer-events-none absolute left-[-12rem] top-0 h-[32rem] w-[32rem] rounded-full bg-orange-500/15 blur-[130px]" /><div className="pointer-events-none absolute right-[-10rem] top-12 h-[28rem] w-[28rem] rounded-full bg-sky-500/15 blur-[130px]" />
      <div className="relative mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.05fr_.95fr]">
        <div><span className="inline-flex items-center gap-2 rounded-full border border-sky-300/25 bg-sky-300/10 px-3 py-2 text-[10px] font-black tracking-[.16em] text-sky-100"><Send className="h-3.5 w-3.5" /> TELEGRAM FOLLOWERS SERVICE</span>
          <h1 className="mt-6 max-w-3xl text-4xl font-black leading-[1.04] tracking-[-.05em] text-white sm:text-6xl">Buy Telegram <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-amber-200">Followers</span> in India</h1>
          <p className="mt-6 max-w-2xl text-base leading-8 text-slate-300">Build a visible public Telegram channel or community with transparent live pricing, clear delivery details, and dashboard tracking. Order using the public link only.</p>
          <div className="mt-7 flex flex-wrap gap-2 text-xs font-bold text-slate-200">{["No Password Required", "Transparent Pricing", "Order Tracking"].map(x => <span key={x} className="inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/[.05] px-3 py-2"><Check className="h-3.5 w-3.5 text-orange-300" />{x}</span>)}</div>
          <div className="mt-8 flex flex-col gap-3 min-[420px]:flex-row"><a href="#order" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#FF7A00] to-[#FFB000] px-6 text-sm font-black text-white shadow-[0_16px_34px_-18px_rgba(255,122,0,.9)]">Start Your Order <ArrowRight className="h-4 w-4" /></a><Link href="/services?platform=telegram" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/15 px-6 text-sm font-black text-white hover:bg-white/5">View Telegram Services</Link><a href="https://wa.me/918860330771?text=Hi%20SocialRUSH%2C%20I%20need%20help%20with%20Telegram%20Followers" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-emerald-300/25 bg-emerald-400/10 px-5 text-sm font-black text-emerald-200"><MessageCircle className="h-4 w-4" /> WhatsApp</a></div>
        </div>
        <ChannelCard rate={rate} delivery={delivery} refill={refill} playing={playing} />
      </div>
    </section>
    <section id="order" className="scroll-mt-20 bg-[#0b0d14] px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-black tracking-[.16em] text-orange-300">LIVE ORDER BUILDER</p><h2 className="mt-3 text-3xl font-black tracking-tight text-white">Build Your Telegram Followers Order</h2><p className="mt-2 text-sm text-slate-400">Choose your quantity and see your total instantly.</p>
      <div className="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_380px]"><article className="rounded-[28px] border border-white/10 bg-[#121620] p-5 shadow-2xl sm:p-7"><p className="text-sm font-black text-white">Choose Followers</p><div className="mt-5 grid grid-cols-2 gap-3 min-[460px]:grid-cols-4">{quick.map(value => <button key={value} type="button" onClick={() => updateQuantity(value)} className={`min-h-20 rounded-2xl border p-3 text-left transition ${quantity === value ? "border-orange-400 bg-orange-400/15 text-white" : "border-white/10 bg-white/[.03] text-slate-300 hover:border-sky-300/40"}`}><strong className="block text-lg">{formatQty(value)}</strong><span className="mt-1 block text-[10px] font-black uppercase tracking-wider text-slate-400">followers</span></button>)}</div>
        <label className="mt-7 block text-sm font-black text-white">Custom quantity <span className="mt-2 flex overflow-hidden rounded-2xl border border-white/10 bg-[#090b10] focus-within:border-orange-400"><button type="button" aria-label="Decrease quantity" onClick={() => updateQuantity(quantity - 1)} className="grid min-h-14 w-14 place-items-center text-orange-300"><Minus className="h-4 w-4" /></button><input value={quantity} type="number" inputMode="numeric" min={min} max={max} step="1" onChange={e => setQuantity(Number(e.target.value))} className="min-w-0 flex-1 bg-transparent text-center font-black text-white outline-none"/><button type="button" aria-label="Increase quantity" onClick={() => updateQuantity(quantity + 1)} className="grid min-h-14 w-14 place-items-center text-orange-300"><Plus className="h-4 w-4" /></button></span></label><p className="mt-2 text-xs text-slate-400">Min {min.toLocaleString("en-IN")} • Max {max.toLocaleString("en-IN")}</p>{showErrors && qtyError && <p role="alert" className="mt-2 text-xs font-bold text-red-300">{qtyError}</p>}
        <label className="mt-8 block text-sm font-black text-white">Public Telegram Channel / Group URL <span className="mt-2 flex rounded-2xl border border-white/10 bg-[#090b10] focus-within:border-sky-300"><span className="grid w-12 place-items-center text-sky-300"><Link2 className="h-5 w-5" /></span><input value={link} onChange={e => setLink(e.target.value)} placeholder={rule.placeholder} className="min-h-14 min-w-0 flex-1 bg-transparent pr-4 text-sm text-white outline-none placeholder:text-slate-600" /></span></label><p className="mt-2 text-xs leading-6 text-slate-400">{rule.helper} Never submit a password, OTP, phone login, or recovery code.</p>{link.trim() && <p className={`mt-2 text-xs font-bold ${linkError ? "text-red-300" : "text-emerald-300"}`}>{linkError || "✓ Valid public Telegram link"}</p>}{showErrors && !link.trim() && <p role="alert" className="mt-2 text-xs font-bold text-red-300">Enter a public Telegram channel or group link to continue.</p>}</article>
        <aside className="rounded-[28px] border border-orange-400/25 bg-[linear-gradient(145deg,#21170f,#111521)] p-6 lg:sticky lg:top-24 lg:h-fit"><div className="flex items-start justify-between"><div><p className="text-[10px] font-black tracking-[.16em] text-orange-200">LIVE ORDER SUMMARY</p><h3 className="mt-2 text-xl font-black text-white">Telegram Followers</h3></div><ShieldCheck className="h-6 w-6 text-sky-300" /></div><dl className="mt-6 space-y-3 text-sm"><Summary label="Quantity" value={quantity.toLocaleString("en-IN")} /><Summary label="Live rate" value={`${formatCurrency(rate, currency)} / 1K`} /><Summary label="Delivery" value={delivery} /><Summary label="Refill/support" value={refill} /><Summary label="Telegram Link Status" value={link.trim() && !linkError ? "Ready" : "Required"} /></dl><div className="mt-6 rounded-2xl border border-white/10 bg-black/25 p-4"><p className="text-[10px] font-black tracking-[.16em] text-orange-200">TOTAL</p><p className="mt-1 text-3xl font-black text-white">{formatCurrency(total, currency)}</p></div><Link href={ready ? orderHref : "#order"} onClick={e => {if (!ready) {e.preventDefault(); setShowErrors(true);}}} aria-disabled={!ready} className={`mt-6 inline-flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl text-sm font-black ${ready ? "bg-gradient-to-r from-[#FF7A00] to-[#FFB000] text-white" : "bg-white/10 text-slate-500"}`}>Continue to Secure Order <ArrowRight className="h-4 w-4" /></Link><p className="mt-4 flex items-center justify-center gap-2 text-center text-xs text-slate-400"><LockKeyhole className="h-4 w-4 text-orange-300"/>Secure checkout • No password required</p></aside></div></div></section>
    <section className="bg-[#07080D] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-7 lg:grid-cols-[1fr_.85fr]"><ChannelCard rate={rate} delivery={delivery} refill={refill} playing={playing} /><div className="flex flex-col justify-center"><p className="text-xs font-black tracking-[.16em] text-sky-200">INTERACTIVE UI PREVIEW</p><h2 className="mt-3 text-3xl font-black tracking-tight text-white">Preview the Telegram channel experience</h2><p className="mt-4 text-sm leading-7 text-slate-400">This original interface preview shows how a public channel can be presented. It is not a customer result or performance forecast.</p><button type="button" onClick={() => setPlaying(!playing)} aria-pressed={playing} className="mt-6 inline-flex min-h-12 w-fit items-center gap-2 rounded-xl border border-sky-300/30 bg-sky-300/10 px-5 text-sm font-black text-sky-100">{playing ? <CirclePause className="h-5 w-5"/> : <CirclePlay className="h-5 w-5"/>}{playing ? "Pause Preview" : "Play Preview"}</button><div className="mt-8 grid gap-3 sm:grid-cols-3">{[["Public-Link Ordering", "Use the required public destination."],["Clear Campaign Details", "Review the live service information."],["Trackable Delivery", "Follow the order in your dashboard."]].map(([title, text]) => <div key={title} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><h3 className="text-sm font-black text-white">{title}</h3><p className="mt-2 text-xs leading-6 text-slate-400">{text}</p></div>)}</div></div></div></section>
    <section className="bg-[#0d1018] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black tracking-[.16em] text-orange-300">WHY SOCIALRUSH</p><h2 className="mt-3 text-3xl font-black text-white">A clearer view of your Telegram order</h2><div className="mt-8 grid gap-4 md:grid-cols-4"><Bento title="Transparent Live Pricing" text={`${formatCurrency(rate, currency)} per 1K from the active service catalog.`} wide/><Bento title="Public Telegram Link Ordering" text="A visible channel or group URL is required."/><Bento title="Secure Checkout" text="Continue through the existing SocialRUSH order flow."/><Bento title="Dashboard Tracking" text="Keep campaign details and status together."/><Bento title="Refill / Support Information" text={refill}/><Bento title="No Password Required" text="Your credentials stay private."/><Bento title="Multi-Platform Services" text="Compare supported services in one catalog."/></div></div></section>
    <section className="bg-[#07080D] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-black text-white">Who this service is for</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Channel Owners","Community Managers","Creators","Brands","Education Communities","Marketing Teams"].map((name,i)=><div key={name} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[.035] p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-orange-400/10 text-orange-300">{i+1}</span><div><h3 className="text-sm font-black text-white">{name}</h3><p className="mt-1 text-xs text-slate-400">For organized public-channel campaign planning.</p></div></div>)}</div></div></section>
    <section className="bg-[#0d1018] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black tracking-[.16em] text-sky-200">HOW IT WORKS</p><ol className="mt-7 grid gap-4 md:grid-cols-3 lg:grid-cols-6">{["Choose Telegram Followers","Select Quantity","Paste Public Telegram Link","Review Live Total","Pay Securely","Track Your Order"].map((item,i)=><li key={item} className="relative rounded-2xl border border-white/10 bg-[#111620] p-4"><span className="text-2xl font-black text-orange-300">0{i+1}</span><h3 className="mt-5 text-sm font-black text-white">{item}</h3></li>)}</ol></div></section>
    <section className="bg-[#07080D] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-black tracking-[.16em] text-orange-300">GOOD TO KNOW</p><h2 className="mt-3 text-3xl font-black text-white">Ordering details, clearly stated</h2><p className="mt-4 text-sm leading-7 text-slate-400">Use the correct accessible Telegram destination. Current delivery and refill/support details are supplied by the active service catalog.</p></div><div className="space-y-3">{faqs.map(([q,a],i)=><div key={q} className="rounded-2xl border border-white/10 bg-white/[.035]"><button type="button" aria-expanded={openFaq===i} onClick={()=>setOpenFaq(openFaq===i?-1:i)} className="flex w-full items-center justify-between gap-4 p-5 text-left text-sm font-black text-white">{q}<ChevronDown className={`h-5 w-5 shrink-0 text-orange-300 transition ${openFaq===i ? "rotate-180" : ""}`}/></button>{openFaq===i&&<p className="border-t border-white/10 px-5 py-4 text-sm leading-7 text-slate-400">{a}</p>}</div>)}</div></div></section>
    <section className="bg-[#0b0d14] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl rounded-[32px] border border-orange-400/20 bg-[radial-gradient(circle_at_top_right,rgba(56,189,248,.15),transparent_40%),linear-gradient(135deg,#1b130d,#101722)] p-7 text-center sm:p-12"><p className="text-xs font-black tracking-[.16em] text-orange-200">TELEGRAM FOLLOWERS</p><h2 className="mt-3 text-3xl font-black text-white">Ready to build your Telegram Followers order?</h2><p className="mt-4 text-lg font-black text-orange-200">Starting from {formatCurrency(rate, currency)} / 1K</p><div className="mt-7 flex flex-col justify-center gap-3 min-[420px]:flex-row"><a href="#order" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-gradient-to-r from-[#FF7A00] to-[#FFB000] px-6 text-sm font-black text-white">Start Your Order</a><Link href="/services?platform=telegram" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/15 px-6 text-sm font-black text-white">Explore Telegram Services</Link></div><p className="mt-5 text-xs font-bold text-slate-400">No password required • Live pricing • Dashboard tracking</p></div></section>
  </PublicShell>;
}

function Summary({label,value}:{label:string;value:string}) { return <div className="flex justify-between gap-4"><dt className="text-slate-400">{label}</dt><dd className="max-w-[60%] text-right font-bold text-slate-100">{value}</dd></div> }
function Bento({title,text,wide=false}:{title:string;text:string;wide?:boolean}) { return <article className={`rounded-2xl border border-white/10 bg-white/[.035] p-5 ${wide ? "md:col-span-2" : ""}`}><Sparkles className="h-5 w-5 text-orange-300"/><h3 className="mt-4 text-sm font-black text-white">{title}</h3><p className="mt-2 text-xs leading-6 text-slate-400">{text}</p></article> }
function ChannelCard({rate,delivery,refill,playing}:{rate:number;delivery:string;refill:string;playing:boolean}) { const count=playing?"12,8••":"12,480"; return <aside className="relative overflow-hidden rounded-[32px] border border-sky-300/20 bg-[linear-gradient(145deg,#111c2c,#0b0d14_60%)] p-4 shadow-[0_30px_90px_-35px_rgba(14,165,233,.45)] sm:p-6"><div className="absolute right-4 top-4 rounded-full border border-sky-300/20 bg-sky-300/10 px-2 py-1 text-[9px] font-black tracking-widest text-sky-100">UI PREVIEW</div><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-full bg-[#2AABEE] text-white"><Send className="h-6 w-6"/></span><div><p className="text-[10px] font-black tracking-[.16em] text-sky-200">TELEGRAM CHANNEL GROWTH DASHBOARD</p><h2 className="mt-1 text-base font-black text-white">Your Channel <span className="ml-2 rounded-full bg-emerald-400/15 px-2 py-1 text-[9px] text-emerald-200">LIVE SERVICE</span></h2><p className="text-xs text-slate-400">@yourchannel • Public link ready</p></div></div><div className="mt-5 rounded-2xl border border-white/10 bg-[#121b29] p-4"><div className="flex items-end justify-between"><div><p className="text-xs text-slate-400">Community members</p><p className={`mt-1 text-3xl font-black text-white ${playing ? "animate-pulse" : ""}`}>{count}</p></div><span className="text-[10px] font-bold text-sky-200">UI Preview</span></div><div className="mt-4 flex h-16 items-end gap-1.5">{[20,35,30,52,48,68,58,82,74,94].map((h,i)=><span key={i} style={{height:`${playing?h:Math.max(18,h-18)}%`}} className={`flex-1 rounded-t bg-gradient-to-t from-orange-500 to-sky-300 transition-all duration-500 ${playing?"animate-pulse":""}`}/>)}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.04] p-3"><p className="text-[10px] font-black text-slate-400">CHANNEL UPDATE</p><p className="mt-2 text-xs leading-5 text-slate-200">A concise community announcement sits here with a clean visual card.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.04] p-3"><p className="text-[10px] font-black text-slate-400">NEW CONTENT</p><div className="mt-2 h-10 rounded-lg bg-[linear-gradient(135deg,rgba(42,171,238,.45),rgba(255,122,0,.35))]"/></div></div><dl className="mt-4 grid gap-2 border-t border-white/10 pt-4 text-xs"><Summary label="Telegram Followers" value={`${formatCurrency(rate,"INR")} / 1K`} /><Summary label="Delivery" value={delivery}/><Summary label="Refill / support" value={refill}/><Summary label="Secure order" value="Protected"/></dl><a href="#order" className="mt-5 inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-white text-sm font-black text-[#0B0B0F]">Build Your Order</a></aside> }
