import Link from "next/link";
import {
  ArrowDown, ArrowRight, Check, CircleAlert, CreditCard, ExternalLink,
  FileText, Link2, MessageCircle, ShieldCheck, WalletCards,
} from "lucide-react";
import PublicShell from "./PublicShell";

type Section = { id: string; title: string; body: string[]; bullets?: string[] };

// The legal copy below intentionally preserves the existing Terms provisions.
const sections: Section[] = [
  { id: "acceptance", title: "Acceptance of terms", body: ["By accessing SocialRUSH, creating an account, funding a wallet, or placing a campaign, you agree to these Terms & Conditions and the service details shown before checkout."] },
  { id: "services", title: "Services", body: ["SocialRUSH provides social media growth services for supported public profiles, pages, channels, posts, and videos across Instagram, YouTube, Facebook, LinkedIn, TikTok, and Twitter/X.", "Availability, rates, quantities, delivery estimates, refill eligibility, and campaign requirements are displayed in the catalog or checkout before an order is confirmed."] },
  { id: "accounts", title: "Accounts and customer responsibilities", body: ["You must provide accurate information, protect your credentials, and have lawful authority to submit each public destination."], bullets: ["Do not use services for unlawful, deceptive, infringing, abusive, or unauthorized activity.", "Do not share your social media password with SocialRUSH or submit links you are not authorized to promote.", "Review the selected service, quantity, link, rate, and total before checkout."] },
  { id: "processing", title: "Campaign processing", body: ["Processing may begin soon after checkout. Delivery timing is an estimate and can be affected by platform changes, service availability, destination settings, quantity, and external conditions.", "SocialRUSH does not guarantee revenue, platform ranking, organic engagement, or a specific commercial result."] },
  { id: "wallet", title: "Wallet, billing, and transactions", body: ["Verified payments credit the applicable account wallet. Campaign charges are deducted when an order is placed. Transaction and order records remain available in the customer dashboard.", "Customers must report suspected duplicate charges or missing credits promptly through support."] },
  { id: "refill", title: "Refill support", body: ["Only services marked refill eligible receive coverage, and only during the displayed period. Eligibility can depend on the destination remaining public and the customer not changing identifiers or using conflicting services."] },
  { id: "refunds", title: "Cancellations and refunds", body: ["Cancellation and refund eligibility follows the Refund Policy. Campaigns already processing or delivered may not be refundable, except for an approved undelivered portion or verified payment error."] },
  { id: "availability", title: "Platform availability", body: ["Social networks and fulfilment systems are operated by third parties. SocialRUSH may pause, replace, or discontinue a service when delivery conditions or platform rules change."] },
  { id: "support", title: "Support and communication", body: ["Customers can use protected support tickets for order, payment, refill, or account issues. Communications must remain accurate and professional so requests can be investigated effectively."] },
  { id: "liability", title: "Liability", body: ["To the extent permitted by law, SocialRUSH is not liable for indirect or consequential loss, third-party platform actions, account changes, external outages, or issues caused by incorrect customer instructions. Aggregate liability is limited to the amount paid for the affected service."] },
  { id: "changes", title: "Changes and contact", body: ["We may update these terms prospectively as the platform changes. Questions or formal notices may be sent to support@getsocialrush.com."] },
];

const overview = [
  [Link2, "Public-link ordering", "Use the correct applicable public destination link."],
  [CreditCard, "Payments", "Review the displayed rate and total before checkout."],
  [FileText, "Delivery", "Details and estimates depend on the selected service."],
  [ShieldCheck, "Refill", "Coverage applies only where the service says it is eligible."],
  [MessageCircle, "Support", "Use official support for order, payment, refill, or account help."],
] as const;

export default function TermsCenter() {
  return <PublicShell>
    <div className="relative overflow-x-clip bg-[#08090d] text-white">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-[38rem] bg-[radial-gradient(circle_at_14%_5%,rgba(255,117,24,.19),transparent_32%),radial-gradient(circle_at_85%_12%,rgba(245,158,11,.12),transparent_30%)]" />
      <main className="relative">
        <section className="border-b border-white/[.08] px-4 py-12 sm:px-6 sm:py-16 lg:px-8 lg:py-20">
          <div className="mx-auto max-w-7xl">
            <nav aria-label="Breadcrumb" className="text-xs text-slate-400"><Link href="/" className="hover:text-orange-200">Home</Link><span className="mx-2">/</span><span>Terms &amp; Conditions</span></nav>
            <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_300px] lg:items-end">
              <div><p className="inline-flex items-center gap-2 rounded-full border border-orange-300/25 bg-orange-400/[.08] px-3 py-1.5 text-[10px] font-black tracking-[.18em] text-orange-200"><ShieldCheck className="h-3.5 w-3.5" />SOCIALRUSH TERMS</p><h1 className="mt-6 max-w-3xl text-4xl font-black leading-[1.04] tracking-[-.05em] sm:text-5xl lg:text-6xl">Clear terms for using SocialRUSH.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-300">Understand the rules that apply when using SocialRUSH services, placing orders, managing payments and accessing your customer account.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#key-terms" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-gradient-to-r from-orange-600 to-amber-400 px-5 text-sm font-black text-white shadow-[0_14px_32px_rgba(234,88,12,.22)]">Read Key Terms <ArrowDown className="h-4 w-4" /></a><Link href="/contact" className="inline-flex min-h-12 items-center rounded-xl border border-white/15 bg-white/[.035] px-5 text-sm font-bold text-white hover:border-orange-300/40">Contact Support</Link></div></div>
              <aside className="rounded-3xl border border-orange-300/20 bg-[#10131b]/90 p-5 shadow-2xl"><p className="text-[10px] font-black tracking-[.16em] text-orange-200">BEFORE YOU ORDER</p><dl className="mt-4 space-y-3 text-sm"><div className="border-b border-white/[.08] pb-3"><dt className="font-bold">Service & quantity</dt><dd className="mt-1 text-slate-400">What you are purchasing and the requested amount.</dd></div><div className="border-b border-white/[.08] pb-3"><dt className="font-bold">Public link</dt><dd className="mt-1 text-slate-400">The applicable destination for delivery.</dd></div><div><dt className="font-bold">Price, delivery & refill</dt><dd className="mt-1 text-slate-400">Review the live details shown for the selected service.</dd></div></dl></aside>
            </div>
          </div>
        </section>

        <section id="key-terms" className="px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-black tracking-[.18em] text-orange-300">QUICK TERMS OVERVIEW</p><h2 className="mt-3 text-2xl font-black sm:text-3xl">The essentials, before the full terms.</h2></div><a href="#terms" className="hidden text-sm font-bold text-orange-200 sm:inline-flex">Full terms <ArrowRight className="ml-1 h-4 w-4" /></a></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{overview.map(([Icon, title, copy]) => <article key={title} className="rounded-2xl border border-white/[.09] bg-[#10131b] p-4"><Icon className="h-5 w-5 text-orange-300" /><h3 className="mt-5 text-sm font-black">{title}</h3><p className="mt-2 text-xs leading-6 text-slate-400">{copy}</p></article>)}</div></div></section>

        <section className="border-y border-amber-300/15 bg-[linear-gradient(100deg,rgba(120,53,15,.22),rgba(16,19,27,.9))] px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-2"><div className="flex gap-4"><CircleAlert className="mt-1 h-6 w-6 shrink-0 text-amber-300" /><div><p className="text-[10px] font-black tracking-[.18em] text-amber-200">CHECK YOUR LINK BEFORE ORDERING</p><p className="mt-2 text-sm leading-7 text-slate-300">Verify the destination link before confirming an order. If an incorrect link has already been submitted, contact support promptly; available options depend on the order status and applicable policy.</p></div></div><div className="flex gap-4 border-t border-white/[.08] pt-5 lg:border-l lg:border-t-0 lg:pl-6 lg:pt-0"><ShieldCheck className="mt-1 h-6 w-6 shrink-0 text-emerald-300" /><div><p className="text-[10px] font-black tracking-[.18em] text-emerald-200">NEVER SUBMIT</p><p className="mt-2 text-sm leading-7 text-slate-300">Do not share a social-media password, OTP, or recovery code. SocialRUSH uses a valid public profile, post, page, channel, or video link where required.</p></div></div></div></section>

        <section id="terms" className="px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[260px_minmax(0,1fr)]"><aside><details className="rounded-2xl border border-white/[.1] bg-[#10131b] p-4 lg:hidden"><summary className="cursor-pointer list-none text-sm font-black">Jump to a section</summary><TermsNav /></details><div className="hidden rounded-2xl border border-white/[.1] bg-[#10131b] p-5 lg:sticky lg:top-24 lg:block"><p className="text-[10px] font-black tracking-[.16em] text-orange-300">TERMS NAVIGATION</p><TermsNav /></div></aside><article className="min-w-0 rounded-[28px] border border-white/[.1] bg-[#10131b] p-5 sm:p-8 lg:p-10">{sections.map((section, index) => <section id={section.id} key={section.id} className="scroll-mt-28 border-b border-white/[.08] py-9 first:pt-0 last:border-0 last:pb-0"><p className="text-[10px] font-black tracking-[.18em] text-orange-300">{String(index + 1).padStart(2, "0")}</p><h2 className="mt-3 text-2xl font-black tracking-[-.025em] sm:text-3xl">{section.title}</h2>{section.body.map(paragraph => <p key={paragraph} className="mt-4 max-w-3xl text-sm leading-8 text-slate-300 sm:text-base">{paragraph}</p>)}{section.bullets && <ul className="mt-5 max-w-3xl space-y-3">{section.bullets.map(item => <li key={item} className="flex gap-3 text-sm leading-7 text-slate-300"><Check className="mt-1 h-4 w-4 shrink-0 text-orange-300" />{item}</li>)}</ul>}{section.id === "refunds" && <Link href="/refund-policy" className="mt-5 inline-flex min-h-11 items-center text-sm font-bold text-orange-200 hover:text-orange-100">Read Refund Policy <ArrowRight className="ml-1 h-4 w-4" /></Link>}{section.id === "wallet" && <Link href="/pricing" className="mt-5 inline-flex min-h-11 items-center text-sm font-bold text-orange-200 hover:text-orange-100">Review current pricing <ArrowRight className="ml-1 h-4 w-4" /></Link>}</section>)}</article></div></section>

        <section className="px-4 pb-16 sm:px-6 lg:px-8 lg:pb-24"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[1.05fr_.95fr]"><div className="rounded-[28px] border border-white/[.1] bg-[#10131b] p-6 sm:p-8"><p className="text-[10px] font-black tracking-[.18em] text-orange-300">TERMS FAQ</p><h2 className="mt-3 text-2xl font-black">Quick answers</h2><div className="mt-5 divide-y divide-white/[.08]">{[["Do I need to provide my social media password?", "No. Do not share your social media password, OTP, or recovery code with SocialRUSH."],["Can I cancel an order after it starts?", "Cancellation and refund eligibility follows the Refund Policy. Processing or delivered campaigns may not be refundable."],["Are all services eligible for refill?", "No. Only services marked refill eligible receive coverage, and only during the displayed period."],["How long does delivery take?", "Delivery timing is an estimate and can vary with platform changes, availability, destination settings, quantity, and external conditions."]].map(([q,a]) => <details key={q} className="group py-2"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between gap-3 text-sm font-bold"><span>{q}</span><span className="text-orange-300 group-open:rotate-45">+</span></summary><p className="pb-4 pr-6 text-sm leading-7 text-slate-400">{a}</p></details>)}</div></div><aside className="rounded-[28px] border border-orange-300/20 bg-[radial-gradient(circle_at_top_right,rgba(249,115,22,.17),transparent_46%),#10131b] p-6 sm:p-8"><WalletCards className="h-7 w-7 text-orange-300" /><p className="mt-5 text-[10px] font-black tracking-[.18em] text-orange-200">RELATED POLICIES & HELP</p><h2 className="mt-3 text-2xl font-black">Find the right guidance.</h2><div className="mt-6 grid gap-2">{[["Privacy Policy", "/privacy-policy"],["Refund Policy", "/refund-policy"],["Customer Safety", "/trust"],["FAQ", "/faq"],["Contact Support", "/contact"]].map(([label, href]) => <Link key={href} href={href} className="flex min-h-11 items-center justify-between rounded-xl border border-white/[.1] bg-black/15 px-4 text-sm font-bold hover:border-orange-300/40">{label}<ExternalLink className="h-4 w-4 text-orange-300" /></Link>)}</div></aside></div></section>
      </main>
    </div>
  </PublicShell>;
}

function TermsNav() { return <nav className="mt-4 space-y-1" aria-label="Terms table of contents">{sections.map((section, index) => <a key={section.id} href={`#${section.id}`} className="flex min-h-9 items-center rounded-lg px-2 text-xs text-slate-400 hover:bg-orange-400/[.08] hover:text-orange-100"><span className="mr-2 text-orange-300">{String(index + 1).padStart(2, "0")}</span>{section.title}</a>)}</nav>; }
