import Link from "next/link";
import { ArrowRight,  ChevronRight, CircleDollarSign, ExternalLink,  LockKeyhole,  ShieldCheck } from "lucide-react";
import PublicShell from "@/components/marketing/PublicShell";
import BreadcrumbJsonLd from "@/components/seo/BreadcrumbJsonLd";
import MarketCurrencyInitializer from "./MarketCurrencyInitializer";
import type { InternationalMarket } from "@/lib/seo/international";
import { activeSmmServices } from "@/lib/smm-service-catalog";

const featured = [
  ["Instagram", "Buy Instagram Followers in the US", "/us/buy-instagram-followers", "Public-profile campaign planning"],
  ["YouTube", "Buy YouTube Subscribers in the US", "/us/buy-youtube-subscribers", "Public channel campaigns"],
  ["YouTube", "Buy YouTube Views in the US", "/us/buy-youtube-views", "Public video and Short campaigns"],
  ["LinkedIn", "Buy LinkedIn Followers in the US", "/us/buy-linkedin-followers", "Professional profile and company-page planning"],
] as const;

const platformRows = [
  ["Instagram", "Audience, post engagement and Reel visibility", "instagram"],
  ["YouTube", "Channel audience, video engagement and viewing activity", "youtube"],
  ["LinkedIn", "Professional profile, post and community services", "linkedin"],
  ["Facebook", "Page audience, post activity and video visibility", "facebook"],
  ["TikTok", "Profile audience and public-video activity", "tiktok"],
  ["X / Twitter", "Profile audience and public-post activity", "x"],
  ["Telegram", "Channel community and post activity", "telegram"],
] as const;

const faqs = [
  ["What social media services does SocialRUSH offer in the United States?", "This US market hub helps visitors browse current Instagram, YouTube, LinkedIn, Facebook, TikTok, X and Telegram service categories. Individual service pages show the applicable destination, live details and order requirements."],
  ["Can I view prices in US dollars?", "Yes. USD display is available to help with campaign planning. It is a display convenience, not a separate US payment flow."],
  ["Is checkout charged in USD or INR?", "Checkout remains INR-authoritative. Review the actual checkout amount and terms before payment; the USD display estimate does not change the checkout currency."],
  ["Which US-specific service pages are available?", "SocialRUSH currently has dedicated US pages for Instagram followers, YouTube subscribers, YouTube views and LinkedIn followers. Other platforms link to the relevant live service category."],
  ["Do I need to share my social media password?", "No. SocialRUSH never asks for your social-media password, OTP, or recovery code. Orders use the required public profile, post, video, channel or page link."],
  ["Are delivery times and refill details the same for every service?", "No. Delivery information and refill eligibility can vary. Check the active service detail and order summary before continuing to checkout."],
  ["Can I track my order?", "Yes. After using the established order flow, order status and history are available from your account dashboard."],
] as const;

export default function UnitedStatesMarketHub({ market }: { market: InternationalMarket }) {
  const serviceCount = (platform: string) => activeSmmServices.filter((service) => service.platform === platform).length;
  const itemList = featured.map(([,, href], position) => ({ "@type": "ListItem", position: position + 1, url: `https://www.getsocialrush.com${href}` }));
  const schema = [
    { "@context": "https://schema.org", "@type": "WebPage", name: "Social Media Growth Services in the United States", url: "https://www.getsocialrush.com/us", description: "A United States market hub for discovering SocialRUSH social media growth services." },
    { "@context": "https://schema.org", "@type": "ItemList", name: "US-specific SocialRUSH service pages", itemListElement: itemList },
    { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
  ];

  return <PublicShell>
    <MarketCurrencyInitializer currency={market.currency} />
    <BreadcrumbJsonLd items={[{ name: "Home", path: "/" }, { name: "United States", path: "/us" }]} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
    <main className="overflow-hidden bg-[#090b10] text-[#f7f4ed]">
      <section className="relative border-b border-white/10 px-5 pb-16 pt-14 sm:px-8 lg:px-10 lg:pb-24 lg:pt-24">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_80%_18%,rgba(255,112,0,.19),transparent_26%),radial-gradient(circle_at_9%_0%,rgba(50,97,180,.13),transparent_26%)]" />
        <div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.03fr_.97fr] lg:items-center">
          <div><p className="text-xs font-black uppercase tracking-[.2em] text-orange-300">SocialRUSH · United States</p><h1 className="mt-5 max-w-3xl text-4xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">Social media growth services for US-facing campaigns.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-300 sm:text-lg">A focused market hub for choosing the right social service, reviewing public-link requirements and moving into the established SocialRUSH order flow with clarity.</p><div className="mt-8 flex flex-col gap-3 min-[430px]:flex-row"><a href="#services" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-orange-500 px-5 text-sm font-black text-white transition hover:bg-orange-400">Explore US services <ArrowRight className="h-4 w-4" /></a><Link href="/pricing" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/20 px-5 text-sm font-black transition hover:border-orange-300 hover:text-orange-200">View pricing</Link></div><p className="mt-7 flex items-center gap-2 text-xs font-bold text-slate-300"><ShieldCheck className="h-4 w-4 text-orange-300" />Public-link ordering · Service details before checkout · Dashboard tracking</p></div>
          <aside className="border border-white/15 bg-[#12151d] p-5 shadow-2xl sm:p-7"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div><p className="text-xs font-black uppercase tracking-[.16em] text-orange-300">US campaign navigator</p><p className="mt-1 text-sm text-slate-400">Start with the platform, then the campaign goal.</p></div><span className="grid h-11 w-11 place-items-center rounded-full border border-orange-400/30 bg-orange-400/10 text-lg font-black text-orange-200">US</span></div><div className="mt-5 divide-y divide-white/10">{platformRows.slice(0, 4).map(([name, copy, key], i) => <Link key={name} href={`/services?platform=${key}`} className="group flex items-center gap-4 py-4"><span className={`grid h-9 w-9 place-items-center rounded-lg text-xs font-black ${i === 0 ? "bg-orange-500 text-white" : "bg-white/8 text-orange-200"}`}>{name === "X / Twitter" ? "X" : name.slice(0, 2).toUpperCase()}</span><span className="min-w-0 flex-1"><b className="block text-sm">{name}</b><span className="mt-0.5 block text-xs text-slate-400">{copy}</span></span><ChevronRight className="h-4 w-4 text-slate-500 transition group-hover:text-orange-300" /></Link>)}</div><div className="mt-4 flex items-center justify-between border-t border-white/10 pt-5 text-xs"><span className="font-bold text-slate-300">USD display for planning</span><span className="rounded-full bg-[#1e355b] px-2.5 py-1 font-black text-blue-100">INR checkout</span></div></aside>
        </div>
      </section>

      <section id="services" className="px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl"><div className="grid gap-8 border-b border-white/10 pb-9 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">Featured US pages</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Start with a focused service page.</h2></div><p className="max-w-2xl text-sm leading-7 text-slate-300">These US-specific pages are designed for their individual service intent. This hub stays broad: it helps you choose the right route before you order.</p></div><div className="mt-7 grid gap-px overflow-hidden border border-white/10 bg-white/10 md:grid-cols-2">{featured.map(([platform, title, href, description], index) => <Link key={href} href={href} className={`group bg-[#0e1118] p-6 transition hover:bg-[#171b25] ${index === 0 ? "md:col-span-2 md:grid md:grid-cols-[1.15fr_.85fr] md:items-end md:gap-8" : ""}`}><div><p className="text-xs font-black uppercase tracking-[.16em] text-orange-300">{platform} · United States</p><h3 className="mt-3 text-xl font-black sm:text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{description}</p></div><span className="mt-5 inline-flex items-center gap-2 text-sm font-black text-orange-200">Open service page <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>

      <section className="border-y border-white/10 bg-[#10131a] px-5 py-16 sm:px-8 lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">Choose your platform</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">A service directory built around real discovery.</h2><p className="mt-5 text-sm leading-7 text-slate-300">Browse active platform categories. The live service catalog and each service page remain the source of truth for availability, pricing and details.</p><Link href="/services" className="mt-6 inline-flex items-center gap-2 text-sm font-black text-orange-200">Explore the full service catalog <ExternalLink className="h-4 w-4" /></Link></div><div className="border-t border-white/10">{platformRows.map(([name, copy, key]) => <Link key={name} href={`/services?platform=${key}`} className="group grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b border-white/10 py-4 sm:py-5"><span className="grid h-10 w-10 place-items-center rounded-lg bg-white/[.06] text-xs font-black text-orange-200">{name === "X / Twitter" ? "X" : name.slice(0, 2).toUpperCase()}</span><span><b className="block text-sm sm:text-base">{name}</b><span className="mt-1 block text-xs leading-5 text-slate-400">{copy}</span></span><span className="flex items-center gap-2 text-xs font-bold text-slate-400"><span className="hidden sm:inline">{serviceCount(key)} active options</span><ChevronRight className="h-4 w-4 text-orange-300 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>

      <section className="px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">Campaign goals</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Not sure what to choose? Begin with the goal.</h2><div className="mt-8 divide-y divide-white/10 border-y border-white/10">{[["Audience growth", "Instagram, YouTube, Facebook, TikTok, X and Telegram profile or channel options", "/services"], ["Post engagement", "Instagram, Facebook, LinkedIn, TikTok and X public-content options", "/services"], ["Video visibility", "YouTube, Instagram, Facebook and TikTok public-video options", "/services?platform=youtube"], ["Professional network growth", "LinkedIn profile, company and USA-targeted service options", "/services?platform=linkedin"], ["Community growth", "Facebook Group, Telegram and LinkedIn Group options", "/services?platform=telegram"]].map(([title, copy, href]) => <Link key={title} href={href} className="group flex items-start justify-between gap-5 py-5"><span><b className="block text-base">{title}</b><span className="mt-1 block text-sm leading-6 text-slate-400">{copy}</span></span><ArrowRight className="mt-1 h-4 w-4 shrink-0 text-orange-300 transition group-hover:translate-x-1" /></Link>)}</div></div><aside className="border border-orange-400/25 bg-[linear-gradient(145deg,#23160f,#12151d_58%)] p-6 sm:p-8"><CircleDollarSign className="h-7 w-7 text-orange-300" /><p className="mt-6 text-xs font-black uppercase tracking-[.16em] text-orange-200">Market information</p><h2 className="mt-3 text-2xl font-black">USD display, one clear checkout rule.</h2><p className="mt-4 text-sm leading-7 text-slate-300">US visitors can use USD display pricing for planning and comparison. The final amount follows the established checkout system, where INR remains authoritative.</p><div className="mt-6 border-t border-white/10 pt-5 text-sm"><p className="font-black text-white">Before you continue</p><p className="mt-2 leading-6 text-slate-400">Review the current price, selected service details and final checkout amount. USD display does not create a separate payment method or local checkout.</p></div></aside></div></section>

      <section className="border-y border-white/10 bg-[#10131a] px-5 py-16 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">How ordering works</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">A clear path from discovery to dashboard.</h2><ol className="mt-9 grid gap-0 border-l border-orange-400/50 md:grid-cols-3 md:border-l-0 md:border-t">{["Choose a platform and service", "Review the service details", "Add the required public profile, post, video or channel link", "Review the price", "Continue to secure checkout", "Track from your account dashboard"].map((step, index) => <li key={step} className="relative min-h-24 border-b border-white/10 py-4 pl-6 md:border-b-0 md:border-r md:px-5 md:pt-7"><span className="absolute -left-[9px] top-5 grid h-[17px] w-[17px] place-items-center rounded-full border border-orange-300 bg-[#10131a] text-[8px] font-black text-orange-200 md:-top-[9px] md:left-5">{String(index + 1).padStart(2, "0")}</span><p className="text-sm font-bold leading-6">{step}</p></li>)}</ol></div></section>

      <section className="px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.8fr_1.2fr]"><aside className="border border-white/15 bg-[#12151d] p-6 sm:p-8"><LockKeyhole className="h-6 w-6 text-orange-300" /><h2 className="mt-5 text-2xl font-black">Keep account access private.</h2><p className="mt-4 text-base font-bold leading-7 text-white">SocialRUSH never asks for your social-media password, OTP, or recovery code.</p><p className="mt-4 text-sm leading-7 text-slate-400">Use the relevant public link. Service-specific delivery information and refill details, where applicable, are shown before checkout.</p><Link href="/trust" className="mt-6 inline-flex items-center gap-2 text-sm font-black text-orange-200">Read safety guidance <ArrowRight className="h-4 w-4" /></Link></aside><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">United States market FAQ</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Useful details before you start.</h2><div className="mt-6 divide-y divide-white/10 border-y border-white/10">{faqs.map(([question, answer]) => <details key={question} className="group py-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-black"><span>{question}</span><ChevronRight className="h-4 w-4 shrink-0 text-orange-300 transition group-open:rotate-90" /></summary><p className="max-w-2xl pt-3 text-sm leading-7 text-slate-300">{answer}</p></details>)}</div></div></div></section>

      <section className="border-t border-white/10 bg-[#0e1118] px-5 py-12 sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">Explore SocialRUSH</p><h2 className="mt-3 text-2xl font-black">More ways to plan a campaign.</h2><div className="mt-5 flex flex-wrap gap-x-5 gap-y-3 text-sm font-bold text-slate-300">{[["All services", "/services"], ["Packages", "/packages"], ["For creators", "/for-creators"], ["For brands", "/for-brands"], ["For agencies", "/for-agencies"], ["Instagram growth guide", "/instagram-growth-india"], ["YouTube growth guide", "/youtube-growth-india"]].map(([label, href]) => <Link key={href} href={href} className="hover:text-orange-200">{label}</Link>)}</div></div><nav aria-label="International markets" className="border-l border-white/10 pl-0 lg:pl-8"><p className="text-xs font-black uppercase tracking-[.16em] text-slate-500">Other markets</p><div className="mt-3 flex flex-wrap gap-2">{[["UK", "/uk"], ["Canada", "/ca"], ["Australia", "/au"], ["UAE", "/ae"], ["Singapore", "/sg"]].map(([label, href]) => <Link key={href} href={href} className="rounded-full border border-white/15 px-3 py-1.5 text-xs font-bold text-slate-300 transition hover:border-orange-300 hover:text-orange-200">{label}</Link>)}</div></nav></div></section>
    </main>
  </PublicShell>;
}
