"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Check, ChevronDown, ChevronUp, Minus, Pause, Play, Plus, ShieldCheck } from "lucide-react";
import type { LiveServiceFacts } from "@/lib/seo/live-service";

const previewComments = [
  ["@creatorhub", "Really enjoyed this one 🔥", "2 min ago"], ["@learnwithme", "Super clear explanation 👏", "5 min ago"], ["@dailywatch", "Nice video!", "8 min ago"], ["@contentstudio", "Great work 🙌", "12 min ago"], ["@viewer_notes", "Loved this part.", "16 min ago"],
] as const;
const faqs = [
  ["Do I need my YouTube password?", "No. Only the public YouTube video URL is required. Never share a password, OTP, or recovery code."],
  ["Which YouTube URL should I submit?", "Submit the exact public video URL. Standard watch links, youtu.be links, and Shorts links are accepted by the existing order validation."],
  ["Can I use a channel URL?", "No. This service requires a specific public video or Short URL, not a channel URL."],
  ["How are YouTube Comments priced?", "The live rate and calculated total are shown before you continue to secure checkout."],
  ["Can I track my order?", "Yes. After checkout, your SocialRUSH dashboard keeps your order status and record together."],
] as const;
function rupees(value: number) { return `₹${value.toLocaleString("en-IN", { maximumFractionDigits: 2 })}`; }
function validLink(value: string) { try { const u = new URL(value); return ["youtube.com", "www.youtube.com", "m.youtube.com", "youtu.be"].includes(u.hostname.toLowerCase()) && (/^\/[A-Za-z0-9_-]+\/?$/.test(u.pathname) || /\/(watch|shorts)\//.test(u.pathname)); } catch { return false; } }

export default function YouTubeCommentsWorkspace({ live }: { live: LiveServiceFacts | null }) {
  const available = Boolean(live?.available && live.rate > 0);
  const min = live?.min ?? 0, max = live?.max ?? 0;
  const [quantity, setQuantity] = useState(min || 10);
  const [url, setUrl] = useState(""); const [playing, setPlaying] = useState(false); const [faq, setFaq] = useState<number | null>(null);
  const validQuantity = Number.isInteger(quantity) && quantity >= min && quantity <= max;
  const validUrl = validLink(url); const total = live ? Math.round(quantity * live.rate * 100 / 1000) / 100 : 0;
  const presets = useMemo(() => [...new Set([10,25,50,100,250,500,min,max].filter(n => n >= min && n <= max))].slice(0, 6), [min,max]);
  const orderHref = available && validQuantity && validUrl ? `/dashboard/new-order?platform=youtube&service=youtube-comments&prefill=1&quantity=${quantity}&link=${encodeURIComponent(url)}` : "/dashboard/new-order?platform=youtube&service=youtube-comments";
  const update = (value: number) => setQuantity(Math.max(min, Math.min(max, Math.floor(value) || min)));
  return <main className="overflow-hidden bg-[#090a0e] text-[#f8f6f1]">
    <section className="relative border-b border-white/10 bg-[radial-gradient(circle_at_80%_12%,rgba(212,48,38,.24),transparent_28%),radial-gradient(circle_at_12%_40%,rgba(245,145,30,.16),transparent_30%)] px-4 pb-14 pt-12 sm:px-6 lg:px-8 lg:pb-20">
      <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div>
        <p className="text-xs font-black tracking-[.18em] text-orange-300">YOUTUBE COMMENTS SERVICE INDIA</p><h1 className="mt-5 text-4xl font-black leading-[1.02] tracking-[-.05em] sm:text-6xl">Buy YouTube Comments in India</h1>
        <p className="mt-6 max-w-xl text-base leading-7 text-slate-300 sm:text-lg">For Indian creators, brands and businesses, configure comments for an eligible public YouTube video with live INR pricing, clear quantity controls and dashboard tracking. Submit the video link only—no YouTube password is required.</p>
        <div className="mt-8 flex flex-wrap gap-3"><a href="#order" className="inline-flex min-h-12 items-center rounded-xl bg-gradient-to-r from-[#ff7800] to-[#ffb000] px-5 font-black text-white">Start Your Order</a><Link href="/services?platform=youtube" className="inline-flex min-h-12 items-center rounded-xl border border-white/15 px-5 font-bold">Explore YouTube Services</Link><a href="https://wa.me/918860330771" className="inline-flex min-h-12 items-center rounded-xl border border-white/15 px-5 font-bold">WhatsApp</a></div>
        <div className="mt-8 flex flex-wrap gap-x-5 gap-y-3 text-xs font-bold text-slate-200">{["Public Video Link","No Password Required","Transparent Pricing","Order Tracking"].map(x=><span key={x} className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-orange-300"/>{x}</span>)}</div></div>
        <CampaignCard live={live} quantity={quantity} total={total} /></div>
    </section>
    <section id="order" className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1fr_360px]"><div className="rounded-[2rem] border border-white/10 bg-[#12141b] p-5 sm:p-8"><p className="text-xs font-black tracking-[.17em] text-red-300">ORDER CONFIGURATION</p><h2 className="mt-3 text-3xl font-black">Build Your YouTube Comments Order</h2><p className="mt-2 text-sm leading-6 text-slate-400">Choose your comment quantity and review your total before continuing.</p>
        {!available ? <p className="mt-6 rounded-xl border border-amber-400/30 bg-amber-400/10 p-4 text-sm text-amber-100">This service is currently unavailable. You can review available YouTube services in the dashboard.</p> : <><div className="mt-7"><label htmlFor="quantity" className="text-sm font-black">Comment quantity</label><div className="mt-3 flex items-center gap-2"><button aria-label="Decrease quantity" onClick={()=>update(quantity-1)} className="grid h-12 w-12 place-items-center rounded-xl border border-white/15"><Minus className="h-4 w-4"/></button><input id="quantity" value={quantity} onChange={e=>setQuantity(Number(e.target.value.replace(/\D/g,"")))} inputMode="numeric" className="h-12 min-w-0 flex-1 rounded-xl border border-orange-400/40 bg-[#090a0e] px-4 text-center text-lg font-black outline-none focus:ring-4 focus:ring-orange-400/20"/><button aria-label="Increase quantity" onClick={()=>update(quantity+1)} className="grid h-12 w-12 place-items-center rounded-xl border border-white/15"><Plus className="h-4 w-4"/></button></div><p className="mt-2 text-xs text-slate-400">Min {min.toLocaleString("en-IN")} · Max {max.toLocaleString("en-IN")} · Whole numbers only</p><div className="mt-3 flex flex-wrap gap-2">{presets.map(n=><button key={n} onClick={()=>update(n)} className={`min-h-10 rounded-full border px-4 text-xs font-black ${quantity===n?"border-orange-400 bg-orange-400/15 text-orange-200":"border-white/15 text-slate-300"}`}>{n}</button>)}</div></div>
          <div className="mt-7"><label htmlFor="video-url" className="text-sm font-black">Public YouTube Video URL</label><input id="video-url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.youtube.com/watch?v=..." className="mt-3 h-12 w-full rounded-xl border border-orange-400/40 bg-[#090a0e] px-4 text-sm outline-none focus:ring-4 focus:ring-orange-400/20"/>{url && <p aria-live="polite" className={`mt-2 text-xs font-bold ${validUrl?"text-emerald-300":"text-red-300"}`}>{validUrl?"✓ Valid public YouTube video link":"Enter a valid public YouTube video or Short link."}</p>}</div></>}</div>
      <aside className="h-fit rounded-[2rem] border border-orange-400/25 bg-[#15120e] p-6 lg:sticky lg:top-24"><p className="text-xs font-black tracking-[.16em] text-orange-300">LIVE ORDER SUMMARY</p><h2 className="mt-3 text-xl font-black">YouTube Comments</h2><dl className="mt-6 space-y-4 text-sm">{[["Quantity",validQuantity?quantity.toLocaleString("en-IN"):"Choose a valid quantity"],["Live Rate",live?`${rupees(live.rate)} / 1K`:"Unavailable"],["Delivery",live?.deliveryTime??"Check dashboard"],["Refill / support",live?.refillPolicy??"Check dashboard"],["Video Link Status",url?(validUrl?"Ready":"Needs a video URL"):"Awaiting link"],["Availability",available?"Available":"Unavailable"]].map(([a,b])=><div key={a} className="grid gap-1 border-b border-white/10 pb-3"><dt className="text-slate-400">{a}</dt><dd className="font-bold">{b}</dd></div>)}</dl><div className="mt-6 flex items-end justify-between"><span className="font-bold text-slate-300">TOTAL</span><strong className="text-3xl">{validQuantity&&available?rupees(total):"—"}</strong></div><Link href={orderHref} className="mt-6 flex min-h-12 items-center justify-center rounded-xl bg-gradient-to-r from-[#ff7800] to-[#ffb000] px-4 text-sm font-black">Continue to Secure Order</Link><p className="mt-3 text-center text-[11px] text-slate-400">Public video only • Secure checkout</p></aside></div></section>
    <section className="border-y border-white/10 bg-[#0e1016] px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.15fr_.85fr]"><VideoPreview playing={playing} setPlaying={setPlaying}/><div className="rounded-[2rem] border border-white/10 bg-[#151821] p-6"><p className="text-xs font-black tracking-[.16em] text-red-300">INTERACTIVE UI PREVIEW</p><h2 className="mt-3 text-2xl font-black">Comment activity, presented clearly</h2><div className="mt-5 flex items-center gap-3 text-xs font-bold text-slate-400"><span>Video</span><span>↓</span><span>Comment section</span><span>↓</span><span>Tracking</span></div><div className="mt-6 space-y-4">{previewComments.slice(0,playing?5:3).map(([name,copy,time],i)=><article key={name} className="flex gap-3"><span className={`mt-1 grid h-9 w-9 shrink-0 place-items-center rounded-full text-xs font-black ${i%2?"bg-orange-500":"bg-red-500"}`}>{name.slice(1,2).toUpperCase()}</span><div><p className="text-sm font-bold">{name} <span className="ml-2 text-xs font-normal text-slate-500">{time}</span></p><p className="mt-1 text-sm text-slate-200">“{copy}”</p><p className="mt-2 text-xs text-slate-500">♡ &nbsp; Reply {i===1?" · View replies":""}</p></div></article>)}</div><button onClick={()=>setPlaying(!playing)} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/15 px-4 text-sm font-bold">{playing?<Pause className="h-4 w-4"/>:<Play className="h-4 w-4"/>}{playing?"Pause preview":"Play preview"}</button></div></div></section>
    <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black tracking-[.16em] text-orange-300">USE THE CORRECT YOUTUBE LINK</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["CHANNEL","youtube.com/@channel","Not accepted"],["VIDEO","youtube.com/watch?v=...","Accepted"],["SHORT","youtube.com/shorts/...","Accepted"]].map(([a,b,c])=><div key={a} className={`rounded-2xl border p-5 ${c==="Accepted"?"border-emerald-400/30 bg-emerald-400/5":"border-white/10 bg-[#12141b]"}`}><p className="text-xs font-black text-orange-200">{a}</p><p className="mt-3 break-all font-mono text-sm">{b}</p><p className={`mt-3 text-xs font-bold ${c==="Accepted"?"text-emerald-300":"text-slate-500"}`}>{c}</p></div>)}</div></div></section>
    <section className="bg-[#12141b] px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-black">How it works</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Choose YouTube Comments","Select Quantity","Paste Public Video URL","Review Live Total","Continue to Secure Checkout","Track Your Order"].map((x,i)=><div key={x} className="rounded-2xl border border-white/10 bg-[#090a0e] p-5"><span className="text-xs font-black text-orange-300">0{i+1}</span><p className="mt-3 font-bold">{x}</p></div>)}</div></div></section>
    <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-[2rem] border border-emerald-400/25 bg-emerald-400/5 p-6"><p className="text-xs font-black tracking-[.16em] text-emerald-300">ORDER SAFELY</p><h2 className="mt-3 text-2xl font-black">Only a public video link is needed.</h2><div className="mt-5 space-y-3 text-sm">{[["Public YouTube Video URL","Required"],["Google / YouTube Password","Not required"],["OTP","Never share"],["Recovery Code","Never share"]].map(([a,b],i)=><div key={a} className="flex items-center justify-between gap-3 border-b border-white/10 pb-3"><span>{a}</span><strong className={i===0?"text-emerald-300":"text-red-300"}>{i===0?"✓":"×"} {b}</strong></div>)}</div></div><div className="rounded-[2rem] border border-white/10 bg-[#12141b] p-6"><p className="text-xs font-black tracking-[.16em] text-orange-300">RELATED YOUTUBE SERVICES</p><h2 className="mt-3 text-2xl font-black">Plan the right campaign surface</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["YouTube Subscribers","/youtube-subscribers","Channel audience count"],["YouTube Views","/youtube-views","Video view count"],["YouTube Likes","/youtube-likes","Video engagement count"],["YouTube Watch Hours","/buy-youtube-watch-hours-india","Watch-time service"]].map(([name,href,copy])=><Link key={name} href={href} className="rounded-xl border border-white/10 bg-white/[.03] p-4 transition hover:border-orange-400/50"><p className="font-bold">{name}</p><p className="mt-1 text-xs text-slate-400">{copy}</p></Link>)}</div></div></div></section>
    <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-black">Questions, answered</h2><div className="mt-6 divide-y divide-white/10 rounded-2xl border border-white/10 bg-[#12141b]">{faqs.map(([q,a],i)=><div key={q}><button aria-expanded={faq===i} onClick={()=>setFaq(faq===i?null:i)} className="flex min-h-14 w-full items-center justify-between gap-5 px-5 text-left font-bold">{q}{faq===i?<ChevronUp className="h-4 w-4 shrink-0"/>:<ChevronDown className="h-4 w-4 shrink-0"/>}</button>{faq===i&&<p className="px-5 pb-5 text-sm leading-6 text-slate-300">{a}</p>}</div>)}</div></div></section>
  </main>;
}
function CampaignCard({live,quantity,total}:{live:LiveServiceFacts|null;quantity:number;total:number}){return <div className="rounded-[2rem] border border-white/15 bg-[#12141b]/95 p-5 shadow-2xl sm:p-6"><div className="flex items-center justify-between"><span className="inline-flex items-center gap-2 text-xs font-black text-red-300"><span className="grid h-5 w-5 place-items-center rounded-md bg-red-600 text-[10px] text-white">▶</span>LIVE SERVICE</span><span className="rounded-full bg-white/5 px-3 py-1 text-[10px] font-bold text-slate-400">UI Preview</span></div><div className="mt-5 overflow-hidden rounded-2xl bg-[#20242d]"><div className="relative aspect-video bg-[linear-gradient(130deg,#a93922,#24121c_45%,#f28c25)] p-5"><span className="rounded bg-black/75 px-2 py-1 text-xs font-bold">09:42</span><div className="absolute bottom-5"><p className="text-2xl font-black">Make space for ideas.</p><p className="text-sm text-orange-100">Creator Studio · Episode 12</p></div></div><div className="p-4"><p className="font-bold">How a simple workflow stays creative</p><p className="mt-1 text-xs text-slate-400">Your Channel · 24.8K subscribers</p><div className="mt-4 flex gap-2 text-xs text-slate-400"><span>♡ 1.2K</span><span>↗ Share</span><span>▣ Comments</span></div></div></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><div className="rounded-xl bg-white/5 p-3"><p className="text-slate-400">Starting from</p><strong className="mt-1 block">{live?`${rupees(live.rate)} / 1K`:"Live catalog unavailable"}</strong></div><div className="rounded-xl bg-white/5 p-3"><p className="text-slate-400">Selected quantity</p><strong className="mt-1 block">{quantity.toLocaleString("en-IN")}</strong></div><div className="rounded-xl bg-white/5 p-3"><p className="text-slate-400">Delivery</p><strong className="mt-1 block">{live?.deliveryTime??"Check service"}</strong></div><div className="rounded-xl bg-white/5 p-3"><p className="text-slate-400">Estimated total</p><strong className="mt-1 block">{live?rupees(total):"—"}</strong></div></div><p className="mt-4 flex items-center gap-2 text-xs font-bold text-emerald-300"><ShieldCheck className="h-4 w-4"/>Public YouTube Video URL · secure order state</p></div>}
function VideoPreview({playing,setPlaying}:{playing:boolean;setPlaying:(value:boolean)=>void}){return <div className="overflow-hidden rounded-[2rem] border border-white/10 bg-[#151821]"><div className="aspect-video bg-[linear-gradient(135deg,#263951,#0e1727_48%,#df5a29)] p-6"><p className="text-xs font-black tracking-[.16em] text-orange-200">YOUR CHANNEL</p><p className="mt-16 max-w-sm text-3xl font-black leading-tight">Build better videos, one thoughtful choice at a time.</p></div><div className="p-5"><p className="font-bold">A practical creative workflow for this week</p><p className="mt-2 text-sm text-slate-400">Your Channel · public video preview</p><div className="mt-4 flex gap-5 text-sm text-slate-300"><span>♡ 1.2K</span><span>↗ Share</span><span>▣ 24 comments</span></div><button onClick={()=>setPlaying(!playing)} className="mt-5 inline-flex min-h-10 items-center gap-2 rounded-lg bg-white/10 px-4 text-sm font-bold">{playing?<Pause className="h-4 w-4"/>:<Play className="h-4 w-4"/>} {playing?"Pause":"Preview comments"}</button></div></div>}
