"use client";

import { AnimatePresence, motion } from "framer-motion";
import { useCallback, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Ticket = { id: string; subject: string; status: string; created_at: string };
type Message = { id: string; sender_id: string; message: string; created_at: string };
const categories = ["Order issue","Payment issue","Refill request","Account issue","Service question"];
const statusStyle: Record<string,string> = { open: "bg-blue-50 text-blue-700", answered: "bg-emerald-50 text-emerald-700", waiting: "bg-amber-50 text-amber-700", closed: "bg-slate-100 text-slate-600" };
const parseSubject = (subject: string) => { const match = subject.match(/^\[([^\]]+)]\s*(.*)$/); return { category: match?.[1] || "General", title: match?.[2] || subject }; };

export default function SupportPage() {
  const [tickets, setTickets] = useState<Ticket[]>([]); const [messages, setMessages] = useState<Message[]>([]); const [activeId, setActiveId] = useState(""); const [userId, setUserId] = useState(""); const [loading, setLoading] = useState(true); const [creating, setCreating] = useState(false); const [toast, setToast] = useState("");
  const active = tickets.find((item) => item.id === activeId);
  const loadTickets = useCallback(async () => { const response = await fetch("/api/support/tickets"); const payload = await response.json() as { data?: Ticket[] }; const rows = payload.data ?? []; setTickets(rows); setActiveId((current) => current || rows[0]?.id || ""); setLoading(false); }, []);
  useEffect(() => { void loadTickets(); void createClient().auth.getUser().then(({ data }) => setUserId(data.user?.id || "")); }, [loadTickets]);
  useEffect(() => { if (!activeId) { setMessages([]); return; } const supabase = createClient(); void supabase.from("support_messages").select("id, sender_id, message, created_at").eq("ticket_id", activeId).order("created_at").then(({ data }) => setMessages((data as Message[] | null) ?? [])); }, [activeId]);
  async function createTicket(formData: FormData) { const category = String(formData.get("category")); const subject = String(formData.get("subject")); const message = String(formData.get("message")); const response = await fetch("/api/support/tickets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subject: `[${category}] ${subject}`, message }) }); if (response.ok) { setCreating(false); setToast("Ticket created successfully"); await loadTickets(); window.setTimeout(() => setToast(""), 2500); } }
  async function sendReply(formData: FormData) { const message = String(formData.get("message") || "").trim(); if (!activeId || !userId || !message) return; const supabase = createClient(); await supabase.from("support_messages").insert({ ticket_id: activeId, sender_id: userId, message }); await supabase.from("support_tickets").update({ status: "open" }).eq("id", activeId); const { data } = await supabase.from("support_messages").select("id, sender_id, message, created_at").eq("ticket_id", activeId).order("created_at"); setMessages((data as Message[] | null) ?? []); await loadTickets(); }

  return <main className="min-h-[calc(100vh-5rem)] bg-[linear-gradient(180deg,#f8faff,#f3f6fb)] p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1550px]"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-600">Customer care</span><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#07152f]">Support Center</h1><p className="mt-2 text-sm text-slate-500">Get professional help with campaigns, payments, refills, and your account.</p></div><button onClick={() => setCreating(true)} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-blue-600/20">+ Create ticket</button></div>
    <section className="mt-7 grid gap-4 md:grid-cols-3">{[["Order & delivery","Track delays, status updates, and campaign delivery.","Order issue"],["Payments & wallet","Resolve funding, transaction, and wallet questions.","Payment issue"],["Refills & service","Request eligible coverage or service guidance.","Refill request"]].map(([title,text,category]) => <button key={title} onClick={() => setCreating(true)} className="rounded-2xl border border-white bg-white/80 p-5 text-left shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 text-blue-600">?</span><h2 className="mt-4 text-sm font-bold">{title}</h2><p className="mt-2 text-xs leading-6 text-slate-500">{text}</p><p className="mt-4 text-[9px] font-bold uppercase tracking-wider text-blue-600">{category} →</p></button>)}</section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[380px_1fr]"><aside className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><div className="flex justify-between"><div><h2 className="text-sm font-bold">Your tickets</h2><p className="mt-1 text-[10px] text-slate-400">{tickets.length} conversations</p></div><span className="h-2 w-2 rounded-full bg-emerald-400"/></div></div><div className="max-h-[650px] divide-y divide-slate-100 overflow-y-auto">{loading ? <div className="space-y-3 p-4">{[1,2,3].map((item) => <div key={item} className="h-24 animate-pulse rounded-xl bg-slate-100"/>)}</div> : tickets.map((ticket) => { const parsed = parseSubject(ticket.subject); return <button key={ticket.id} onClick={() => setActiveId(ticket.id)} className={`w-full p-5 text-left transition ${activeId === ticket.id ? "bg-blue-50" : "hover:bg-slate-50"}`}><div className="flex items-center justify-between"><span className="text-[9px] font-bold text-blue-600">#{ticket.id.slice(0,8).toUpperCase()}</span><span className={`rounded-full px-2 py-1 text-[9px] font-bold capitalize ${statusStyle[ticket.status] || statusStyle.open}`}>{ticket.status}</span></div><p className="mt-3 truncate text-xs font-bold">{parsed.title}</p><div className="mt-2 flex justify-between text-[9px] text-slate-400"><span>{parsed.category}</span><span>{new Date(ticket.created_at).toLocaleDateString("en-IN")}</span></div></button>; })}{!loading && tickets.length === 0 && <div className="p-10 text-center"><p className="text-sm font-bold">No tickets yet</p><p className="mt-1 text-xs text-slate-400">Create a ticket whenever you need help.</p></div>}</div></aside>
      <section className="flex min-h-[620px] flex-col overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{active ? <><header className="flex items-start justify-between border-b border-slate-100 p-5"><div><div className="flex items-center gap-2"><span className="text-[9px] font-bold text-blue-600">#{active.id.slice(0,8).toUpperCase()}</span><span className={`rounded-full px-2 py-1 text-[9px] font-bold capitalize ${statusStyle[active.status] || statusStyle.open}`}>{active.status}</span></div><h2 className="mt-2 text-sm font-bold">{parseSubject(active.subject).title}</h2><p className="mt-1 text-[10px] text-slate-400">{parseSubject(active.subject).category}</p></div><button onClick={async () => { await createClient().from("support_tickets").update({ status: "closed" }).eq("id", active.id); await loadTickets(); }} className="rounded-lg border border-slate-200 px-3 py-2 text-[9px] font-bold text-slate-500">Close ticket</button></header><div className="flex-1 space-y-4 overflow-y-auto bg-slate-50/60 p-5 sm:p-7">{messages.map((message) => { const mine = message.sender_id === userId; return <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} key={message.id} className={`flex ${mine ? "justify-end" : "justify-start"}`}><div className={`max-w-[80%] rounded-2xl p-4 text-xs leading-6 shadow-sm ${mine ? "rounded-br-sm bg-blue-600 text-white" : "rounded-bl-sm bg-white text-slate-600"}`}><p>{message.message}</p><p className={`mt-2 text-[8px] ${mine ? "text-blue-200" : "text-slate-400"}`}>{new Date(message.created_at).toLocaleString("en-IN")}</p></div></motion.div>; })}{messages.length === 0 && <p className="py-14 text-center text-xs text-slate-400">No messages yet.</p>}</div>{active.status !== "closed" && <form action={sendReply} className="border-t border-slate-100 p-4"><textarea name="message" required rows={2} className="w-full resize-none rounded-xl border border-slate-200 px-4 py-3 text-xs outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10" placeholder="Write your message..."/><div className="mt-3 flex items-center justify-between"><label className="cursor-pointer rounded-lg border border-dashed border-slate-300 px-3 py-2 text-[9px] font-bold text-slate-500"><input type="file" accept="image/*" className="hidden"/>📎 Attach screenshot</label><button className="rounded-xl bg-blue-600 px-5 py-2.5 text-xs font-bold text-white">Send message</button></div></form>}</> : <div className="grid flex-1 place-items-center p-8 text-center"><div><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-xl text-blue-600">?</span><h2 className="mt-4 text-sm font-bold">Select a conversation</h2><p className="mt-2 text-xs text-slate-400">Choose a ticket or create a new one.</p></div></div>}</section></div></div>
    <AnimatePresence>{creating && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4 backdrop-blur-sm"><motion.div initial={{ scale: .95, y: 16 }} animate={{ scale: 1, y: 0 }} className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-[9px] font-bold uppercase tracking-wider text-blue-600">New support request</p><h2 className="mt-2 text-xl font-bold">Create a ticket</h2></div><button onClick={() => setCreating(false)} className="grid h-8 w-8 place-items-center rounded-lg bg-slate-100 text-lg">×</button></div><form action={createTicket} className="mt-6 space-y-4"><label className="block text-[10px] font-bold uppercase tracking-wider text-slate-500">Category<select name="category" required className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-xs">{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label className="block text-[10px] font-bold uppercase tracking-wider text-slate-500">Subject<input name="subject" required minLength={3} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-xs" placeholder="Briefly describe the issue"/></label><label className="block text-[10px] font-bold uppercase tracking-wider text-slate-500">Message<textarea name="message" required rows={5} className="mt-2 w-full resize-none rounded-xl border border-slate-200 px-4 py-3 text-xs" placeholder="Include relevant order or transaction details..."/></label><label className="block cursor-pointer rounded-xl border border-dashed border-slate-300 p-4 text-center text-[10px] font-semibold text-slate-500"><input type="file" accept="image/*" className="hidden"/>📎 Attach screenshot or payment proof <span className="block pt-1 text-[8px] text-slate-400">Attachment upload coming soon</span></label><button className="w-full rounded-xl bg-blue-600 py-3 text-xs font-bold text-white">Submit support ticket</button></form></motion.div></motion.div>}</AnimatePresence>{toast && <motion.div initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} className="fixed bottom-6 right-6 z-[60] rounded-xl bg-emerald-600 px-5 py-3 text-xs font-bold text-white shadow-xl">✓ {toast}</motion.div>}</main>;
}
