export interface BigPackage {
  packageId: string;
  platform: "Instagram" | "YouTube" | "LinkedIn" | "Facebook" | "Telegram" | "TikTok" | "X";
  service: "followers" | "subscribers" | "likes" | "views" | "members";
  title: string;
  quantity: number;
  quantityLabel: string;
  basePriceINR: number;
  discountBadge?: string; // e.g., "Save 10%", "Best Value", "Agency Pack"
  deliveryTime: string; // e.g., "2–5 days"
  description: string;
  bestFor: string;
}

export const bigPackages: BigPackage[] = [
  // Instagram Followers
  {
    packageId: "ig-followers-5k",
    platform: "Instagram",
    service: "followers",
    title: "5K Followers",
    quantity: 5000,
    quantityLabel: "5,000",
    basePriceINR: 2499,
    discountBadge: "Save 10%",
    deliveryTime: "2–5 days",
    description: "Start a focused Instagram follower package with 5,000 included followers.",
    bestFor: "Creators starting growth campaigns",
  },
  {
    packageId: "ig-followers-10k",
    platform: "Instagram",
    service: "followers",
    title: "10K Followers",
    quantity: 10000,
    quantityLabel: "10,000",
    basePriceINR: 4499,
    discountBadge: "Save 15%",
    deliveryTime: "2–5 days",
    description: "Reach 10,000 followers milestone with premium growth service.",
    bestFor: "Growing Instagram pages",
  },
  {
    packageId: "ig-followers-20k",
    platform: "Instagram",
    service: "followers",
    title: "20K Followers",
    quantity: 20000,
    quantityLabel: "20,000",
    basePriceINR: 8499,
    discountBadge: "Best Value",
    deliveryTime: "4–10 days",
    description: "Major profile expansion with 20,000 followers.",
    bestFor: "Brands and influencers",
  },
  {
    packageId: "ig-followers-50k",
    platform: "Instagram",
    service: "followers",
    title: "50K Followers",
    quantity: 50000,
    quantityLabel: "50,000",
    basePriceINR: 19999,
    discountBadge: "Agency Pack",
    deliveryTime: "7–14 days",
    description: "Large Instagram follower package for established pages and agency campaigns.",
    bestFor: "Agencies and established brands",
  },

  // Instagram Likes
  {
    packageId: "ig-likes-5k",
    platform: "Instagram",
    service: "likes",
    title: "5K Likes",
    quantity: 5000,
    quantityLabel: "5,000",
    basePriceINR: 999,
    discountBadge: "Save 10%",
    deliveryTime: "1–3 days",
    description: "Boost post engagement with 5,000 likes.",
    bestFor: "Content creators",
  },
  {
    packageId: "ig-likes-10k",
    platform: "Instagram",
    service: "likes",
    title: "10K Likes",
    quantity: 10000,
    quantityLabel: "10,000",
    basePriceINR: 1799,
    discountBadge: "Save 15%",
    deliveryTime: "1–3 days",
    description: "Significant engagement boost with 10,000 likes.",
    bestFor: "Regular posts and reels",
  },
  {
    packageId: "ig-likes-20k",
    platform: "Instagram",
    service: "likes",
    title: "20K Likes",
    quantity: 20000,
    quantityLabel: "20,000",
    basePriceINR: 3299,
    discountBadge: "Best Value",
    deliveryTime: "2–5 days",
    description: "Heavy engagement support with 20,000 likes.",
    bestFor: "Popular posts and campaigns",
  },
  {
    packageId: "ig-likes-50k",
    platform: "Instagram",
    service: "likes",
    title: "50K Likes",
    quantity: 50000,
    quantityLabel: "50,000",
    basePriceINR: 7499,
    discountBadge: "Agency Pack",
    deliveryTime: "5–10 days",
    description: "Maximum engagement with 50,000 likes.",
    bestFor: "Viral content and campaigns",
  },

  // Instagram Views
  {
    packageId: "ig-views-50k",
    platform: "Instagram",
    service: "views",
    title: "50K Views",
    quantity: 50000,
    quantityLabel: "50,000",
    basePriceINR: 999,
    discountBadge: "Save 10%",
    deliveryTime: "1–3 days",
    description: "Boost reel and story visibility with 50,000 views.",
    bestFor: "Short-form content",
  },
  {
    packageId: "ig-views-100k",
    platform: "Instagram",
    service: "views",
    title: "100K Views",
    quantity: 100000,
    quantityLabel: "100,000",
    basePriceINR: 1799,
    discountBadge: "Best Value",
    deliveryTime: "2–5 days",
    description: "Major visibility expansion with 100,000 views.",
    bestFor: "Growing content reach",
  },
  {
    packageId: "ig-views-500k",
    platform: "Instagram",
    service: "views",
    title: "500K Views",
    quantity: 500000,
    quantityLabel: "500,000",
    basePriceINR: 7999,
    discountBadge: "Scale Pack",
    deliveryTime: "5–10 days",
    description: "Massive reach with 500,000 views.",
    bestFor: "Viral content strategy",
  },
  {
    packageId: "ig-views-1m",
    platform: "Instagram",
    service: "views",
    title: "1M Views",
    quantity: 1000000,
    quantityLabel: "1,000,000",
    basePriceINR: 14999,
    discountBadge: "Agency Pack",
    deliveryTime: "7–15 days",
    description: "Million-view milestone for premium content.",
    bestFor: "High-volume campaigns",
  },

  // YouTube Subscribers
  {
    packageId: "yt-subscribers-1k",
    platform: "YouTube",
    service: "subscribers",
    title: "1K Subscribers",
    quantity: 1000,
    quantityLabel: "1,000",
    basePriceINR: 3999,
    deliveryTime: "3–7 days",
    description: "Reach 1,000 YouTube subscribers milestone.",
    bestFor: "New YouTube channels",
  },
  {
    packageId: "yt-subscribers-2k",
    platform: "YouTube",
    service: "subscribers",
    title: "2K Subscribers",
    quantity: 2000,
    quantityLabel: "2,000",
    basePriceINR: 7499,
    discountBadge: "Save 10%",
    deliveryTime: "4–10 days",
    description: "Double subscriber growth with 2,000 subscribers.",
    bestFor: "Growing channels",
  },
  {
    packageId: "yt-subscribers-5k",
    platform: "YouTube",
    service: "subscribers",
    title: "5K Subscribers",
    quantity: 5000,
    quantityLabel: "5,000",
    basePriceINR: 17999,
    discountBadge: "Best Value",
    deliveryTime: "5–12 days",
    description: "Serious channel authority with 5,000 subscribers.",
    bestFor: "Content creators",
  },
  {
    packageId: "yt-subscribers-10k",
    platform: "YouTube",
    service: "subscribers",
    title: "10K Subscribers",
    quantity: 10000,
    quantityLabel: "10,000",
    basePriceINR: 34999,
    discountBadge: "Agency Pack",
    deliveryTime: "7–14 days",
    description: "Achieve 10,000+ subscribers for established authority.",
    bestFor: "Agencies and brands",
  },

  // YouTube Likes
  {
    packageId: "yt-likes-5k",
    platform: "YouTube",
    service: "likes",
    title: "5K Likes",
    quantity: 5000,
    quantityLabel: "5,000",
    basePriceINR: 1999,
    deliveryTime: "2–5 days",
    description: "Boost video engagement with 5,000 likes.",
    bestFor: "Video content creators",
  },
  {
    packageId: "yt-likes-10k",
    platform: "YouTube",
    service: "likes",
    title: "10K Likes",
    quantity: 10000,
    quantityLabel: "10,000",
    basePriceINR: 3499,
    discountBadge: "Save 10%",
    deliveryTime: "3–7 days",
    description: "Significant engagement boost with 10,000 likes.",
    bestFor: "Popular videos",
  },
  {
    packageId: "yt-likes-20k",
    platform: "YouTube",
    service: "likes",
    title: "20K Likes",
    quantity: 20000,
    quantityLabel: "20,000",
    basePriceINR: 6499,
    discountBadge: "Best Value",
    deliveryTime: "4–10 days",
    description: "Heavy engagement with 20,000 likes.",
    bestFor: "Content campaigns",
  },
  {
    packageId: "yt-likes-50k",
    platform: "YouTube",
    service: "likes",
    title: "50K Likes",
    quantity: 50000,
    quantityLabel: "50,000",
    basePriceINR: 14999,
    discountBadge: "Agency Pack",
    deliveryTime: "7–12 days",
    description: "Premium engagement with 50,000 likes.",
    bestFor: "Major campaigns",
  },

  // YouTube Views
  {
    packageId: "yt-views-10k",
    platform: "YouTube",
    service: "views",
    title: "10K Views",
    quantity: 10000,
    quantityLabel: "10,000",
    basePriceINR: 1799,
    deliveryTime: "2–5 days",
    description: "Kickstart video visibility with 10,000 views.",
    bestFor: "New uploads",
  },
  {
    packageId: "yt-views-50k",
    platform: "YouTube",
    service: "views",
    title: "50K Views",
    quantity: 50000,
    quantityLabel: "50,000",
    basePriceINR: 7999,
    discountBadge: "Save 10%",
    deliveryTime: "4–10 days",
    description: "Major reach expansion with 50,000 views.",
    bestFor: "Growing channel reach",
  },
  {
    packageId: "yt-views-100k",
    platform: "YouTube",
    service: "views",
    title: "100K Views",
    quantity: 100000,
    quantityLabel: "100,000",
    basePriceINR: 14999,
    discountBadge: "Best Value",
    deliveryTime: "5–12 days",
    description: "Premium visibility with 100,000 views.",
    bestFor: "Popular videos",
  },
  {
    packageId: "yt-views-500k",
    platform: "YouTube",
    service: "views",
    title: "500K Views",
    quantity: 500000,
    quantityLabel: "500,000",
    basePriceINR: 64999,
    discountBadge: "Agency Pack",
    deliveryTime: "10–15 days",
    description: "Massive reach with 500,000 views.",
    bestFor: "Large campaigns",
  },

  // LinkedIn Followers
  {
    packageId: "li-followers-1k",
    platform: "LinkedIn",
    service: "followers",
    title: "1K Followers",
    quantity: 1000,
    quantityLabel: "1,000",
    basePriceINR: 2999,
    deliveryTime: "3–7 days",
    description: "Build professional authority with 1,000 followers.",
    bestFor: "Professionals starting out",
  },
  {
    packageId: "li-followers-5k",
    platform: "LinkedIn",
    service: "followers",
    title: "5K Followers",
    quantity: 5000,
    quantityLabel: "5,000",
    basePriceINR: 12999,
    discountBadge: "Save 10%",
    deliveryTime: "5–10 days",
    description: "Established authority with 5,000 followers.",
    bestFor: "Professionals and brands",
  },
  {
    packageId: "li-followers-10k",
    platform: "LinkedIn",
    service: "followers",
    title: "10K Followers",
    quantity: 10000,
    quantityLabel: "10,000",
    basePriceINR: 24999,
    discountBadge: "Best Value",
    deliveryTime: "7–12 days",
    description: "Premium thought leadership with 10,000 followers.",
    bestFor: "C-level and influencers",
  },
  {
    packageId: "li-followers-20k",
    platform: "LinkedIn",
    service: "followers",
    title: "20K Followers",
    quantity: 20000,
    quantityLabel: "20,000",
    basePriceINR: 47999,
    discountBadge: "Agency Pack",
    deliveryTime: "10–14 days",
    description: "Executive-level authority with 20,000 followers.",
    bestFor: "Agencies and enterprises",
  },

  // LinkedIn Likes
  {
    packageId: "li-likes-1k",
    platform: "LinkedIn",
    service: "likes",
    title: "1K Likes",
    quantity: 1000,
    quantityLabel: "1,000",
    basePriceINR: 2499,
    deliveryTime: "2–5 days",
    description: "Boost post credibility with 1,000 likes.",
    bestFor: "Professional posts",
  },
  {
    packageId: "li-likes-5k",
    platform: "LinkedIn",
    service: "likes",
    title: "5K Likes",
    quantity: 5000,
    quantityLabel: "5,000",
    basePriceINR: 10999,
    discountBadge: "Save 10%",
    deliveryTime: "3–7 days",
    description: "Significant professional engagement with 5,000 likes.",
    bestFor: "Content campaigns",
  },
  {
    packageId: "li-likes-10k",
    platform: "LinkedIn",
    service: "likes",
    title: "10K Likes",
    quantity: 10000,
    quantityLabel: "10,000",
    basePriceINR: 19999,
    discountBadge: "Best Value",
    deliveryTime: "5–10 days",
    description: "Premium engagement with 10,000 likes.",
    bestFor: "Major announcements",
  },

  // Facebook Followers
  {
    packageId: "fb-followers-5k",
    platform: "Facebook",
    service: "followers",
    title: "5K Followers",
    quantity: 5000,
    quantityLabel: "5,000",
    basePriceINR: 1299,
    deliveryTime: "2–5 days",
    description: "Build page audience with 5,000 followers.",
    bestFor: "Local businesses",
  },
  {
    packageId: "fb-followers-10k",
    platform: "Facebook",
    service: "followers",
    title: "10K Followers",
    quantity: 10000,
    quantityLabel: "10,000",
    basePriceINR: 2399,
    discountBadge: "Save 10%",
    deliveryTime: "3–7 days",
    description: "Expand page reach with 10,000 followers.",
    bestFor: "Growing brands",
  },
  {
    packageId: "fb-followers-20k",
    platform: "Facebook",
    service: "followers",
    title: "20K Followers",
    quantity: 20000,
    quantityLabel: "20,000",
    basePriceINR: 4499,
    discountBadge: "Best Value",
    deliveryTime: "5–10 days",
    description: "Established page presence with 20,000 followers.",
    bestFor: "Established pages",
  },
  {
    packageId: "fb-followers-50k",
    platform: "Facebook",
    service: "followers",
    title: "50K Followers",
    quantity: 50000,
    quantityLabel: "50,000",
    basePriceINR: 9999,
    discountBadge: "Agency Pack",
    deliveryTime: "7–14 days",
    description: "Major page authority with 50,000 followers.",
    bestFor: "Agencies and enterprises",
  },

  // Facebook Likes
  {
    packageId: "fb-likes-5k",
    platform: "Facebook",
    service: "likes",
    title: "5K Likes",
    quantity: 5000,
    quantityLabel: "5,000",
    basePriceINR: 599,
    deliveryTime: "1–3 days",
    description: "Boost post engagement with 5,000 likes.",
    bestFor: "Content posts",
  },
  {
    packageId: "fb-likes-10k",
    platform: "Facebook",
    service: "likes",
    title: "10K Likes",
    quantity: 10000,
    quantityLabel: "10,000",
    basePriceINR: 999,
    discountBadge: "Save 10%",
    deliveryTime: "2–5 days",
    description: "Significant engagement with 10,000 likes.",
    bestFor: "Regular posts",
  },
  {
    packageId: "fb-likes-20k",
    platform: "Facebook",
    service: "likes",
    title: "20K Likes",
    quantity: 20000,
    quantityLabel: "20,000",
    basePriceINR: 1799,
    discountBadge: "Best Value",
    deliveryTime: "3–7 days",
    description: "Heavy engagement with 20,000 likes.",
    bestFor: "Campaigns",
  },
  {
    packageId: "fb-likes-50k",
    platform: "Facebook",
    service: "likes",
    title: "50K Likes",
    quantity: 50000,
    quantityLabel: "50,000",
    basePriceINR: 3999,
    discountBadge: "Agency Pack",
    deliveryTime: "5–10 days",
    description: "Premium engagement with 50,000 likes.",
    bestFor: "Major campaigns",
  },

  // Telegram Members
  {
    packageId: "tg-members-5k",
    platform: "Telegram",
    service: "members",
    title: "5K Members",
    quantity: 5000,
    quantityLabel: "5,000",
    basePriceINR: 3499,
    deliveryTime: "3–7 days",
    description: "Grow community with 5,000 members.",
    bestFor: "Small communities",
  },
  {
    packageId: "tg-members-10k",
    platform: "Telegram",
    service: "members",
    title: "10K Members",
    quantity: 10000,
    quantityLabel: "10,000",
    basePriceINR: 6499,
    discountBadge: "Save 10%",
    deliveryTime: "5–10 days",
    description: "Establish community with 10,000 members.",
    bestFor: "Growing groups",
  },
  {
    packageId: "tg-members-20k",
    platform: "Telegram",
    service: "members",
    title: "20K Members",
    quantity: 20000,
    quantityLabel: "20,000",
    basePriceINR: 11999,
    discountBadge: "Best Value",
    deliveryTime: "7–12 days",
    description: "Build community authority with 20,000 members.",
    bestFor: "Established channels",
  },
  {
    packageId: "tg-members-50k",
    platform: "Telegram",
    service: "members",
    title: "50K Members",
    quantity: 50000,
    quantityLabel: "50,000",
    basePriceINR: 27999,
    discountBadge: "Agency Pack",
    deliveryTime: "10–14 days",
    description: "Premium community status with 50,000 members.",
    bestFor: "Large communities",
  },

  // TikTok Followers
  {
    packageId: "tt-followers-5k",
    platform: "TikTok",
    service: "followers",
    title: "5K Followers",
    quantity: 5000,
    quantityLabel: "5,000",
    basePriceINR: 2199,
    deliveryTime: "2–5 days",
    description: "Kickstart TikTok presence with 5,000 followers.",
    bestFor: "New creators",
  },
  {
    packageId: "tt-followers-10k",
    platform: "TikTok",
    service: "followers",
    title: "10K Followers",
    quantity: 10000,
    quantityLabel: "10,000",
    basePriceINR: 3999,
    discountBadge: "Save 10%",
    deliveryTime: "3–7 days",
    description: "Grow TikTok presence with 10,000 followers.",
    bestFor: "Growing creators",
  },
  {
    packageId: "tt-followers-20k",
    platform: "TikTok",
    service: "followers",
    title: "20K Followers",
    quantity: 20000,
    quantityLabel: "20,000",
    basePriceINR: 7499,
    discountBadge: "Best Value",
    deliveryTime: "5–10 days",
    description: "Established TikTok presence with 20,000 followers.",
    bestFor: "Content creators",
  },
  {
    packageId: "tt-followers-50k",
    platform: "TikTok",
    service: "followers",
    title: "50K Followers",
    quantity: 50000,
    quantityLabel: "50,000",
    basePriceINR: 16999,
    discountBadge: "Agency Pack",
    deliveryTime: "7–14 days",
    description: "Large TikTok follower package for established creator and brand campaigns.",
    bestFor: "Agencies and brands",
  },

  // X/Twitter Followers
  {
    packageId: "x-followers-5k",
    platform: "X",
    service: "followers",
    title: "5K Followers",
    quantity: 5000,
    quantityLabel: "5,000",
    basePriceINR: 2199,
    deliveryTime: "2–5 days",
    description: "Build Twitter/X presence with 5,000 followers.",
    bestFor: "New accounts",
  },
  {
    packageId: "x-followers-10k",
    platform: "X",
    service: "followers",
    title: "10K Followers",
    quantity: 10000,
    quantityLabel: "10,000",
    basePriceINR: 3999,
    discountBadge: "Save 10%",
    deliveryTime: "3–7 days",
    description: "Grow Twitter/X following with 10,000 followers.",
    bestFor: "Active accounts",
  },
  {
    packageId: "x-followers-20k",
    platform: "X",
    service: "followers",
    title: "20K Followers",
    quantity: 20000,
    quantityLabel: "20,000",
    basePriceINR: 7499,
    discountBadge: "Best Value",
    deliveryTime: "5–10 days",
    description: "Twitter/X authority with 20,000 followers.",
    bestFor: "Influencers",
  },
  {
    packageId: "x-followers-50k",
    platform: "X",
    service: "followers",
    title: "50K Followers",
    quantity: 50000,
    quantityLabel: "50,000",
    basePriceINR: 16999,
    discountBadge: "Agency Pack",
    deliveryTime: "7–14 days",
    description: "Twitter/X premium status with 50,000 followers.",
    bestFor: "Agencies and brands",
  },
];

export function getPackageById(packageId: string): BigPackage | undefined {
  return bigPackages.find((p) => p.packageId === packageId);
}

export function getPackagesByPlatform(platform: string): BigPackage[] {
  return bigPackages.filter((p) => p.platform === platform);
}

export const platforms = ["Instagram", "YouTube", "LinkedIn", "Facebook", "Telegram", "TikTok", "X"] as const;
