import { SERVICE_PRICES, type ServiceCode } from "./service-pricing";

export type SmmPlatformId = "instagram" | "youtube" | "facebook" | "linkedin" | "telegram" | "tiktok" | "x";

export type SmmService = {
  platform: SmmPlatformId;
  code: ServiceCode;
  name: string;
  description: string;
  pricePer1000: number;
  minQuantity: number;
  maxQuantity: number;
  /** The only supported step is one unit unless a service explicitly says otherwise. */
  quantityStep?: number;
  deliveryTime: string;
  refillPolicy: string;
  refillSupported?: boolean;
  refillDays?: number | null;
  qualityType: string;
  importantInstruction: string;
  isActive: boolean;
};

export const platformMeta: Record<SmmPlatformId, { label: string; short: string; icon: string; gradient: string }> = {
  instagram: { label: "Instagram", short: "IG", icon: "instagram", gradient: "from-[#FF7A00] via-[#FF9F00] to-[#FFC400]" },
  youtube: { label: "YouTube", short: "YT", icon: "youtube", gradient: "from-red-500 to-red-600" },
  facebook: { label: "Facebook", short: "FB", icon: "facebook", gradient: "from-orange-500 to-amber-600" },
  linkedin: { label: "LinkedIn", short: "IN", icon: "linkedin", gradient: "from-amber-500 to-orange-600" },
  telegram: { label: "Telegram", short: "TG", icon: "telegram", gradient: "from-orange-500 to-amber-600" },
  tiktok: { label: "TikTok", short: "TT", icon: "tiktok", gradient: "from-amber-500 to-orange-600" },
  x: { label: "Twitter / X", short: "X", icon: "twitter", gradient: "from-slate-600 to-slate-900" },
};

export const smmServiceCatalog: SmmService[] = [
  {
    platform: "instagram",
    code: "instagram-followers",
    name: "Instagram Followers",
    description: "Compare Instagram follower campaigns with clear pricing, delivery estimates and eligible refill support.",
    pricePer1000: SERVICE_PRICES["instagram-followers"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-7 days",
    refillPolicy: "30 days refill",
    qualityType: "Premium",
    importantInstruction: "Use public profile URL only.",
    isActive: true,
  },
  {
    platform: "instagram",
    code: "instagram-likes",
    name: "Instagram Likes",
    description: "Increase engagement and social proof on posts and reels.",
    pricePer1000: SERVICE_PRICES["instagram-likes"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-3 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public post/reel URL.",
    isActive: true,
  },
  {
    platform: "instagram",
    code: "instagram-views",
    name: "Instagram Views",
    description: "Compare Instagram view campaigns for public posts or Reels with clear pricing and delivery estimates.",
    pricePer1000: SERVICE_PRICES["instagram-views"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-3 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public reel/post URL.",
    isActive: true,
  },
  {
    platform: "instagram",
    code: "instagram-comments",
    name: "Instagram Comments",
    description: "Boost conversations and social proof on your Instagram posts and reels with comment engagement.",
    pricePer1000: SERVICE_PRICES["instagram-comments"],
    minQuantity: 100,
    maxQuantity: 10000,
    deliveryTime: "1–24 hours",
    refillPolicy: "No refill",
    qualityType: "Premium",
    importantInstruction: "Use a public Instagram post or reel URL and keep it available while the order is processing.",
    isActive: true,
  },
  {
    platform: "instagram",
    code: "instagram-saves",
    name: "Instagram Saves",
    description: "Strengthen post and Reel engagement signals with Instagram save activity.",
    pricePer1000: SERVICE_PRICES["instagram-saves"],
    minQuantity: 100,
    maxQuantity: 1000,
    deliveryTime: "Shown with the active service",
    refillPolicy: "Shown with the active service",
    qualityType: "Premium",
    importantInstruction: "Use a public Instagram post or reel URL and keep it available while the order is processing.",
    isActive: true,
  },
  {
    platform: "youtube",
    code: "youtube-subscribers",
    name: "YouTube Subscribers",
    description: "Compare YouTube subscriber campaigns with clear package sizes, delivery estimates and support details.",
    pricePer1000: SERVICE_PRICES["youtube-subscribers"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "3-10 days",
    refillPolicy: "30 days refill",
    qualityType: "Premium",
    importantInstruction: "Use public channel URL.",
    isActive: true,
  },
  {
    platform: "youtube",
    code: "youtube-likes",
    name: "YouTube Likes",
    description: "Compare YouTube like campaigns for public videos with clear pricing and delivery details.",
    pricePer1000: SERVICE_PRICES["youtube-likes"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public video URL.",
    isActive: true,
  },
  {
    platform: "youtube",
    code: "youtube-views",
    name: "YouTube Views",
    description: "Compare YouTube view campaigns for public videos with transparent package options.",
    pricePer1000: SERVICE_PRICES["youtube-views"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public video URL and keep video public.",
    isActive: true,
  },
  {
    platform: "facebook",
    code: "facebook-followers",
    name: "Facebook Followers",
    description: "Grow page audience and strengthen brand trust.",
    pricePer1000: SERVICE_PRICES["facebook-followers"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-8 days",
    refillPolicy: "30 days refill",
    qualityType: "Premium",
    importantInstruction: "Use public page/profile URL.",
    isActive: true,
  },
  {
    platform: "facebook",
    code: "facebook-likes",
    name: "Facebook Likes",
    description: "Increase interactions and social proof across posts.",
    pricePer1000: SERVICE_PRICES["facebook-likes"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-5 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public post URL.",
    isActive: true,
  },
  {
    platform: "facebook",
    code: "facebook-views",
    name: "Facebook Views",
    description: "Expand content reach and improve campaign visibility.",
    pricePer1000: SERVICE_PRICES["facebook-views"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-4 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public video URL.",
    isActive: true,
  },
  {
    platform: "facebook",
    code: "facebook-shares",
    name: "Facebook Shares",
    description: "Expand post distribution with quality share activity.",
    pricePer1000: SERVICE_PRICES["facebook-shares"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-5 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use a public Facebook post URL.",
    isActive: true,
  },
  {
    platform: "linkedin",
    code: "linkedin-followers",
    name: "LinkedIn Profile Followers",
    description: "Improve professional authority and profile visibility.",
    pricePer1000: SERVICE_PRICES["linkedin-followers"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-9 days",
    refillPolicy: "Refill eligible",
    qualityType: "Professional",
    importantInstruction: "Use public profile URL and avoid URL changes.",
    isActive: true,
  },
  {
    platform: "linkedin",
    code: "linkedin-likes",
    name: "LinkedIn Likes",
    description: "Boost credibility with stronger post-level social proof.",
    pricePer1000: SERVICE_PRICES["linkedin-likes"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-6 days",
    refillPolicy: "Refill eligible",
    qualityType: "Professional",
    importantInstruction: "Use public post URL.",
    isActive: true,
  },
  {
    platform: "telegram",
    code: "telegram-members",
    name: "Telegram Premium Members",
    description: "Scale channel audience and strengthen community traction.",
    pricePer1000: SERVICE_PRICES["telegram-members"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public channel/group URL.",
    isActive: true,
  },
  {
    platform: "tiktok",
    code: "tiktok-followers",
    name: "TikTok Followers",
    description: "Build profile momentum with quality follower growth.",
    pricePer1000: SERVICE_PRICES["tiktok-followers"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public profile URL.",
    isActive: true,
  },
  {
    platform: "tiktok",
    code: "tiktok-likes",
    name: "TikTok Likes",
    description: "Increase engagement strength on short-form content.",
    pricePer1000: SERVICE_PRICES["tiktok-likes"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-4 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public post URL.",
    isActive: true,
  },
  {
    platform: "tiktok",
    code: "tiktok-views",
    name: "TikTok Views",
    description: "Improve reach and discovery on short-form videos.",
    pricePer1000: SERVICE_PRICES["tiktok-views"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-3 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public video URL.",
    isActive: true,
  },
  {
    platform: "x",
    code: "x-followers",
    name: "X Followers",
    description: "Increase profile authority and long-term social visibility.",
    pricePer1000: SERVICE_PRICES["x-followers"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "30 days refill",
    qualityType: "Premium",
    importantInstruction: "Use public profile URL and avoid handle changes.",
    isActive: true,
  },
];

/**
 * Legacy entries carried their refill rule as prose.  This normalization keeps
 * the published wording intact while exposing one typed rule to all new code.
 */
export const normalizedSmmServiceCatalog: readonly SmmService[] = smmServiceCatalog.map((service) => ({
  ...service,
  quantityStep: service.quantityStep ?? 1,
  refillSupported: service.refillSupported ?? /refill eligible|\d+ days refill/i.test(service.refillPolicy),
  refillDays: service.refillDays ?? (service.refillPolicy.match(/(\d+)\s*days/i) ? Number(service.refillPolicy.match(/(\d+)\s*days/i)?.[1]) : null),
}));

export const activeSmmServices = normalizedSmmServiceCatalog.filter((service) => service.isActive);

export function getServiceById(code: string): SmmService | undefined {
  return normalizedSmmServiceCatalog.find((service) => service.code === code);
}

export const getServiceBySlug = getServiceById;
