import { SERVICE_PRICES, type ServiceCode } from "./service-pricing";

export type SmmPlatformId = "instagram" | "youtube" | "facebook" | "linkedin" | "telegram" | "tiktok" | "x";

export type SmmService = {
  platform: SmmPlatformId;
  code: ServiceCode;
  name: string;
  description: string;
  pricePer1000: number;
  minQuantity: number;
  maxQuantity: number;
  /** The only supported step is one unit unless a service explicitly says otherwise. */
  quantityStep?: number;
  deliveryTime: string;
  refillPolicy: string;
  refillSupported?: boolean;
  refillDays?: number | null;
  qualityType: string;
  importantInstruction: string;
  isActive: boolean;
  /** Service facts must be obtained from the protected live catalog before ordering. */
  requiresLiveCatalogFacts?: boolean;
};

export const platformMeta: Record<SmmPlatformId, { label: string; short: string; icon: string; gradient: string }> = {
  instagram: { label: "Instagram", short: "IG", icon: "instagram", gradient: "from-[#FF7A00] via-[#FF9F00] to-[#FFC400]" },
  youtube: { label: "YouTube", short: "YT", icon: "youtube", gradient: "from-red-500 to-red-600" },
  facebook: { label: "Facebook", short: "FB", icon: "facebook", gradient: "from-orange-500 to-amber-600" },
  linkedin: { label: "LinkedIn", short: "IN", icon: "linkedin", gradient: "from-amber-500 to-orange-600" },
  telegram: { label: "Telegram", short: "TG", icon: "telegram", gradient: "from-orange-500 to-amber-600" },
  tiktok: { label: "TikTok", short: "TT", icon: "tiktok", gradient: "from-amber-500 to-orange-600" },
  x: { label: "Twitter / X", short: "X", icon: "twitter", gradient: "from-slate-600 to-slate-900" },
};

export const smmServiceCatalog: SmmService[] = [
  {
    platform: "instagram",
    code: "instagram-followers",
    name: "Instagram Followers",
    description: "Compare Instagram follower campaigns with clear pricing, delivery estimates and eligible refill support.",
    pricePer1000: SERVICE_PRICES["instagram-followers"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-7 days",
    refillPolicy: "30 days refill",
    qualityType: "Premium",
    importantInstruction: "Use public profile URL only.",
    isActive: true,
  },
  {
    platform: "instagram",
    code: "instagram-likes",
    name: "Instagram Likes",
    description: "Increase engagement and social proof on posts and reels.",
    pricePer1000: SERVICE_PRICES["instagram-likes"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-3 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public post/reel URL.",
    isActive: true,
  },
  {
    platform: "instagram",
    code: "instagram-views",
    name: "Instagram Views",
    description: "Compare Instagram view campaigns for public posts or Reels with clear pricing and delivery estimates.",
    pricePer1000: SERVICE_PRICES["instagram-views"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-3 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public reel/post URL.",
    isActive: true,
  },
  {
    platform: "instagram",
    code: "instagram-comments",
    name: "Instagram Comments",
    description: "Boost conversations and social proof on your Instagram posts and reels with comment engagement.",
    pricePer1000: SERVICE_PRICES["instagram-comments"],
    minQuantity: 100,
    maxQuantity: 10000,
    deliveryTime: "1–24 hours",
    refillPolicy: "No refill",
    qualityType: "Premium",
    importantInstruction: "Use a public Instagram post or reel URL and keep it available while the order is processing.",
    isActive: true,
  },
  {
    platform: "instagram",
    code: "instagram-saves",
    name: "Instagram Saves",
    description: "Strengthen post and Reel engagement signals with Instagram save activity.",
    pricePer1000: SERVICE_PRICES["instagram-saves"],
    minQuantity: 100,
    maxQuantity: 1000,
    deliveryTime: "Shown with the active service",
    refillPolicy: "Shown with the active service",
    qualityType: "Premium",
    importantInstruction: "Use a public Instagram post or reel URL and keep it available while the order is processing.",
    requiresLiveCatalogFacts: true,
    isActive: true,
  },
  {
    platform: "instagram",
    code: "instagram-shares",
    name: "Instagram Shares",
    description: "Expand post and Reel engagement with Instagram share activity.",
    pricePer1000: SERVICE_PRICES["instagram-shares"],
    // These are safe UI defaults matching the existing active service row.
    // New Order immediately replaces them with the live Supabase values, and
    // checkout independently validates and prices from that same row.
    minQuantity: 100,
    maxQuantity: 100000,
    deliveryTime: "1–24 hours",
    refillPolicy: "No refill",
    qualityType: "Premium",
    importantInstruction: "Use a public Instagram post or reel URL and keep it available while the order is processing.",
    requiresLiveCatalogFacts: true,
    isActive: true,
  },
  {
    platform: "youtube",
    code: "youtube-subscribers",
    name: "YouTube Subscribers",
    description: "Compare YouTube subscriber campaigns with clear package sizes, delivery estimates and support details.",
    pricePer1000: SERVICE_PRICES["youtube-subscribers"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "3-10 days",
    refillPolicy: "30 days refill",
    qualityType: "Premium",
    importantInstruction: "Use public channel URL.",
    isActive: true,
  },
  {
    platform: "youtube",
    code: "youtube-likes",
    name: "YouTube Likes",
    description: "Compare YouTube like campaigns for public videos with clear pricing and delivery details.",
    pricePer1000: SERVICE_PRICES["youtube-likes"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public video URL.",
    isActive: true,
  },
  {
    platform: "youtube",
    code: "youtube-views",
    name: "YouTube Views",
    description: "Compare YouTube view campaigns for public videos with transparent package options.",
    pricePer1000: SERVICE_PRICES["youtube-views"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public video URL and keep video public.",
    isActive: true,
  },
  {
    platform: "youtube",
    code: "youtube-comments",
    name: "YouTube Comments",
    description: "Build visible conversation and engagement around your YouTube videos with comment activity.",
    pricePer1000: SERVICE_PRICES["youtube-comments"],
    minQuantity: 0,
    maxQuantity: 0,
    deliveryTime: "Shown with the active service",
    refillPolicy: "Shown with the active service",
    qualityType: "Shown with the active service",
    importantInstruction: "Submit the correct public YouTube video URL and keep the video public while the order is processing.",
    // Keep the service in the customer catalog, but do not expose its zero
    // placeholder rate: New Order replaces it only with protected live facts.
    isActive: true,
    requiresLiveCatalogFacts: true,
  },
  {
    platform: "youtube",
    code: "youtube-watch-hours",
    name: "YouTube Watch Hours",
    description: "Build extended viewing activity around your public YouTube content with transparent watch-hour packages and dashboard tracking.",
    pricePer1000: SERVICE_PRICES["youtube-watch-hours"],
    minQuantity: 0,
    maxQuantity: 0,
    deliveryTime: "Shown with the active service",
    refillPolicy: "Shown with the active service",
    qualityType: "Shown with the active service",
    importantInstruction: "Submit the correct public YouTube video URL and keep the video public while the order is processing.",
    isActive: true,
    requiresLiveCatalogFacts: true,
  },
  {
    platform: "facebook",
    code: "facebook-group-members",
    name: "Facebook Group Members",
    description: "Grow your Facebook community with group member packages, transparent pricing, and dashboard order tracking.",
    pricePer1000: SERVICE_PRICES["facebook-group-members"],
    minQuantity: 0,
    maxQuantity: 0,
    deliveryTime: "Shown with the active service",
    refillPolicy: "Shown with the active service",
    qualityType: "Shown with the active service",
    importantInstruction: "Facebook Group must be public or accessible as required by the service. Enter the correct Facebook Group URL and do not change privacy settings while the order is processing.",
    isActive: true,
    requiresLiveCatalogFacts: true,
  },
  {
    platform: "facebook",
    code: "facebook-followers",
    name: "Facebook Followers",
    description: "Grow page audience and strengthen brand trust.",
    pricePer1000: SERVICE_PRICES["facebook-followers"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-8 days",
    refillPolicy: "30 days refill",
    qualityType: "Premium",
    importantInstruction: "Use public page/profile URL.",
    isActive: true,
  },
  {
    platform: "facebook",
    code: "facebook-likes",
    name: "Facebook Likes",
    description: "Increase interactions and social proof across posts.",
    pricePer1000: SERVICE_PRICES["facebook-likes"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-5 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public post URL.",
    isActive: true,
  },
  {
    platform: "facebook",
    code: "facebook-views",
    name: "Facebook Views",
    description: "Expand content reach and improve campaign visibility.",
    pricePer1000: SERVICE_PRICES["facebook-views"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-4 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public video URL.",
    isActive: true,
  },
  {
    platform: "facebook",
    code: "facebook-shares",
    name: "Facebook Shares",
    description: "Expand post distribution with quality share activity.",
    pricePer1000: SERVICE_PRICES["facebook-shares"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-5 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use a public Facebook post URL.",
    isActive: true,
  },
  {
    platform: "linkedin",
    code: "linkedin-followers",
    name: "LinkedIn Profile Followers",
    description: "Improve professional authority and profile visibility.",
    pricePer1000: SERVICE_PRICES["linkedin-followers"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-9 days",
    refillPolicy: "Refill eligible",
    qualityType: "Professional",
    importantInstruction: "Use public profile URL and avoid URL changes.",
    isActive: true,
  },
  {
    platform: "linkedin",
    code: "linkedin-likes",
    name: "LinkedIn Likes",
    description: "Boost credibility with stronger post-level social proof.",
    pricePer1000: SERVICE_PRICES["linkedin-likes"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-6 days",
    refillPolicy: "Refill eligible",
    qualityType: "Professional",
    importantInstruction: "Use public post URL.",
    isActive: true,
  },
  {
    platform: "telegram",
    code: "telegram-members",
    name: "Telegram Premium Members",
    description: "Scale channel audience and strengthen community traction.",
    pricePer1000: SERVICE_PRICES["telegram-members"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public channel/group URL.",
    isActive: true,
  },
  {
    platform: "telegram", code: "telegram-post-views", name: "Telegram Post Views",
    description: "Increase visible viewing activity on an eligible public Telegram channel post.",
    pricePer1000: SERVICE_PRICES["telegram-post-views"], minQuantity: 100, maxQuantity: 100000,
    deliveryTime: "1-2 days", refillPolicy: "No Refill", qualityType: "Standard",
    importantInstruction: "Submit the exact public Telegram post and keep it accessible while the order is processing.", requiresLiveCatalogFacts: true, isActive: true,
  },
  {
    platform: "telegram", code: "telegram-post-reactions", name: "Telegram Post Reactions",
    description: "Increase visible engagement on an eligible public Telegram post with reaction activity.",
    pricePer1000: SERVICE_PRICES["telegram-post-reactions"], minQuantity: 100, maxQuantity: 100000,
    deliveryTime: "1-2 days", refillPolicy: "No Refill", qualityType: "Standard",
    importantInstruction: "Submit the exact public Telegram post that should receive reactions and keep it accessible while processing.", requiresLiveCatalogFacts: true, isActive: true,
  },
  {
    platform: "telegram", code: "telegram-poll-votes", name: "Telegram Poll Votes",
    description: "Increase voting activity on an eligible public Telegram poll. Provide the exact public poll post URL and answer number.",
    pricePer1000: SERVICE_PRICES["telegram-poll-votes"], minQuantity: 100, maxQuantity: 100000,
    deliveryTime: "1-2 days", refillPolicy: "No Refill", qualityType: "Standard",
    importantInstruction: "Submit the exact public Telegram post containing the poll, provide the answer number for the option receiving votes, and keep it accessible while processing.", requiresLiveCatalogFacts: true, isActive: true,
  },
  {
    platform: "tiktok",
    code: "tiktok-followers",
    name: "TikTok Followers",
    description: "Increase visible follower activity on an eligible public TikTok profile.",
    pricePer1000: SERVICE_PRICES["tiktok-followers"],
    minQuantity: 100,
    maxQuantity: 100000,
    deliveryTime: "1-2 days",
    refillPolicy: "30 Days Refill",
    qualityType: "Standard",
    importantInstruction: "Enter the correct public TikTok profile URL and keep the profile publicly accessible while the order is processing.",
    isActive: true,
    requiresLiveCatalogFacts: true,
  },
  {
    platform: "tiktok",
    code: "tiktok-likes",
    name: "TikTok Likes",
    description: "Increase visible engagement on an eligible public TikTok video with like activity.",
    pricePer1000: SERVICE_PRICES["tiktok-likes"],
    minQuantity: 100,
    maxQuantity: 100000,
    deliveryTime: "1-2 days",
    refillPolicy: "No Refill",
    qualityType: "Standard",
    importantInstruction: "Enter the correct public TikTok video URL and keep the video publicly accessible while the order is processing.",
    isActive: true,
    requiresLiveCatalogFacts: true,
  },
  {
    platform: "tiktok",
    code: "tiktok-views",
    name: "TikTok Views",
    description: "Increase visible viewing activity on an eligible public TikTok video.",
    pricePer1000: SERVICE_PRICES["tiktok-views"],
    minQuantity: 100,
    maxQuantity: 100000,
    deliveryTime: "1-2 days",
    refillPolicy: "No Refill",
    qualityType: "Standard",
    importantInstruction: "Enter the correct public TikTok video URL and keep the video publicly accessible while the order is processing.",
    isActive: true,
    requiresLiveCatalogFacts: true,
  },
  {
    platform: "tiktok", code: "tiktok-custom-comments", name: "TikTok Custom Comments",
    description: "Add customer-provided comment activity to an eligible public TikTok video.",
    pricePer1000: SERVICE_PRICES["tiktok-custom-comments"], minQuantity: 100, maxQuantity: 100000,
    deliveryTime: "1-2 days", refillPolicy: "No Refill", qualityType: "Standard",
    importantInstruction: "Enter the correct public TikTok video URL and provide exactly one custom comment per line. The number of comments must match the order quantity.", isActive: true, requiresLiveCatalogFacts: true,
  },
  {
    platform: "tiktok", code: "tiktok-story-views", name: "TikTok Story Views",
    description: "Increase viewing activity on an eligible public TikTok story.",
    pricePer1000: SERVICE_PRICES["tiktok-story-views"], minQuantity: 100, maxQuantity: 100000,
    deliveryTime: "1-2 days", refillPolicy: "No Refill", qualityType: "Standard",
    importantInstruction: "Enter the correct eligible TikTok target URL and keep the target accessible while the order is processing.", isActive: true, requiresLiveCatalogFacts: true,
  },
  {
    platform: "tiktok", code: "tiktok-saves", name: "TikTok Saves",
    description: "Increase save activity on an eligible public TikTok video.",
    pricePer1000: SERVICE_PRICES["tiktok-saves"], minQuantity: 100, maxQuantity: 100000,
    deliveryTime: "1-2 days", refillPolicy: "No Refill", qualityType: "Standard",
    importantInstruction: "Enter the correct public TikTok video URL and keep the video publicly accessible while the order is processing.", isActive: true, requiresLiveCatalogFacts: true,
  },
  {
    platform: "x",
    code: "x-followers",
    name: "X Followers",
    description: "Increase profile authority and long-term social visibility.",
    pricePer1000: SERVICE_PRICES["x-followers"],
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "30 days refill",
    qualityType: "Premium",
    importantInstruction: "Use public profile URL and avoid handle changes.",
    isActive: true,
  },
  {
    platform: "x", code: "twitter-likes", name: "Twitter / X Likes",
    description: "Increase visible engagement on a public Twitter/X post with like activity.",
    pricePer1000: SERVICE_PRICES["twitter-likes"], minQuantity: 0, maxQuantity: 0,
    deliveryTime: "Estimate shown before checkout", refillPolicy: "No Refill", qualityType: "Standard",
    importantInstruction: "Submit the correct public Twitter/X post URL and keep the post public while the order is processing.", requiresLiveCatalogFacts: true, isActive: true,
  },
  {
    platform: "x", code: "twitter-views", name: "Twitter / X Views",
    description: "Increase visible reach and activity on an eligible public Twitter/X post.",
    pricePer1000: SERVICE_PRICES["twitter-views"], minQuantity: 0, maxQuantity: 0,
    deliveryTime: "Estimate shown before checkout", refillPolicy: "No Refill", qualityType: "Standard",
    importantInstruction: "Submit the correct public Twitter/X post URL and keep the post public while the order is processing.", requiresLiveCatalogFacts: true, isActive: true,
  },
  {
    platform: "x", code: "twitter-retweets", name: "Twitter / X Retweets",
    description: "Increase distribution and visible sharing activity on a public Twitter/X post.",
    pricePer1000: SERVICE_PRICES["twitter-retweets"], minQuantity: 0, maxQuantity: 0,
    deliveryTime: "Estimate shown before checkout", refillPolicy: "No Refill", qualityType: "Standard",
    importantInstruction: "Submit the correct public Twitter/X post URL and keep the post public while the order is processing.", requiresLiveCatalogFacts: true, isActive: true,
  },
  {
    platform: "x", code: "twitter-crypto-followers", name: "Twitter / X Crypto-Based Followers",
    description: "Grow your crypto-focused Twitter/X profile with specialized crypto-based followers. Suitable for cryptocurrency, Web3, blockchain, NFT and related profiles.",
    pricePer1000: SERVICE_PRICES["twitter-crypto-followers"], minQuantity: 0, maxQuantity: 0,
    deliveryTime: "Up to 1K/day", refillPolicy: "No Refill", qualityType: "Crypto-Based",
    importantInstruction: "Twitter/X profile must remain public during delivery. Fixed delivery speed.", requiresLiveCatalogFacts: true, isActive: true,
  },
  {
    platform: "x", code: "twitter-crypto-likes", name: "Twitter / X Crypto-Based Likes",
    description: "Increase engagement on crypto-related Twitter/X posts with specialized crypto-based likes. Suitable for crypto, Web3, blockchain, NFT and related content.",
    pricePer1000: SERVICE_PRICES["twitter-crypto-likes"], minQuantity: 0, maxQuantity: 0,
    deliveryTime: "Up to 1K/day", refillPolicy: "No Refill", qualityType: "Crypto-Based",
    importantInstruction: "Post must remain public during delivery. Fixed delivery speed.", requiresLiveCatalogFacts: true, isActive: true,
  },
  {
    platform: "x", code: "twitter-crypto-retweets", name: "Twitter / X Crypto-Based Retweets",
    description: "Expand the reach of crypto-related Twitter/X posts with specialized crypto-based retweets. Ideal for cryptocurrency, Web3, blockchain, NFT and related content.",
    pricePer1000: SERVICE_PRICES["twitter-crypto-retweets"], minQuantity: 0, maxQuantity: 0,
    deliveryTime: "Up to 1K/day", refillPolicy: "No Refill", qualityType: "Crypto-Based",
    importantInstruction: "Post must remain public during delivery. Fixed delivery speed.", requiresLiveCatalogFacts: true, isActive: true,
  },
  {
    platform: "x", code: "twitter-crypto-custom-comments", name: "Twitter / X Crypto-Based Custom Comments",
    description: "Add custom crypto-focused comments to eligible Twitter/X posts. Enter the comments you want delivered and keep the post public while the order is processing.",
    pricePer1000: SERVICE_PRICES["twitter-crypto-custom-comments"], minQuantity: 0, maxQuantity: 0,
    deliveryTime: "Up to 250/day", refillPolicy: "No Refill", qualityType: "Crypto-Based · Custom Comments",
    importantInstruction: "Post must remain public during delivery. Enter one comment per line; fixed delivery speed.", requiresLiveCatalogFacts: true, isActive: true,
  },
];

/**
 * Legacy entries carried their refill rule as prose.  This normalization keeps
 * the published wording intact while exposing one typed rule to all new code.
 */
export const normalizedSmmServiceCatalog: readonly SmmService[] = smmServiceCatalog.map((service) => ({
  ...service,
  quantityStep: service.quantityStep ?? 1,
  refillSupported: service.refillSupported ?? /refill eligible|\d+ days refill/i.test(service.refillPolicy),
  refillDays: service.refillDays ?? (service.refillPolicy.match(/(\d+)\s*days/i) ? Number(service.refillPolicy.match(/(\d+)\s*days/i)?.[1]) : null),
}));

export const activeSmmServices = normalizedSmmServiceCatalog.filter((service) => service.isActive);

export function getServiceById(code: string): SmmService | undefined {
  return normalizedSmmServiceCatalog.find((service) => service.code === code);
}

export const getServiceBySlug = getServiceById;
