export type SmmPlatformId = "instagram" | "youtube" | "facebook" | "linkedin" | "telegram" | "tiktok" | "x";

export type SmmService = {
  platform: SmmPlatformId;
  code: string;
  name: string;
  description: string;
  pricePer1000: number;
  minQuantity: number;
  maxQuantity: number;
  deliveryTime: string;
  refillPolicy: string;
  qualityType: string;
  importantInstruction: string;
  isActive: boolean;
};

export const platformMeta: Record<SmmPlatformId, { label: string; short: string; icon: string; gradient: string }> = {
  instagram: { label: "Instagram", short: "IG", icon: "instagram", gradient: "from-pink-500 via-fuchsia-500 to-sky-500" },
  youtube: { label: "YouTube", short: "YT", icon: "youtube", gradient: "from-rose-500 to-red-600" },
  facebook: { label: "Facebook", short: "FB", icon: "facebook", gradient: "from-blue-500 to-indigo-600" },
  linkedin: { label: "LinkedIn", short: "IN", icon: "linkedin", gradient: "from-cyan-500 to-blue-600" },
  telegram: { label: "Telegram", short: "TG", icon: "telegram", gradient: "from-sky-500 to-cyan-600" },
  tiktok: { label: "TikTok", short: "TT", icon: "tiktok", gradient: "from-violet-500 to-fuchsia-600" },
  x: { label: "Twitter / X", short: "X", icon: "twitter", gradient: "from-slate-600 to-slate-900" },
};

export const smmServiceCatalog: SmmService[] = [
  {
    platform: "instagram",
    code: "instagram-followers",
    name: "Instagram Real Followers",
    description: "Build profile authority with gradual premium follower delivery.",
    pricePer1000: 599,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-7 days",
    refillPolicy: "30 days refill",
    qualityType: "Premium",
    importantInstruction: "Use public profile URL only.",
    isActive: true,
  },
  {
    platform: "instagram",
    code: "instagram-likes",
    name: "Instagram Likes",
    description: "Increase engagement and social proof on posts and reels.",
    pricePer1000: 299,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-3 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public post/reel URL.",
    isActive: true,
  },
  {
    platform: "instagram",
    code: "instagram-views",
    name: "Instagram Views",
    description: "Increase reach and visibility with high-retention view delivery.",
    pricePer1000: 99,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-3 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public reel/post URL.",
    isActive: true,
  },
  {
    platform: "youtube",
    code: "youtube-subscribers",
    name: "YouTube Subscribers",
    description: "Strengthen channel credibility with premium subscriber campaigns.",
    pricePer1000: 3999,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "3-10 days",
    refillPolicy: "30 days refill",
    qualityType: "Premium",
    importantInstruction: "Use public channel URL.",
    isActive: true,
  },
  {
    platform: "youtube",
    code: "youtube-likes",
    name: "YouTube Likes",
    description: "Improve engagement and social proof with high-quality YouTube likes.",
    pricePer1000: 499,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public video URL.",
    isActive: true,
  },
  {
    platform: "youtube",
    code: "youtube-views",
    name: "YouTube Views",
    description: "Boost discoverability through increased high-retention views.",
    pricePer1000: 499,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public video URL and keep video public.",
    isActive: true,
  },
  {
    platform: "facebook",
    code: "facebook-followers",
    name: "Facebook Followers",
    description: "Grow page audience and strengthen brand trust.",
    pricePer1000: 499,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-8 days",
    refillPolicy: "30 days refill",
    qualityType: "Premium",
    importantInstruction: "Use public page/profile URL.",
    isActive: true,
  },
  {
    platform: "facebook",
    code: "facebook-likes",
    name: "Facebook Likes",
    description: "Increase interactions and social proof across posts.",
    pricePer1000: 299,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-5 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public post URL.",
    isActive: true,
  },
  {
    platform: "facebook",
    code: "facebook-views",
    name: "Facebook Views",
    description: "Expand content reach and improve campaign visibility.",
    pricePer1000: 199,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-4 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public video URL.",
    isActive: true,
  },
  {
    platform: "linkedin",
    code: "linkedin-followers",
    name: "LinkedIn Profile Followers",
    description: "Improve professional authority and profile visibility.",
    pricePer1000: 1499,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-9 days",
    refillPolicy: "Refill eligible",
    qualityType: "Professional",
    importantInstruction: "Use public profile URL and avoid URL changes.",
    isActive: true,
  },
  {
    platform: "linkedin",
    code: "linkedin-likes",
    name: "LinkedIn Likes",
    description: "Boost credibility with stronger post-level social proof.",
    pricePer1000: 899,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-6 days",
    refillPolicy: "Refill eligible",
    qualityType: "Professional",
    importantInstruction: "Use public post URL.",
    isActive: true,
  },
  {
    platform: "telegram",
    code: "telegram-members",
    name: "Telegram Members",
    description: "Scale channel audience and strengthen community traction.",
    pricePer1000: 799,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public channel/group URL.",
    isActive: true,
  },
  {
    platform: "tiktok",
    code: "tiktok-followers",
    name: "TikTok Followers",
    description: "Build profile momentum with quality follower growth.",
    pricePer1000: 799,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public profile URL.",
    isActive: true,
  },
  {
    platform: "tiktok",
    code: "tiktok-likes",
    name: "TikTok Likes",
    description: "Increase engagement strength on short-form content.",
    pricePer1000: 249,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-4 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public post URL.",
    isActive: true,
  },
  {
    platform: "tiktok",
    code: "tiktok-views",
    name: "TikTok Views",
    description: "Improve reach and discovery on short-form videos.",
    pricePer1000: 99,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-3 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public video URL.",
    isActive: true,
  },
  {
    platform: "x",
    code: "x-followers",
    name: "X Followers",
    description: "Increase profile authority and long-term social visibility.",
    pricePer1000: 999,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "2-7 days",
    refillPolicy: "30 days refill",
    qualityType: "Premium",
    importantInstruction: "Use public profile URL and avoid handle changes.",
    isActive: true,
  },
  {
    platform: "x",
    code: "x-likes",
    name: "X Likes",
    description: "Improve engagement and social proof for campaign tweets.",
    pricePer1000: 399,
    minQuantity: 100,
    maxQuantity: 1000000,
    deliveryTime: "1-5 days",
    refillPolicy: "Refill eligible",
    qualityType: "Premium",
    importantInstruction: "Use public post URL.",
    isActive: true,
  },
];

export const activeSmmServices = smmServiceCatalog.filter((service) => service.isActive);
