import { createClient } from "@/lib/supabase/server";
import { adjustBalance, changeUserRole } from "@/app/admin/actions";
import { AdminPageHeader, inputClass, primaryButton } from "@/components/admin/AdminUI";

const money = (value: number | string) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(Number(value));

export default async function UsersPage() {
  const supabase = await createClient();
  const { data: users } = await supabase.from("profiles").select("id, email, full_name, balance, role, created_at, orders(count)").order("created_at", { ascending: false });
  return <main className="mx-auto max-w-[1600px] p-5 sm:p-8"><AdminPageHeader title="Users" description="Review accounts, manage balances, and control administrative access."/><section className="panel-card mt-7 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr>{["User","Joined","Orders","Balance","Role","Balance action","Access"].map((head) => <th key={head} className="px-5 py-3">{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{(users ?? []).map((user) => { const orders = user.orders as unknown as { count: number }[]; return <tr key={user.id} className="hover:bg-slate-50"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className={`grid h-9 w-9 place-items-center rounded-xl text-[10px] font-bold ${user.role === "admin" ? "bg-violet-50 text-violet-600" : "bg-blue-50 text-blue-600"}`}>{(user.full_name || user.email).slice(0,2).toUpperCase()}</span><div><p className="font-semibold">{user.full_name || "Unnamed user"}</p><p className="mt-1 text-[9px] text-slate-400">{user.email}</p></div></div></td><td className="px-5 py-4 text-slate-500">{new Date(user.created_at).toLocaleDateString("en-IN")}</td><td className="px-5 py-4 font-semibold">{orders?.[0]?.count ?? 0}</td><td className="px-5 py-4 font-bold text-[#0a1733]">{money(user.balance)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold capitalize ${user.role === "admin" ? "bg-violet-50 text-violet-700" : "bg-slate-100 text-slate-600"}`}>{user.role}</span></td><td className="px-5 py-4"><details><summary className="cursor-pointer list-none rounded-lg bg-blue-50 px-3 py-2 text-center text-[10px] font-bold text-blue-600">Adjust</summary><form action={adjustBalance} className="mt-3 w-56 rounded-xl border bg-white p-3 shadow-xl"><input type="hidden" name="user_id" value={user.id}/><label className="text-[10px] font-semibold">Amount<input name="amount" type="number" min="0.01" step="0.01" required className={inputClass}/></label><select name="operation" className={`${inputClass} mt-3`}><option value="add">Add balance</option><option value="deduct">Deduct balance</option></select><button className={`${primaryButton} mt-3 w-full`}>Apply adjustment</button></form></details></td><td className="px-5 py-4"><form action={changeUserRole} className="flex gap-2"><input type="hidden" name="user_id" value={user.id}/><select name="role" defaultValue={user.role} className="rounded-lg border border-slate-200 bg-white px-2 py-2 text-[10px]"><option value="user">User</option><option value="admin">Admin</option></select><button className="rounded-lg bg-[#0a1b3d] px-3 py-2 text-[10px] font-bold text-white">Save</button></form></td></tr>; })}</tbody></table></div></section></main>;
}
