import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { updateTransactionStatus } from "@/app/admin/actions";
import { AdminPageHeader, AdminStatus } from "@/components/admin/AdminUI";

const statuses = ["all", "pending", "completed", "failed", "cancelled"];
const money = (value: number | string) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(Number(value));

export default async function TransactionsPage({ searchParams }: { searchParams?: { status?: string } }) {
  const supabase = await createClient(); const filter = statuses.includes(searchParams?.status || "") ? searchParams!.status! : "all";
  let query = supabase.from("transactions").select("id, amount, type, status, created_at, profiles(email, full_name)").order("created_at", { ascending: false }); if (filter !== "all") query = query.eq("status", filter); const { data: transactions } = await query.limit(100);
  return <main className="mx-auto max-w-[1500px] p-5 sm:p-8"><AdminPageHeader title="Transactions" description="Audit wallet credits, debits, refunds, and payment states."/><div className="mt-6 flex flex-wrap gap-2">{statuses.map((status) => <Link key={status} href={status === "all" ? "/admin/transactions" : `/admin/transactions?status=${status}`} className={`rounded-xl px-3.5 py-2.5 text-xs font-semibold capitalize ${filter === status ? "bg-blue-600 text-white" : "border border-slate-200 bg-white text-slate-500"}`}>{status}</Link>)}</div><section className="panel-card mt-5 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr>{["Transaction","User","Date","Type","Amount","Status","Manage"].map((head) => <th key={head} className="px-5 py-3">{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{(transactions ?? []).map((transaction) => { const profile = transaction.profiles as unknown as { full_name?: string; email?: string } | null; return <tr key={transaction.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-bold text-blue-600">#{transaction.id.slice(0,8).toUpperCase()}</td><td className="px-5 py-4"><p className="font-semibold">{profile?.full_name || "User"}</p><p className="mt-1 text-[9px] text-slate-400">{profile?.email}</p></td><td className="px-5 py-4 text-slate-500">{new Date(transaction.created_at).toLocaleString("en-IN")}</td><td className="px-5 py-4 font-semibold capitalize">{transaction.type}</td><td className={`px-5 py-4 font-bold ${transaction.type === "credit" || transaction.type === "refund" ? "text-emerald-600" : "text-slate-800"}`}>{money(transaction.amount)}</td><td className="px-5 py-4"><AdminStatus value={transaction.status}/></td><td className="px-5 py-4"><form action={updateTransactionStatus} className="flex gap-2"><input type="hidden" name="id" value={transaction.id}/><select name="status" defaultValue={transaction.status} className="rounded-lg border border-slate-200 px-2 py-2 text-[10px]">{statuses.slice(1).map((status) => <option key={status}>{status}</option>)}</select><button className="rounded-lg bg-[#0a1b3d] px-3 py-2 text-[10px] font-bold text-white">Save</button></form></td></tr>; })}{!transactions?.length && <tr><td colSpan={7} className="p-14 text-center text-slate-400">No transactions found.</td></tr>}</tbody></table></div></section></main>;
}
