import { createClient } from "@/lib/supabase/server";
import { acknowledgeIncident, resolveIncident } from "../actions";

const stamp = (value: string) => new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
export default async function IncidentsPage({ searchParams }: { searchParams: { status?: string; severity?: string } }) {
  const db = await createClient(); let query = db.from("operational_incidents").select("id,incident_type,severity,status,title,safe_summary,source,first_seen_at,last_seen_at,occurrence_count,resolution_note", { count: "exact" }).order("last_seen_at", { ascending: false }).limit(50);
  if (["open", "acknowledged", "resolved"].includes(searchParams.status || "")) query = query.eq("status", searchParams.status!);
  if (["critical", "high", "medium", "low", "informational"].includes(searchParams.severity || "")) query = query.eq("severity", searchParams.severity!);
  const { data, error, count } = await query;
  return <main className="mx-auto max-w-[1400px] px-4 pb-8 pt-6 sm:px-8"><header><p className="text-[10px] font-black uppercase tracking-[.16em] text-orange-300">Operations</p><h1 className="mt-2 text-3xl font-black text-white">Incidents</h1><p className="mt-2 text-sm text-slate-300">Privacy-safe operational signals. {count ?? 0} recent incidents.</p></header><form className="mt-5 flex flex-wrap gap-3" aria-label="Filter incidents"><select name="status" defaultValue={searchParams.status} className="min-h-11 rounded-xl border border-white/15 bg-[#121212] px-3 text-sm"><option value="">All statuses</option><option value="open">Open</option><option value="acknowledged">Acknowledged</option><option value="resolved">Resolved</option></select><select name="severity" defaultValue={searchParams.severity} className="min-h-11 rounded-xl border border-white/15 bg-[#121212] px-3 text-sm"><option value="">All severities</option>{["critical","high","medium","low","informational"].map(x=><option key={x} value={x}>{x}</option>)}</select><button className="min-h-11 rounded-xl border border-orange-400/30 px-4 text-sm font-bold text-orange-200">Apply</button></form>{error ? <p role="alert" className="mt-6 rounded-xl bg-red-500/10 p-4 text-red-100">Incidents could not be loaded.</p> : <div className="mt-6 grid gap-4">{(data ?? []).map(i=><article key={i.id} className="dashboard-glass p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wide text-orange-300">{i.severity} · {i.status}</p><h2 className="mt-1 font-black text-white">{i.title}</h2><p className="mt-2 max-w-3xl break-words text-sm text-slate-300">{i.safe_summary}</p><p className="mt-3 text-xs text-slate-400">{i.incident_type} · {i.source} · Seen {stamp(i.first_seen_at)} · Last seen {stamp(i.last_seen_at)} · {i.occurrence_count} occurrences</p></div>{i.status !== "resolved" && <div className="flex flex-wrap gap-2">{i.status === "open" && <form action={acknowledgeIncident}><input type="hidden" name="id" value={i.id}/><button aria-label={`Acknowledge ${i.title}`} className="min-h-11 rounded-xl border border-white/20 px-3 text-xs font-bold">Acknowledge</button></form>}<form action={resolveIncident} className="flex gap-2"><input type="hidden" name="id" value={i.id}/><input name="note" required minLength={3} maxLength={1000} aria-label={`Resolution note for ${i.title}`} placeholder="Resolution note" className="min-h-11 w-40 rounded-xl border border-white/15 bg-[#111] px-3 text-xs"/><button className="min-h-11 rounded-xl bg-emerald-500/20 px-3 text-xs font-bold text-emerald-100">Resolve</button></form></div>}</div></article>)}{!data?.length && <p className="dashboard-glass p-5 text-sm text-slate-400">No incidents match these filters.</p>}</div>}</main>;
}
