"use client";

import { AlertTriangle, ArrowUpRight, CheckCircle2, CircleDashed, Clock3, Eye, Layers3, Plus, RefreshCw, RotateCcw, Search, UsersRound, XCircle } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import PlatformIcon from "@/components/PlatformIcon";
import { track } from "@/lib/analytics/events";
import { formatCurrency } from "@/lib/currency";
import { usePreferredCurrency } from "@/lib/currency/use-currency";
import { customerOrderServices } from "@/lib/order-service-experience";
import { customerOrderStatus, customerStatusClass } from "@/lib/customer-order-status";
import { formatPublicOrderId } from "@/lib/orders/public-reference";
import { createClient } from "@/lib/supabase/client";

type Campaign={id:string;publicOrderId:string;service:string;platform:string;link:string;quantity:number;amount:number;status:string;paymentStatus:string;createdAt:string;packageName:string|null;deliveredCount:number|null;remains:number|null;progress:number|null;deliveryTime:string|null;refillPolicy:string|null;refillEligible:boolean;refillRequestedAt:string|null};
const activeStatuses=["pending","processing","in_progress","partial","refill_requested","refilling"];
const statusIcons:Record<string,typeof Clock3>={completed:CheckCircle2,cancelled:XCircle,failed:AlertTriangle,processing:RefreshCw,in_progress:RefreshCw,refilling:RefreshCw};
function StatusBadge({status}:{status:string}){const Icon=statusIcons[status]||Clock3;return <span className={`inline-flex max-w-full items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-bold ${customerStatusClass(status)}`}><Icon className="h-3 w-3 shrink-0"/><span className="truncate">{customerOrderStatus(status).label}</span></span>}
function PaymentBadge({status}:{status:string}){return status==="verification_pending"?<span className="inline-flex items-center gap-1 rounded-full border border-orange-400/30 bg-orange-500/10 px-2 py-1 text-[10px] font-bold text-orange-200"><Clock3 className="h-3 w-3"/>Payment verification</span>:null}
function reorderHref(item:Campaign){const service=customerOrderServices.find(c=>c.name.toLowerCase()===item.service.toLowerCase())??customerOrderServices.find(c=>c.platform===item.platform.toLowerCase()&&item.service.toLowerCase().includes(c.code.split("-").pop()||""));return service?`/dashboard/new-order?${new URLSearchParams({platform:service.platform,service:service.code,quantity:String(item.quantity),link:item.link,resume:"1"})}`:null}
function repeat(item:Campaign,source:string){track("repeat_order_click",{platform:item.platform.toLowerCase(),order_id:item.id,source})}
function growthPath(source:string){track("repeat_growth_path_click",{source})}
export default function CampaignHistoryPage(){const {currency,rates}=usePreferredCurrency("INR");const money=(v:number)=>formatCurrency(v,currency,rates);const[campaigns,setCampaigns]=useState<Campaign[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[platform,setPlatform]=useState("all"),[error,setError]=useState(""),[reload,setReload]=useState(0);
useEffect(()=>{const load=async()=>{setLoading(true);setError("");const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){setError("Orders could not be loaded right now.");setLoading(false);return}const{data,error:e}=await s.from("orders").select("id, public_order_id, service_name, platform, link, quantity, charge, status, payment_status, created_at, package_name, delivered_count, remaining_count, progress_percent, refill_eligible, refill_requested_at, services(name, delivery_time, refill_policy, categories(name))").eq("user_id",user.id).order("created_at",{ascending:false});if(e){setError("Orders could not be loaded right now.");setLoading(false);return}setCampaigns((data??[]).map(r=>{const sv=r.services as unknown as {name?:string;delivery_time?:string;refill_policy?:string;categories?:{name?:string}|null}|null;return{id:r.id,publicOrderId:formatPublicOrderId(r.public_order_id),service:r.service_name||sv?.name||"Growth service",platform:r.platform||sv?.categories?.name?.split(" ")[0]||"Other",link:r.link||"",quantity:Number(r.quantity??0),amount:Number(r.charge??0),status:r.status||"pending",paymentStatus:r.payment_status||"paid",createdAt:r.created_at,packageName:r.package_name,deliveredCount:r.delivered_count===null?null:Number(r.delivered_count),remains:r.remaining_count===null?null:Number(r.remaining_count),progress:r.progress_percent===null?null:Number(r.progress_percent),deliveryTime:sv?.delivery_time||null,refillPolicy:sv?.refill_policy||null,refillEligible:Boolean(r.refill_eligible),refillRequestedAt:r.refill_requested_at||null}}));setLoading(false)};void load()},[reload]);
const platforms=useMemo(()=>Array.from(new Set(campaigns.map(i=>i.platform))).sort(),[campaigns]);const statuses=useMemo(()=>Array.from(new Set(campaigns.map(i=>i.status))).sort(),[campaigns]);const filtered=useMemo(()=>campaigns.filter(i=>`${i.publicOrderId} ${i.platform} ${i.service}`.toLowerCase().includes(search.toLowerCase())&&(status==="all"||i.status===status)&&(platform==="all"||i.platform===platform)),[campaigns,platform,search,status]);const summary=useMemo(()=>({total:campaigns.length,active:campaigns.filter(i=>activeStatuses.includes(i.status)).length,completed:campaigns.filter(i=>i.status==="completed").length,pending:campaigns.filter(i=>i.status==="pending").length,payment:campaigns.filter(i=>i.paymentStatus==="verification_pending").length}),[campaigns]);const last=campaigns.find(i=>i.status==="completed"&&reorderHref(i));const reset=()=>{setSearch("");setStatus("all");setPlatform("all")};
return <main className="min-h-[calc(100vh-5rem)] bg-[radial-gradient(circle_at_top_left,rgba(255,122,0,.13),transparent_30%),#050505] p-4 text-white sm:p-6 lg:p-8"><div className="mx-auto max-w-[1500px]"><header className="flex flex-col gap-5 border-b border-white/10 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-orange-300">Orders</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Your campaigns</h1><p className="mt-2 text-sm text-slate-400">Track delivery, payment and refill status, then repeat successful campaigns faster.</p></div><Link href="/dashboard/new-order" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#FF7A00] to-[#FFB000] px-5 text-sm font-black"><Plus className="h-4 w-4"/>Place New Order</Link></header>
<section className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-5">{[["Total",summary.total,CircleDashed],["Active",summary.active,RefreshCw],["Completed",summary.completed,CheckCircle2],["Pending",summary.pending,Clock3],["Payment Check",summary.payment,Clock3]].map(([l,v,I])=>{const Icon=I as typeof Clock3;return <article key={String(l)} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.13em] text-slate-400"><Icon className="h-4 w-4"/>{String(l)}</p><p className="mt-2 text-2xl font-black">{String(v)}</p></article>})}</section>
{last?<section className="mt-5 rounded-2xl border border-orange-400/20 bg-orange-500/[.07] p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-orange-300">Repeat revenue</p><h2 className="mt-1 text-lg font-black">Repeat your latest successful campaign</h2><p className="mt-1 text-xs text-slate-400">Service, quantity and link are prefilled. Current live pricing is shown before checkout.</p></div><Link href={reorderHref(last)!} onClick={()=>repeat(last,"order_history_buy_again")} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#FF7A00] to-[#FFB000] px-4 text-sm font-black"><RotateCcw className="h-4 w-4"/>Repeat last order</Link></div></section>:null}
<section className="mt-5 grid gap-3 lg:grid-cols-3"><Link href="/dashboard/campaign-stacks" onClick={()=>growthPath("order_history_campaign_stacks")} className="group rounded-2xl border border-orange-400/20 bg-orange-500/[.06] p-4 transition hover:border-orange-400/40"><Layers3 className="h-5 w-5 text-orange-300"/><h2 className="mt-3 font-black">Build a broader campaign</h2><p className="mt-1 text-xs leading-5 text-slate-400">Compare complementary services at current catalog pricing and review each order separately.</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-black text-orange-200">Explore campaign stacks <ArrowUpRight className="h-3.5 w-3.5"/></span></Link><Link href="/packages" onClick={()=>growthPath("order_history_packages")} className="group rounded-2xl border border-white/10 bg-white/[.035] p-4 transition hover:border-orange-400/30"><Plus className="h-5 w-5 text-orange-300"/><h2 className="mt-3 font-black">Compare larger requirements</h2><p className="mt-1 text-xs leading-5 text-slate-400">Review current package and quantity options when a single repeat order is not enough.</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-black text-orange-200">Compare packages <ArrowUpRight className="h-3.5 w-3.5"/></span></Link><Link href="/for-agencies#bulk-lead-engine" onClick={()=>growthPath("order_history_agency")} className="group rounded-2xl border border-white/10 bg-white/[.035] p-4 transition hover:border-orange-400/30"><UsersRound className="h-5 w-5 text-orange-300"/><h2 className="mt-3 font-black">Recurring or bulk requirement?</h2><p className="mt-1 text-xs leading-5 text-slate-400">Share platform, expected quantity, frequency and campaign scope for an agency or reseller requirement.</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-black text-orange-200">Discuss bulk requirement <ArrowUpRight className="h-3.5 w-3.5"/></span></Link></section>
<section className="mt-5 rounded-2xl border border-white/10 bg-[#101116] p-3 sm:p-4"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><label className="relative"><Search className="absolute left-3 top-4 h-4 w-4 text-orange-300"/><input value={search} onChange={e=>setSearch(e.target.value)} className="min-h-12 w-full rounded-xl border border-white/10 bg-black/25 pl-10 pr-3 text-sm" placeholder="Search orders"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="min-h-12 rounded-xl border border-white/10 bg-black/25 px-3 text-sm"><option value="all">All statuses</option>{statuses.map(i=><option key={i} value={i}>{customerOrderStatus(i).label}</option>)}</select><select value={platform} onChange={e=>setPlatform(e.target.value)} className="min-h-12 rounded-xl border border-white/10 bg-black/25 px-3 text-sm"><option value="all">All platforms</option>{platforms.map(i=><option key={i}>{i}</option>)}</select><button onClick={reset} className="min-h-12 rounded-xl border border-white/10 text-sm font-bold">Reset</button></div></section>
{loading?<p className="mt-8 text-center text-slate-400">Loading orders…</p>:error?<div className="mt-8 text-center"><p>{error}</p><button onClick={()=>setReload(v=>v+1)} className="mt-3 rounded-xl bg-orange-500 px-4 py-2 font-bold">Try again</button></div>:<section className="mt-5 grid gap-3">{filtered.map(i=><Card key={i.id} item={i} money={money}/>)}{!filtered.length?<p className="rounded-2xl border border-white/10 p-8 text-center text-slate-400">No orders match these filters.</p>:null}</section>}</div></main>}
function Card({item,money}:{item:Campaign;money:(v:number)=>string}){const reorder=reorderHref(item);const progress=item.progress===null?null:Math.max(0,Math.min(100,item.progress));return <article className="rounded-2xl border border-white/10 bg-[#101116] p-4 sm:p-5"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><PlatformIcon platform={item.platform} className="h-5 w-5"/><h2 className="font-black">{item.service}</h2><StatusBadge status={item.status}/><PaymentBadge status={item.paymentStatus}/></div><p className="mt-2 text-xs text-slate-400">{item.publicOrderId} · {new Date(item.createdAt).toLocaleDateString("en-IN")} · {money(item.amount)}</p>{item.link?<a href={item.link} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex max-w-full items-center gap-1 text-xs text-orange-200"><span className="truncate">{item.link}</span><ArrowUpRight className="h-3 w-3"/></a>:null}<div className="mt-4 grid gap-2 sm:grid-cols-3"><Info label="Ordered" value={item.quantity.toLocaleString("en-IN")}/><Info label="Delivered" value={item.deliveredCount===null?"Updating":item.deliveredCount.toLocaleString("en-IN")}/><Info label="Remaining" value={item.remains===null?"Updating":item.remains.toLocaleString("en-IN")}/></div>{progress!==null?<div className="mt-4"><div className="mb-1 flex justify-between text-[10px] text-slate-400"><span>Delivery progress</span><span>{Math.round(progress)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-[#FF7A00] to-[#FFB000]" style={{width:`${progress}%`}}/></div></div>:null}<div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-[10px] text-slate-500">{item.deliveryTime?<span>Delivery: {item.deliveryTime}</span>:null}{item.refillPolicy?<span>Refill: {item.refillPolicy}</span>:null}{item.refillEligible?<span className="text-emerald-300">Refill eligible</span>:null}{item.refillRequestedAt?<span className="text-orange-200">Refill requested</span>:null}</div></div><div className="flex shrink-0 flex-col gap-2 sm:flex-row lg:flex-col"><Link href={`/dashboard/orders/${item.id}`} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-orange-400/25 bg-orange-500/10 px-4 text-sm font-bold text-orange-100"><Eye className="h-4 w-4"/>View Details</Link>{reorder&&item.status==="completed"?<Link href={reorder} onClick={()=>repeat(item,"order_history_card")} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#FF7A00] to-[#FFB000] px-4 text-sm font-black"><RotateCcw className="h-4 w-4"/>Order Again</Link>:null}</div></div></article>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/[.07] bg-black/20 p-3"><p className="text-[9px] font-black uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-1 text-sm font-bold text-white">{value}</p></div>}
