"use client";

import { AlertTriangle, ArrowUpRight, CheckCircle2, CircleDashed, Clock3, Eye, Plus, RefreshCw, RotateCcw, Search, XCircle } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import PlatformIcon from "@/components/PlatformIcon";
import { track } from "@/lib/analytics/events";
import { formatCurrency } from "@/lib/currency";
import { usePreferredCurrency } from "@/lib/currency/use-currency";
import { customerOrderServices } from "@/lib/order-service-experience";
import { customerOrderStatus, customerStatusClass } from "@/lib/customer-order-status";
import { formatPublicOrderId } from "@/lib/orders/public-reference";
import { createClient } from "@/lib/supabase/client";

type Campaign = { id:string; publicOrderId:string; service:string; platform:string; link:string; quantity:number; amount:number; status:string; paymentStatus:string; createdAt:string; packageName:string|null; deliveredCount:number|null; remains:number|null; progress:number|null; deliveryTime:string|null; refillPolicy:string|null; refillEligible:boolean; refillRequestedAt:string|null };
const activeStatuses=["pending","processing","in_progress","partial","refill_requested","refilling"];
const statusIcons:Record<string,typeof Clock3>={completed:CheckCircle2,cancelled:XCircle,failed:AlertTriangle,processing:RefreshCw,in_progress:RefreshCw,refilling:RefreshCw};
function StatusBadge({status}:{status:string}){const Icon=statusIcons[status]||Clock3;return <span className={`inline-flex max-w-full items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-bold ${customerStatusClass(status)}`}><Icon className="h-3 w-3 shrink-0"/><span className="truncate">{customerOrderStatus(status).label}</span></span>}
function PaymentVerificationBadge({paymentStatus}:{paymentStatus:string}){return paymentStatus==="verification_pending"?<span className="ml-1 inline-flex items-center gap-1 rounded-full border border-orange-400/30 bg-orange-500/10 px-2.5 py-1 text-[10px] font-bold text-orange-200"><Clock3 className="h-3 w-3"/>Payment verification</span>:null}
function reorderHref(item:Campaign){const service=customerOrderServices.find(c=>c.name.toLowerCase()===item.service.toLowerCase())??customerOrderServices.find(c=>c.platform===item.platform.toLowerCase()&&item.service.toLowerCase().includes(c.code.split("-").pop()||""));return service?`/dashboard/new-order?${new URLSearchParams({platform:service.platform,service:service.code,quantity:String(item.quantity),link:item.link,resume:"1"})}`:null}
function trackRepeat(item:Campaign,source:string){track("repeat_order_click",{platform:item.platform.toLowerCase(),order_id:item.id,source})}
export default function CampaignHistoryPage(){
 const {currency,rates}=usePreferredCurrency("INR"); const money=(v:number)=>formatCurrency(v,currency,rates);
 const [campaigns,setCampaigns]=useState<Campaign[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[platform,setPlatform]=useState("all"),[loadError,setLoadError]=useState(""); const [reloadKey,setReloadKey]=useState(0);
 useEffect(()=>{const load=async()=>{setLoading(true);setLoadError("");const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){setLoadError("Orders could not be loaded right now.");setLoading(false);return}const {data,error}=await supabase.from("orders").select("id, public_order_id, service_name, platform, link, quantity, charge, status, payment_status, created_at, package_name, delivered_count, remaining_count, progress_percent, refill_eligible, refill_requested_at, services(name, delivery_time, refill_policy, categories(name))").eq("user_id",user.id).order("created_at",{ascending:false});if(error){setLoadError("Orders could not be loaded right now.");setLoading(false);return}setCampaigns((data??[]).map(row=>{const service=row.services as unknown as {name?:string;delivery_time?:string;refill_policy?:string;categories?:{name?:string}|null}|null;return{id:row.id,publicOrderId:formatPublicOrderId(row.public_order_id),service:row.service_name||service?.name||"Growth service",platform:row.platform||service?.categories?.name?.split(" ")[0]||"Other",link:row.link||"",quantity:Number(row.quantity??0),amount:Number(row.charge??0),status:row.status||"pending",paymentStatus:row.payment_status||"paid",createdAt:row.created_at,packageName:row.package_name,deliveredCount:row.delivered_count===null?null:Number(row.delivered_count),remains:row.remaining_count===null?null:Number(row.remaining_count),progress:row.progress_percent===null?null:Number(row.progress_percent),deliveryTime:service?.delivery_time||null,refillPolicy:service?.refill_policy||null,refillEligible:Boolean(row.refill_eligible),refillRequestedAt:row.refill_requested_at||null}}));setLoading(false)};void load()},[reloadKey]);
 const platforms=useMemo(()=>Array.from(new Set(campaigns.map(i=>i.platform))).sort(),[campaigns]); const availableStatuses=useMemo(()=>Array.from(new Set(campaigns.map(i=>i.status))).sort(),[campaigns]); const filtered=useMemo(()=>campaigns.filter(i=>`${i.publicOrderId} ${i.platform} ${i.service}`.toLowerCase().includes(search.toLowerCase())&&(status==="all"||i.status===status)&&(platform==="all"||i.platform===platform)),[campaigns,platform,search,status]);
 const summary=useMemo(()=>({total:campaigns.length,active:campaigns.filter(i=>activeStatuses.includes(i.status)).length,completed:campaigns.filter(i=>i.status==="completed").length,pending:campaigns.filter(i=>i.status==="pending").length,verificationPending:campaigns.filter(i=>i.paymentStatus==="verification_pending").length}),[campaigns]); const repeatable=useMemo(()=>campaigns.filter(i=>i.status==="completed"&&reorderHref(i)),[campaigns]); const reset=()=>{setSearch("");setStatus("all");setPlatform("all")}; const hasFilters=Boolean(search||status!=="all"||platform!=="all");
 return <main className="min-h-[calc(100vh-5rem)] bg-[#050505] p-4 text-white sm:p-6 lg:p-8"><div className="mx-auto max-w-[1500px]">
 <header className="flex flex-col gap-5 border-b border-white/10 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-orange-300">Orders</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Your campaigns</h1><p className="mt-2 text-sm text-slate-400">Track campaigns, verify payments and quickly repeat successful orders.</p></div><Link href="/dashboard/new-order" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#FF7A00] to-[#FFB000] px-5 text-sm font-black"><Plus className="h-4 w-4"/>Place New Order</Link></header>
 <section className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-5">{[["Total Orders",summary.total],["Active / Processing",summary.active],["Completed",summary.completed],["Pending",summary.pending],["Payment Check",summary.verificationPending]].map(([l,v])=><article key={String(l)} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-[9px] font-black uppercase tracking-[.13em] text-slate-400">{l}</p><p className="mt-2 text-2xl font-black">{v}</p></article>)}</section>
 {!loading&&!loadError&&repeatable[0]?<section className="mt-5 rounded-2xl border border-orange-400/20 bg-orange-500/[.07] p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-orange-300">Repeat faster</p><h2 className="mt-1 text-lg font-black">Buy again in one click</h2><p className="mt-1 text-xs leading-5 text-slate-400">Reuse the service, quantity and profile link from your latest completed campaign. Current live pricing applies before checkout.</p></div><Link href={reorderHref(repeatable[0])!} onClick={()=>trackRepeat(repeatable[0],"order_history_buy_again")} className="inline-flex min-h-11 shrink-0 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#FF7A00] to-[#FFB000] px-4 text-sm font-black"><RotateCcw className="h-4 w-4"/>Repeat last order</Link></div></section>:null}
 <section className="mt-5 rounded-2xl border border-white/10 bg-[#101116] p-3 sm:p-4"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><label className="relative"><Search className="absolute left-3 top-4 h-4 w-4 text-orange-300"/><input value={search} onChange={e=>setSearch(e.target.value)} className="min-h-12 w-full rounded-xl border border-white/10 bg-black/25 pl-10 pr-3 text-sm" placeholder="Search orders"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="min-h-12 rounded-xl border border-white/10 bg-black/25 px-3 text-sm"><option value="all">All statuses</option>{availableStatuses.map(i=><option key={i} value={i}>{customerOrderStatus(i).label}</option>)}</select><select value={platform} onChange={e=>setPlatform(e.target.value)} className="min-h-12 rounded-xl border border-white/10 bg-black/25 px-3 text-sm"><option value="all">All platforms</option>{platforms.map(i=><option key={i}>{i}</option>)}</select><button disabled={!hasFilters} onClick={reset} className="min-h-12 rounded-xl border border-white/10 text-sm font-bold disabled:opacity-40">Reset</button></div></section>
 {loading?<p className="mt-8 text-center text-slate-400">Loading orders…</p>:loadError?<div className="mt-8 text-center"><p>{loadError}</p><button onClick={()=>setReloadKey(v=>v+1)} className="mt-3 rounded-xl bg-orange-500 px-4 py-2 font-bold">Try again</button></div>:<section className="mt-5 grid gap-3">{filtered.map(item=><OrderCard key={item.id} item={item} money={money}/>)}{!filtered.length?<p className="rounded-2xl border border-white/10 p-8 text-center text-slate-400">No orders match these filters.</p>:null}</section>}
 </div></main>}
function OrderCard({item,money}:{item:Campaign;money:(v:number)=>string}){const reorder=reorderHref(item);return <article className="rounded-2xl border border-white/10 bg-[#101116] p-4 sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><PlatformIcon platform={item.platform} className="h-5 w-5"/><h2 className="font-black">{item.service}</h2><StatusBadge status={item.status}/><PaymentVerificationBadge paymentStatus={item.paymentStatus}/></div><p className="mt-2 text-xs text-slate-400">{item.publicOrderId} · {item.quantity.toLocaleString("en-IN")} · {money(item.amount)}</p>{item.link?<a href={item.link} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex max-w-full items-center gap-1 text-xs text-orange-200"><span className="truncate">{item.link}</span><ArrowUpRight className="h-3 w-3"/></a>:null}</div><div className="flex flex-col gap-2 sm:flex-row"><Link href={`/dashboard/orders/${item.id}`} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-orange-400/25 bg-orange-500/10 px-4 text-sm font-bold text-orange-100"><Eye className="h-4 w-4"/>View Details</Link>{reorder&&item.status==="completed"?<Link href={reorder} onClick={()=>trackRepeat(item,"order_history_card")} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#FF7A00] to-[#FFB000] px-4 text-sm font-black"><RotateCcw className="h-4 w-4"/>Order Again</Link>:null}</div></div></article>}
