import { createClient } from "@/lib/supabase/server";
import { addCategory, deleteCategory, updateCategory } from "@/app/admin/actions";
import { AdminPageHeader, Modal, inputClass, primaryButton } from "@/components/admin/AdminUI";
import PlatformIcon from "@/components/PlatformIcon";

export default async function CategoriesPage() {
  const supabase = await createClient();
  const { data: categories } = await supabase.from("categories").select("id, name, services(count)").order("name");
  return <main className="mx-auto max-w-[1200px] p-4 sm:p-8"><AdminPageHeader title="Categories" description="Organize your service catalog by social platform or service type." action={<Modal label="+ Add category" title="Create category"><form action={addCategory}><label className="text-xs font-semibold">Category name<input name="name" required className={inputClass} placeholder="e.g. TikTok"/></label><button className={`${primaryButton} mt-5 w-full`}>Add category</button></form></Modal>}/><section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{(categories ?? []).map((category) => { const count = category.services as unknown as { count: number }[]; return <article key={category.id} className="panel-card p-5"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-orange-50 text-orange-600"><PlatformIcon platform={category.name} className="h-5 w-5" /></span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold text-slate-500">{count?.[0]?.count ?? 0} services</span></div><h2 className="mt-5 text-sm font-bold">{category.name}</h2><p className="mt-1 text-xs text-slate-400">Category #{category.id}</p><div className="mt-5 flex flex-wrap gap-2 border-t border-slate-100 pt-4"><Modal label="Edit" title={`Edit ${category.name}`}><form action={updateCategory}><input type="hidden" name="id" value={category.id}/><label className="text-xs font-semibold">Category name<input name="name" required defaultValue={category.name} className={inputClass}/></label><button className={`${primaryButton} mt-5 w-full`}>Save changes</button></form></Modal><form action={deleteCategory}><input type="hidden" name="id" value={category.id}/><button className="rounded-xl bg-rose-50 px-4 py-3 text-xs font-bold text-rose-600 hover:bg-rose-100">Delete</button></form></div></article>; })}{!categories?.length && <p className="text-sm text-slate-400">No categories found.</p>}</section></main>;
}
