import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { isUuid } from "@/lib/security/request";
import { formatPublicOrderId } from "@/lib/orders/public-reference";

const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" })[character] || character);
const money = (value: number) => new Intl.NumberFormat("en-IN", { style:"currency", currency:"INR" }).format(value);
export async function GET(_: Request, { params }: { params: { id: string } }) {
  if (!isUuid(params.id)) return NextResponse.json({ error: "Invalid order reference." }, { status: 422 });
  const supabase = await createClient(); const { data:{ user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { data: order, error } = await supabase.from("orders").select("id,public_order_id,created_at,platform,service_name,quantity,unit_price,charge,payment_status,status,link,profiles(full_name,email)").eq("id",params.id).maybeSingle();
  if (error) return NextResponse.json({ error:"Receipt could not be generated." },{status:400}); if (!order) return NextResponse.json({ error:"Order not found." },{status:404});
  if (!['paid','completed'].includes(String(order.payment_status || '').toLowerCase()) && !['completed','processing','in_progress','partial','refilling','refill_requested'].includes(order.status)) return NextResponse.json({ error:"A receipt is available after payment is confirmed." },{status:409});
  const profile = order.profiles as unknown as { full_name?:string; email?:string } | null; const reference=formatPublicOrderId(order.public_order_id); const date=new Date(order.created_at).toLocaleString("en-IN");
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>SocialRUSH receipt ${escapeHtml(reference)}</title><style>body{font-family:Arial,sans-serif;color:#15171c;margin:0;padding:40px;background:#f4f4f5}.receipt{max-width:760px;margin:auto;background:#fff;padding:42px;border-top:7px solid #ff7600;box-shadow:0 8px 30px #0002}h1{margin:0;color:#111;font-size:30px}.brand{color:#ff7600;font-weight:800;letter-spacing:1px}.muted{color:#64748b}table{width:100%;border-collapse:collapse;margin-top:28px}th,td{text-align:left;padding:13px;border-bottom:1px solid #e5e7eb;font-size:14px}th{color:#64748b;text-transform:uppercase;font-size:11px;letter-spacing:.7px}.total{font-size:20px;font-weight:800;color:#ff7600}.box{background:#fff7ed;padding:15px;margin-top:24px;border-radius:8px;font-size:13px}@media print{body{padding:0;background:#fff}.receipt{box-shadow:none}}</style></head><body><main class="receipt"><div style="display:flex;justify-content:space-between;gap:20px"><div><div class="brand">SOCIALRUSH</div><h1>Payment Receipt</h1><p class="muted">getSocialRUSH · Generated ${escapeHtml(new Date().toLocaleString("en-IN"))}</p></div><div class="muted"><b>Order</b><br>${escapeHtml(reference)}<br>${escapeHtml(date)}</div></div><table><tr><th>Customer</th><td>${escapeHtml(profile?.full_name || "Customer")}<br><span class="muted">${escapeHtml(profile?.email || user.email || "")}</span></td></tr><tr><th>Platform</th><td>${escapeHtml(order.platform || "Not specified")}</td></tr><tr><th>Service</th><td>${escapeHtml(order.service_name || "Growth service")}</td></tr><tr><th>Quantity</th><td>${escapeHtml(Number(order.quantity).toLocaleString("en-IN"))}</td></tr>${order.unit_price !== null ? `<tr><th>Unit rate</th><td>${escapeHtml(String(order.unit_price))} / 1K</td></tr>` : ""}<tr><th>Payment status</th><td>${escapeHtml(order.payment_status || "Paid")}</td></tr><tr><th>Order status</th><td>${escapeHtml(order.status)}</td></tr><tr><th>Campaign link</th><td style="word-break:break-all">${escapeHtml(order.link)}</td></tr><tr><th>Final amount</th><td class="total">${escapeHtml(money(Number(order.charge)))}</td></tr></table><div class="box">This is a payment receipt for your SocialRUSH order. It does not include tax, GST, or company registration information.</div></main></body></html>`;
  return new NextResponse(html,{headers:{"Content-Type":"text/html; charset=utf-8","Content-Disposition":`attachment; filename="SocialRUSH-${reference}-receipt.html"`,"Cache-Control":"private, no-store"}});
}
