"use client";
import { useState } from "react";
import { saveBlogArticle } from "@/app/admin/actions";

type Block = { type: "paragraph" | "heading" | "bullet_list" | "quote" | "tip" | "important" | "warning" | "example" | "checklist"; text: string; items?: string[] };
const kinds: Block["type"][] = ["paragraph", "heading", "bullet_list", "quote", "tip", "important", "warning", "example", "checklist"];
export default function BlogEditor({ article }: { article?: Record<string, unknown> }) {
  const initial: Block[] = Array.isArray(article?.content) ? article?.content as Block[] : [{ type: "paragraph", text: "" }];
  const [blocks, setBlocks] = useState<Block[]>(initial); const [title, setTitle] = useState(String(article?.title || ""));
  const patch = (index: number, value: Partial<Block>) => setBlocks((all) => all.map((block, i) => i === index ? { ...block, ...value } : block));
  const move = (index: number, amount: number) => setBlocks((all) => { const next = [...all], target = index + amount; if (target < 0 || target >= next.length) return all; [next[index], next[target]] = [next[target], next[index]]; return next; });
  const field = "mt-1 min-h-11 w-full rounded-xl border border-white/10 bg-black/30 px-3 text-white";
  return <form action={saveBlogArticle} className="grid gap-5">
    <input type="hidden" name="id" value={String(article?.id || "")} /><input type="hidden" name="content" value={JSON.stringify(blocks)} />
    <div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Title<input required minLength={10} maxLength={120} name="title" value={title} onChange={(e) => setTitle(e.target.value)} className={field}/></label><label className="text-sm font-bold">Slug<input required name="slug" defaultValue={String(article?.slug || "")} placeholder={title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")} className={field}/></label><label className="text-sm font-bold md:col-span-2">Description<textarea required minLength={50} maxLength={300} name="description" defaultValue={String(article?.description || "")} className={`${field} min-h-24`}/></label><label className="text-sm font-bold">Category<input required name="category" defaultValue={String(article?.category || "")} className={field}/></label><label className="text-sm font-bold">Author (only genuine information)<input name="author_name" defaultValue={String(article?.author_name || "")} className={field}/></label><label className="text-sm font-bold">Hero image URL<input name="hero_image_url" type="url" defaultValue={String(article?.hero_image_url || "")} className={field}/></label><label className="text-sm font-bold">Hero image alt text<input name="hero_image_alt" defaultValue={String(article?.hero_image_alt || "")} className={field}/></label></div>
    <section className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-center justify-between"><h2 className="font-black">Content blocks</h2><button type="button" onClick={() => setBlocks([...blocks, { type: "paragraph", text: "" }])} className="min-h-11 rounded-xl bg-white/10 px-4 font-bold">Add block</button></div><div className="mt-4 grid gap-3">{blocks.map((block,index)=><div key={index} className="rounded-xl border border-white/10 p-3"><div className="flex gap-2"><select value={block.type} onChange={(e)=>patch(index,{type:e.target.value as Block["type"]})} className={field}>{kinds.map(kind=><option key={kind}>{kind}</option>)}</select><button type="button" aria-label="Move block up" onClick={()=>move(index,-1)} className="min-h-11 px-3">↑</button><button type="button" aria-label="Move block down" onClick={()=>move(index,1)} className="min-h-11 px-3">↓</button><button type="button" aria-label="Remove block" onClick={()=>setBlocks(blocks.filter((_,i)=>i!==index))} className="min-h-11 px-3 text-red-300">Remove</button></div><textarea value={block.text} onChange={(e)=>patch(index,{text:e.target.value})} aria-label={`${block.type} text`} className={`${field} mt-2 min-h-24`}/></div>)}</div></section>
    <details className="rounded-2xl border border-white/10 p-4"><summary className="cursor-pointer font-black">SEO, FAQs & publishing</summary><div className="mt-4 grid gap-4 md:grid-cols-2"><label>SEO title<input name="seo_title" defaultValue={String(article?.seo_title || "")} className={field}/></label><label>SEO description<input name="seo_description" defaultValue={String(article?.seo_description || "")} className={field}/></label><label>Related slugs (comma separated)<input name="related_slugs" defaultValue={Array.isArray(article?.related_slugs)?article?.related_slugs.join(","):""} className={field}/></label><label>Redirect destination<input name="redirect_to" defaultValue={String(article?.redirect_to || "")} placeholder="/blog/new-slug" className={field}/></label><label className="md:col-span-2">FAQs (JSON array)<textarea name="faqs" defaultValue={JSON.stringify(article?.faq_items || [])} className={`${field} min-h-24`}/></label><label>Status<select name="status" defaultValue={String(article?.status || "draft")} className={field}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option><option value="redirect">Redirect</option></select></label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" name="featured" value="true" defaultChecked={Boolean(article?.featured)}/> Featured (published only appears publicly)</label></div></details>
    <button className="min-h-12 rounded-xl bg-orange-500 px-5 font-black text-white">Save article</button>
  </form>;
}
