"use client";

import { useMemo, useState, useTransition } from "react";
import { CheckCircle2, Play, ShieldCheck } from "lucide-react";
import { runCrmAutomation, saveAutomationSettings } from "@/app/admin/crm/actions";
import type { CrmAutomationSettings, CrmAutomationRun } from "@/lib/crm/types";

type Props = { settings: CrmAutomationSettings; latest: CrmAutomationRun | null };
type Form = { enabled: boolean; newCustomerDays: number; atRiskDays: number; inactiveDays: number; highValuePercentile: number; vipPercentile: number; vipMinOrders: number; retention: boolean; support: boolean; refill: boolean };
const percentiles = [.8, .85, .9, .95];
const percentileLabel = (p: number) => `Top ${Math.round((1 - p) * 100)}%`;

export default function CrmAutomationsPanel({ settings, latest }: Props) {
  const [form, setForm] = useState<Form>({ enabled: settings.enabled, newCustomerDays: settings.new_customer_days, atRiskDays: settings.at_risk_days, inactiveDays: settings.inactive_days, highValuePercentile: settings.high_value_percentile, vipPercentile: settings.vip_percentile, vipMinOrders: settings.vip_min_orders, retention: settings.create_retention_followups, support: settings.create_support_followups, refill: settings.create_refill_followups });
  const [message, setMessage] = useState<string>(""); const [pending, startTransition] = useTransition(); const changed = useMemo(() => JSON.stringify(form) !== JSON.stringify({ enabled: settings.enabled, newCustomerDays: settings.new_customer_days, atRiskDays: settings.at_risk_days, inactiveDays: settings.inactive_days, highValuePercentile: settings.high_value_percentile, vipPercentile: settings.vip_percentile, vipMinOrders: settings.vip_min_orders, retention: settings.create_retention_followups, support: settings.create_support_followups, refill: settings.create_refill_followups }), [form, settings]);
  const set = <K extends keyof Form>(key: K, value: Form[K]) => setForm(current => ({ ...current, [key]: value }));
  function save() { startTransition(async () => { try { await saveAutomationSettings(form); setMessage("Settings saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Settings could not be saved."); } }); }
  function toggleMaster() { const enabled = !form.enabled; if (!enabled && !window.confirm("Pause CRM automation? Customer and order data will remain unchanged. Automatic CRM classification and follow-up creation will pause until re-enabled.")) return; set("enabled", enabled); startTransition(async () => { try { await saveAutomationSettings({ ...form, enabled }); setMessage(enabled ? "Automation is active." : "Automation is paused."); } catch (error) { set("enabled", !enabled); setMessage(error instanceof Error ? error.message : "Settings could not be saved."); } }); }
  function run() { if (!window.confirm("Run CRM automation now?")) return; startTransition(async () => { try { const result=await runCrmAutomation(); setMessage(result?.status === "completed" ? `Automation completed successfully. ${result.customers_scanned} customers scanned, ${result.tags_added} tags added, ${result.followups_created} follow-ups created.` : "Automation is running. The history will refresh shortly."); } catch (error) { setMessage(error instanceof Error ? error.message : "Automation could not be started."); } }); }
  return <>
    {message && <div role="status" className="mb-5 flex items-center gap-2 rounded-xl border border-orange-400/20 bg-orange-500/[.07] px-4 py-3 text-sm text-orange-100"><CheckCircle2 size={16}/>{message}</div>}
    <div className="mb-6 flex flex-col gap-3 rounded-2xl border border-orange-400/20 bg-gradient-to-r from-orange-500/[.09] to-[#111111] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-white">CRM Automation</h2><p className="mt-1 max-w-2xl text-sm text-[#9CA3AF]">Automatically evaluate customer activity, lifecycle, value and follow-up opportunities each day.</p></div><button type="button" onClick={toggleMaster} disabled={pending} className={`flex shrink-0 items-center gap-3 rounded-xl border px-3 py-2 text-xs font-bold ${form.enabled ? "border-emerald-400/30 bg-emerald-500/10 text-emerald-100" : "border-white/15 bg-white/5 text-[#D1D5DB]"}`}><span className={`h-2.5 w-2.5 rounded-full ${form.enabled ? "bg-emerald-400" : "bg-[#6B7280]"}`}/>{form.enabled ? "ON" : "OFF"}<span className={`relative h-5 w-9 rounded-full ${form.enabled ? "bg-emerald-500" : "bg-[#4B5563]"}`}><span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white transition ${form.enabled ? "left-4.5" : "left-0.5"}`}/></span></button></div>
    <div className="grid gap-5 xl:grid-cols-2">
      <section className="card"><Heading title="Customer Lifecycle Rules" text="Define when customer activity becomes a lifecycle opportunity."/><div className="mt-5 grid gap-4 sm:grid-cols-3"><NumericField label="New customer window" value={form.newCustomerDays} onChange={v=>set("newCustomerDays",v)} helper="1–90 days"/><NumericField label="At risk after" value={form.atRiskDays} onChange={v=>set("atRiskDays",v)} helper="7–365 days"/><NumericField label="Inactive after" value={form.inactiveDays} onChange={v=>set("inactiveDays",v)} helper="14–730 days"/></div><p className="mt-4 text-xs leading-5 text-[#9CA3AF]">A recent first paid order becomes New Customer. Customers without a valid recent order become At Risk, then Inactive.</p></section>
      <section className="card"><Heading title="Customer Value Rules" text="Segments update dynamically as SocialRUSH customer spending changes."/><div className="mt-5 grid gap-4 sm:grid-cols-3"><Select label="High Value" value={form.highValuePercentile} onChange={v=>set("highValuePercentile",v)}/><Select label="VIP" value={form.vipPercentile} onChange={v=>set("vipPercentile",v)}/><NumericField label="VIP minimum orders" value={form.vipMinOrders} onChange={v=>set("vipMinOrders",v)} helper="Valid paid orders"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Threshold label="Current High Value Threshold" value={latest?.details?.high_value_threshold}/><Threshold label="Current VIP Threshold" value={latest?.details?.vip_threshold}/></div></section>
      <section className="card"><Heading title="Automatic Follow-ups" text="Choose which CRM opportunities can create follow-ups automatically."/><div className="mt-4 space-y-3"><Toggle label="Retention follow-ups" text="For At Risk and Inactive customers." checked={form.retention} onChange={v=>set("retention",v)}/><Toggle label="Support follow-ups" text="For unresolved customer support tickets." checked={form.support} onChange={v=>set("support",v)}/><Toggle label="Refill follow-ups" text="For refill requests needing attention." checked={form.refill} onChange={v=>set("refill",v)}/></div></section>
      <section className="card"><Heading title="Manual Override Protection" text="Admin decisions always take priority."/><div className="mt-5 grid gap-3 sm:grid-cols-2"><Protected label="Lifecycle manual overrides"/><Protected label="Priority manual overrides"/></div><p className="mt-4 text-xs leading-5 text-[#9CA3AF]">If an admin manually changes a customer’s lifecycle or priority, automation will not silently overwrite that choice.</p></section>
    </div>
    <section className="card mt-5"><Heading title="Automatic Customer Tags" text="Automation maintains relevant customer context without touching your manual tags."/><div className="mt-4 flex flex-wrap gap-2">{["Repeat Customer","High Value","VIP","Needs Follow-up","Instagram","YouTube","Facebook","LinkedIn","Twitter/X","Telegram","TikTok"].map(tag=><span key={tag} className="rounded-full border border-orange-400/20 bg-orange-500/[.08] px-3 py-1.5 text-xs font-semibold text-orange-100">{tag}</span>)}</div><p className="mt-4 text-xs text-[#9CA3AF]">Manual tags are preserved. Automation manages only tags created by automation.</p></section>
    <div className="sticky bottom-4 z-10 mt-5 flex justify-end"><button type="button" disabled={pending || !changed} onClick={save} className="rounded-xl bg-orange-500 px-5 py-3 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{pending ? "Saving…" : "Save automation settings"}</button></div>
    <button type="button" onClick={run} disabled={pending} className="fixed bottom-5 right-5 z-20 flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-3 text-xs font-bold text-white shadow-lg shadow-orange-950/50 disabled:opacity-60"><Play size={15}/>{pending ? "Running automation…" : "Run Automation Now"}</button>
  </>;
}
function Heading({title,text}:{title:string;text:string}) { return <><h2 className="text-base font-bold text-white">{title}</h2><p className="mt-1 text-sm text-[#9CA3AF]">{text}</p></>; }
function NumericField({label,value,onChange,helper}:{label:string;value:number;onChange:(v:number)=>void;helper:string}) { return <label className="block text-xs font-bold uppercase tracking-wide text-[#D1D5DB]">{label}<div className="mt-2 flex rounded-xl border border-white/10 bg-[#0B0B0F]"><input aria-label={label} type="number" value={value} onChange={e=>onChange(Number(e.target.value))} className="min-w-0 flex-1 bg-transparent px-3 py-2.5 text-sm text-white outline-none"/><span className="py-2.5 pr-3 text-xs text-[#9CA3AF]">days</span></div><span className="mt-1 block normal-case font-normal text-[#6B7280]">{helper}</span></label>; }
function Select({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}) { return <label className="block text-xs font-bold uppercase tracking-wide text-[#D1D5DB]">{label}<select aria-label={label} value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0B0B0F] px-3 py-2.5 text-sm text-white outline-none">{percentiles.map(p=><option key={p} value={p}>{label === "VIP" ? `${percentileLabel(p)} + orders` : percentileLabel(p)}</option>)}</select></label>; }
function Toggle({label,text,checked,onChange}:{label:string;text:string;checked:boolean;onChange:(v:boolean)=>void}) { return <label className="flex cursor-pointer items-center justify-between gap-4 rounded-xl border border-white/10 bg-[#0B0B0F] p-3"><span><b className="block text-sm text-white">{label}</b><span className="mt-1 block text-xs text-[#9CA3AF]">{text}</span></span><input aria-label={label} type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="h-4 w-4 accent-orange-500"/></label>; }
function Threshold({label,value}:{label:string;value:number|undefined}) { return <div className="rounded-xl bg-[#0B0B0F] p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-[#9CA3AF]">{label}</p><b className="mt-1 block text-lg text-white">{typeof value === "number" ? new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(value) : "Available after a run"}</b><p className="mt-1 text-xs text-[#6B7280]">Calculated dynamically from current customer spending.</p></div>; }
function Protected({label}:{label:string}) { return <div className="flex items-center gap-3 rounded-xl bg-emerald-500/[.06] p-4"><ShieldCheck size={18} className="text-emerald-300"/><span><b className="block text-sm text-white">{label}</b><small className="text-emerald-200">Protected</small></span></div>; }
