import type { Metadata } from "next";
import Link from "next/link";
import { Check, Eye, Heart, Link2, ShieldCheck, Sparkles, Zap } from "lucide-react";
import PublicShell from "@/components/marketing/PublicShell";
import InstagramLikesOrderPanel from "@/components/marketing/InstagramLikesOrderPanel";
import PlatformIcon from "@/components/PlatformIcon";
import { SEO_SITE_URL } from "@/lib/seo/metadata";
import { getServiceById } from "@/lib/smm-service-catalog";

// This component is rendered by the canonical /instagram-likes route. The
// legacy /buy-instagram-likes-india route is redirected by middleware, so all
// visible structured data must reinforce the canonical commercial URL.
const path = "/instagram-likes";
const url = `${SEO_SITE_URL}${path}`;
const service = getServiceById("instagram-likes");
const trust = ["No Password Required", "Live Catalog Pricing", "Public Link Ordering", "Order Tracking", "Refill Information", "Secure Checkout"];
const faqs = [
  ["How do I buy Instagram likes?", "Choose a valid quantity, paste the public Instagram post or Reel link, review the live total, then continue through the SocialRUSH order flow."],
  ["Do I need to provide my Instagram password?", "No. This service uses the public link to the post or Reel. SocialRUSH does not require your Instagram password."],
  ["Which Instagram link should I submit?", "Submit the exact public URL for the Instagram post, Reel, or supported video content that should receive likes."],
  ["How is the price calculated?", "The total is calculated from the active Instagram Likes catalog rate and your selected quantity. Your chosen display currency is applied by the existing currency system."],
  ["How long does delivery take?", "The current delivery estimate is displayed in the live order summary and can vary with the active service and order quantity."],
  ["Can I track my order?", "Yes. After continuing through the existing order flow, you can follow status from your SocialRUSH dashboard."],
  ["What does refill mean?", "Refill eligibility and terms are shown by the active catalog before you continue. Review them before placing an order."],
  ["Can I order likes for Reels?", "Yes, where the Reel has a valid public Instagram URL. Use the exact Reel link in the order builder."],
  ["What happens if I submit the wrong link?", "Review the public link before continuing. If it is not a supported Instagram post or Reel URL, the builder will ask you to correct it."],
] as const;
const related = [
  { code: "instagram-followers", title: "Instagram follower packages", copy: "Explore public-profile campaigns with clear delivery information.", href: "/buy-instagram-followers-india", icon: Heart },
  { code: "instagram-views", title: "Instagram Views", copy: "Review options for public post and Reel visibility.", href: "/buy-instagram-views-india", icon: Eye },
  { code: "instagram-likes", title: "Instagram Packages", copy: "Compare active Instagram services in one place.", href: "/packages?platform=instagram", icon: Sparkles },
] as const;
function schema(value: object) { return JSON.stringify(value).replace(/</g, "\\u003c"); }

export const metadata: Metadata = {
  title: { absolute: "Buy Indian Instagram Likes | Live INR Plans | SocialRUSH" },
  description: "Buy Indian Instagram likes with live INR pricing, public post or Reel link ordering, service details before checkout and dashboard tracking.",
  keywords: ["buy Indian Instagram likes", "Indian Instagram likes", "buy Instagram likes India", "buy Instagram likes in rupees", "Instagram likes service India"],
  alternates: { canonical: url },
  openGraph: { type: "website", locale: "en_IN", title: "Buy Indian Instagram Likes | Live INR Plans | SocialRUSH", description: "Build an Instagram likes order with live INR pricing and public-link ordering.", url },
  twitter: { card: "summary_large_image", title: "Buy Indian Instagram Likes | Live INR Plans | SocialRUSH", description: "Live INR pricing, public-link ordering and dashboard tracking." },
};

export default function Page() {
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: SEO_SITE_URL }, { "@type": "ListItem", position: 2, name: "Instagram Likes", item: url }] };
  return <PublicShell tone="light3d"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: schema(faqSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: schema(breadcrumbSchema) }} />
    <section className="relative overflow-hidden px-4 pb-14 pt-14 sm:px-6 sm:pt-20 lg:px-8 lg:pb-20"><div className="absolute -left-20 top-0 h-80 w-80 rounded-full bg-orange-500/20 blur-3xl" /><div className="absolute right-0 top-16 h-72 w-72 rounded-full bg-fuchsia-500/10 blur-3xl" /><div className="relative mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.12fr_.88fr]"><div><span className="inline-flex items-center gap-2 rounded-full border border-orange-400/30 bg-[#151515]/80 px-3 py-2 text-[10px] font-black uppercase tracking-[.14em] text-orange-200"><PlatformIcon platform="Instagram" className="h-4 w-4" />Instagram Likes Service</span><h1 className="mt-6 max-w-3xl text-4xl font-black leading-[1.08] tracking-[-.04em] text-white sm:text-5xl lg:text-6xl">Buy Instagram Likes <span className="bg-gradient-to-r from-orange-300 via-amber-300 to-orange-400 bg-clip-text text-transparent">in India</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-[#D1D5DB] sm:text-lg">Build an Instagram likes order with live pricing, a public post or Reel link, and current delivery information shown before you continue to checkout.</p><div className="mt-8 flex flex-col gap-3 min-[420px]:flex-row"><a href="#packages" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-gradient-to-r from-[#FF7A00] to-[#FFB000] px-6 text-sm font-black text-white shadow-[0_18px_34px_-14px_rgba(255,196,0,.75)] transition hover:-translate-y-0.5">Start Your Order</a><Link href="/packages?platform=instagram" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-orange-400/30 bg-[#151515] px-6 text-sm font-black text-orange-100">View Instagram Packages</Link></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-3">{["No Password Required", "Transparent Pricing", "Order Tracking"].map(item => <span key={item} className="flex items-center gap-2 text-xs font-bold text-[#D1D5DB]"><Check className="h-4 w-4 text-orange-300" />{item}</span>)}</div></div>
      <aside className="relative overflow-hidden rounded-[2rem] border border-orange-400/25 bg-[linear-gradient(145deg,#2b120f,#181117_55%,#0c0c0c)] p-6 shadow-[0_34px_85px_-38px_rgba(255,122,0,.8)] sm:p-7"><div className="absolute -right-10 -top-10 h-40 w-40 rounded-full bg-orange-500/20 blur-3xl" /><div className="relative flex items-start justify-between"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-[#f77737] via-[#fd1d1d] to-[#c13584] text-white"><PlatformIcon platform="Instagram" className="h-6 w-6" /></span><div><p className="text-sm font-black text-white">Instagram Likes</p><p className="mt-1 text-[10px] font-black uppercase tracking-[.15em] text-emerald-300">Live service</p></div></div><Heart className="h-6 w-6 fill-orange-300 text-orange-300" /></div><div className="relative mt-7 rounded-2xl border border-white/10 bg-black/25 p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#9CA3AF]">Starting from</p><p className="mt-2 text-3xl font-black text-white">₹{service?.pricePer1000.toLocaleString("en-IN")} <span className="text-sm text-orange-200">/ 1K</span></p></div><div className="grid h-16 w-16 place-items-center rounded-full border-4 border-orange-300/25 bg-orange-500/10"><Heart className="h-7 w-7 fill-orange-300 text-orange-300" /></div></div><div className="mt-6 flex items-center gap-2">{[42, 64, 52, 84, 72, 94, 78].map((height, index) => <span key={index} className="flex-1 rounded-full bg-gradient-to-t from-orange-600 to-pink-400" style={{ height: `${height / 2}px` }} />)}</div></div><div className="relative mt-5 grid grid-cols-2 gap-3 text-xs">{[["Public link", "Required"], ["Secure order", "Protected"], ["Refill", service?.refillPolicy || "—"], ["Delivery", service?.deliveryTime || "—"]].map(([label, value]) => <div key={label} className="rounded-xl bg-white/[.05] p-3"><p className="text-[#9CA3AF]">{label}</p><p className="mt-1 font-black text-white">{value}</p></div>)}</div><a href="#packages" className="relative mt-5 flex min-h-12 items-center justify-center rounded-xl bg-white px-5 text-sm font-black text-[#161616]">Build your order →</a></aside></div></section>
    <section className="border-y border-orange-400/15 bg-[#111] px-4 py-5 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-wrap justify-center gap-x-7 gap-y-3">{trust.map(item => <span key={item} className="flex items-center gap-2 text-xs font-bold text-[#D1D5DB]"><ShieldCheck className="h-4 w-4 text-orange-300" />{item}</span>)}</div></section>
    <InstagramLikesOrderPanel />
    <section className="px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.16em] text-orange-300">Built for engagement</p><h2 className="mt-3 max-w-2xl text-3xl font-black text-white">Indian Instagram likes for public posts and Reels</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-[#D1D5DB]">If you are comparing Instagram likes in India, start with the public post or Reel you want to support. The live order builder shows the current INR total and service details for that content before you continue.</p><div className="mt-7 grid gap-4 md:grid-cols-3">{[[Heart, "Strengthen Social Proof", "Support the visible presentation of selected public content."], [Eye, "Support Content Visibility", "Add likes to the public post or Reel you have chosen."], [Zap, "Simple Ordering Process", "Choose a valid quantity, submit your link and track the order."]].map(([Icon, title, text]) => { const FeatureIcon = Icon as typeof Heart; return <article key={String(title)} className="rounded-[24px] border border-white/[.06] bg-[linear-gradient(145deg,#1c1b1b,#111)] p-5 shadow-[0_20px_45px_-36px_rgba(0,0,0,.95)] transition hover:-translate-y-1 hover:border-orange-400/25"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-orange-500/10"><FeatureIcon className="h-6 w-6 text-orange-300" /></span><h3 className="mt-5 text-lg font-black text-white">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-[#D1D5DB]">{String(text)}</p></article>})}</div></div></section>
    <section className="border-y border-white/5 bg-[#111] px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.16em] text-orange-300">How it works</p><h2 className="mt-3 text-3xl font-black text-white">From public link to order tracking</h2><div className="mt-8 grid gap-2 md:grid-cols-4 md:gap-0">{[["01", "Choose Likes", "Select a valid quantity."], ["02", "Add Content Link", "Provide the public Instagram post or Reel URL."], ["03", "Review & Pay", "Confirm the live total through the existing secure order flow."], ["04", "Track Your Order", "Follow order status from the SocialRUSH dashboard."]].map(([number, title, text], index, steps) => <article key={number} className="relative flex gap-4 py-2 md:block md:px-4">{index < steps.length - 1 ? <span className="absolute bottom-0 left-5 top-12 w-px bg-gradient-to-b from-orange-400/60 to-transparent md:left-[calc(50%+1.8rem)] md:right-0 md:top-5 md:h-px md:w-auto md:bg-gradient-to-r" /> : null}<span className="relative z-10 grid h-11 w-11 shrink-0 place-items-center rounded-full border border-orange-400/40 bg-[#17110c] text-sm font-black text-orange-200">{number}</span><div><h3 className="mt-1 text-base font-black text-white md:mt-5">{title}</h3><p className="mt-2 max-w-[15rem] text-sm leading-6 text-[#D1D5DB]">{text}</p></div></article>)}</div></div></section>
    <section className="bg-[#111] px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><div className="mx-auto max-w-7xl"><article className="rounded-[28px] border border-white/[.07] bg-[linear-gradient(135deg,#171717,#111)] p-6"><Link2 className="h-7 w-7 text-orange-300" /><h2 className="mt-4 text-2xl font-black text-white">Good to know before ordering</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{["Use the correct public Instagram post or Reel URL.", "Keep submitted content public while delivery is processing.", "Delivery and refill eligibility come from the active service.", "SocialRUSH never needs your Instagram password.", "Avoid changing or deleting the submitted content while processing."].map(item => <p key={item} className="flex items-start gap-3 rounded-xl bg-white/[.035] p-3 text-sm leading-6 text-[#D1D5DB]"><Check className="mt-0.5 h-4 w-4 shrink-0 text-orange-300" />{item}</p>)}</div></article><div className="mt-10"><h2 className="text-2xl font-black text-white">Related Instagram services</h2><p className="mt-2 text-sm text-[#D1D5DB]">Compare more active Instagram service options.</p><div className="mt-5 grid gap-3 md:grid-cols-3">{related.map(({code,title,copy,href,icon: Icon}) => { const current = getServiceById(code); return <Link key={title} href={href} className="group rounded-2xl border border-white/[.08] bg-[#161616] p-5 transition hover:-translate-y-1 hover:border-orange-400/35"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-orange-500/10 text-orange-300"><Icon className="h-5 w-5" /></span><span className="text-orange-300 transition group-hover:translate-x-1">→</span></div><h3 className="mt-5 text-base font-black text-white">{title}</h3><p className="mt-1 text-sm leading-6 text-[#D1D5DB]">{copy}</p>{current ? <p className="mt-4 text-xs font-black text-orange-200">From ₹{current.pricePer1000.toLocaleString("en-IN")} / 1K</p> : null}</Link>})}</div></div></div></section>
    <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl"><h2 className="text-center text-3xl font-black text-white">Instagram Likes FAQs</h2><div className="mt-8 grid gap-3">{faqs.map(([question, answer]) => <details key={question} className="rounded-2xl border border-orange-400/20 bg-[#111] p-5"><summary className="cursor-pointer list-none text-sm font-black text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-orange-300">{question}</summary><p className="mt-3 text-sm leading-7 text-[#D1D5DB]">{answer}</p></details>)}</div></div></section>
    <section className="px-4 pb-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl rounded-[2rem] border border-orange-400/25 bg-gradient-to-r from-[#18120b] to-[#151515] p-8 text-center sm:p-12"><h2 className="text-3xl font-black text-white">Ready to build your Instagram Likes order?</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-[#D1D5DB]">Choose your quantity, add your public Instagram content link and continue through the secure SocialRUSH order flow.</p><div className="mt-7 flex flex-col justify-center gap-3 min-[420px]:flex-row"><a href="#packages" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-gradient-to-r from-[#FF7A00] to-[#FFB000] px-6 text-sm font-black text-white">Start Your Order</a><Link href="/services?platform=instagram" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-orange-400/30 px-6 text-sm font-black text-orange-100">Explore Instagram Services</Link></div></div></section>
  </PublicShell>;
}
