const fs = require('node:fs');
const [beforeFile, afterFile, outputFile = 'docs/performance/report.md'] = process.argv.slice(2);
if (!beforeFile || !afterFile) throw new Error('Usage: node scripts/performance-report.cjs before.json after.json [report.md]');
const before = JSON.parse(fs.readFileSync(beforeFile, 'utf8'));
const after = JSON.parse(fs.readFileSync(afterFile, 'utf8'));
const names = { '/': 'Homepage', '/services': 'Services', '/packages': 'Packages', '/dashboard': 'Dashboard', '/dashboard/wallet': 'Wallet' };
const routes = before.summary.filter(s => s.key.startsWith('desktop|') && s.key.endsWith('|cold')).map(s => s.key.split('|')[1]);
const stat = (report, profile, route, cache, metric, percentile = 'median') => report.summary.find(s => s.key === `${profile}|${route}|${cache}`)?.[metric]?.[percentile];
const pair = (profile, route, cache, metric, percentile = 'median', factor = 1) => `${(stat(before, profile, route, cache, metric, percentile) / factor).toFixed(metric === 'cls' ? 4 : 0)} → ${(stat(after, profile, route, cache, metric, percentile) / factor).toFixed(metric === 'cls' ? 4 : 0)}`;
const lines = ['# SocialRUSH performance results', '', 'Baseline: main at `0a30ae3778d932bbbb36f93e182a57b2bd31b251` (PR #622).', 'The following comparisons use five samples per route/profile/cache condition on the same Windows runner, Node and Chromium versions. Full conditions and limitations are in [README.md](README.md). Timings are milliseconds; JS sizes are decimal KB. Arrows show baseline → optimized build.', ''];
for (const profile of ['desktop', 'mobile-4g']) {
  lines.push(`## ${profile}: cold browser cache`, '', '| Page | TTFB median | FCP median | LCP median | LCP p75 | CLS p75 | JS KB median | Requests median |', '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |');
  for (const route of routes) lines.push(`| ${names[route] || 'Checkout (order review)'} | ${pair(profile, route, 'cold', 'ttfb')} | ${pair(profile, route, 'cold', 'fcp')} | ${pair(profile, route, 'cold', 'lcp')} | ${pair(profile, route, 'cold', 'lcp', 'p75')} | ${pair(profile, route, 'cold', 'cls', 'p75')} | ${pair(profile, route, 'cold', 'jsBytes', 'median', 1000)} | ${pair(profile, route, 'cold', 'requestCount')} |`);
  lines.push('', `## ${profile}: repeat document visits`, '', 'Public routes use warm browser HTTP cache. Private routes retain the same test-transport limitation on both sides and retransfer JavaScript; do not treat them as fully warm-cache samples.', '', '| Page | TTFB median | LCP median | LCP p75 |', '| --- | ---: | ---: | ---: |');
  for (const route of routes) lines.push(`| ${names[route] || 'Checkout (order review)'} | ${pair(profile, route, 'warm', 'ttfb')} | ${pair(profile, route, 'warm', 'lcp')} | ${pair(profile, route, 'warm', 'lcp', 'p75')} |`);
  lines.push('');
}
lines.push('## Internal navigation', '', 'A real App Router homepage → services click, starting from a warm homepage and an unvisited services destination. Waits for the rendered heading, not a loading skeleton.', '', '| Profile | Median | p75 |', '| --- | ---: | ---: |');
for (const profile of ['desktop', 'mobile-4g']) lines.push(`| ${profile} | ${pair(profile, '/ -> /services', 'warm-transition', 'transitionMs')} | ${pair(profile, '/ -> /services', 'warm-transition', 'transitionMs', 'p75')} |`);
lines.push('', 'Destination-warm after-only journeys are recorded separately in `warm-navigation.json`; they do not establish a before/after improvement.', '', '## Observed main-thread work', '', 'Total duration of long tasks in the fixed observation window, including work other than hydration. This is not an isolated hydration-cost measurement.', '', '| Profile | Page | Median long-task ms before → after |', '| --- | --- | ---: |');
for (const profile of ['desktop', 'mobile-4g']) for (const route of routes) {
  const median = report => report.samples.filter(s => s.profile === profile && s.route === route && s.cache === 'cold').map(s => s.longTasks.reduce((total, ms) => total + ms, 0)).sort((a,b) => a-b)[2];
  lines.push(`| ${profile} | ${names[route] || 'Checkout'} | ${median(before).toFixed(0)} → ${median(after).toFixed(0)} |`);
}
lines.push('', '## Network and database evidence', '', 'Five read-only production HTTP probes before delivery (same client, separate TLS connections; not a geographic or preview comparison):', '', '| Endpoint | TTFB median | TTFB p75 |', '| --- | ---: | ---: |', '| Homepage | 487 ms | 590 ms |', '| Services | 776 ms | 780 ms |', '| Public service health | 164 ms | 333 ms |', '', 'An initial separate probe saw homepage TTFB 5610 ms and services TTFB 2900 ms; these are retained as variability evidence, not mixed into the five-sample set.', '', 'The directory makes one fresh live-catalog query instead of 31. Read-only production EXPLAIN measured the combined query at 0.229 ms. This demonstrates a small query execution cost, not an end-to-end database latency improvement. Local API timings are synthetic and must not be represented as live financial/API timings.', '', 'The previous service-directory editorial chunk was 96,705 transferred bytes and took about 2.71 seconds in the first throttled mobile sample. It rendered nothing on that route. Directory detail-link prefetch also transferred service landing payloads and JavaScript before a selection; the final change disables that secondary viewport prefetch.', '', 'Images, font assets and image quality are unchanged. No image-size improvement is claimed. Current image-initiator totals omit preloaded images. System fonts avoid an external font dependency.', '', '## Validation and remaining work', '', 'See the delivery/validation record below for final checks and preview/PR links. Public pages still include a large shared stylesheet (~63 KB transferred in the baseline). A full public-layout/CSS split would need a separate scoped visual regression effort. Private pages retain live data fetching and the full sidebar layout-animation API. No field after-release p75, isolated hydration benchmark, multi-region browser probe, or real payment submission is claimed.', '');
fs.mkdirSync(require('node:path').dirname(outputFile), { recursive: true });
const deliveryFile = require('node:path').join(require('node:path').dirname(outputFile), 'delivery.md');
if (fs.existsSync(deliveryFile)) lines.push(fs.readFileSync(deliveryFile, 'utf8'));
fs.writeFileSync(outputFile, lines.join('\n'));
