"use server";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { canPromoteCandidate } from "@/lib/crm/prospecting";
import { parseProspectingCsv } from "@/lib/crm/prospecting";
import { runProspectDiscovery } from "@/lib/crm/prospect-discovery";
const v=(d:FormData,k:string)=>String(d.get(k)||"").trim();
async function admin(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Authentication required");const {data:p}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(p?.role!=="admin")throw new Error("Admin access required");return{supabase,user};}
const domain=(x:string)=>x.toLowerCase().replace(/^https?:\/\//,"").replace(/^www\./,"").split("/")[0]||null;
async function isSuppressedBusinessEmail(supabase:any,email?:string|null){const normalized=String(email||"").trim().toLowerCase();if(!normalized)return false;const {data}=await supabase.from("crm_suppression_list").select("email");return (data||[]).some((row:any)=>String(row.email||"").trim().toLowerCase()===normalized);}
export async function addCandidate(d:FormData){const {supabase,user}=await admin(),email=v(d,"business_email").toLowerCase()||null;if(!v(d,"business_name"))throw new Error("Business name is required.");if(email&&!/^\S+@\S+\.\S+$/.test(email))throw new Error("Use a valid public business email.");const {data,error}=await supabase.from("crm_lead_candidates").insert({business_name:v(d,"business_name"),domain:domain(v(d,"domain")||v(d,"website_url")),website_url:v(d,"website_url")||null,country:v(d,"country")||null,contact_name:v(d,"contact_name")||null,contact_role:v(d,"contact_role")||null,business_email:email,email_type:v(d,"email_type")||"unknown",email_verification_status:v(d,"email_verification_status")||"unverified",source:"manual",source_name:"Manual research",created_by:user.id}).select("id").single();if(error)throw new Error(error.message);await supabase.from("crm_candidate_activities").insert({candidate_id:data.id,activity_type:"imported",details:{source:"manual"},created_by:user.id});await supabase.rpc("refresh_crm_prospecting_intelligence");revalidatePath("/admin/crm/prospecting");}
export async function setCandidateStatus(d:FormData){const {supabase,user}=await admin(),id=v(d,"candidate_id"),status=v(d,"status");if(!["researching","qualified","ready","rejected","duplicate"].includes(status))throw new Error("Invalid status.");const {error}=await supabase.from("crm_lead_candidates").update({qualification_status:status,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(error.message);await supabase.from("crm_candidate_activities").insert({candidate_id:id,activity_type:status==="qualified"?"qualified":status==="rejected"?"rejected":"note",details:{status},created_by:user.id});revalidatePath("/admin/crm/prospecting");revalidatePath(`/admin/crm/prospecting/${id}`);}
export async function promoteCandidate(d:FormData){const {supabase,user}=await admin(),id=v(d,"candidate_id");const {data:c,error}=await supabase.from("crm_lead_candidates").select("*").eq("id",id).single();if(error||!c)throw new Error("Candidate unavailable.");const gate=canPromoteCandidate(c);if(!gate.allowed)throw new Error(gate.reasons.join(". "));if(await isSuppressedBusinessEmail(supabase,c.business_email))throw new Error("Candidate is on the suppression list and cannot be promoted.");const {data:lead,error:problem}=await supabase.from("crm_leads").insert({business_name:c.business_name,domain:c.domain,website_url:c.website_url,country:c.country,city:c.city,industry:c.industry,company_type:c.company_type||"business",employee_range:c.employee_range,instagram_url:c.instagram_url,linkedin_url:c.linkedin_url,youtube_url:c.youtube_url,tiktok_url:c.tiktok_url,source:c.source,source_name:c.source_name,source_url:c.source_url,status:"new",priority:c.fit_grade==="high_fit"?"high":"normal",score:c.fit_score,recommended_service:c.recommended_service,created_by:user.id}).select("id").single();if(problem)throw new Error(problem.message);if(c.business_email)await supabase.from("crm_lead_contacts").insert({lead_id:lead.id,full_name:c.contact_name||c.business_name,job_title:c.contact_role,email:c.business_email,email_type:c.email_type,verification_status:c.email_verification_status==="valid"?"valid":"unverified",compliance_status:"review",contact_basis:"public_business_contact",is_primary:true,source_url:c.source_url});await supabase.from("crm_lead_candidates").update({qualification_status:"promoted",promoted_lead_id:lead.id,promoted_at:new Date().toISOString()}).eq("id",id);await supabase.from("crm_candidate_activities").insert({candidate_id:id,activity_type:"promoted",details:{lead_id:lead.id},created_by:user.id});revalidatePath("/admin/crm/prospecting");revalidatePath(`/admin/crm/leads/${lead.id}`);}
export async function approveSeparateCandidate(d:FormData){const {supabase,user}=await admin(),id=v(d,"candidate_id");const {data:c,error:loadError}=await supabase.from("crm_lead_candidates").select("*").eq("id",id).single();if(loadError||!c)throw new Error("Candidate unavailable.");if(!c.duplicate_lead_id)throw new Error("Candidate has no duplicate to resolve.");const gate=canPromoteCandidate({...c,duplicate_override:true});if(!gate.allowed)throw new Error(gate.reasons.join(". "));if(await isSuppressedBusinessEmail(supabase,c.business_email))throw new Error("Candidate is on the suppression list and cannot be approved separately.");const {error}=await supabase.from("crm_lead_candidates").update({duplicate_override:true,duplicate_resolution:"approved_separate",qualification_status:"qualified",updated_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(error.message);await supabase.from("crm_candidate_activities").insert({candidate_id:id,activity_type:"note",details:{duplicate_resolution:"approved_separate"},created_by:user.id});revalidatePath(`/admin/crm/prospecting/${id}`);}
export async function importCsvCandidates(d:FormData){const {supabase,user}=await admin(),source=v(d,"source_name")||"CSV import",text=String(d.get("csv_text")||"");if(text.length>1024*1024)throw new Error("CSV exceeds 1 MB limit.");const rows=parseProspectingCsv(text),valid=rows.filter(r=>!r.errors.length);const [sup,leads,contacts]=await Promise.all([supabase.from("crm_suppression_list").select("email"),supabase.from("crm_leads").select("id,domain"),supabase.from("crm_lead_contacts").select("email")]);const suppressed=new Set((sup.data||[]).map(x=>x.email.trim().toLowerCase())),domains=new Set((leads.data||[]).map(x=>x.domain?.toLowerCase()).filter(Boolean)),emails=new Set((contacts.data||[]).map(x=>x.email.trim().toLowerCase()));let skipped=rows.length-valid.length,duplicate=0,blocked=0;const batch=valid.flatMap(r=>{const x=r.data,hit=(x.business_email&&suppressed.has(x.business_email))||false,dup=(x.domain&&domains.has(x.domain))||(x.business_email&&emails.has(x.business_email));if(hit){blocked++;skipped++;return []}if(dup){duplicate++;skipped++;return []}return[{...x,business_name:x.business_name!,source:"csv",source_name:source,created_by:user.id}]});for(let i=0;i<batch.length;i+=100){const {data,error}=await supabase.from("crm_lead_candidates").insert(batch.slice(i,i+100)).select("id");if(error)throw new Error(error.message);if(data?.length)await supabase.from("crm_candidate_activities").insert(data.map(x=>({candidate_id:x.id,activity_type:"imported",details:{source:"csv",source_name:source},created_by:user.id})));}await supabase.rpc("refresh_crm_prospecting_intelligence");revalidatePath("/admin/crm/prospecting");return{imported:batch.length,skipped,duplicate,suppressed:blocked,invalid:rows.length-valid.length};}
export async function previewCsvCandidates(text:string){const {supabase}=await admin();if(text.length>1024*1024)throw new Error("CSV exceeds 1 MB limit.");const rows=parseProspectingCsv(text);const [sup,leads,contacts]=await Promise.all([supabase.from("crm_suppression_list").select("email"),supabase.from("crm_leads").select("domain"),supabase.from("crm_lead_contacts").select("email")]);const se=new Set((sup.data||[]).map(x=>x.email.toLowerCase())),ds=new Set((leads.data||[]).map(x=>x.domain?.toLowerCase())),es=new Set((contacts.data||[]).map(x=>x.email.toLowerCase()));const checked=rows.map(r=>{const x=r.data;if(r.errors.length)return{...r,status:"Invalid",reason:r.errors.join(", ")};if(x.business_email&&se.has(x.business_email))return{...r,status:"Suppressed",reason:"Suppression list"};if((x.domain&&ds.has(x.domain))||(x.business_email&&es.has(x.business_email)))return{...r,status:"Exact Duplicate",reason:"Existing CRM match"};return{...r,status:"Ready",reason:""}});return{rows:checked,summary:{total:checked.length,valid:checked.filter(x=>x.status!=="Invalid").length,ready:checked.filter(x=>x.status==="Ready").length,invalid:checked.filter(x=>x.status==="Invalid").length,suppressed:checked.filter(x=>x.status==="Suppressed").length,exact:checked.filter(x=>x.status==="Exact Duplicate").length,possible:0}};}
export async function mergeCandidateIntoLead(d:FormData){const {supabase,user}=await admin(),candidateId=v(d,"candidate_id"),leadId=v(d,"lead_id");const [{data:c},{data:l},{data:allContacts},{data:suppressed}]=await Promise.all([supabase.from("crm_lead_candidates").select("*").eq("id",candidateId).single(),supabase.from("crm_leads").select("*").eq("id",leadId).single(),supabase.from("crm_lead_contacts").select("email").eq("lead_id",leadId),supabase.from("crm_suppression_list").select("email")]);if(!c||!l)throw new Error("Candidate or lead unavailable.");const gate=canPromoteCandidate({...c,duplicate_override:true});if(!gate.allowed)throw new Error(gate.reasons.join(". "));if(await isSuppressedBusinessEmail(supabase,c.business_email))throw new Error("Candidate is on the suppression list and cannot be merged.");const fields=["domain","website_url","country","city","industry","company_type","employee_range","instagram_url","linkedin_url","youtube_url","tiktok_url","recommended_service"] as const;const update:any={updated_at:new Date().toISOString()};fields.forEach(k=>{if(!l[k]&&c[k])update[k]=c[k]});if(Object.keys(update).length>1){const {error}=await supabase.from("crm_leads").update(update).eq("id",leadId);if(error)throw new Error(error.message)}const email=c.business_email?.toLowerCase();const exists=(allContacts||[]).some(x=>x.email.toLowerCase()===email),isSuppressed=(suppressed||[]).some(x=>x.email.toLowerCase()===email);if(email&&!exists&&!isSuppressed&&!['invalid','bounced'].includes(c.email_verification_status)&&c.compliance_status!=="blocked")await supabase.from("crm_lead_contacts").insert({lead_id:leadId,full_name:c.contact_name||c.business_name,job_title:c.contact_role,email,email_type:c.email_type,verification_status:c.email_verification_status==="valid"?"valid":"unverified",compliance_status:"review",contact_basis:"public_business_contact",is_primary:false,source_url:c.source_url});await supabase.from("crm_lead_candidates").update({qualification_status:"promoted",promoted_lead_id:leadId,promoted_at:new Date().toISOString(),duplicate_resolution:"merged_existing"}).eq("id",candidateId);await supabase.from("crm_candidate_activities").insert({candidate_id:candidateId,activity_type:"promoted",details:{lead_id:leadId,resolution:"merged_existing"},created_by:user.id});revalidatePath(`/admin/crm/leads/${leadId}`);revalidatePath(`/admin/crm/prospecting/${candidateId}`);}

export async function runDiscoveryNow() {
  const { user } = await admin();

  await runProspectDiscovery({
    trigger: "manual",
    createdBy: user.id,
  });

  revalidatePath("/admin/crm/prospecting");
}