"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { ArrowRight, Check, ChevronDown, Clipboard, Copy, FileImage, ImageIcon, Camera, LockKeyhole, RotateCcw, ShieldCheck, Sparkles, Type, UserRound } from "lucide-react";

const LIMIT = 2200;
const example = "A small creative habit can change the way your week feels.\n\nSave this for your next planning session, then give yourself room to make the first draft imperfect.\n\n#contentcreator #socialmediatips #creativeworkflow";

function Metric({ label, value }: { label: string; value: string | number }) {
  return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-3.5"><p className="text-[10px] font-black uppercase tracking-[.14em] text-slate-500">{label}</p><p className="mt-1 text-xl font-black text-white">{value}</p></div>;
}

export default function InstagramCaptionWorkspace() {
  const [caption, setCaption] = useState("");
  const [copied, setCopied] = useState(false);
  const [previewChecked, setPreviewChecked] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const editorRef = useRef<HTMLTextAreaElement>(null);
  const metrics = useMemo(() => {
    const chars = caption.length;
    const words = caption.trim() ? caption.trim().split(/\s+/).length : 0;
    const tags = caption.match(/#[\p{L}\p{N}_]+/gu) || [];
    const lines = caption ? caption.split(/\r?\n/).length - 1 : 0;
    return { chars, words, tags, lines };
  }, [caption]);
  const remaining = LIMIT - metrics.chars;
  const percent = Math.min(100, (metrics.chars / LIMIT) * 100);
  const state = metrics.chars === 0 ? "Ready to write" : remaining < 0 ? "Over limit" : metrics.chars >= 2000 ? "Approaching limit" : "Within limit";
  const stateColor = remaining < 0 ? "text-rose-300" : metrics.chars >= 2000 ? "text-amber-200" : "text-emerald-300";
  const write = (value: string) => { setCaption(value); setCopied(false); };
  async function copyCaption() { if (!caption) return; try { await navigator.clipboard.writeText(caption); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } catch { setCopied(false); } }
  function clear() { write(""); setPreviewChecked(false); editorRef.current?.focus(); }

  const faqs = [
    ["What is Instagram's caption character limit?", "Instagram captions allow up to 2,200 characters. This tool uses that limit for its live character total."],
    ["Does this tool count hashtags and spaces?", "Yes. Hashtags are detected from the caption text, and spaces count as characters because they are part of the text you enter."],
    ["Does SocialRUSH save my caption?", "No. The counter and preview run locally in your browser. The caption is cleared when you refresh or leave this page."],
    ["Do I need to connect Instagram?", "No. There is no Instagram login, password, or account connection required. SocialRUSH is an independent tool and is not affiliated with Instagram or Meta."],
    ["Can I use this for Reels or business accounts?", "You can use it to draft captions for either. Always review your final caption in the relevant Instagram publishing flow, as display can vary by device and app version."],
  ];

  return <>
    <section className="relative isolate overflow-hidden px-4 pb-12 pt-10 sm:px-6 lg:pb-16 lg:pt-14">
      <div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(circle_at_82%_12%,rgba(255,118,0,.18),transparent_23%),radial-gradient(circle_at_97%_24%,rgba(193,53,132,.12),transparent_19%),linear-gradient(180deg,#07080d,#0b0e16)]" />
      <div className="mx-auto max-w-7xl">
        <Link href="/tools" className="inline-flex min-h-11 items-center gap-1 text-sm font-bold text-orange-300">Creator tools <ArrowRight className="h-4 w-4" /> Instagram caption counter</Link>
        <div className="mt-5 grid gap-8 lg:grid-cols-[1fr_.88fr] lg:items-center">
          <div><p className="inline-flex items-center gap-2 rounded-full border border-orange-300/30 bg-orange-400/[.08] px-3 py-2 text-[10px] font-black tracking-[.16em] text-orange-200"><Sparkles className="h-3.5 w-3.5" /> FREE INSTAGRAM CREATOR TOOL</p><h1 className="mt-5 max-w-3xl text-[clamp(2.35rem,5vw,4.45rem)] leading-[.98]">Instagram Caption &amp; Character Counter</h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-300">Write, review and measure your Instagram caption before publishing — directly in your browser.</p><div className="mt-7 flex flex-col gap-3 min-[390px]:flex-row"><a href="#caption-editor" className="btn-primary min-h-12 justify-center gap-2 px-5">Start Writing <ArrowRight className="h-4 w-4" /></a><Link href="/tools" className="btn-secondary min-h-12 justify-center px-5">Explore Creator Tools</Link></div><div className="mt-6 flex flex-wrap gap-2">{[[Check,"Free to use"],[UserRound,"No login required"],[Type,"Browser-based"],[ShieldCheck,"Privacy-first"]].map(([Icon,label])=>{const I=Icon as typeof Check;return <span key={String(label)} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-white/10 bg-white/[.035] px-3 text-xs font-semibold text-slate-300"><I className="h-3.5 w-3.5 text-orange-300" />{String(label)}</span>;})}</div></div>
          <aside aria-label="Caption editor interface preview" className="relative overflow-hidden rounded-[1.75rem] border border-orange-300/25 bg-[linear-gradient(145deg,#171c2a,#0d1019)] p-5 shadow-[0_26px_70px_rgba(0,0,0,.38)] sm:p-6"><div className="absolute -right-12 -top-12 h-36 w-36 rounded-full bg-fuchsia-500/10 blur-3xl" /><div className="relative flex items-center justify-between"><p className="text-[10px] font-black tracking-[.16em] text-orange-200">UI PREVIEW</p><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-[10px] font-bold text-emerald-300">Ready to review</span></div><div className="relative mt-5 rounded-2xl border border-white/10 bg-[#0a0d14]/80 p-4"><p className="text-[10px] font-black tracking-[.14em] text-slate-400">CAPTION DRAFT</p><p className="mt-3 text-sm leading-6 text-slate-300">Make space for the idea before you make it perfect. Save this for your next creative reset. #creatorworkflow</p><div className="mt-5 grid grid-cols-2 gap-2"><Metric label="Characters" value="742" /><Metric label="Words" value="118" /><Metric label="Hashtags" value="12" /><Metric label="Line Breaks" value="8" /></div></div><p className="relative mt-3 text-xs text-slate-500">Demo values only — your live counts appear below.</p></aside>
        </div>
      </div>
    </section>

    <section id="caption-editor" className="border-y border-white/10 bg-[#0b0e16] px-4 py-10 sm:px-6 lg:py-14"><div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black tracking-[.15em] text-orange-200">YOUR WRITING WORKSPACE</p><h2 className="mt-2 text-3xl">Draft with a clear view of every detail.</h2></div><p aria-live="polite" className={`text-sm font-bold ${stateColor}`}>{state}</p></div><div className="grid gap-5 xl:grid-cols-[minmax(0,1.12fr)_minmax(340px,.88fr)]">
      <article className="rounded-[1.75rem] border border-orange-400/30 bg-[linear-gradient(145deg,#171b27,#0e111a)] p-4 shadow-[0_22px_60px_rgba(0,0,0,.22)] sm:p-6"><div className="flex items-center justify-between gap-3"><label htmlFor="caption-editor-field" className="text-lg font-black text-white">Instagram Caption</label><span className="text-xs font-semibold text-slate-400">Local draft</span></div><textarea ref={editorRef} id="caption-editor-field" value={caption} onChange={e=>write(e.target.value)} maxLength={LIMIT} placeholder="Write or paste your Instagram caption here..." className="mt-4 min-h-[300px] w-full resize-y rounded-2xl border border-white/10 bg-[#090b11] p-4 text-base leading-7 text-white outline-none transition placeholder:text-slate-600 focus:border-orange-400 focus:ring-4 focus:ring-orange-400/10 sm:p-5" aria-describedby="caption-counter" />
        <div id="caption-counter" className="mt-4"><div className="flex items-center justify-between gap-4 text-sm"><span className="font-bold text-slate-200">{metrics.chars.toLocaleString()} / {LIMIT.toLocaleString()} characters</span><span className={stateColor}>{remaining >= 0 ? `${remaining.toLocaleString()} remaining` : `${Math.abs(remaining).toLocaleString()} over`}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full transition-[width] ${remaining < 0 ? "bg-rose-400" : metrics.chars >= 2000 ? "bg-amber-300" : "bg-gradient-to-r from-orange-500 to-amber-300"}`} style={{width:`${percent}%`}} /></div></div>
        <div className="mt-5 flex flex-col gap-3 min-[450px]:flex-row"><button type="button" onClick={copyCaption} disabled={!caption} className="btn-primary min-h-12 flex-1 justify-center gap-2 disabled:cursor-not-allowed disabled:opacity-45"><Copy className="h-4 w-4" />{copied ? "Copied" : "Copy Caption"}</button><button type="button" onClick={clear} className="btn-secondary min-h-12 flex-1 justify-center gap-2"><RotateCcw className="h-4 w-4" />Clear Caption</button><button type="button" onClick={()=>{write(example); editorRef.current?.focus();}} className="min-h-12 rounded-xl border border-white/10 px-4 text-sm font-bold text-slate-200 transition hover:border-orange-300/50 hover:text-orange-100">Try Example</button></div>
      </article>
      <aside className="space-y-5"><article className="rounded-[1.75rem] border border-white/10 bg-[#111522] p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black tracking-[.14em] text-orange-200">LIVE ANALYSIS</p><h2 className="mt-2 text-xl">Caption facts</h2></div><Clipboard className="h-5 w-5 text-orange-300" /></div><div aria-live="polite" className="mt-5 grid grid-cols-2 gap-3"><Metric label="Characters" value={metrics.chars.toLocaleString()} /><Metric label="Words" value={metrics.words} /><Metric label="Hashtags" value={metrics.tags.length} /><Metric label="Line Breaks" value={metrics.lines} /></div>{metrics.tags.length > 0 && <div className="mt-4 rounded-xl border border-fuchsia-300/15 bg-fuchsia-400/[.05] p-3"><p className="text-xs font-bold text-fuchsia-100">Detected hashtags</p><p className="mt-2 break-words text-xs leading-5 text-fuchsia-200/80">{metrics.tags.join(" ")}</p></div>}</article>
        <article className="rounded-[1.75rem] border border-white/10 bg-[#10131c] p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black tracking-[.14em] text-orange-200">PREVIEW</p><h2 className="mt-2 text-xl">Your post caption</h2></div><Camera className="h-5 w-5 text-orange-300" /></div><div className="mt-5 overflow-hidden rounded-2xl border border-white/10 bg-[#080a0f]"><div className="flex items-center gap-3 p-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[linear-gradient(135deg,#ffb000,#f45460,#7c3aed)] p-[2px]"><span className="grid h-full w-full place-items-center rounded-full bg-[#131722] text-[10px] font-black">YR</span></span><div><p className="text-sm font-bold">Your Profile</p><p className="text-[10px] text-slate-500">Caption preview</p></div></div><div className="grid aspect-[1.45/1] place-items-center bg-[radial-gradient(circle_at_30%_25%,rgba(255,166,0,.42),transparent_20%),radial-gradient(circle_at_70%_70%,rgba(190,60,140,.27),transparent_32%),linear-gradient(135deg,#1b2437,#0d101a)]"><FileImage className="h-10 w-10 text-white/50" /><span className="sr-only">Generic post artwork placeholder</span></div><div className="p-4"><p className="line-clamp-3 whitespace-pre-wrap text-sm leading-6 text-slate-200">{caption || "Your caption will appear here after you start writing."}</p>{caption && <button type="button" onClick={()=>setPreviewChecked(true)} className="mt-2 text-xs font-bold text-slate-400 hover:text-orange-200">more</button>}<p className="mt-3 text-[11px] leading-5 text-slate-500">Feed display can vary by device and Instagram app version.</p></div></div></article></aside>
    </div></div></section>

    <section className="px-4 py-14 sm:px-6"><div className="mx-auto max-w-7xl"><div className="grid gap-5 lg:grid-cols-2"><article className="rounded-[1.6rem] border border-emerald-300/20 bg-[linear-gradient(145deg,#0d1b1a,#10131b)] p-6 sm:p-7"><p className="text-xs font-black tracking-[.15em] text-emerald-300">PRIVACY-FIRST</p><h2 className="mt-3 text-3xl">Your caption stays in your browser</h2><p className="mt-3 leading-7 text-slate-300">No Instagram login, password, or account connection is required. Counts and the preview are generated locally from the text you enter.</p><div className="mt-6 grid grid-cols-3 gap-2 text-center text-xs font-bold">{[["YOUR CAPTION",Type],["BROWSER ANALYSIS",LockKeyhole],["COUNTS + PREVIEW",Check]].map(([label,Icon])=>{const I=Icon as typeof Type;return <div key={String(label)} className="rounded-xl border border-white/10 bg-white/[.04] p-3"><I className="mx-auto h-4 w-4 text-emerald-300" /><p className="mt-2 text-[9px] leading-4 text-slate-300">{String(label)}</p></div>})}</div></article><article className="rounded-[1.6rem] border border-white/10 bg-[#10131c] p-6 sm:p-7"><p className="text-xs font-black tracking-[.15em] text-orange-200">QUICK WRITING CHECKLIST</p><h2 className="mt-3 text-2xl">Review the facts before you publish.</h2><div className="mt-5 space-y-3">{[[caption.length>0,"Caption entered"],[caption.length>0&&remaining>=0,"Within character limit"],[metrics.tags.length>0,"Hashtags detected"],[previewChecked,"Preview checked"]].map(([done,label])=><div key={String(label)} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.035] px-4 py-3 text-sm"><span className={`grid h-6 w-6 place-items-center rounded-full ${done?"bg-emerald-400/15 text-emerald-300":"bg-white/[.06] text-slate-500"}`}>{done?<Check className="h-4 w-4"/>:"○"}</span>{String(label)}</div>)}</div></article></div>
      <div className="mt-12 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><article><p className="text-xs font-black tracking-[.15em] text-orange-200">CAPTION BASICS</p><h2 className="mt-3 text-3xl">Make your caption easy to scan</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{["Lead with the important point","Use clear spacing","Keep hashtags intentional","Review the mobile preview","Avoid unnecessary repetition"].map(item=><li key={item} className="flex items-center gap-3 rounded-xl border border-white/10 bg-[#10131c] p-4 text-sm text-slate-300"><Check className="h-4 w-4 shrink-0 text-orange-300" />{item}</li>)}</ul></article><article className="rounded-[1.6rem] border border-fuchsia-300/15 bg-[linear-gradient(145deg,#171222,#10131c)] p-6"><p className="text-xs font-black tracking-[.15em] text-fuchsia-200">HASHTAG BASICS</p><h2 className="mt-3 text-2xl">Use hashtags intentionally</h2><p className="mt-4 text-sm leading-7 text-slate-300">Hashtag strategy varies by niche, audience and content. This tool counts the hashtags in your draft; it does not score or rank them.</p></article></div>
      <div className="mt-14"><p className="text-xs font-black tracking-[.15em] text-orange-200">CREATOR WORKFLOW</p><h2 className="mt-3 text-3xl">From draft to publish.</h2><div className="mt-6 grid gap-3 md:grid-cols-4">{[["01","Write or paste caption"],["02","Check characters and hashtags"],["03","Preview the post"],["04","Copy and publish manually"]].map(([n,text])=><div key={n} className="relative rounded-2xl border border-white/10 bg-[#10131c] p-5"><span className="text-xl font-black text-orange-300">{n}</span><p className="mt-7 font-bold text-white">{text}</p></div>)}</div></div>
    </div></section>

    <section className="border-y border-white/10 bg-[#0b0e16] px-4 py-14 sm:px-6"><div className="mx-auto max-w-7xl"><h2 className="text-3xl">Continue your creator workflow</h2><div className="mt-6 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{[["/tools/instagram-engagement-rate-calculator","Instagram Engagement Rate Calculator","Calculate engagement rate",Clipboard],["/tools/social-media-image-resizer","Social Media Image Resizer","Resize image",ImageIcon],["/tools/youtube-thumbnail-preview","YouTube Thumbnail Preview & Title Checker","Preview thumbnail",FileImage],["/tools/utm-link-builder","UTM Link Builder","Build UTM link",ArrowRight]].map(([href,title,cta,Icon])=>{const I=Icon as typeof Clipboard;return <Link key={String(href)} href={String(href)} className="group rounded-2xl border border-white/10 bg-[#10131c] p-5 transition hover:-translate-y-1 hover:border-orange-400/45"><I className="h-5 w-5 text-orange-300"/><h3 className="mt-4 font-bold text-white">{String(title)}</h3><span className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-orange-200">{String(cta)} <ArrowRight className="h-4 w-4"/></span></Link>})}</div><div className="mt-10 flex flex-col justify-between gap-5 rounded-[1.6rem] border border-orange-400/25 bg-[radial-gradient(circle_at_85%_0%,rgba(255,118,0,.2),transparent_32%),#111522] p-6 sm:p-8 lg:flex-row lg:items-center"><div><p className="text-xs font-black tracking-[.15em] text-orange-200">PREPARING YOUR NEXT INSTAGRAM CAMPAIGN?</p><h2 className="mt-3 text-2xl">Plan your caption, then explore your next campaign.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Use creator tools to prepare your content, then explore SocialRUSH Instagram services with transparent pricing and public-link ordering.</p></div><div className="flex flex-wrap gap-3"><Link href="/buy-instagram-followers-india" className="btn-primary min-h-12">Explore Instagram follower packages</Link><Link href="/pricing" className="btn-secondary min-h-12">View Pricing</Link></div></div></div></section>

    <section className="px-4 py-14 sm:px-6"><div className="mx-auto max-w-4xl"><p className="text-xs font-black tracking-[.15em] text-orange-200">FAQ</p><h2 className="mt-3 text-3xl">Caption counter questions</h2><div className="mt-6 space-y-3">{faqs.map(([q,a],index)=><article key={q} className="rounded-2xl border border-white/10 bg-[#10131c]"><button type="button" aria-expanded={openFaq===index} aria-controls={`caption-faq-${index}`} onClick={()=>setOpenFaq(openFaq===index?null:index)} className="flex min-h-14 w-full items-center justify-between gap-4 px-5 text-left text-sm font-bold text-white"><span>{q}</span><ChevronDown className={`h-4 w-4 shrink-0 text-orange-300 transition ${openFaq===index?"rotate-180":""}`} /></button>{openFaq===index&&<p id={`caption-faq-${index}`} className="border-t border-white/10 px-5 py-4 text-sm leading-6 text-slate-400">{a}</p>}</article>)}</div></div></section>
  </>;
}
