import Link from "next/link";
import { redirect } from "next/navigation";
import { Archive, FolderKanban, Plus, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { archiveClient, linkProfile, saveClient } from "./actions";

export default async function ClientsPage() {
  const db = await createClient(); const { data: { user } } = await db.auth.getUser(); if (!user) redirect("/login");
  const [{ data: clients }, { data: profiles }, { data: orders }] = await Promise.all([
    db.from("customer_clients").select("id,name,contact_name,email,notes,archived_at,created_at,client_social_profiles(saved_profile_id,saved_social_profiles(label,platform,public_url))").eq("user_id", user.id).order("created_at", { ascending: false }),
    db.from("saved_social_profiles").select("id,label,platform,public_url").eq("user_id", user.id).order("created_at", { ascending: false }),
    db.from("orders").select("id,client_id,status,charge,created_at").eq("user_id", user.id).order("created_at", { ascending: false }).limit(250),
  ]);
  const liveClients = (clients || []).filter((client) => !client.archived_at);
  return <main className="dashboard-premium-page mx-auto w-full max-w-[1500px] px-4 pb-10 pt-5 text-white sm:px-6 lg:px-8"><header className="flex flex-col gap-4 rounded-[1.35rem] border border-orange-400/20 bg-[linear-gradient(125deg,#17150f,#101218_60%)] p-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-orange-300">Agency workspace</p><h1 className="mt-2 text-3xl font-black">Clients</h1><p className="mt-2 text-sm text-slate-300">Keep brands, profiles and order activity organized without changing fulfilment.</p></div><Link href="/dashboard/new-campaign" className="btn-dashboard-primary gap-2 px-4 text-sm"><FolderKanban className="h-4 w-4"/>Create campaign</Link></header>
    <section className="dashboard-glass mt-4 p-4 sm:p-5"><h2 className="text-lg font-black">Add client</h2><form action={saveClient} className="mt-4 grid gap-3 md:grid-cols-2"><input name="name" required maxLength={120} placeholder="Client / brand name" className="dashboard-input"/><input name="contact_name" maxLength={120} placeholder="Contact name (optional)" className="dashboard-input"/><input name="email" type="email" maxLength={320} placeholder="Email (optional)" className="dashboard-input"/><textarea name="notes" maxLength={2000} placeholder="Notes (optional)" className="dashboard-input min-h-11 md:col-span-2"/><button className="btn-dashboard-primary w-fit gap-2 px-4 text-sm"><Plus className="h-4 w-4"/>Add client</button></form></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-2">{liveClients.length ? liveClients.map((client) => { const clientOrders = (orders || []).filter((order) => order.client_id === client.id); const completed = clientOrders.filter((order) => order.status === "completed").length; const profilesForClient = (client.client_social_profiles || []) as unknown as Array<{ saved_social_profiles: { label: string; platform: string; public_url: string } | null }>;
      return <article key={client.id} className="dashboard-glass p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-orange-500/10 text-orange-300"><Users className="h-5 w-5"/></span><div><Link href={`/dashboard/clients/${client.id}`} className="block truncate text-lg font-black hover:text-orange-200">{client.name}</Link><p className="text-xs text-slate-400">{client.contact_name || client.email || "No contact details"}</p></div></div></div><form action={archiveClient}><input type="hidden" name="id" value={client.id}/><button aria-label={`Archive ${client.name}`} className="rounded-lg p-2 text-slate-400 hover:bg-white/5 hover:text-orange-200"><Archive className="h-4 w-4"/></button></form></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-white/[.035] p-3"><b className="block text-lg">{clientOrders.length}</b><span className="text-[10px] text-slate-400">Orders</span></div><div className="rounded-xl bg-white/[.035] p-3"><b className="block text-lg text-emerald-300">{completed}</b><span className="text-[10px] text-slate-400">Completed</span></div><div className="rounded-xl bg-white/[.035] p-3"><b className="block text-lg">₹{clientOrders.reduce((sum, order) => sum + Number(order.charge || 0), 0).toLocaleString("en-IN")}</b><span className="text-[10px] text-slate-400">Spent</span></div></div><div className="mt-4 flex flex-wrap gap-2">{profilesForClient.map((entry, i) => entry.saved_social_profiles ? <Link key={i} href={`/dashboard/new-order?prefill=1&link=${encodeURIComponent(entry.saved_social_profiles.public_url)}`} className="rounded-lg border border-white/10 bg-white/[.035] px-2.5 py-1.5 text-xs text-slate-200">{entry.saved_social_profiles.platform}: {entry.saved_social_profiles.label}</Link> : null)}</div><form action={linkProfile} className="mt-4 flex gap-2"><input type="hidden" name="client_id" value={client.id}/><select name="profile_id" className="dashboard-input min-w-0 flex-1 text-xs" defaultValue=""><option value="" disabled>Link a saved social profile</option>{(profiles || []).map((profile) => <option key={profile.id} value={profile.id}>{profile.platform}: {profile.label}</option>)}</select><button className="btn-dashboard-secondary px-3 text-xs">Link</button></form><div className="mt-4 flex gap-3 text-xs font-bold text-orange-300"><Link href={`/dashboard/clients/${client.id}`}>View workspace</Link><Link href={`/dashboard/new-order?client=${client.id}`}>Start order</Link><Link href={`/dashboard/new-campaign?client=${client.id}`}>Campaign</Link></div></article>; }) : <div className="dashboard-glass p-10 text-center lg:col-span-2"><Users className="mx-auto h-8 w-8 text-orange-300"/><h2 className="mt-3 font-black">No clients yet</h2><p className="mt-1 text-sm text-slate-400">Add a brand to organize future orders and saved profiles.</p></div>}</section></main>;
}
