/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { AlertTriangle, ArrowUpRight, CheckCircle2, Clock3, Flame, ShieldCheck, Workflow } from "lucide-react";
import { getCommandCenterData } from "@/lib/crm/command-center";
import { dateTime } from "@/lib/crm/types";
import AutopilotRefreshButton from "@/components/admin/AutopilotRefreshButton";

const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase());
const age=(value:string)=>{const minutes=Math.max(0,Math.floor((Date.now()-Date.parse(value))/60000));return minutes<60?`${minutes}m ago`:minutes<1440?`${Math.floor(minutes/60)}h ago`:`${Math.floor(minutes/1440)}d ago`;};
const severityStyle:Record<string,string>={critical:"bg-red-500/15 text-red-200",high:"bg-orange-500/15 text-orange-100",medium:"bg-amber-500/15 text-amber-100",low:"bg-white/10 text-[#D1D5DB]"};

export default async function CommandCenterPage(){
  const data=await getCommandCenterData(); const hour=new Date().getHours(); const greeting=hour<12?"Good morning":hour<18?"Good afternoon":"Good evening"; const health=data.health?.status||"healthy";
  const dueToday=data.leadFollowups.filter((x:any)=>x.due_at>=data.today&&x.due_at<=data.now).length+data.customerFollowups.filter((x:any)=>x.due_at>=data.today&&x.due_at<=data.now).length;
  const overdue=data.leadFollowups.filter((x:any)=>x.due_at<data.now).length+data.customerFollowups.filter((x:any)=>x.due_at<data.now).length;
  const topActions=data.attention.slice(0,3);
  return <main className="mx-auto max-w-[1650px] p-4 pb-20 sm:p-8"><header className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-orange-300">SocialRUSH Autopilot</p><h1 className="mt-2 text-3xl font-black text-white sm:text-4xl">{greeting}.</h1><p className="mt-2 text-sm text-[#9CA3AF]">Here&apos;s what needs your attention today.</p></div><div className="flex flex-wrap items-center gap-3"><span className={`inline-flex items-center gap-2 rounded-full px-3 py-2 text-xs font-bold ${health==="healthy"?"bg-emerald-500/10 text-emerald-200":"bg-orange-500/10 text-orange-100"}`}><i className={`h-2 w-2 rounded-full ${health==="healthy"?"bg-emerald-400":"bg-orange-400"}`}/>{data.attention.length?`${data.attention.length} items need attention`:"All systems healthy"}</span><AutopilotRefreshButton/></div></header>
    {data.errors>0&&<div className="mt-5 rounded-xl border border-amber-400/25 bg-amber-500/10 px-4 py-3 text-xs text-amber-100">Some live metrics are temporarily unavailable. The remaining command-center signals are still shown.</div>}
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Overdue",overdue,AlertTriangle,"text-red-200"],["Due today",dueToday,Clock3,"text-amber-100"],["Hot leads",data.hotLeads.length,Flame,"text-orange-200"],["Automation",label(health),Workflow,health==="healthy"?"text-emerald-200":"text-orange-100"]].map(([title,value,Icon,color])=>{const C=Icon as typeof Clock3;return <article key={String(title)} className="rounded-2xl border border-white/10 bg-[#111111] p-5"><div className="flex items-center justify-between text-[#9CA3AF]"><span className="text-[10px] font-bold uppercase tracking-wider">{String(title)}</span><C size={16} className="text-orange-300"/></div><b className={`mt-3 block text-2xl ${String(color)}`}>{String(value)}</b></article>})}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_.8fr]"><div className="rounded-2xl border border-white/10 bg-[#111111]"><div className="flex items-center justify-between border-b border-white/10 p-5"><div><h2 className="font-bold text-white">Needs Your Attention</h2><p className="mt-1 text-xs text-[#9CA3AF]">Ranked by business impact and urgency.</p></div><AlertTriangle className="text-orange-300" size={18}/></div>{data.attention.length?<div className="divide-y divide-white/10">{data.attention.map((item:any,index:number)=><article key={`${item.category}-${index}`} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${severityStyle[item.severity]}`}>{item.severity}</span><span className="py-1 text-[10px] font-bold uppercase tracking-wide text-[#9CA3AF]">{item.category}</span></div><h3 className="mt-2 truncate text-sm font-bold text-white">{item.title}</h3><p className="mt-1 text-xs text-[#9CA3AF]">{item.reason} · {age(item.age)}</p></div><Link href={item.href} className="inline-flex shrink-0 items-center gap-1 text-xs font-bold text-orange-200">{item.cta}<ArrowUpRight size={14}/></Link></article>)}</div>:<div className="p-10 text-center"><CheckCircle2 className="mx-auto text-emerald-300"/><h3 className="mt-3 font-bold text-white">Everything is covered</h3><p className="mt-1 text-sm text-[#9CA3AF]">No urgent CRM actions right now.</p></div>}</div>
      <aside className="rounded-2xl border border-orange-400/20 bg-[radial-gradient(circle_at_top_right,rgba(255,122,0,.18),transparent_45%),#111111] p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-orange-300">Today&apos;s CEO Brief</p><h2 className="mt-2 font-bold text-white">Daily operating pulse</h2></div><Flame className="text-orange-300"/></div><div className="mt-5 space-y-2 text-sm">{[["🔥",`${data.hotLeads.length} hot leads`],["💬",`${data.replyCounts.find((x:any)=>x[0]==="interested")?.[1]||0} interested replies`],["📌",`${dueToday} follow-ups due`],["⚠️",`${overdue} overdue follow-ups`],["✅",`Automation health: ${label(health)}`]].map(([icon,text])=><p key={String(text)} className="text-[#D1D5DB]"><span className="mr-2">{icon}</span>{text}</p>)}</div><h3 className="mt-6 text-sm font-bold text-white">Your top 3 actions</h3><ol className="mt-3 space-y-3">{topActions.length?topActions.map((action:any,index:number)=><li key={index} className="flex gap-3 text-xs text-[#D1D5DB]"><b className="text-orange-200">{index+1}</b><span>{action.title} — {action.reason}</span></li>):<li className="text-xs text-[#9CA3AF]">No urgent actions identified.</li>}</ol><p className="mt-5 text-[10px] text-[#737B8B]">Last refreshed {data.brief?.generated_at?dateTime(data.brief.generated_at):"not yet generated"}</p></aside></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-[#111111]"><div className="flex items-center justify-between border-b border-white/10 p-5"><div><h2 className="font-bold text-white">Hot Leads</h2><p className="mt-1 text-xs text-[#9CA3AF]">Explainable rule-based scores.</p></div><Link href="/admin/crm/leads" className="text-xs font-bold text-orange-200">All leads</Link></div>{data.hotLeads.length?<div className="divide-y divide-white/10">{data.hotLeads.slice(0,5).map((item:any)=><article className="p-5" key={item.lead.id}><div className="flex justify-between gap-3"><div><h3 className="font-bold text-white">{item.lead.business_name}</h3><p className="mt-1 text-xs text-[#9CA3AF]">{item.contact?.full_name||item.contact?.email||"No primary contact"} · {label(item.lead.status)}</p></div><span className="h-fit rounded-full bg-orange-500/15 px-2.5 py-1 text-xs font-black text-orange-100">{item.score}</span></div><p className="mt-3 text-xs text-[#D1D5DB]">{item.latest?`Latest reply: ${label(item.latest.classification||"unclassified")}`:"No reply yet"} · {item.followup?`Follow-up ${item.followup.due_at<data.now?"overdue":"scheduled"}`:"No follow-up scheduled"}</p><div className="mt-3 flex flex-wrap gap-1.5">{(item.score_reasons||[]).slice(0,3).map((reason:any)=> <span key={reason.reason} className="rounded-md bg-white/5 px-2 py-1 text-[10px] text-[#9CA3AF]">{reason.points>0?"+":""}{reason.points} {reason.reason}</span>)}</div><Link className="mt-3 inline-block text-xs font-bold text-orange-200" href={`/admin/crm/leads/${item.lead.id}`}>View lead</Link></article>)}</div>:<div className="p-10 text-center text-sm text-[#9CA3AF]">No hot leads right now. Refresh Autopilot after new replies arrive.</div>}</section>
      <section className="rounded-2xl border border-white/10 bg-[#111111]"><div className="border-b border-white/10 p-5"><h2 className="font-bold text-white">Customers Needing Attention</h2><p className="mt-1 text-xs text-[#9CA3AF]">VIP, at-risk, and inactive customers with a due follow-up.</p></div>{data.customerAttention.length?<div className="divide-y divide-white/10">{data.customerAttention.map((item:any)=><article key={item.followup.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-bold text-white">{item.profile?.full_name||item.profile?.email||"Customer"}</h3><p className="mt-1 text-xs text-[#9CA3AF]">{label(item.customer.lifecycle_stage)} · {item.followup.title} · due {age(item.followup.due_at)}</p><div className="mt-2 flex flex-wrap gap-1">{item.tags.slice(0,3).map((tag:string)=><span key={tag} className="rounded-md bg-orange-500/10 px-2 py-1 text-[10px] text-orange-100">{tag}</span>)}</div></div><Link href={`/admin/crm/customers/${item.followup.customer_id}`} className="shrink-0 text-xs font-bold text-orange-200">View customer</Link></article>)}</div>:<div className="p-10 text-center text-sm text-[#9CA3AF]">No VIP or at-risk customers have a follow-up due.</div>}</section></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><section className="rounded-2xl border border-white/10 bg-[#111111] p-5"><h2 className="font-bold text-white">Sales Pipeline</h2><div className="mt-5 space-y-3">{data.funnel.map(([status,count]:any)=> <div key={status}><div className="flex justify-between text-xs"><span className="text-[#9CA3AF]">{label(status)}</span><b className="text-white">{count}</b></div><div className="mt-1.5 h-1.5 rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-orange-500 to-amber-300" style={{width:`${Math.min(100,Number(count)*12)}%`}}/></div></div>)}</div></section><section className="rounded-2xl border border-white/10 bg-[#111111] p-5"><h2 className="font-bold text-white">Reply Intelligence</h2><p className="mt-1 text-xs text-[#9CA3AF]">Last 7 days · classifications only, no misleading rate estimate.</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{data.replyCounts.map(([kind,count]:any)=><div key={kind} className="rounded-xl bg-white/[.035] p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-[#9CA3AF]">{label(kind)}</p><b className="mt-2 block text-xl text-white">{count}</b></div>)}</div></section></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-[#111111] p-5"><div className="flex items-center gap-2"><Workflow size={17} className="text-orange-300"/><h2 className="font-bold text-white">Automation Health</h2></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><p className="text-[#9CA3AF]">Processed 24h <b className="ml-1 text-white">{data.health?.summary?.processed_24h??0}</b></p><p className="text-[#9CA3AF]">Failed 24h <b className="ml-1 text-white">{data.health?.summary?.failed_24h??0}</b></p><p className="text-[#9CA3AF]">Current failures <b className="ml-1 text-white">{data.health?.summary?.current_failures??0}</b></p><p className="text-[#9CA3AF]">Stuck events <b className="ml-1 text-white">{data.health?.summary?.stuck_events??0}</b></p></div><Link href="/admin/crm/automations" className="mt-5 inline-block text-xs font-bold text-orange-200">View automation details</Link></section><section className="rounded-2xl border border-white/10 bg-[#111111] p-5"><div className="flex items-center gap-2"><ShieldCheck size={17} className="text-orange-300"/><h2 className="font-bold text-white">Safety Status</h2></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs">{[["Outbound Auto Send",data.settings.autoSend],["AI Auto Reply",data.settings.replies?.generate_ai_reply_drafts],["Reply Detection",data.settings.replies?.reply_detection_enabled],["Auto Classification",data.settings.replies?.auto_classify_replies],["Sequence Stop on Reply",data.settings.replies?.auto_stop_sequence_on_reply],["Follow-up Creation",data.settings.replies?.create_reply_followups]].map(([name,enabled])=><div key={String(name)} className="flex justify-between rounded-lg bg-white/[.035] p-3"><span className="text-[#9CA3AF]">{String(name)}</span><b className={enabled?"text-emerald-200":"text-orange-100"}>{enabled?"ON":"OFF"}</b></div>)}</div></section></section>
  </main>;
}
