import Link from "next/link";
import { campaignPackages } from "@/lib/campaign-packages";

export default function PackageComparison({ serviceName }: { serviceName: string }) {
  return <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-6 sm:px-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Package comparison</p><h2 className="mt-3 text-2xl font-bold tracking-tight text-[#0a1733]">Choose your {serviceName} program.</h2><p className="mt-2 text-sm text-slate-500">Compare investment, duration, capabilities, audience fit, and expected outcomes.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-xs"><thead><tr className="bg-slate-50"><th className="px-6 py-4 font-semibold text-slate-500">Package</th>{campaignPackages.map((item) => <th key={item.id} className={`px-5 py-4 ${item.id === "professional" ? "bg-blue-50 text-blue-700" : "text-slate-700"}`}><p className="text-sm font-bold">{item.name}</p><p className="mt-1 text-lg font-bold">{item.priceLabel}</p></th>)}</tr></thead><tbody className="divide-y divide-slate-100">{[
    ["Campaign duration", ...campaignPackages.map((item) => item.duration)],
    ["Recommended audience", ...campaignPackages.map((item) => item.audience)],
    ["Expected outcome", ...campaignPackages.map((item) => item.outcome)],
    ["ROI potential", ...campaignPackages.map((item) => item.roi)],
  ].map((row) => <tr key={row[0]}><th className="px-6 py-4 font-semibold text-slate-700">{row[0]}</th>{row.slice(1).map((value,index) => <td key={`${row[0]}-${value}`} className={`px-5 py-4 leading-5 text-slate-500 ${index === 2 ? "bg-blue-50/50" : ""}`}>{value}</td>)}</tr>)}<tr><th className="px-6 py-5">Get started</th>{campaignPackages.map((item) => <td key={item.id} className={`px-5 py-5 ${item.id === "professional" ? "bg-blue-50/50" : ""}`}><Link href={item.id === "enterprise" ? "/dashboard/support" : "/register"} className={`block rounded-lg px-3 py-2.5 text-center text-[10px] font-bold ${item.id === "professional" ? "bg-blue-600 text-white" : "border border-slate-200 text-slate-700"}`}>{item.id === "enterprise" ? "Request proposal" : "Select package"}</Link></td>)}</tr></tbody></table></div></section>;
}
