import { BarChart3, ImageIcon, Link2, Type, Video } from "lucide-react";

export const tools = [
  { slug: "instagram-engagement-rate-calculator", title: "Instagram Engagement Rate Calculator", short: "Calculate post engagement against followers or reach.", description: "Free Instagram engagement rate calculator for creators, brands and social media teams.", icon: BarChart3, keywords: ["Instagram engagement rate calculator", "Instagram engagement calculator"], service: "/services/instagram-likes", serviceLabel: "Explore Instagram growth services", faqs: [{ q: "What is a good Instagram engagement rate?", a: "A useful benchmark varies by audience size and format. Compare your own recent posts consistently and look for improving engagement quality over time." }, { q: "Does this calculator access my Instagram account?", a: "No. Enter your numbers manually; this tool does not connect to, scrape, or access Instagram." }] },
  { slug: "social-media-image-resizer", title: "Social Media Image Resizer", short: "Resize and crop images for popular social formats.", description: "Resize social media images locally in your browser for Instagram, YouTube and more.", icon: ImageIcon, keywords: ["social media image resizer", "Instagram image resizer", "YouTube thumbnail resizer"], service: "/services", serviceLabel: "Plan your next social campaign", faqs: [{ q: "Are my images uploaded?", a: "No. Resizing happens locally in your browser. Your image is not sent to SocialRUSH servers." }, { q: "Which formats can I use?", a: "Use common browser-supported image formats such as JPG, PNG, and WebP." }] },
  { slug: "youtube-thumbnail-preview", title: "YouTube Thumbnail Preview & Title Checker", short: "Preview a thumbnail and check title length before publishing.", description: "Preview YouTube thumbnails and check title length on desktop and mobile-inspired layouts.", icon: Video, keywords: ["YouTube thumbnail preview", "YouTube title checker"], service: "/services/youtube-views", serviceLabel: "Explore YouTube growth services", faqs: [{ q: "Does this publish to YouTube?", a: "No. It is a planning preview only and does not connect to YouTube." }, { q: "What title length should I aim for?", a: "Keep the clearest message near the beginning. This checker flags long titles so you can review how they may scan on smaller screens." }] },
  { slug: "instagram-caption-counter", title: "Instagram Caption & Character Counter", short: "Count characters, words, hashtags and line breaks as you write.", description: "Free Instagram caption character counter with hashtag and word counts.", icon: Type, keywords: ["Instagram caption character counter", "Instagram caption counter"], service: "/services/instagram-followers", serviceLabel: "Explore Instagram growth services", faqs: [{ q: "What is Instagram's caption limit?", a: "Instagram captions allow up to 2,200 characters. This tool highlights your current total while you write." }, { q: "Does it save my caption?", a: "No. Your caption stays in your browser and is cleared when you refresh or leave the page." }] },
  { slug: "utm-link-builder", title: "UTM Link Builder", short: "Create clean campaign links with consistent UTM parameters.", description: "Build UTM-tracked campaign URLs for social media, creator and paid campaigns.", icon: Link2, keywords: ["UTM link builder", "campaign URL builder", "social media UTM builder"], service: "/services", serviceLabel: "Explore growth services", faqs: [{ q: "What are UTM parameters?", a: "They are tags added to a link so analytics tools can identify where visits came from and which campaign drove them." }, { q: "Does this shorten links?", a: "No. It creates a full tagged URL that you can paste into your preferred shortener if needed." }] },
] as const;

export type Tool = (typeof tools)[number];
export const toolBySlug = Object.fromEntries(tools.map((tool) => [tool.slug, tool])) as Record<string, Tool>;
