import { BarChart3, ClipboardCheck, DollarSign, ImageIcon, Link2, Type, Video } from "lucide-react";

const rawTools = [
  { slug: "instagram-engagement-rate-calculator", title: "Instagram Engagement Rate Calculator", short: "Calculate post engagement against followers or reach.", description: "Calculate your Instagram engagement rate using your own follower, like and comment data. Free tool for creators, brands and social media teams.", icon: BarChart3, keywords: ["Instagram engagement rate calculator", "Instagram engagement calculator"], service: "/services/instagram-likes", serviceLabel: "Explore Instagram growth services", faqs: [{ q: "What is a good Instagram engagement rate?", a: "A useful benchmark varies by audience size and format. Compare your own recent posts consistently and look for improving engagement quality over time." }, { q: "Does this calculator access my Instagram account?", a: "No. Enter your numbers manually; this tool does not connect to, scrape, or access Instagram." }] },
  { slug: "social-media-image-resizer", title: "Social Media Image Resizer", short: "Resize and crop images for popular social formats.", description: "Free social media image resizer for Instagram, YouTube, Facebook, and LinkedIn. Resize images online locally in your browser.", icon: ImageIcon, keywords: ["social media image resizer", "free social media image resizer", "Instagram image resizer", "resize image for Instagram", "YouTube thumbnail resizer", "social media image size tool", "resize image online"], service: "/services", serviceLabel: "Plan your next social campaign", faqs: [{ q: "Are my images uploaded?", a: "No. Resizing happens locally in your browser. Your image is not sent to SocialRUSH servers." }, { q: "Which formats can I use?", a: "Use JPG, PNG, and WebP images." }, { q: "Can I resize for Instagram or YouTube?", a: "Yes. The tool includes Instagram post, Story / Reel, and YouTube thumbnail presets." }] },
  { slug: "youtube-thumbnail-preview", title: "YouTube Thumbnail Preview & Title Checker", short: "Preview a thumbnail and check title length before publishing.", description: "Preview a YouTube thumbnail and title in desktop and mobile-style layouts. Check title length and presentation before publishing your video.", icon: Video, keywords: ["YouTube thumbnail preview", "YouTube title checker"], service: "/services/youtube-views", serviceLabel: "Explore YouTube growth services", faqs: [{ q: "Does this publish to YouTube?", a: "No. It is a planning preview only and does not connect to YouTube." }, { q: "What title length should I aim for?", a: "Keep the clearest message near the beginning. This checker flags long titles so you can review how they may scan on smaller screens." }] },
  { slug: "instagram-caption-counter", title: "Instagram Caption & Character Counter", short: "Count characters, words, hashtags and line breaks as you write.", description: "Count Instagram caption characters, words and hashtags before posting. Use this free SocialRUSH tool to stay within platform limits.", icon: Type, keywords: ["Instagram caption character counter", "Instagram caption counter"], service: "/services/instagram-followers", serviceLabel: "Explore Instagram growth services", faqs: [{ q: "What is Instagram's caption limit?", a: "Instagram captions allow up to 2,200 characters. This tool highlights your current total while you write." }, { q: "Does it save my caption?", a: "No. Your caption stays in your browser and is cleared when you refresh or leave the page." }] },
  { slug: "utm-link-builder", title: "UTM Link Builder", short: "Create clean campaign links with consistent UTM parameters.", description: "Build campaign URLs with UTM parameters for social media, creator and paid campaigns. Create clean tracking links quickly with SocialRUSH.", icon: Link2, keywords: ["UTM link builder", "free UTM builder", "campaign URL builder", "UTM campaign URL generator", "UTM parameter generator", "social media UTM builder", "marketing URL builder"], service: "/services", serviceLabel: "Explore growth services", faqs: [{ q: "What are UTM parameters?", a: "They are tags added to a link so analytics tools can identify where visits came from and which campaign drove them." }, { q: "What does utm_source mean?", a: "utm_source identifies where traffic came from, such as instagram, youtube, or a newsletter." }, { q: "What does utm_medium mean?", a: "utm_medium describes the marketing channel type, such as social, email, cpc, or referral." }, { q: "What does utm_campaign mean?", a: "utm_campaign is a clear identifier for the promotion or campaign you want to analyze." }, { q: "Do UTM parameters change the destination page?", a: "No. They add campaign context to the URL while keeping the destination page the same." }, { q: "Can I use UTM links for Instagram or YouTube?", a: "Yes. Add the tagged link wherever it is appropriate for your campaign." }, { q: "Does this shorten links?", a: "No. It creates a full tagged URL that you can paste into your preferred shortener if needed." }] },
  { slug: "youtube-engagement-rate-calculator", title: "YouTube Engagement Rate Calculator", short: "Calculate engagement, view-to-subscriber and like-to-view ratios.", description: "Calculate your YouTube engagement rate from your own views, likes and comments. Free tool for creators, channels and social media teams.", icon: BarChart3, keywords: ["YouTube engagement rate calculator", "YouTube engagement calculator"], service: "/youtube-subscribers", serviceLabel: "Explore YouTube services", faqs: [{ q: "Are these official YouTube metrics?", a: "No. These are transparent planning ratios calculated from the values you enter." }, { q: "Does this connect to my channel?", a: "No. Your figures stay in your browser and no YouTube account access is required." }] },
  { slug: "youtube-revenue-calculator", title: "YouTube Revenue Estimator", short: "Estimate a monthly ad-revenue range from views and an RPM range.", description: "Estimate a possible YouTube monthly revenue range from your views and estimated RPM. Not a guarantee.", icon: DollarSign, keywords: ["YouTube revenue calculator", "YouTube earnings estimator", "YouTube revenue calculator India"], service: "/youtube-subscribers", serviceLabel: "Explore YouTube services", faqs: [{ q: "Is this a revenue guarantee?", a: "No. It is an estimate only. Actual earnings vary substantially by monetized playbacks, geography, niche, seasonality, format and YouTube policies." }, { q: "What is RPM?", a: "RPM is estimated revenue per 1,000 views after YouTube's revenue share. Enter a range you consider realistic for your channel." }] },
  { slug: "social-media-growth-budget-calculator", title: "Social Media Growth Budget Calculator", short: "Plan a transparent creator budget using your own inputs.", description: "Estimate a social media growth budget with your own content, promotion, tools and support costs. No live market prices are assumed.", icon: DollarSign, keywords: ["social media growth budget calculator", "creator marketing budget calculator", "social media budget planner India"], service: "/pricing", serviceLabel: "Review current SocialRUSH pricing", faqs: [{ q: "Does this calculator use SocialRUSH prices?", a: "No. You enter every amount yourself. Check live package information separately before making a purchase decision." }, { q: "Is this a forecast of results?", a: "No. It is a planning total only. Costs do not guarantee reach, engagement, revenue, or other outcomes." }] },
  { slug: "creator-growth-checklist", title: "Creator Growth Checklist", short: "Work through an actionable pre-flight checklist for content and campaigns.", description: "A free interactive creator growth checklist covering profile readiness, content, measurement, public links and account safety.", icon: ClipboardCheck, keywords: ["creator growth checklist", "social media campaign checklist", "creator campaign planning"], service: "/services", serviceLabel: "Explore growth services", faqs: [{ q: "Is the checklist a guarantee of growth?", a: "No. It helps organise preparation and measurement; results depend on content, audience, platform conditions, and execution." }, { q: "Do I need to share account access?", a: "No. This checklist works in your browser and reinforces that passwords, OTPs, and recovery codes should not be shared." }] },
  { slug: "creator-growth-goal-planner", title: "Creator Growth Goal Planner", short: "Turn a growth goal into a weekly content and measurement plan.", description: "Plan a transparent creator growth goal using your own baseline, target, timeframe and publishing capacity. No platform data is accessed.", icon: ClipboardCheck, keywords: ["creator growth goal planner", "social media goal planner", "creator growth planning tool"], service: "/services", serviceLabel: "Explore growth services", faqs: [{ q: "Does this predict followers or views?", a: "No. It simply breaks a self-entered goal into a planning cadence. Platform results depend on content, audience fit and many factors outside this tool." }, { q: "Does SocialRUSH access my account data?", a: "No. All values are entered by you and stay in your browser." }] },
 ] as const;

const canonicalServiceLinks: Record<string, string> = {
  "/services/instagram-followers": "/services?platform=instagram",
  "/services/instagram-likes": "/services?platform=instagram",
  "/services/youtube-views": "/services?platform=youtube",
};

export const tools = rawTools.map((tool) => ({
  ...tool,
  service: canonicalServiceLinks[tool.service] ?? tool.service,
}));

export type Tool = (typeof tools)[number];
export const toolBySlug = Object.fromEntries(tools.map((tool) => [tool.slug, tool])) as Record<string, Tool>;
