-- Complete, idempotent admin portal support.
-- Safe to re-run: no existing tables or customer data are dropped.

alter table public.profiles add column if not exists is_blocked boolean not null default false;

create table if not exists public.packages (
  id bigint generated by default as identity primary key,
  name text not null,
  platform text not null,
  price numeric(14, 2) not null default 0 check (price >= 0),
  features jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.website_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

alter table public.support_tickets drop constraint if exists support_tickets_status_check;
alter table public.support_tickets
  add constraint support_tickets_status_check
  check (status in ('open', 'pending', 'answered', 'solved', 'closed'));

alter table public.packages enable row level security;
alter table public.website_settings enable row level security;

drop policy if exists "packages_read_active_or_admin" on public.packages;
create policy "packages_read_active_or_admin" on public.packages
  for select to authenticated using (is_active or public.is_admin());
drop policy if exists "packages_admin_insert" on public.packages;
create policy "packages_admin_insert" on public.packages
  for insert to authenticated with check (public.is_admin());
drop policy if exists "packages_admin_update" on public.packages;
create policy "packages_admin_update" on public.packages
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "packages_admin_delete" on public.packages;
create policy "packages_admin_delete" on public.packages
  for delete to authenticated using (public.is_admin());

drop policy if exists "website_settings_admin_select" on public.website_settings;
create policy "website_settings_admin_select" on public.website_settings
  for select to authenticated using (public.is_admin());
drop policy if exists "website_settings_admin_insert" on public.website_settings;
create policy "website_settings_admin_insert" on public.website_settings
  for insert to authenticated with check (public.is_admin());
drop policy if exists "website_settings_admin_update" on public.website_settings;
create policy "website_settings_admin_update" on public.website_settings
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

insert into public.website_settings (key, value)
values (
  'general',
  jsonb_build_object(
    'whatsapp_number', '8860330771',
    'support_email', 'support@getsocialrush.com',
    'currency_rates', jsonb_build_object('INR', 1, 'USD', 0.012, 'EUR', 0.011, 'GBP', 0.0093, 'AED', 0.044, 'CAD', 0.016, 'AUD', 0.018),
    'payment_instructions', '',
    'notice_text', ''
  )
)
on conflict (key) do nothing;

create or replace function public.admin_set_user_blocked(p_user_id uuid, p_blocked boolean)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if p_user_id = auth.uid() and p_blocked then raise exception 'You cannot block your own administrator account'; end if;
  update public.profiles set is_blocked = p_blocked where id = p_user_id;
  if not found then raise exception 'User not found'; end if;
end;
$$;

revoke all on function public.admin_set_user_blocked(uuid, boolean) from public;
grant execute on function public.admin_set_user_blocked(uuid, boolean) to authenticated;

create or replace function public.admin_review_payment(p_transaction_id uuid, p_decision text)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  v_transaction public.transactions%rowtype;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if p_decision not in ('approve', 'reject') then raise exception 'Invalid payment decision'; end if;

  select * into v_transaction
  from public.transactions
  where id = p_transaction_id
  for update;

  if not found then raise exception 'Payment not found'; end if;
  if v_transaction.status <> 'pending' then raise exception 'Payment has already been reviewed'; end if;
  if v_transaction.type <> 'credit' then raise exception 'Only pending credit payments can be reviewed'; end if;
  if coalesce(v_transaction.payment_method, '') <> 'manual_upi' then
    raise exception 'Only manual payments can be reviewed by an administrator';
  end if;

  if p_decision = 'approve' then
    update public.profiles
      set balance = balance + v_transaction.amount
      where id = v_transaction.user_id;
    update public.transactions set status = 'completed' where id = p_transaction_id;
  else
    update public.transactions set status = 'failed' where id = p_transaction_id;
  end if;
end;
$$;

revoke all on function public.admin_review_payment(uuid, text) from public;
grant execute on function public.admin_review_payment(uuid, text) to authenticated;
