import type { Metadata } from "next";
import Link from "next/link";
import MarketingIcon from "@/components/marketing/MarketingIcon";
import PageHero from "@/components/marketing/PageHero";
import PortalCTA from "@/components/marketing/PortalCTA";
import PublicShell from "@/components/marketing/PublicShell";
import { agencyServices } from "@/lib/marketing/content";

export const metadata: Metadata = { title: "Social Media Growth Pricing", description: "Review transparent starting rates for SocialRUSH followers, likes, views, and subscriber services, then calculate the exact total before checkout." };
const platformNames = ["Instagram", "YouTube", "Facebook", "LinkedIn", "TikTok", "Twitter/X"];

export default function PricingPage() {
  return <PublicShell><PageHero eyebrow="Transparent campaign pricing" title="Know the rate, quantity, and total before you confirm." description="Pricing depends on the selected platform, service, and quantity. Your customer dashboard calculates the exact current total before any campaign charge is applied." />
    <section className="px-5 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-4 md:grid-cols-3">{[["wallet", "Fund securely", "Verified Razorpay payments credit your account wallet."], ["search", "Choose and calculate", "Select a live service and enter the campaign quantity."], ["shield", "Review before confirming", "Check the total, destination, delivery, and refill details."]].map(([icon, title, text], index) => <article key={title} className="relative rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-600"><MarketingIcon name={icon as "wallet" | "search" | "shield"} className="h-6 w-6" /></span><span className="absolute right-5 top-5 text-3xl font-black text-blue-100">0{index + 1}</span><h2 className="mt-5 text-base font-bold text-[#07152f]">{title}</h2><p className="mt-2 text-xs leading-6 text-slate-500">{text}</p></article>)}</div></section>
    <section className="bg-[#f6f9ff] px-5 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Starting-price overview</p><h2 className="mt-4 text-3xl font-bold text-[#07152f]">Compare services by platform.</h2><p className="mt-3 text-sm leading-7 text-slate-600">These public starting rates help with planning. The campaign dashboard remains the source of truth for current availability and the final checkout amount.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-2">{platformNames.map((platform) => { const services = agencyServices.filter((service) => service.platform === platform); return <article key={platform} className="overflow-hidden rounded-3xl border border-white bg-white shadow-[0_12px_45px_-25px_rgba(7,21,47,.25)]"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-[10px] font-black text-blue-700">{platform.slice(0, 2).toUpperCase()}</span><h2 className="text-lg font-bold text-[#07152f]">{platform}</h2></div><Link href={`/services#${platform.toLowerCase().replace("/", "-")}`} className="text-[10px] font-bold text-blue-600">View details</Link></div><div className="divide-y divide-slate-100">{services.map((service) => <div key={service.slug} className="flex items-center justify-between gap-4 px-6 py-4 transition hover:bg-blue-50/40"><div><h3 className="text-xs font-bold text-slate-700">{service.name}</h3><p className="mt-1 text-[9px] text-slate-400">Tracked order · Total reviewed before checkout</p></div><p className="shrink-0 text-sm font-bold text-blue-600">{service.price}</p></div>)}</div></article>; })}</div></div></section>
    <section className="px-5 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-[30px] bg-gradient-to-br from-[#07152f] to-blue-800 p-7 text-white sm:p-9"><MarketingIcon name="card" className="h-8 w-8 text-blue-300" /><h2 className="mt-6 text-2xl font-bold">How wallet charging works</h2><div className="mt-6 space-y-4">{["Add funds through a verified Razorpay checkout.", "Select the service, public link, and quantity.", "Review the current rate and exact campaign total.", "Wallet balance is used only after you confirm the order."].map((item, index) => <div key={item} className="flex gap-3 text-xs leading-6 text-slate-300"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-blue-500/20 text-[9px] font-bold text-blue-300">{index + 1}</span>{item}</div>)}</div></div><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Pricing questions</p><div className="mt-5 space-y-3">{[["Why are prices shown per 1,000?", "The per-1,000 rate provides a consistent comparison. Your quantity is calculated proportionally in New Campaign."], ["Can the rate change?", "Service conditions can change. The current rate and total are always displayed before confirmation."], ["Does every service include refill coverage?", "No. Eligible services are marked with their applicable refill terms before checkout."], ["When is my wallet charged?", "Only when you confirm a valid campaign order with sufficient balance."]].map(([question, answer]) => <details key={question} className="group rounded-2xl border border-slate-200 bg-white p-5 open:border-blue-200 open:shadow-lg"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 text-sm font-bold text-[#07152f]">{question}<span className="text-blue-600 transition group-open:rotate-45">+</span></summary><p className="mt-4 text-xs leading-6 text-slate-500">{answer}</p></details>)}</div></div></div></section>
    <section className="px-5 pb-20 sm:px-6"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-6 rounded-3xl border border-blue-100 bg-blue-50 p-7 sm:flex-row sm:items-center"><div><h2 className="text-xl font-bold text-[#07152f]">Ready to see current campaign pricing?</h2><p className="mt-2 text-xs leading-6 text-slate-600">Open the secure campaign flow and review live availability before ordering.</p></div><PortalCTA className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white">Check live services <MarketingIcon name="arrow" className="h-4 w-4" /></PortalCTA></div></section>
  </PublicShell>;
}
