import type { Metadata } from "next";
import PageHero from "@/components/marketing/PageHero";
import PortalCTA from "@/components/marketing/PortalCTA";
import PublicShell from "@/components/marketing/PublicShell";
import { agencyServices } from "@/lib/marketing/content";

export const metadata: Metadata = { title: "Social Media Growth Pricing", description: "Review transparent starting rates for SocialRUSH followers, likes, views, and subscriber services, then calculate the exact total before checkout." };

export default function PricingPage() {
  return <PublicShell><PageHero eyebrow="Transparent pricing" title="Clear rates before you launch." description="Rates are shown per 1,000 units. Choose a service and quantity in New Campaign to calculate the exact wallet charge before confirming your order." /><section className="bg-[#f6f9ff] px-5 py-16 sm:px-6 lg:py-20"><div className="mx-auto max-w-7xl"><div className="mb-10 grid gap-4 md:grid-cols-3">{[["1. Add funds", "Fund your wallet securely through supported Razorpay payment methods."], ["2. Set quantity", "Choose a live service and enter the quantity required for your campaign."], ["3. Confirm total", "Review the final charge and delivery details before wallet checkout."]].map(([title, text]) => <article key={title} className="rounded-2xl border border-white bg-white p-5 shadow-sm"><h2 className="text-sm font-bold text-[#07152f]">{title}</h2><p className="mt-2 text-xs leading-6 text-slate-500">{text}</p></article>)}</div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{agencyServices.map((service) => <article key={service.slug} className="rounded-2xl border border-white bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><p className="text-[10px] font-bold uppercase tracking-wider text-blue-600">{service.platform}</p><h2 className="mt-3 text-base font-bold text-[#07152f]">{service.name}</h2><p className="mt-4 text-2xl font-bold text-blue-600">{service.price}</p><p className="mt-3 text-xs leading-6 text-slate-500">Live total calculation · Secure wallet checkout · Campaign tracking</p><PortalCTA className="mt-5 flex min-h-11 items-center justify-center rounded-xl bg-blue-600 px-4 py-3 text-center text-xs font-bold text-white transition hover:bg-blue-700">Check live availability</PortalCTA></article>)}</div><div className="mt-10 rounded-2xl border border-blue-100 bg-blue-50 p-6 text-sm leading-7 text-blue-900"><strong>Pricing note:</strong> Service rates and availability can change as delivery conditions change. Your campaign checkout always shows the current rate, quantity, and final total before you confirm an order.</div></div></section></PublicShell>;
}
