import Link from "next/link";
import PricingGrid from "@/components/marketing/pricing/PricingGrid";
import PublicShell from "@/components/marketing/PublicShell";
import BreadcrumbJsonLd from "@/components/seo/BreadcrumbJsonLd";
import { createPageMetadata } from "@/lib/seo/metadata";
import { getLiveServiceFacts } from "@/lib/seo/live-service";
import { activeSmmServices, type SmmService } from "@/lib/smm-service-catalog";

export const revalidate = 300;

export const metadata = createPageMetadata({ title: "Social Media Service Pricing India | Live Rates", description: "Compare live SocialRUSH pricing for Instagram, YouTube, Facebook, LinkedIn, Telegram, TikTok and X services, including delivery and refill details.", path: "/pricing", keywords: ["social media service pricing India", "Instagram followers price India", "Instagram likes price", "YouTube subscribers price India", "Facebook followers price", "LinkedIn followers price"] });
const faqs = [["How is SocialRUSH pricing calculated?", "The selected quantity is calculated from the active catalog rate, normally shown per 1,000 units. Your exact estimated total is visible before you continue."],["Are prices live?", "Yes. This page reads the same active service catalog used by the order experience."],["What does price per 1K mean?", "It is the rate for 1,000 units. For example, an order for 500 units is calculated as half of the displayed 1K rate."],["Can I choose a custom quantity?", "Yes, provided it is a whole number within the live minimum and maximum for the selected service."],["Do I need to share my password?", "No. SocialRUSH orders use the relevant public profile, post, video, channel, or group link."],["Where do I see my final total?", "The calculator and the existing order flow show the current total before you confirm an order."]] as const;
const faqSchema = JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }).replace(/</g, "\\u003c");

export default async function PricingPage() {
  const liveOnlyCodes = new Set(["twitter-likes", "twitter-views", "twitter-retweets", "twitter-crypto-followers", "twitter-crypto-likes", "twitter-crypto-retweets", "twitter-crypto-custom-comments"]);
  const liveDefinitions = [
    ["instagram-followers", "instagram", "Instagram Real Followers"],
    ["linkedin-followers", "linkedin", "LinkedIn Profile Followers"],
    ["x-followers", "x", "X Followers"],
    ["twitter-likes", "x", "Twitter / X Likes"],
    ["twitter-views", "x", "Twitter / X Views"],
    ["twitter-retweets", "x", "Twitter / X Retweets"],
    ["twitter-crypto-followers", "x", "Twitter / X Crypto-Based Followers"],
    ["twitter-crypto-likes", "x", "Twitter / X Crypto-Based Likes"],
    ["twitter-crypto-retweets", "x", "Twitter / X Crypto-Based Retweets"],
    ["twitter-crypto-custom-comments", "x", "Twitter / X Crypto-Based Custom Comments"],
  ] as const;
  const liveCatalog = await Promise.all(liveDefinitions.map(async ([code, platform, name]) => {
    const fallback = activeSmmServices.find((service) => service.code === code);
    const live = await getLiveServiceFacts(platform, name, code);
    return fallback && live?.available && Number.isFinite(live.rate) && live.rate > 0 && live.min > 0 && live.max >= live.min ? { ...fallback, pricePer1000: live.rate, minQuantity: live.min, maxQuantity: live.max, deliveryTime: live.deliveryTime, refillPolicy: live.refillPolicy, qualityType: live.qualityType, importantInstruction: live.importantInstruction } satisfies SmmService : fallback;
  }));
  const serviceCatalog = activeSmmServices.map((service) => liveCatalog.find((live) => live?.code === service.code) ?? service).filter((service) => !liveOnlyCodes.has(service.code) || liveCatalog.some((live) => live?.code === service.code && live.pricePer1000 > 0 && live.minQuantity > 0 && live.maxQuantity >= live.minQuantity));
  return <PublicShell tone="light3d"><BreadcrumbJsonLd items={[{ name: "Home", path: "/" }, { name: "Pricing", path: "/pricing" }]} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: faqSchema }} />
  <div className="relative overflow-hidden bg-[#090a0f] text-white"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_12%_4%,rgba(255,107,0,.22),transparent_25%),radial-gradient(circle_at_86%_18%,rgba(26,74,150,.22),transparent_28%)]" />
    <section className="relative mx-auto max-w-7xl px-5 pb-14 pt-14 sm:px-6 sm:pt-20 lg:px-8 lg:pb-20"><p className="text-[11px] font-black uppercase tracking-[.2em] text-orange-300">Transparent SocialRUSH Pricing</p><div className="mt-5 grid gap-8 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><h1 className="max-w-4xl text-4xl font-black leading-[1.03] tracking-[-.05em] sm:text-6xl">Clear pricing before you <span className="text-orange-300">place an order.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-300">Compare live SocialRUSH service rates across Instagram, YouTube, Facebook, LinkedIn, Telegram, TikTok and X.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="#pricing-catalog" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-gradient-to-r from-[#FF6200] to-[#FF9A00] px-5 text-sm font-black text-white">Compare Prices</Link><Link href="/packages" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/15 bg-white/[.04] px-5 text-sm font-black text-white">View Packages</Link></div></div><div className="grid grid-cols-2 gap-2 rounded-3xl border border-white/10 bg-white/[.035] p-4 text-xs text-slate-300 sm:grid-cols-3">{["Live catalog rates","Public-link ordering","No password required","Secure checkout","Dashboard tracking"].map((item) => <span key={item} className="rounded-xl border border-white/[.07] bg-black/20 px-3 py-3 font-bold">✓ {item}</span>)}</div></div></section>
    <section className="relative border-y border-white/[.08] bg-[#0d0f16] px-5 py-7 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-3 md:grid-cols-3">{[["Live rate","Current catalog price for the selected service."],["Quantity","Your chosen campaign amount within that service’s live limits."],["Total","Calculated before you continue to checkout."]].map(([title, copy], index) => <div key={title} className="flex gap-4 rounded-2xl bg-white/[.035] p-4"><span className="text-xl font-black text-orange-300">0{index + 1}</span><div><h2 className="text-xs font-black uppercase tracking-[.15em] text-white">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-400">{copy}</p></div></div>)}</div><p className="mx-auto mt-4 max-w-7xl text-xs text-slate-500">Rates marked “/ 1K” are the price for 1,000 units; the calculator scales that live rate to your selected quantity.</p></section>
    <section id="pricing-catalog" className="relative mx-auto max-w-7xl px-5 py-14 sm:px-6 lg:px-8 lg:py-20"><PricingGrid serviceCatalog={serviceCatalog} /></section>
    <section className="relative mx-auto grid max-w-7xl gap-4 px-5 pb-14 sm:px-6 lg:grid-cols-2 lg:px-8"><div className="rounded-3xl border border-orange-400/25 bg-orange-500/[.07] p-7"><p className="text-[10px] font-black uppercase tracking-[.18em] text-orange-300">Custom service</p><h2 className="mt-3 text-2xl font-black">Choose exactly what you need</h2><ul className="mt-4 space-y-2 text-sm text-slate-300"><li>Choose an exact service</li><li>Set a valid quantity</li><li>See your calculated total</li></ul><Link href="/services" className="mt-6 inline-flex min-h-11 items-center font-black text-orange-200">Explore Services →</Link></div><div className="rounded-3xl border border-white/10 bg-white/[.04] p-7"><p className="text-[10px] font-black uppercase tracking-[.18em] text-slate-400">Ready-made package</p><h2 className="mt-3 text-2xl font-black">Compare a pre-set campaign</h2><ul className="mt-4 space-y-2 text-sm text-slate-300"><li>Pre-set quantity</li><li>Clear total price</li><li>Quick selection</li></ul><Link href="/packages" className="mt-6 inline-flex min-h-11 items-center font-black text-orange-200">View Packages →</Link></div></section>
    <section className="relative mx-auto max-w-7xl px-5 pb-14 sm:px-6 lg:px-8"><div className="rounded-3xl border border-white/10 bg-[#101116] p-6 sm:p-8"><p className="text-[10px] font-black uppercase tracking-[.18em] text-orange-300">Pricing clarity</p><h2 className="mt-3 text-2xl font-black">Why service rates can vary</h2><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{["Service type","Platform","Quantity","Delivery profile","Refill/support terms","Display currency"].map((item) => <span key={item} className="rounded-xl border border-white/[.07] bg-white/[.03] p-3 text-sm font-bold text-slate-200">{item}</span>)}</div></div></section>
    <section className="relative mx-auto max-w-7xl px-5 pb-20 sm:px-6 lg:px-8"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-orange-300">Questions, answered</p><h2 className="mt-3 text-3xl font-black tracking-tight">How to read SocialRUSH pricing</h2><p className="mt-4 text-sm leading-7 text-slate-400"><strong className="text-orange-200">₹799 / 1K</strong> means ₹799 is the current rate for 1,000 units. Your final total depends on the validated quantity you select.</p></div><div className="space-y-2">{faqs.map(([question, answer]) => <details key={question} className="group rounded-2xl border border-white/10 bg-white/[.035] p-4 open:bg-white/[.06]"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-bold">{question}<span className="text-xl text-orange-300 group-open:rotate-45">+</span></summary><p className="pt-3 text-sm leading-6 text-slate-400">{answer}</p></details>)}</div></div></section>
  </div></PublicShell>; }
