import assert from "node:assert/strict";
import test from "node:test";
import { canPromoteCandidate, normalizeDomain, normalizeEmail, parseProspectingCsv } from "../../lib/crm/prospecting.ts";
import { getDiscoveryWebsite, isLowQualityDiscoveryResult } from "../../lib/crm/prospect-discovery-filters.ts";
import { companySeedFromResult, extractCompanyNameFromLinkedInTitle, resolveOfficialWebsite } from "../../lib/crm/prospect-discovery-resolver.ts";

test("normalizes domains and emails for duplicate lookup",()=>{assert.equal(normalizeDomain(" https://WWW.Acme.com/path "),"acme.com");assert.equal(normalizeEmail(" SALES@Acme.COM "),"sales@acme.com")});
test("CSV aliases, blanks and invalid required rows are deterministic",()=>{const rows=parseProspectingCsv("company,website,email,country\nAcme,www.acme.com, SALES@ACME.COM ,US\n,,,");assert.equal(rows[0].data.business_name,"Acme");assert.equal(rows[0].data.domain,"acme.com");assert.equal(rows[0].data.business_email,"sales@acme.com");assert.equal(rows[1].data.country,null);assert.ok(rows[1].errors.length)});
test("CSV rejects more than 500 rows",()=>assert.throws(()=>parseProspectingCsv(`business_name\n${Array(501).fill("Acme").join("\n")}`)));
test("clean public-business candidate is promotion eligible",()=>assert.equal(canPromoteCandidate({business_email:"hi@acme.com",email_verification_status:"valid",compliance_status:"eligible"}).allowed,true));
test("suppressed and compliance blocked candidates cannot promote",()=>{assert.equal(canPromoteCandidate({fit_grade:"do_not_contact"}).allowed,false);assert.equal(canPromoteCandidate({compliance_status:"blocked"}).allowed,false)});
test("invalid, promoted, rejected and internal candidates cannot promote",()=>{for(const c of [{business_email:"x@a.com",email_verification_status:"invalid"},{promoted_lead_id:"id"},{qualification_status:"rejected"},{source_name:"Internal Resend E2E Test"}])assert.equal(canPromoteCandidate(c).allowed,false)});
test("unresolved duplicate blocks but approved separate permits promotion",()=>{assert.equal(canPromoteCandidate({duplicate_lead_id:"id"}).allowed,false);assert.equal(canPromoteCandidate({duplicate_lead_id:"id",duplicate_override:true}).allowed,true)});
test("CSV never produces a guessed email",()=>{const row=parseProspectingCsv("business_name,website\nAcme,acme.com")[0];assert.equal(row.data.business_email,null)});

test("duplicate override never bypasses safety blockers",()=>{assert.equal(canPromoteCandidate({duplicate_lead_id:"id",duplicate_override:true,fit_grade:"do_not_contact"}).allowed,false);assert.equal(canPromoteCandidate({duplicate_lead_id:"id",duplicate_override:true,qualification_status:"rejected"}).allowed,false);});

test("internal test business name is blocked even without source marker",()=>assert.equal(canPromoteCandidate({business_name:"SocialRUSH Internal Test"}).allowed,false));
test("discovery rejects known low-quality source domains",()=>{for(const url of ["https://companydatabase.in/acme","https://cpcb.nic.in/industry","https://ibef.org/industry"])assert.equal(getDiscoveryWebsite(url),null)});
test("discovery allows a normal business website",()=>assert.deepEqual(getDiscoveryWebsite("https://www.acme-agency.in/contact"),{domain:"acme-agency.in",websiteUrl:"https://www.acme-agency.in"}));
test("discovery rejects obvious company-list result",()=>assert.equal(isLowQualityDiscoveryResult({url:"https://example.com/top-ecommerce-companies",title:"Top 20 E-commerce Companies in India",description:"A ranking of the best companies"}),true));
test("discovery staging never supplies a guessed email",()=>{const discovered={business_email:null,email_verification_status:"unverified"};assert.equal(discovered.business_email,null);assert.equal(discovered.email_verification_status,"unverified")});
test("LinkedIn company titles extract deterministic business names",()=>{assert.equal(extractCompanyNameFromLinkedInTitle("Minimalist | LinkedIn"),"Minimalist");assert.equal(extractCompanyNameFromLinkedInTitle("Example Labs - LinkedIn"),"Example Labs")});
test("only LinkedIn company-profile URLs can become seeds",()=>{assert.equal(companySeedFromResult({title:"Jane Doe | LinkedIn",url:"https://www.linkedin.com/in/jane-doe"}),null);assert.equal(companySeedFromResult({title:"Acme | LinkedIn",url:"https://www.linkedin.com/posts/acme"}),null);assert.equal(companySeedFromResult({title:"Marketing | LinkedIn",url:"https://www.linkedin.com/company/marketing"}),null)});
test("resolver rejects weak sources and non-company results",()=>{for(const url of ["https://inc42.com/article/acme","https://discoveringbrands.com/acme","https://instagram.com/acme","https://gov.in/acme.pdf","https://example.com/top-brands"])assert.equal(resolveOfficialWebsite("Acme",{url,title:"Acme official website",description:"Acme"}),null)});
test("resolver requires a strong company-domain match",()=>{const hit=resolveOfficialWebsite("The Minimalist Company Pvt Ltd",{url:"https://minimalist.co/",title:"Minimalist | Official site",description:"Minimalist skincare"});assert.ok(hit);assert.ok(hit!.score>=70);assert.equal(resolveOfficialWebsite("Minimalist",{url:"https://acme.co/",title:"Minimalist official website",description:"Minimalist"}),null)});
