import type { Metadata } from "next";
import PageHero from "@/components/marketing/PageHero";
import PortalCTA from "@/components/marketing/PortalCTA";
import PublicShell from "@/components/marketing/PublicShell";
import { publicFaqs } from "@/lib/marketing/content";

export const metadata: Metadata = { title: "Frequently Asked Questions", description: "Get answers about SocialRUSH ordering, wallet funding, delivery, refills, public links, campaign tracking, and support." };

export default function FaqPage() {
  const schema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: publicFaqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };
  return <PublicShell><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><PageHero eyebrow="Frequently asked questions" title="Clear answers before you place a campaign." description="Learn how SocialRUSH services, wallet payments, delivery, refills, order tracking, and support work." /><section className="bg-[#f6f9ff] px-5 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-4xl space-y-3">{publicFaqs.map(([question, answer], index) => <details key={question} className="group rounded-2xl border border-white bg-white shadow-sm transition open:border-blue-200 open:shadow-lg"><summary className="flex min-h-16 cursor-pointer list-none items-center gap-3 p-4 sm:gap-4 sm:p-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-blue-50 text-xs font-bold text-blue-600">{String(index + 1).padStart(2, "0")}</span><h2 className="flex-1 text-sm font-bold leading-6 text-[#07152f]">{question}</h2><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-slate-50 text-blue-600 transition group-open:rotate-45">+</span></summary><p className="border-t border-blue-50 px-4 py-5 text-sm leading-7 text-slate-600 sm:px-5 sm:pl-[5.25rem]">{answer}</p></details>)}</div><div className="mx-auto mt-10 flex max-w-4xl flex-col items-center justify-between gap-5 rounded-2xl bg-[#07152f] p-6 text-white sm:flex-row"><div><h2 className="font-bold">Still need help choosing a service?</h2><p className="mt-1 text-xs leading-6 text-slate-300">Create an account to browse campaigns, or contact us before ordering.</p></div><div className="flex flex-wrap gap-2"><a href="/contact" className="inline-flex min-h-11 items-center rounded-xl border border-white/15 px-4 py-2 text-xs font-bold">Contact support</a><PortalCTA className="inline-flex min-h-11 items-center rounded-xl bg-blue-600 px-4 py-2 text-xs font-bold">Open services</PortalCTA></div></div></section></PublicShell>;
}
