import Link from "next/link";
import PublicShell from "@/components/marketing/PublicShell";
import MarketCurrencyInitializer from "@/components/marketing/MarketCurrencyInitializer";
import BreadcrumbJsonLd from "@/components/seo/BreadcrumbJsonLd";
import ServiceLandingOrderBuilder from "./ServiceLandingOrderBuilder";
import { activeSmmServices } from "@/lib/smm-service-catalog";
import { countryServiceAlternates, type PublishedCountryServicePage } from "@/lib/seo/international";

export default function CountryServiceLandingPage({ page }: { page: PublishedCountryServicePage }) {
  const service = activeSmmServices.find((item) => item.code === page.catalogServiceCode)!;
  const path = `/${page.market.slug}/${page.serviceSlug}`;
  const faqs = [["What link should I provide?", page.copy.faq], [`What currency will I see in ${page.market.name}?`, `${page.market.currency} is used for display planning. The authoritative checkout is processed in INR.`], ["When does delivery begin?", `The current service information shows an estimated ${service.deliveryTime} delivery window. Keep the destination public while processing.`], ["Is a refill included?", `This service currently shows: ${service.refillPolicy}. Contact support with an order ID if eligible support is needed.`]];
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "Service", name: page.h1, url: `https://www.getsocialrush.com${path}`, offers: { "@type": "Offer", priceCurrency: "INR", price: service.pricePer1000, description: `Price per 1,000 ${service.name}` } }, { "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }] };
  return <PublicShell><MarketCurrencyInitializer currency={page.market.currency} /><BreadcrumbJsonLd items={[{ name: "Home", path: "/" }, { name: page.market.name, path: `/${page.market.slug}` }, { name: service.name, path }]} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
    <main><section className="bg-[#0b0d13] px-5 py-14 text-white sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.25fr_.75fr]"><div><p className="text-xs font-black uppercase tracking-[.16em] text-orange-300">SocialRUSH · {page.market.name}</p><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">{page.h1}</h1><p className="mt-5 max-w-3xl text-base leading-8 text-slate-300">{page.intro}</p><div className="mt-7 flex flex-wrap gap-3"><Link href="#order-builder" className="rounded-xl bg-orange-500 px-5 py-3 text-sm font-black">Choose a package</Link><Link href={`/${page.market.slug}`} className="rounded-xl border border-white/15 px-5 py-3 text-sm font-black">{page.market.name} services</Link></div></div><aside className="rounded-3xl border border-orange-400/25 bg-white/[.04] p-6"><p className="text-xs font-black uppercase tracking-wider text-orange-300">Service details</p><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-slate-400">Delivery</dt><dd className="font-bold">{service.deliveryTime}</dd></div><div><dt className="text-slate-400">Refill</dt><dd className="font-bold">{service.refillPolicy}</dd></div><div><dt className="text-slate-400">Quantity</dt><dd className="font-bold">{service.minQuantity.toLocaleString("en-IN")}–{service.maxQuantity.toLocaleString("en-IN")}</dd></div></dl><p className="mt-5 text-xs leading-5 text-slate-300">No password is required. {page.market.paymentNote}</p></aside></div></section>
    <ServiceLandingOrderBuilder service={service} />
    <section className="px-5 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-2"><article><h2 className="text-3xl font-black">What to know before ordering</h2><p className="mt-4 text-sm leading-7 text-slate-300">{page.copy.consideration} Choose a quantity within the listed limits, then use the public destination requested by the form. The total is calculated from the existing INR catalog price; local currency is display-only.</p></article><article className="rounded-3xl border border-white/10 bg-[#101219] p-6"><h2 className="text-2xl font-black">How it works</h2><ol className="mt-4 space-y-3 text-sm leading-6 text-slate-300"><li>1. Select a valid quantity.</li><li>2. Add the correct public {service.platform} link.</li><li>3. Review the total and continue to the existing secure order flow.</li></ol></article></div></section>
    <section className="bg-[#0b0d13] px-5 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><h2 className="text-3xl font-black">Frequently asked questions</h2><div className="mt-7 grid gap-4">{faqs.map(([question, answer]) => <article key={question} className="rounded-2xl border border-white/10 bg-[#101219] p-5"><h3 className="font-black">{question}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{answer}</p></article>)}</div></div></section>
    <section className="px-5 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-black">Available in other markets</h2><div className="mt-6 flex flex-wrap gap-3">{Object.entries(countryServiceAlternates(page)).map(([locale, href]) => <Link key={locale} href={href} className="rounded-xl border border-white/10 px-4 py-3 text-sm font-bold">{locale}</Link>)}</div></div></section></main>
  </PublicShell>;
}
