"use client";

import Link from "next/link";
import { ChevronDown, Heart, Link2, MessageCircle, Minus, Pause, Play, Plus, Send, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import PlatformIcon from "@/components/PlatformIcon";
import { validateCampaignLink, linkRules } from "@/lib/order-service-experience";
import type { LiveServiceFacts } from "@/lib/seo/live-service";

type Props = { live: LiveServiceFacts | null };

const money = (value: number) => `₹${value.toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
const compact = (value: number) => value >= 1000 ? `${value / 1000}K` : value.toLocaleString("en-IN");

export default function InstagramSharesLanding({ live }: Props) {
  const service = live && live.available ? live : null;
  const min = service?.min ?? 0;
  const max = service?.max ?? 0;
  const [quantity, setQuantity] = useState(min ? String(min) : "");
  const [destination, setDestination] = useState("");
  const [playing, setPlaying] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const numericQuantity = Number(quantity || 0);
  const quantityError = !service ? "Instagram Shares is currently unavailable." : !Number.isInteger(numericQuantity) || numericQuantity < min || numericQuantity > max ? `Choose a whole quantity from ${min.toLocaleString("en-IN")} to ${max.toLocaleString("en-IN")}.` : "";
  const linkError = destination.trim() ? validateCampaignLink(destination, linkRules["instagram-shares"]) : "";
  const linkValid = Boolean(destination.trim() && !linkError);
  const valid = Boolean(service && !quantityError && linkValid);
  const total = service ? Math.round((numericQuantity * service.rate * 100) / 1000) / 100 : 0;
  const presets = useMemo(() => service ? [...new Set([min, 250, 500, 1000, 2000, 5000, max].filter((item) => item >= min && item <= max))].slice(0, 6) : [], [service, min, max]);
  const handoff = () => {
    if (!valid) return;
    const params = new URLSearchParams({ platform: "instagram", service: "instagram-shares", resume: "1", quantity: String(numericQuantity), link: destination.trim() });
    window.location.assign(`/dashboard/new-order?${params.toString()}`);
  };
  const adjust = (change: number) => service && setQuantity(String(Math.min(max, Math.max(min, numericQuantity + change))));
  const faqs = [
    ["Do I need my Instagram password?", "No. This service requires only the public Instagram post or Reel link. Never share a password, OTP, or recovery code."],
    ["Which Instagram URL should I use?", "Use the exact public URL for an eligible post or Reel. A profile URL is not accepted for Instagram Shares."],
    ["Can I use a Reel URL?", "Yes. Public URLs using instagram.com/reel/... and instagram.com/p/... are accepted by the current order validation."],
    ["How are Instagram Shares priced?", service ? `The live rate is ${money(service.rate)} per 1K. Your estimate updates with the selected whole-number quantity.` : "Live pricing is unavailable until the active catalog service is available."],
    ["Can I track the order?", "Yes. After secure checkout, order status is available in your SocialRUSH dashboard."],
    ["Do shares guarantee more views or reach?", "No. This service does not guarantee recommendations, organic reach, virality, or any platform outcome."],
  ];

  return <main className="overflow-hidden bg-[#090b11] text-[#f7f3ea]">
    <section className="relative isolate border-b border-white/10 px-4 pb-16 pt-14 sm:px-6 lg:px-8 lg:pb-24 lg:pt-20">
      <div className="pointer-events-none absolute -left-24 top-0 h-80 w-80 rounded-full bg-orange-500/20 blur-3xl" /><div className="pointer-events-none absolute right-0 top-12 h-80 w-80 rounded-full bg-fuchsia-700/15 blur-3xl" />
      <div className="relative mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.02fr_.98fr] lg:items-center">
        <div><span className="inline-flex items-center gap-2 rounded-full border border-orange-400/30 bg-orange-400/10 px-3 py-2 text-[10px] font-black tracking-[.16em] text-orange-200"><Send className="h-3.5 w-3.5" /> INSTAGRAM SHARES SERVICE INDIA</span>
          <h1 className="mt-6 max-w-3xl text-4xl font-black leading-[1.03] tracking-[-.045em] sm:text-6xl">Buy Instagram <span className="bg-gradient-to-r from-orange-300 via-amber-300 to-orange-500 bg-clip-text text-transparent">Shares</span> in India</h1>
          <p className="mt-6 max-w-2xl text-base leading-8 text-slate-300 sm:text-lg">Order share activity for an eligible public Instagram post or Reel. Review live pricing and delivery details, then track your order from the SocialRUSH dashboard.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><a href="#order" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#ff7600] to-[#ffb000] px-6 text-sm font-black text-white shadow-[0_18px_35px_-14px_rgba(255,135,0,.9)]">Start Your Order <Send className="h-4 w-4" /></a><Link href="/services?platform=instagram" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/15 bg-white/5 px-6 text-sm font-bold">Explore Instagram Services</Link><a href="https://wa.me/918860330771?text=Hi%20SocialRUSH%2C%20I%20need%20help%20with%20Instagram%20Shares" target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-emerald-400/25 bg-emerald-400/10 px-6 text-sm font-bold text-emerald-200">WhatsApp</a></div>
          <div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs font-bold text-slate-300"><span>✓ No Password Required</span><span>✓ Transparent Pricing</span><span>✓ Order Tracking</span></div></div>
        <div className="rounded-[2rem] border border-white/15 bg-[linear-gradient(145deg,#17121b,#0d111b_60%,#17110d)] p-4 shadow-2xl sm:p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-fuchsia-500 via-rose-500 to-orange-400"><PlatformIcon platform="Instagram" className="h-6 w-6" /></span><div><p className="text-[10px] font-black tracking-[.16em] text-orange-200">INSTAGRAM SHARE ACTIVITY</p><p className="text-sm font-bold">Dashboard preview</p></div></div><span className="rounded-full bg-emerald-400/15 px-2.5 py-1 text-[10px] font-black text-emerald-200">{service ? "LIVE SERVICE" : "SERVICE STATUS"}</span></div>
          <div className="mt-5 grid gap-4 sm:grid-cols-[1.05fr_.95fr]"><div className="rounded-2xl border border-white/10 bg-[#10121a] p-3"><div className="flex items-center gap-2 text-xs"><span className="h-7 w-7 rounded-full bg-gradient-to-br from-amber-300 to-fuchsia-500" /><b>@yourbrand</b><span className="ml-auto text-slate-500">•••</span></div><div className="mt-3 grid aspect-[1.1] place-items-center rounded-xl bg-[radial-gradient(circle_at_65%_25%,#ffb22c_0,transparent_18%),linear-gradient(135deg,#5d1c65,#f25256_45%,#ff9e35)]"><div className="rounded-full border border-white/50 bg-white/15 p-5 backdrop-blur"><Send className="h-10 w-10 -rotate-12 text-white" /></div></div><div className="mt-3 flex items-center gap-3 text-white"><Heart className="h-4 w-4" /><MessageCircle className="h-4 w-4" /><Send className="h-5 w-5 text-orange-300" /><span className="ml-auto text-[10px] text-slate-400">Original UI preview</span></div><p className="mt-2 text-xs text-slate-300"><b>@yourbrand</b> A fresh drop, made to be shared.</p></div>
            <div className="space-y-3"><div className="rounded-2xl border border-orange-400/20 bg-orange-400/[.08] p-4"><p className="text-[10px] font-black tracking-wider text-orange-200">SHARE COUNT <span className="text-slate-500">• UI PREVIEW</span></p><p className="mt-2 text-3xl font-black">{(numericQuantity || min || 0).toLocaleString("en-IN")}</p><div className="mt-3 flex h-9 items-end gap-1">{[35,50,42,76,58,90,70].map((h,i)=><span key={i} className={`flex-1 rounded-t bg-gradient-to-t from-orange-500 to-amber-200 ${playing ? "animate-pulse" : ""}`} style={{height:`${h}%`, animationDelay:`${i*100}ms`}} />)}</div></div><dl className="rounded-2xl border border-white/10 bg-white/[.035] p-4 text-xs"><div className="flex justify-between gap-3"><dt>Starting from</dt><dd className="font-bold text-orange-200">{service ? `${money(service.rate)} / 1K` : "Unavailable"}</dd></div><div className="mt-3 flex justify-between gap-3"><dt>Delivery</dt><dd className="text-right font-bold">{service?.deliveryTime ?? "Check current service"}</dd></div><div className="mt-3 flex justify-between gap-3"><dt>Destination</dt><dd className="font-bold text-emerald-200">Post / Reel required</dd></div><div className="mt-3 flex justify-between gap-3"><dt>Secure order</dt><dd className="font-bold text-emerald-200">Protected</dd></div></dl></div></div></div>
      </div>
    </section>

    <section id="order" className="scroll-mt-24 px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[1fr_370px]"><div className="rounded-[1.75rem] border border-white/10 bg-[#11131c] p-5 sm:p-8"><p className="text-xs font-black tracking-[.15em] text-orange-200">QUICK ORDER BUILDER</p><h2 className="mt-3 text-3xl font-black">Build Your Instagram Shares Order</h2><p className="mt-2 text-sm leading-6 text-slate-400">Choose your share quantity and review your total before continuing.</p>
        <div className="mt-7"><label htmlFor="share-quantity" className="text-sm font-bold">Quantity</label><div className="mt-2 flex gap-2"><button aria-label="Decrease quantity" type="button" onClick={()=>adjust(-1)} disabled={!service} className="grid h-12 w-12 place-items-center rounded-xl border border-white/15 bg-white/5 disabled:opacity-40"><Minus className="h-4 w-4" /></button><input id="share-quantity" inputMode="numeric" value={quantity} onChange={e=>setQuantity(e.target.value.replace(/\D/g,""))} className="min-w-0 flex-1 rounded-xl border border-orange-400/30 bg-[#080a10] px-4 font-black outline-none focus:ring-4 focus:ring-orange-500/20" /><button aria-label="Increase quantity" type="button" onClick={()=>adjust(1)} disabled={!service} className="grid h-12 w-12 place-items-center rounded-xl border border-white/15 bg-white/5 disabled:opacity-40"><Plus className="h-4 w-4" /></button></div><p className={`mt-2 text-xs ${quantityError ? "text-red-300" : "text-slate-400"}`}>{quantityError || `Min ${min.toLocaleString("en-IN")} • Max ${max.toLocaleString("en-IN")} • Whole numbers only`}</p><div className="mt-3 flex flex-wrap gap-2">{presets.map(value=><button key={value} type="button" onClick={()=>setQuantity(String(value))} className={`min-h-10 rounded-full border px-3 text-xs font-black ${numericQuantity===value?"border-orange-400 bg-orange-400/15 text-orange-200":"border-white/15 bg-white/5 text-slate-300"}`}>{compact(value)}</button>)}</div></div>
        <div className="mt-7"><label htmlFor="instagram-url" className="text-sm font-bold">Instagram Post / Reel URL</label><div className="relative mt-2"><Link2 className="absolute left-4 top-4 h-5 w-5 text-orange-300" /><input id="instagram-url" value={destination} onChange={e=>setDestination(e.target.value)} placeholder="https://www.instagram.com/p/..." className="min-h-14 w-full rounded-xl border border-orange-400/30 bg-[#080a10] py-3 pl-12 pr-4 text-sm outline-none focus:ring-4 focus:ring-orange-500/20" aria-describedby="instagram-url-help" /></div><p id="instagram-url-help" className={`mt-2 text-xs ${linkError ? "text-red-300" : linkValid ? "text-emerald-300" : "text-slate-400"}`}>{linkError || (linkValid ? "✓ Valid Instagram content link" : "Use the exact public post or Reel link. Profile URLs are not supported.")}</p></div>
        <div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-[10px] font-black tracking-wider text-slate-400">RATE</p><p className="mt-2 font-black text-orange-200">{service ? `${money(service.rate)} / 1K` : "—"}</p></div><div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-[10px] font-black tracking-wider text-slate-400">QUANTITY</p><p className="mt-2 font-black">{numericQuantity.toLocaleString("en-IN") || "—"}</p></div><div className="rounded-2xl border border-orange-400/25 bg-orange-400/[.08] p-4"><p className="text-[10px] font-black tracking-wider text-orange-200">ESTIMATED TOTAL</p><p className="mt-2 text-xl font-black">{service ? money(total) : "—"}</p></div></div></div>
      <aside className="h-fit rounded-[1.75rem] border border-orange-400/25 bg-[linear-gradient(160deg,#20150a,#11131c_65%)] p-5 shadow-xl lg:sticky lg:top-24"><p className="text-[10px] font-black tracking-[.16em] text-orange-200">LIVE ORDER SUMMARY</p><h2 className="mt-3 text-xl font-black">Instagram Shares</h2><dl className="mt-6 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-400">Quantity</dt><dd className="font-bold">{numericQuantity.toLocaleString("en-IN") || "—"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-400">Live rate</dt><dd className="font-bold">{service ? `${money(service.rate)} / 1K` : "—"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-400">Delivery</dt><dd className="text-right font-bold">{service?.deliveryTime ?? "Unavailable"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-400">Refill / support</dt><dd className="text-right font-bold">{service?.refillPolicy ?? "—"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-400">Destination</dt><dd className={linkValid?"font-bold text-emerald-200":"font-bold text-slate-300"}>{linkValid?"Valid link":"Required"}</dd></div></dl><div className="my-5 border-t border-white/10" /><div className="flex justify-between"><span className="font-bold">TOTAL</span><strong className="text-2xl text-orange-200">{service ? money(total) : "—"}</strong></div><button type="button" onClick={handoff} disabled={!valid} className="mt-6 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#ff7600] to-[#ffb000] px-4 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-40">Continue to Secure Order <Send className="h-4 w-4" /></button><p className="mt-3 text-center text-[11px] text-slate-400">Public link only • Secure checkout</p></aside></div></section>

    <section className="border-y border-white/10 bg-[#0d1018] px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-2"><div className="rounded-[1.75rem] border border-fuchsia-400/20 bg-[radial-gradient(circle_at_80%_10%,rgba(217,70,239,.23),transparent_26%),#12121b] p-6"><p className="text-xs font-black tracking-[.15em] text-fuchsia-200">INTERACTIVE SHARE ACTIVITY PREVIEW</p><div className="mt-6 flex items-center gap-4"><button type="button" onClick={()=>setPlaying(!playing)} className="grid h-12 w-12 place-items-center rounded-full bg-white text-[#101018]" aria-label={playing ? "Pause UI preview" : "Play UI preview"}>{playing?<Pause className="h-5 w-5" />:<Play className="ml-0.5 h-5 w-5" />}</button><div><p className="font-black">{playing ? "Preview playing" : "Preview paused"}</p><p className="text-xs text-slate-400">Conceptual UI only — not delivery behaviour.</p></div></div><div className="mt-8 flex items-center justify-between gap-3"><span className="rounded-xl bg-white/5 px-3 py-2 text-xs">Post</span><span className={`h-px flex-1 bg-gradient-to-r from-orange-400 to-fuchsia-400 ${playing?"animate-pulse":""}`} /><Send className="h-5 w-5 text-orange-300" /><span className="rounded-xl bg-white/5 px-3 py-2 text-xs">Share Activity</span></div><div className="mt-5 flex flex-wrap gap-2">{["Direct","Story","Message","Share Link"].map(chip=><span key={chip} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-slate-300">{chip}</span>)}</div></div><div className="rounded-[1.75rem] border border-orange-400/20 bg-[#11131c] p-6"><p className="text-xs font-black tracking-[.15em] text-orange-200">CAMPAIGN DETAILS</p><div className="mt-6 grid grid-cols-2 gap-3 text-sm">{[["Platform","Instagram"],["Service","Shares"],["Destination","Post / Reel"],["Quantity",numericQuantity?numericQuantity.toLocaleString("en-IN"):"—"],["Delivery",service?.deliveryTime ?? "—"],["Order status","Ready"]].map(([label,value])=><div key={label} className="rounded-xl border border-white/10 bg-white/[.035] p-3"><p className="text-[10px] font-black tracking-wider text-slate-500">{label}</p><p className="mt-1 font-bold">{value}</p></div>)}</div></div></div></section>
    <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black tracking-[.15em] text-orange-200">USE THE CORRECT INSTAGRAM LINK</p><div className="mt-5 grid gap-3 md:grid-cols-3">{[["PROFILE","instagram.com/username","Not supported"],["POST","instagram.com/p/...","Supported"],["REEL","instagram.com/reel/...","Supported"]].map(([kind,url,status])=><div key={kind} className={`rounded-2xl border p-5 ${status==="Supported"?"border-emerald-400/25 bg-emerald-400/[.06]":"border-white/10 bg-white/[.03]"}`}><p className="text-xs font-black tracking-wider">{kind}</p><p className="mt-3 font-mono text-sm text-slate-300">{url}</p><p className={`mt-4 text-xs font-bold ${status==="Supported"?"text-emerald-300":"text-slate-500"}`}>{status}</p></div>)}</div><div className="mt-10 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[1.75rem] border border-white/10 bg-[#11131c] p-6"><p className="text-xs font-black tracking-wider text-orange-200">WHY SOCIALRUSH</p><h2 className="mt-3 text-3xl font-black">Clear service details, designed around the order.</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{["Transparent Live Pricing","Public Content-Link Ordering","Secure Checkout","Dashboard Tracking","Clear Delivery Details","Refill/Support Information"].map((item,i)=><div key={item} className={`rounded-2xl border p-4 ${i===0?"border-orange-400/25 bg-orange-400/[.08] sm:col-span-2":"border-white/10 bg-white/[.03]"}`}><Sparkles className="h-4 w-4 text-orange-300"/><p className="mt-3 font-bold">{item}</p></div>)}</div></div><div className="rounded-[1.75rem] border border-white/10 bg-[#11131c] p-6"><p className="text-xs font-black tracking-wider text-fuchsia-200">SHARES VS OTHER INSTAGRAM SERVICES</p><div className="mt-5 space-y-3 text-sm">{[["Followers","Profile-level service"],["Likes","Post engagement count"],["Views","Content view count"],["Comments","Comment activity"],["Shares","Share activity"]].map(([label,text])=><div key={label} className="flex justify-between gap-3 rounded-xl bg-white/[.035] px-3 py-2.5"><b>{label}</b><span className="text-right text-slate-400">{text}</span></div>)}</div></div></div></div></section>
    <section className="bg-[#0d1018] px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black tracking-[.15em] text-orange-200">HOW IT WORKS</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Choose Instagram Shares","Select Quantity","Paste Public Post/Reel URL","Review Live Total","Continue to Secure Checkout","Track Your Order"].map((item,i)=><div key={item} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[.03] p-4"><span className="text-lg font-black text-orange-300">{String(i+1).padStart(2,"0")}</span><span className="font-bold">{item}</span></div>)}</div><div className="mt-10 rounded-[1.75rem] border border-emerald-400/20 bg-emerald-400/[.06] p-6"><p className="text-xs font-black tracking-wider text-emerald-200">NO PASSWORD / SAFETY</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Public Post/Reel Link","✓ Required"],["Instagram Password","× Not required"],["OTP","× Never share"],["Recovery Code","× Never share"]].map(([label,text])=><div key={label} className="rounded-xl bg-black/15 p-3"><p className="text-xs text-slate-300">{label}</p><p className="mt-2 font-bold text-emerald-200">{text}</p></div>)}</div></div></div></section>
    <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-2"><div><p className="text-xs font-black tracking-[.15em] text-orange-200">RELATED INSTAGRAM SERVICES</p><h2 className="mt-3 text-3xl font-black">Choose the right service for the content.</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{[["Instagram Followers","/buy-instagram-followers-india"],["Instagram Likes","/instagram-likes"],["Instagram Views","/instagram-views"],["Instagram Comments","/buy-instagram-comments-india"]].map(([label,href])=><Link key={label} href={href} className="rounded-2xl border border-white/10 bg-white/[.03] p-4 transition hover:border-orange-400/50"><p className="font-bold">{label}</p><span className="mt-3 inline-block text-xs font-black text-orange-200">Explore service →</span></Link>)}</div></div><div><p className="text-xs font-black tracking-[.15em] text-orange-200">FAQ</p><div className="mt-5 space-y-2">{faqs.map(([question,answer],i)=><div key={question} className="rounded-2xl border border-white/10 bg-white/[.03]"><button type="button" className="flex min-h-14 w-full items-center justify-between gap-4 px-4 text-left font-bold" onClick={()=>setOpenFaq(openFaq===i?null:i)} aria-expanded={openFaq===i}>{question}<ChevronDown className={`h-4 w-4 shrink-0 transition ${openFaq===i?"rotate-180":""}`} /></button>{openFaq===i?<p className="border-t border-white/10 px-4 py-4 text-sm leading-6 text-slate-300">{answer}</p>:null}</div>)}</div></div></div></section>
  </main>;
}
